### DISCUSSION TITLE
urlencoded paths

### DISCUSSION THREAD

**Discussion by vixns** [envoyproxy/gateway#2842] [Q&A] [answered]
Hi,
When migrating from ingress to gateway api using envoy gateway, We are facing an issue with an hosted gitlab instance.
Gitlab use url encoded paths for some api endpoints, eg https://docs.gitlab.com/ee/api/rest/index.html#namespaced-path-encoding

Envoy gateway seems to decode these berfore routing, which leads in 404 responses from gitlab api.
How can we prevent that ?

**Comment by liorokman** [comment, marked as answer]
Take a look at the `ClientTrafficPolicy` in the [latest version](https://gateway.envoyproxy.io/latest/api/extension_types/#pathescapedslashaction).

Seems like what you're looking for is the `escapedSlashesAction` knob set to `KeepUnchanged`:

```yaml
kind: ClientTrafficPolicy

spec:
   path:
      escapedSlashesAction: KeepUnchanged

```
