### DISCUSSION TITLE
Active health checks

### DISCUSSION THREAD

**Discussion by jan-machacek-kosik** [envoyproxy/gateway#3406] [Q&A] [answered]
I am testing the active health check in Envoy Gateway, but it looks like it doesn’t work as I expected. 
I have a BackendTrafficPolicy with a healthCheck that points to an endpoint that always returns response code 500. 

I can see that Envoy calls the healthcheck endpoint, and in the cluster stats, I can see that the cluster is unhealthy (health_flags::/failed_active_hc). 
So I expect that the entire cluster will be removed from traffic. But when I call the endpoint, the traffic is routed to the cluster regardless of whether the health checks return false or not.

Should Envoy really stop traffic to an unhealthy cluster?

**Comment by arkodg** [comment]
@jan-machacek-kosik can you share a sample BTP and HTTPRoute sample config, so we can better understand what your backend and policy looks like

**Reply by jan-machacek-kosik** [reply]
@arkodg Thank you, here is my BackendTrafficPolicy and HTTPRoute:

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: test-server-policy
  namespace: services
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: api-test-route
    namespace: services

  healthCheck:
    active:
      timeout: "500ms"
      interval: "1s"
      unhealthyThreshold: 3
      healthyThreshold: 1
      type: HTTP
      http:
        path: "/error"
        method: "GET"
        expectedStatuses:
          - 200
          - 201

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-test-route
  namespace: services
spec:
  parentRefs:
    - name: eg
      namespace: infra
  rules:
  - matches:
      - path:
          value: "/test"
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
    backendRefs:
      - name: api-test
        kind: Service
        weight: 1
        port: 3001
```

The healthcheck endpoint always returns status code 500 but Envoy always sends traffic to cluster behind the HTTPRoute.
