### DISCUSSION TITLE
Is there away to enable HSTS HTTP Strict Transport Security for envoy gateway

### DISCUSSION THREAD

**Discussion by davem-git** [envoyproxy/gateway#3823] [Q&A]
I'm looking to replace nginx ingress with envoy-gateway. I  ran my site through ssl labs.  While I got an A with envoy-gateway. I got an A+ with nginx.  From what I can tell the only difference is the HSTS setting is called out on the NGINX one and not the envoy-gateway.

**Comment by arkodg** [comment]
hey @davem-git can you try setting the header using this filter https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPHeaderFilter ?

**Reply by mazzy89** [reply]
I'm also interested. I'm going to test this out.

**Reply by davem-git** [reply]
did you test it out? how did you implement it?

**Reply by davem-git** [reply]
@mazzy89 did you have a chance to test it? if so can you provide some examples?

**Reply by mazzy89** [reply]
You just need to set up the `Strict-Transport-Security` in the header response and it will work.

```yaml
    filters:
    - responseHeaderModifier:
        add:
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains; preload
      type: ResponseHeaderModifier
```
