### DISCUSSION TITLE
How do i set configurations for mutiple gateways

### DISCUSSION THREAD

**Discussion by davem-git** [envoyproxy/gateway#4018] [Q&A] [answered]
I use the  EnvoyProxy config pretty heavily. I set affinity, loadBalancerIP, and I plan on setting load balancer port numbers.  My question is when I go to create a second gateway, how can I set these settings for that one. I don't see how this ties in to a specific gateway or allows me to enter more than one. What is the  recommendations to handle this use case
```yaml
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
```
