### DISCUSSION TITLE
Do i need any specific configuration for websockets ?

### DISCUSSION THREAD

**Discussion by stecullum** [envoyproxy/gateway#4068] [General]
Can someone provide the simplest sample of connecting to a websocket server and setting the loadbalancer policy to "leastConnected" ( https://gateway.envoyproxy.io/docs/api/extension_types/#loadbalancer )

I have read the documentation and the only reference to websockets is here https://gateway.envoyproxy.io/docs/api/extension_types/#appprotocoltype which needs a backendRef etc

_I have seen documentation thats says use annotations and other threads implied its built in_ 

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: websockets
  annotations:
    gateway.envoyproxy.io/ws: "true"  # Enable WebSocket upgrades

do i need to do something like this

...
     filters:  # Add any additional filters if required
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: "Connection"
                value: "Upgrade"
              - name: "Upgrade"
                value: "websocket"

 ```
 
Im just very confused as what is needed and would appreciate a simple manifest that highlights things clearly ..

Thanks
