### DISCUSSION TITLE
Prefer one backend over another if it has live endpoints

### DISCUSSION THREAD

**Discussion by natkondrashova** [envoyproxy/gateway#4266] [Q&A] [answered]
This example shows how to split traffic between two services:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: echo
  namespace: default
spec:
  parentRefs:
    - name: eg
      namespace: default
  hostnames:
    - <HOSTNAME>
  rules:
    - matches:
        - headers:
            - type: Exact
              name: Cookie
              value: "svc=echo-1"
      backendRefs:
        - group: ""
          kind: Service
          name: echo-1
          port: 3000
        - group: ""
          kind: Service
          name: echo-2
          port: 3000
```
But is it possible to configure the HTTPRoute so that:
- It sends all requests to the echo-1 service if echo-1 has live endpoints.
- If echo-1 does not have any live endpoints, then the requests should be forwarded to the echo-2 service instead
?
