### DISCUSSION TITLE
How to use NGinx parameter inside URL

### DISCUSSION THREAD

**Discussion by gid-fieldcode** [envoyproxy/gateway#4322] [Q&A]
In our SecurityPolicy, we need to define a parametric  JWKS URI (utilizing `%REQ(Host)%` ) like this:
```
remoteJWKS:
        uri: https://%REQ(Host)%/auth/certs
```
However this gives us an error: 

` "error": "invalid remote JWKS URI: parse \"https://%REQ(Host)%/auth/certs\": invalid URL escape \"%RE\"\n invalid remote JWKS URI: parse \"https://%REQ(Host)%/auth/certs\": invalid URL escape \"%RE\""} `

Please suggest the proper syntax.

**Comment by gid-fieldcode** [comment]
Kind reminder....

**Reply by arkodg** [reply]
why is the JWKS parameterized ? shouldnt it be fixed for a set of routes ?

**Reply by gid-fieldcode** [reply]
@arkodg  Because we have a separate Keycloak "domain" per tenant, therefore the service that receives the request needs to see how it was called (with what domain name) so it can understand what is the requesting tenant and then return the proper response. So the domain name of the URI cannot be fixed. It must be like `tenant_name.fieldcode.com/auth/certs`, and we were hoping we'd get "tenant_name" with` %REQ(Host)%`, just like we did with the header modifier of the HTTPRoute definition below:

```
        requestHeaderModifier:
          set:
            - name: X-Forwarded-Proto
              value: "https"                            
            - name: X-Forwarded-Port
              value: "443"          
            - name: X-Forwarded-Host
              value: "%REQ(Host)%"
```

**Reply by gid-fieldcode** [reply]
@arkodg Is there any hope with this? Can it be done with Lua? If yes, can I find an example somewhere?

**Reply by arkodg** [reply]
@zhaohuabing @guydc any suggestions?

**Reply by zhaohuabing** [reply]
Unfortunately,  `uri` doesn't support parameter as requestHeaderModifier does. https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/http_uri.proto#envoy-v3-api-msg-config-core-v3-httpuri

@gid-fieldcode If I understand it correctly, you still need to define a separate SecurityPolicy for each tenant, so you should be able to specify the fixed JWKS uri in each SecurityPolicy?

**Reply by gid-fieldcode** [reply]
@zhaohuabing  No, we want to have a single SP that will cover all tenants and all routes, but the remoteJWKS uri must depend on which tenant submitted the API request. 

Can what you are suggesting actually work? If a request comes in, how will Envoy know what SP to apply? 

From what we have seen in our testing with TCPdump traces, and also in your code, you don't contact this URI all the time, you cache the certificate for 5min. So all requests during the next 5min will be handled using the same certificate. This kills us. We would be happy if you used cache for 5min just like you do now, but caching _one certificate per distinct tenant_.  The tenant identifier is basically the subdomain name of the API call, so if the request came to `foobar.mycompany.com/api/service`, the tenant is `foobar` or even `foobar.mycompany.com`, it doesn't really matter. This way all requests by the _same_ tenant would use the certificate that is right _for that tenant_. Whereas now, all tenants use the single same certificate, which fails for us. This way performance would not suffer, as  5min caching would still apply, it would just keep track of a few dozen entries rather than one. 

As we have seen in our TCP dump, the requests to the remoteJWKS URI contain a header `x-forwarded-host` that contains the domain name, which means that the service that answers can figure our the proper response per tenant. So if the caching mechanism cached the pair "tenant - certificate", we would be all set.

I hope it's all clear.

**Reply by arkodg** [reply]
how many tenants are there ? can you create a HTTPRoute per tenant (unique hostname) and target a unique SP to it ?

**Reply by gid-fieldcode** [reply]
We have dozens of tenants, and the list changes frequently as new tenants sign up and others get deleted due to inactivity, so this is a no-go.

**Reply by zhaohuabing** [reply]
@gid-fieldcode A SP can have multiple JWT providers, and the JWT is considered valid if any of the providers successfully validate the JWT. A possible solution for your use case is implement a controller that monitors the tenants and automatically updates the SP to add/delete JWT providers as needed.  

```yaml
  apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: SecurityPolicy
  metadata:
    namespace: envoy-gateway
    name: policy-for-gateway
  spec:
    targetRef:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: route-for-multiple-tenants
    jwt:
      providers:
      - name: tenant1
        issuer: https://tenant1.foo.com
        audiences:
        - tenant1.foo.com
        remoteJWKS:
          uri: https://tenant1.foo.com/jwt/public-key/jwks.json
      - name: tenant2
        issuer: https://tenant2.foo.com
        audiences:
        - tenant2.foo.com
        remoteJWKS:
          uri: https://tenant2.foo.com/jwt/public-key/jwks.json
       - name: tenant3
        issuer: https://tenant3.foo.com
        audiences:
        - tenant3.foo.com
        remoteJWKS:
          uri: https://tenant3.foo.com/jwt/public-key/jwks.json 
      ......        
```

**Reply by gid-fieldcode** [reply]
@zhaohuabing Thanks for your suggestion.

We have implemented such a controller and just tested it. The autogenerated SP YAML manifest has one provider entry for each tenant. It starts like this:
```

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: new-sync-policy
  namespace: test
spec:
  targetRefs:
  - group: gateway.networking.k8s.io  
    kind: HTTPRoute
    name: time-zone-gsl      
  jwt:
    providers:
    - name: thistenant-provider
      remoteJWKS:        
        uri: http://thistenant.acme.wtf/auth/realms/thistenant/protocol/openid-connect/certs        
      claimToHeaders:
      - claim: iss
        header: x-acme-envoy-tenant
    - name: acme-provider
      remoteJWKS:        
        uri: http://acme.acme.wtf/auth/realms/acme/protocol/openid-connect/certs        
      claimToHeaders:
      - claim: iss
        header: x-acme-envoy-tenant
```

However when we apply it, we get this error:  
```

The SecurityPolicy "new-sync-policy" is invalid:
* spec.jwt.providers: Too many: 51: must have at most 4 items
```
Is there a way around this?
