### DISCUSSION TITLE
WebSockets over TLSRoute

### DISCUSSION THREAD

**Discussion by eadwu** [envoyproxy/gateway#4353] [General]
I saw that it is supported for HTTPRoute by default now https://github.com/envoyproxy/gateway/issues/836 and I didn't have any problems using it, but now I wish to perform SSL passthrough so I converted it to a TLSRoute and the SSL and webpage are successfully loaded, although WebSockets fail to be connected.

It doesn't look like `wss` urls work over `TLSRoute` and I do see a RFC (https://gateway-api.sigs.k8s.io/geps/gep-1911/?h=) although it doesn't look like it has made it into implementation. 

Is it possible to WebSockets working over `TLSRoute`?

**Comment by arkodg** [comment]
probably worth digging into why its not working in EG
do you have access logs handy ?
envoy examples says it supports it https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/websocket#step-6-test-proxying-wss-passthrough

**Reply by eadwu** [reply]
I think Step 5 is more like what I am doing, although I am not terminated the TLS here. I don't use any `TCPProxy` or `TCPRoute`.

If I compare the YAML files, I don't see
```
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_wss_to_wss
          upgrade_configs:
          - upgrade_type: websocket
```

which I think is required based of the step 5 description.
