### DISCUSSION TITLE
OIDC authentication using Entra ID

### DISCUSSION THREAD

**Discussion by fad3t** [envoyproxy/gateway#4686] [Q&A] [answered]
Hi everyone,
I'm giving the Envoy Gateway a try and wanted to test the OIDC authentation using Entra ID.
I more or less followed the guide described [here](https://gateway.envoyproxy.io/docs/tasks/security/oidc/), however I'm unable to get to the web page - I'm getting a "The page isn't redirecting properly".
From what I see in my browser logs, going to `/` redirects me to Entra ID (so far so good), auth is happening and brings me back to the callback URL (`https://example.com/oauth2/callback` in my case). This call redirects me to `/`, which sends me again to Entra ID etc etc..
The web page is served by a basic NGINX container - this works well if I remove the security policy.
I suppose I'm missing a step or something, but cannot figure out what -- any hint would be welcome!

**Comment by fad3t** [comment]
Adding some manifests:

The security policy:
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: web-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: web
  oidc:
    provider:
      issuer: "https://login.microsoftonline.com/<snip>/v2.0"
    clientID: "<snip>"
    clientSecret:
      name: "web-oidc-secret"
    redirectURL: "https://example.com/oauth2/callback"
    logoutPath: "/logout"
```

The HTTP route:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web
spec:
  hostnames:
  - example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    sectionName: websecure
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: web
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```

And the gateway:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: google-trust-services
  name: envoy-gateway
spec:
  gatewayClassName: eg
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: example.com
    name: websecure
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: web-tls
      mode: Terminate
```

**Reply by arkodg** [reply]
@fad3t can you also share the Envoy Gateway version you are using ? is it v1.1.3 or v1.2.1 ?
some users have encountered  https://github.com/envoyproxy/gateway/issues/4678 with v1.2.1 and reverting to v1.1.3 seems to have resolved their issue

**Reply by fad3t** [reply]
Oh right, I'm using 1.2.1. I'll give 1.1.3 a try and let you know.

**Reply by arkodg** [reply]
cc @zhaohuabing

**Reply by fad3t** [reply]
Same issue with 1.1.3 :(

**Reply by arkodg** [reply]
thanks for checking, @zhaohuabing should be able to help with pointers

**Comment by zhaohuabing** [comment]
Hi @fad3t I'm trying to reproduce this with Entra ID. You could also try the same configuration with the Google OIDC provider and see if it works.

**Reply by fad3t** [reply, marked as answer]
Apologies, I just gave it another try and somehow it is now working..
No idea what happened (maybe needed some time for the Entra ID application to become fully available..?).
Thx anyway for your time!

**Reply by zhaohuabing** [reply]
No worries at all! I’m glad to hear it’s now working for you. If you run into any other issues or have more questions, feel free to reach out.

**Comment by zhaohuabing** [comment]
Hi @fad3t I create a trial account and tried with Entra ID and it works. You may want to follow the [OIDC task](https://gateway.envoyproxy.io/docs/tasks/security/oidc/) and try it again to see if anything missing in your previous setup.

My test setup with Entra ID:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: example-cert
      mode: Terminate
 ---
 apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web
spec:
  hostnames:
  - www.example.com
  - example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: backend
      port: 3000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-example
spec:
  oidc:
    clientID: f7093afc-9cef-467a-a0c7-2a4855f37767
    clientSecret:
      group: ""
      kind: Secret
      name: web-oidc-secret
    logoutPath: /logout
    provider:
      issuer: https://login.microsoftonline.com/586825f5-20ff-4acc-859c-5c10dcbe58b8/v2.0
    redirectURL: https://www.example.com/oauth2/callback
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: web        
```


Test result:

<img width="1434" alt="Screenshot 2024-11-10 at 04 26 59" src="https://github.com/user-attachments/assets/ce88d331-2dd9-4433-a398-69dc7df96f51">

<img width="1434" alt="Screenshot 2024-11-10 at 04 26 38" src="https://github.com/user-attachments/assets/e9d8990c-8675-47f6-83aa-2c37616e4521">
