### DISCUSSION TITLE
Dynamic use of EnvoyProxy..envoyDeployment.pod.topologySpreadConstraints.labelSelector in a GatewayClass?

### DISCUSSION THREAD

**Discussion by Skaronator** [envoyproxy/gateway#4835] [Q&A]
Hi, I am trying to configure `topologySpreadConstraints` at the `GatewayClass` level. However, the `topologySpreadConstraints` feature requires a `labelSelector` to function correctly. The challenge is that, when applied to GatewayClass, some label values need to be dynamic.

For instance, I’d like to use the same labelSelector as the Deployment resource, which looks like this:

```yaml
    matchLabels:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/managed-by: envoy-gateway
      app.kubernetes.io/name: envoy
      gateway.envoyproxy.io/owning-gateway-name: private
      gateway.envoyproxy.io/owning-gateway-namespace: network
```

The issue is that the labels `gateway.envoyproxy.io/owning-gateway-name` and `gateway.envoyproxy.io/owning-gateway-namespace` are dynamically set by the corresponding Gateway, not the GatewayClass.

Is there a way to handle this? Ideally, the CRD should use the same labelSelector as the default for the Deployment. If users need customization, they should be able to specify an empty object or define their own labels.
