### DISCUSSION TITLE
x509: Certificate signed by unknown authority

### DISCUSSION THREAD

**Discussion by sachinshaji** [envoyproxy/gateway#4847] [Q&A] [answered]
We use Envoy Gateway(installed using helm chart) as our Gateway API in MicroK8s cluster(redhat VM, air-gapped). We have our backend application and keycloak server running as pod inside micro K8s redhat VM. Our domain 'https://ppp.company.cloud' **works as expected** without using keycloak as our authentication server. As everything is in  air-gapped installation I use firefox browser in my VM to access the 'https://ppp.company.cloud' domain(/etc/hosts entries are made) which has a self signed certificate.  

But once we create a [security policy](https://gateway.envoyproxy.io/v0.6/design/security-policy/) I starts to get following error.
OIDC: error fetching endpoints from issuer: get "https://ppp.company.cloud/realms/myrealm/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority.

How can I make the security policy trust the self-signed certificate I have created. My firefox browser doesnot trust it but gives me warning. Is there any option to make the security policy by pass the certificate validation. Could you please help here.

Sharing our security policy yaml
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: eg-ppp-oidc-security-policy
  namespace: ppp-dev-ns
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: gateway-ppp-app-routes-oidc
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: all-gw-ppp-api-routes-oidc
  oidc:
    provider:
      issuer: "https://auth.ppp.company.cloud/realms/myrealm"
      authorizationEndpoint: "https://auth.ppp.company.cloud/realms/myrealm/protocol/openid-connect/auth"
      tokenEndpoint: "https://auth.ppp.company.cloud/realms/myrealm/protocol/openid-connect/token"
    clientID: "company.ppp.envoy-oidc.client"
    clientSecret:
      name: "company.ppp.envoy-oidc.client-secret"
    redirectURL: "https://ppp.company.cloud/pppapp/main/oauth2/callback"
    logoutPath: "/pppapp/main/logout"
    forwardAccessToken: true
    refreshToken: true
    cookieNames:
      accessToken: werwerwe
      idToken: ewrwewe

```

**Comment by arkodg** [comment]
the docs are not in yet, but you should be able to achieve this using the `backendRefs` field to link to a `Backend` and specify a custom ca cert using `BackendTLSPolicy`
there's a partial config in here https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/testdata/securitypolicy-with-oidc-backendcluster.in.yaml

cc @zhaohuabing

**Reply by sachinshaji** [reply]
Thanks for the replay.
We follow the documentation you have mentioned. We have created- 'Backend' and 'BackendTLSPolicy' and use the 'backendRefs' inside security policy. But still we get the same certificate error. 

Let me share the components we have created.



```

apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: enable-backend-tls
  namespace: default
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: tls-backend
    sectionName: "443"
  validation:
    caCertificateRefs:
    - name: example-ca
      group: ''
      kind: ConfigMap
    hostname: www.example.com

apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: enable-backend-tls
  namespace: default
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: tls-backend
    sectionName: "443"
  validation:
    caCertificateRefs:
    - name: example-ca
      group: ''
      kind: ConfigMap
    hostname: www.example.com

```

```
backends:
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: Backend
  metadata:
    name: backend-fqdn
    namespace: envoy-gateway
  spec:
    endpoints:
    - fqdn:
        hostname: 'oauth.ppp.company.com'
        port: 443
securityPolicies:
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: SecurityPolicy
  metadata:
    namespace: envoy-gateway
    name: policy-for-gateway
    uid: b8284d0f-de82-4c65-b204-96a0d3f258a1
  spec:
    targetRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-1
    oidc:
      provider:
        backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: backend-fqdn
          port: 443
        backendSettings:
          retry:
            numRetries: 3
            perRetry:
              backOff:
                baseInterval: 1s
                maxInterval: 5s
            retryOn:
              triggers: ["5xx", "gateway-error", "reset"]
        issuer: "https://oauth.ppp.company.com"
        authorizationEndpoint: "https://oauth.ppp.company.com/oauth2/v2/auth"
        tokenEndpoint: "https://oauth.ppp.company.com/token"
      clientID: "client1.apps.googleusercontent.com"
      clientSecret:
        name: "client1-secret"
      redirectURL: "https://www.example.com/bar/oauth2/callback"
      logoutPath: "/bar/logout"
      forwardAccessToken: true
      defaultTokenTTL: 30m
      refreshToken: true
      defaultRefreshTokenTTL: 24h

```

Could you please help us here. We have been trying this for last 2 days and could not get any resoution here. We have created the configmap with correct ca.crt also. Not able to debug this issue. Could you suggest any work around if possible?

**Reply by sachinshaji** [reply, marked as answer]
Similar discussion at https://github.com/envoyproxy/gateway/issues/4838 may be its more useful

**Comment by sachinshaji** [comment]
May I ask one more question here, how is SecurityPolicy trying to connect to the issuers and verify the certificate?
  AFAIK, SecurityPolicy is not creating any pod internally. Can you please help me understand is it actually connecting to any pod/deployment.
 We install envoy using helm chart. As part of that a deployment(envoy-gateway) is created. Then when we create a Gateway K8's object and another deployment(envoy-proxy) is getting created.
 To which deployment does the SecurityPolicy connects to? Is it to the envoy-gateway which is installed as part of helm or is it to the envoy-proxy which is installed with kubectl.
 Can we fix this issue if we make any of these deployments/pods trust our self signed CA. Any help is really appreciated :)

**Reply by zhaohuabing** [reply]
Hi @sachinshaji You should define a `BackendTLSPolicy` targeting on the `backend-fqdn` Backend. Something like the follwing:

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: enable-backend-tls
  namespace: default
spec:
  targetRefs:
  - group: ''
    kind: Backend
    name: backend-fqdn
    sectionName: "443"
  validation:
    caCertificateRefs:
    - name: example-ca
      group: ''
      kind: ConfigMap
    hostname: oauth.ppp.company.com
```

**Comment by sachinshaji** [comment]
Hello @zhaohuabing, Sorry for the late response.
  Above configuration also could not save us from 'OAuth Flow failed' error. During debugging we made the pod(created when we deploy Gateway) trust the self signed certificate(copied the self-signed certificate inside the pod and ran update-ca-trust command) and somehow the error is gone. I am not sure if the approach we follow is correct or how SecurityPolicy is linked to the pod. This is a work around  which worked in an air-gapped linux(RHEL) VM.

Things work fine with 'BackendTLSPolicy' and 'Backend' when the same is carried out in a DockerDesktop. Let me know if you any suggestions.

**Reply by zhaohuabing** [reply]
Hi @sachinshaji If you can provide the below informatin, I may help debug this:
* Turn on debug log with an `EnvoyProxy` resource, and collect the log when the 'OAuth Flow failed' happens.
* Collect any errors in EG when the 'OAuth Flow failed' happens.
* The SecurityPolicy resource

**Reply by sachinshaji** [reply]
@zhaohuabing Thanks for extending the support. Sharing the details.

> EnvoyProxy logs
> =================
> {"start_time":"2024-12-20T09:25:27.301Z","method":"POST","x-envoy-origin-path":"/realms/software/protocol/openid-connect/token","protocol":"HTTP/1.1","response_code":"200","response_flags":"-","response_code_details":"via_upstream","connection_termination_details":"-","upstream_transport_failure_reason":"-","bytes_received":"240","bytes_sent":"6247","duration":"138","x-envoy-upstream-service-time":"-","x-forwarded-for":"10.1.124.91,10.1.124.67","user-agent":"-","x-request-id":"0d2717ea-7b82-42d9-8dac-339e394ea880",":authority":"auth.dld.hid-software.company.cloud","upstream_host":"10.1.124.74:8080","upstream_cluster":"httproute/company-dld-ns/gateway-iam-route/rule/0","upstream_local_address":"10.1.124.91:57074","downstream_local_address":"10.1.124.91:10080","downstream_remote_address":"10.1.124.67:58808","requested_server_name":"-","route_name":"httproute/company-dld-ns/gateway-iam-route/rule/0/match/0/auth_dld_hid-software_company_cloud"}
> {"start_time":"2024-12-20T09:25:27.290Z","method":"GET","x-envoy-origin-path":"/dldapp/main/oauth2/callback?state=http%3A%2F%2Fdld.hid-software.company.cloud%2Fdldapp%2Fmain&session_state=e9b0d5dc-af7b-40c4-ad71-9eff876e5ecb&iss=https%3A%2F%2Fauth.dld.hid-software.company.cloud%2Frealms%2Fsoftware&code=3605b76f-bdb6-4881-bb2e-dee76e00d8f7.e9b0d5dc-af7b-40c4-ad71-9eff876e5ecb.30037e48-eaf1-4c08-a651-4ce5a1e5599a","protocol":"HTTP/1.1","response_code":"302","response_flags":"-","response_code_details":"oauth.logged_in","connection_termination_details":"-","upstream_transport_failure_reason":"-","bytes_received":"0","bytes_sent":"0","duration":"151","x-envoy-upstream-service-time":"-","x-forwarded-for":"172.16.118.204,10.1.124.67","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","x-request-id":"7772e498-1b88-4022-989f-0962b141f9b0",":authority":"dld.hid-software.company.cloud","upstream_host":"-","upstream_cluster":"httproute/company-dld-ns/gateway-dld-app-routes-oidc/rule/0","upstream_local_address":"-","downstream_local_address":"10.1.124.91:10080","downstream_remote_address":"10.1.124.67:47772","requested_server_name":"-","route_name":"httproute/company-dld-ns/gateway-dld-app-routes-oidc/rule/0/match/0/dld_hid-software_company_cloud"}
> {"start_time":"2024-12-20T09:25:27.447Z","method":"GET","x-envoy-origin-path":"/dldapp/main","protocol":"HTTP/1.1","response_code":"200","response_flags":"-","response_code_details":"via_upstream","connection_termination_details":"-","upstream_transport_failure_reason":"-","bytes_received":"0","bytes_sent":"3541","duration":"1","x-envoy-upstream-service-time":"-","x-forwarded-for":"172.16.118.204,10.1.124.67","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","x-request-id":"8a01a2f5-576e-4253-9968-2939638fb054",":authority":"dld.hid-software.company.cloud","upstream_host":"10.1.124.103:8080","upstream_cluster":"httproute/company-dld-ns/gateway-dld-app-routes-oidc/rule/0","upstream_local_address":"10.1.124.91:58348","downstream_local_address":"10.1.124.91:10080","downstream_remote_address":"10.1.124.67:47772","requested_server_name":"-","route_name":"httproute/company-dld-ns/gateway-dld-app-routes-oidc/rule/0/match/0/dld_hid-software_company_cloud"}
> {"start_time":"2024-12-20T09:25:27.987Z","method":"GET","x-envoy-origin-path":"/api/bff/v1/userinfo","protocol":"HTTP/1.1","response_code":"200","response_flags":"-","response_code_details":"via_upstream","connection_termination_details":"-","upstream_transport_failure_reason":"-","bytes_received":"0","bytes_sent":"195","duration":"19","x-envoy-upstream-service-time":"-","x-forwarded-for":"172.16.118.204,10.1.124.67","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","x-request-id":"6ec52124-5b77-4ee8-b1fe-0d89afcca737",":authority":"dld.hid-software.company.cloud","upstream_host":"10.1.124.106:8090","upstream_cluster":"httproute/company-dld-ns/all-gw-dld-api-routes-oidc/rule/0","upstream_local_address":"10.1.124.91:58998","downstream_local_address":"10.1.124.91:10080","downstream_remote_address":"10.1.124.67:47772","requested_server_name":"-","route_name":"httproute/company-dld-ns/all-gw-dld-api-routes-oidc/rule/0/match/0/dld_hid-software_company_cloud"}
> {"start_time":"2024-12-20T09:25:28.038Z","method":"GET","x-envoy-origin-path":"/simpl-element-icons.d236bddaa76eb872.woff2","protocol":"HTTP/1.1","response_code":"200","response_flags":"-","response_code_details":"via_upstream","connection_termination_details":"-","upstream_transport_failure_reason":"-","bytes_received":"0","bytes_sent":"86996","duration":"0","x-envoy-upstream-service-time":"-","x-forwarded-for":"172.16.118.204,10.1.124.67","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","x-request-id":"0b3b9f44-9122-4956-9204-af1e52c263a0",":authority":"dld.hid-software.company.cloud","upstream_host":"10.1.124.103:8080","upstream_cluster":"httproute/company-dld-ns/gateway-dld-app-routes-no-login/rule/0","upstream_local_address":"10.1.124.91:58308","downstream_local_address":"10.1.124.91:10080","downstream_remote_address":"10.1.124.67:47772","requested_server_name":"-","route_name":"httproute/company-dld-ns/gateway-dld-app-routes-no-login/rule/0/match/0/dld_hid-software_company_cloud"}

> EG logs
> =========
> 2024-12-20T09:23:53.721Z        INFO    provider        kubernetes/status_updater.go:140        received a status update        {"runner": "provider", "namespace": "company-dld-ns", "name": "all-gw-dld-api-routes-api"}
> 2024-12-20T09:23:53.721Z        INFO    xds-translator  runner/runner.go:55     received an update      {"runner": "xds-translator"}
> 2024-12-20T09:23:53.721Z        INFO    provider.all-gw-dld-api-routes-api.company-dld-ns       kubernetes/status_updater.go:104        status unchanged, bypassing update      {"runner": "provider"}
> 2024-12-20T09:23:53.721Z        INFO    provider        kubernetes/status_updater.go:140        received a status update        {"runner": "provider", "namespace": "company-dld-ns", "name": "all-gw-dld-api-routes-oidc"}
> 2024-12-20T09:23:53.721Z        INFO    provider.all-gw-dld-api-routes-oidc.company-dld-ns      kubernetes/status_updater.go:104        status unchanged, bypassing update      {"runner": "provider"}
> 2024-12-20T09:23:53.721Z        INFO    provider        kubernetes/status_updater.go:140        received a status update        {"runner": "provider", "namespace": "company-dld-ns", "name": "eg-dld-oidc-security-policy"}
> 2024-12-20T09:23:53.721Z        ERROR   xds-translator  runner/runner.go:85     failed to translate xds ir      {"runner": "xds-translator", "error": "xds secret exists\nxds secret exists\nxds secret exists\nxds secret exists\nxds secret exists\nxds secret exists\nxds secret exists\nxds secret exists"}
> 2024-12-20T09:23:53.721Z        ERROR   watchable       message/watchutil.go:56 observed an error       {"runner": "xds-translator", "error": "xds secret exists\nxds secret exists\nxds secret exists\nxds secret exists\nxds secret exists\nxds secret exists\nxds secret exists\nxds secret exists"}
> 2024-12-20T09:23:53.722Z        INFO    xds-server      runner/runner.go:140    received an update      {"runner": "xds-server"}
> 2024-12-20T09:23:53.736Z        INFO    xds-server      v3/simple.go:569        open delta watch ID:31 for type.googleapis.com/envoy.config.listener.v3.Listener Resources:map[] from nodeID: "envoy-company-dld-ns-eg-f3158790-5b59955985-hh795",  version "7"
> 2024-12-20T09:23:53.738Z        INFO    xds-server      v3/simple.go:569        open delta watch ID:32 for type.googleapis.com/envoy.config.route.v3.RouteConfiguration Resources:map[company-dld-ns/eg/http-app-dld-hid-software-company-cloud:{}] from nodeID: "envoy-company-dld-ns-eg-f3158790-5b59955985-hh795",  version "7"
> 2024-12-20T09:23:53.738Z        INFO    xds-server      v3/simple.go:569        open delta watch ID:33 for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret Resources:map[oauth2/client_secret/securitypolicy/company-dld-ns/eg-dld-oidc-security-policy:{} oauth2/hmac_secret/securitypolicy/company-dld-ns/eg-dld-oidc-security-policy:{}] from nodeID: "envoy-company-dld-ns-eg-f3158790-5b59955985-hh795",  version "7"
> 2024-12-20T09:23:53.739Z        INFO    xds-server      v3/simple.go:569        open delta watch ID:34 for type.googleapis.com/envoy.config.cluster.v3.Cluster Resources:map[] from nodeID: "envoy-company-dld-ns-eg-f3158790-5b59955985-hh795",  version "7"
> 2024-12-20T09:23:53.748Z        INFO    provider        kubernetes/status_updater.go:140        received a status update        {"runner": "provider", "namespace": "company-dld-ns", "name": "gateway-dld-app-routes-no-login"}
> 2024-12-20T09:23:53.748Z        INFO    provider.gateway-dld-app-routes-no-login.company-dld-ns kubernetes/status_updater.go:104        status unchanged, bypassing update      {"runner": "provider"}
> 2024-12-20T09:23:53.748Z        INFO    provider        kubernetes/status_updater.go:140        received a status update        {"runner": "provider", "namespace": "company-dld-ns", "name": "gateway-dld-app-routes-oidc"}
> 2024-12-20T09:23:53.749Z        INFO    provider.gateway-dld-app-routes-oidc.company-dld-ns     kubernetes/status_updater.go:104        status unchanged, bypassing update      {"runner": "provider"}
> 2024-12-20T09:23:53.749Z        INFO    provider        kubernetes/status_updater.go:140        received a status update        {"runner": "provider", "namespace": "company-dld-ns", "name": "gateway-iam-route"}
> 2024-12-20T09:23:53.749Z        INFO    provider.gateway-iam-route.company-dld-ns       kubernetes/status_updater.go:104        status unchanged, bypassing update      {"runner": "provider"}
> 2024-12-20T09:23:53.749Z        INFO    provider        kubernetes/status_updater.go:140        received a status update        {"runner": "provider", "namespace": "company-dld-ns", "name": "eg"}

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: eg-dld-oidc-security-policy
  namespace: company-dld-ns
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: gateway-dld-app-routes-oidc
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: all-gw-dld-api-routes-oidc
  oidc:
    provider:
      issuer: "https://auth.dld.hid-software.company.cloud/realms/software"
      backendRefs:
      - group: gateway.envoyproxy.io
        kind: Backend
        name: keycloak-backend
        port: 443
      backendSettings:
       retry:
         numRetries: 3
         perRetry:
           backOff:
              baseInterval: 1s
              maxInterval: 5s
         retryOn:
           triggers: ["5xx", "gateway-error", "reset"]
           #issuer: "http://host.docker.internal:59666/realms/master"
           # issuer: "https://auth.dld.hid-software.company.cloud/realms/master"
      authorizationEndpoint: "https://auth.dld.hid-software.company.cloud/realms/software/protocol/openid-connect/auth"
      tokenEndpoint: "https://auth.dld.hid-software.company.cloud/realms/software/protocol/openid-connect/token"
    clientID: "company.dld.envoy-oidc.client"
    clientSecret:
      name: "company.dld.envoy-oidc.client-secret"
    redirectURL: "https://dld.hid-software.company.cloud/dldapp/main/oauth2/callback"
    logoutPath: "/dldapp/main/logout"
    forwardAccessToken: True
    refreshToken: True
    #defaultTokenTTL: 30m
    #defaultRefreshTokenTTL: 24h
    cookieNames:
      accessToken: dld-acctfgteihfdbgsk
      idToken: dld-id4534tujns
```

* _Turn on debug log with an EnvoyProxy resource, and collect the log when the 'OAuth Flow failed' happens_. --> I could not find this option to do this in helm chart, hence the logs are from the pods of EnvoyGateway and EnvoyProxy.

**Reply by zhaohuabing** [reply]
@sachinshaji Can you turn on EnvoyProxy debug by configurating the follwing EnvoyProxy and share the Envoy log when the oauth2 flow failed?

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
spec:
  logging:
    level:
      default: debug
```

Customize EnvoyProxy: https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/
