### DISCUSSION TITLE
Expected route selection prioritization with RegularExpression

### DISCUSSION THREAD

**Discussion by BadLiveware** [envoyproxy/gateway#4849] [Q&A]
Route selection priority

It seems like its not possible to override routing selection via more specific matches using regex and query parameters,
I would expect that if two `RegularExpression` paths matches, other match attributes would be used as tie breakers, for example queryParams.

This is a simplified example:
Default everything to the backend `old-web` via `PathPrefix: /`
Override other HTTPRoutes to `old-web` on regex `.*` AND query parameter `next=0`
Match a specific route(`(/<i18n>)?/valuation`) to `nextweb`
Try to override that route by going to `/en/valuation?next=0`, the selected route will be `nextweb`
Try to override that route by going to `/en/valuation?ow=1`, the selected route will be `nextweb`

What is the expected outcome of the route selection in this situation?

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: old-web-internal
  namespace: dev-ops
spec:
  hostnames:
    - www.dev-ops.example.org
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
      namespace: envoy-gateway-system
  rules:
	# Fallback to old-web
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: old-web
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
	# Force to tw by setting ?next=0 
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: old-web
          weight: 1
      matches:
		# What I would expect to work
        - path:
            type: PathPrefix
            value: /
          queryParams:
            - name: next
              type: Exact
              value: '0'
		# This doesnt seem to matter
        - path:
            type: RegularExpression
            value: .*
          queryParams:
            - name: next
              type: Exact
              value: '0'
        - path:
            type: RegularExpression
            value: .*
          queryParams:
            - name: ow
              type: Exact
              value: '1'
```

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: valuation-internal
  namespace: dev-ops
spec:
  hostnames:
    - www.dev-ops.example.org
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: next-web
          port: 80
          weight: 1
      matches:
		# Route /<i18n>/valuation to nw
		# 	I would expect this to get overriden by setting next=0, but it doesnt
        - path:
            type: RegularExpression
            value: ^(/(en|da|de|sv|fr|nl){1})?/valuation$
        # This will not get overriden, same as above
		- path:
            type: Exact
            value: /en/valuation
        # This will get overriden
		- path:
            type: PathPrefix
            value: /en/valuation
```
