### DISCUSSION TITLE
Way to raise the default maxConnections

### DISCUSSION THREAD

**Discussion by dghubble** [envoyproxy/gateway#5136] [Q&A]
I'm finding that the envoy proxy default of 1024 max connections is quite low. So every HTTPRoute is having to define a `BackendTrafficPolicy` to raise it. I've not found a way to raise the default and recently tried to bind a BackendTrafficPolicy to the gateway to provide a higher default.

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: default
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mygateway
  circuitBreaker:
    # Envoy Proxy defaults to 1024 which is too low
    maxConnections: 30000
```

But with envoy-gateway 1.2.5, dumping the envoy proxy config shows its still using 1024 for an HTTPRoute that otherwise has no `BackendTrafficPolicy`.

Is this approach supposed to work (i.e. bug)? I know security policies have a most specific match behavior but I've not seen that claimed for BackendTrafficPolicy.
