### DISCUSSION TITLE
Assistance Needed: Customizing Envoy Proxy Image

### DISCUSSION THREAD

**Discussion by playgroundctl** [envoyproxy/gateway#5215] [Q&A] [answered]
Hey,  

Could you please advise on how to customize the Envoy proxy image (by default is: `docker.io/envoyproxy/envoy:distroless-v1.33.0`)?  

I've reviewed the CRDs and templates in the Envoy Gateway Helm chart ([repo link](https://github.com/envoyproxy/gateway/tree/main/charts/gateway-helm)), but I couldn't find any reference or configuration option for specifying a custom image. This is necessary when deploying a Gateway instance.  

I also followed the documentation on customizing the Envoy proxy image ([guide link](https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/#customize-envoyproxy-image)), but I was unsuccessful.  

#### `eg-gatewayclass.yaml`  
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
```  

#### `eg-custom.yaml`  
* Using a locally available image: `docker.io/library/envoy:distroless-v1.33.0` with `imagePullPolicy: Never`) 
* Additionally, I have configured this in three namespaces—`default`, `iam`, and `envoy-gateway-system`—out of caution due to my uncertainties
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          image: "docker.io/library/envoy:distroless-v1.33.0"
```  

#### `iam-gateway.yaml`  
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: iam-gateway
  labels:
    app: iam
    blueprintpart: gatewayApiV1 # kpt-set: ${GATEWAY_API_V1_LABEL}
  namespace: iam
spec:
  gatewayClassName: eg
  # infrastructure:
  #   parametersRef:
  #     group: gateway.envoyproxy.io
  #     kind: EnvoyProxy
  #     name: custom-proxy-config
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: iam-tls-secret # kpt-set: ${GATEWAY_API_V1_SECRET_NAME_TLS}
    - name: ldaps
      protocol: TLS
      port: 636
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: iam-tls-secret # kpt-set: ${GATEWAY_API_V1_SECRET_NAME_TLS}
```  

### Observations  

- In environments where the default Envoy image (`docker.io/envoyproxy/envoy:distroless-v1.33.0`) is accessible, the Kubernetes deployment appears, and I can patch it if needed. The controller and deployment are created in the `envoy-gateway-system` namespace by default.  
- In environments where the default image **cannot** be pulled, the deployment is missing from Kubernetes events, and a Gateway is not configured.  

Could someone provide the exact steps needed to successfully customize the Envoy proxy container image? Any guidance would be greatly appreciated!  

The documentation states, *"After applying the config, you can get the deployment image and see that it has changed."* But I wish to pass the deployment's image before the deployment is created, how to do that?

Thanks!

PS. Envoy Gateway (https://gateway.envoyproxy.io/docs/install/install-yaml/#install-with-yaml) `v1.3.0` is used.
