### DISCUSSION TITLE
How can I configure an extra cluster that I need in my (Http)Filter

### DISCUSSION THREAD

**Discussion by aukevanleeuwen** [envoyproxy/gateway#5301] [Q&A] [answered]
Hello,

I'm using a Lua filter to send off some information to an external HTTP service (using https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#httpcall). For this I need an extra backend to exist. Currently I've used an `EnvoyPatchPolicy` to do this, but as soon as I get into - for example - upstream TLS configuration it becomes difficult to manage. I've tried to add another 'orphaned' `Backend`, but that doesn't result in an Envoy `cluster` automagically. Probably _because_ it's orphaned, there are no `HttpRoutes` connected to it. It would be nice if that would work however, because that way I should also be able to add a `BackendTLSPolicy` to it.

I thought of using a 'dummy' listener and try to hide that from being exposed as a `LoadBalancer` type service. Or perhaps adding another `HttpRoute` to the 'main' listener that will always result in a negative match (i.e. adding a header match on something like `X-Foo == true && X-Foo != true`), but it seems rather silly. 

Are there other ways that I'm overlooking?

**Comment by zhaohuabing** [comment]
@aukevanleeuwen as a workaround, creating a dummy `Listener` or `HttpRoute` would work. 
Think it loud—should we consider adding direct support for this within the `Lua` extension?  cc @envoyproxy/gateway-maintainers @rudrakhp

The following YAML snippet is a rough idea how it might look within the lua extension:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: lua-inline-test
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend
  lua:
    - type: Inline
      inline: |
        function envoy_on_response(response_handle)
          response_handle:headers():add("x-lua-custom", "FOO")
        end
      backendRefs:
        - name: cluster-used-by-lua
          port: 8080  
```
