### DISCUSSION TITLE
migrating from nginx, matching annotations

### DISCUSSION THREAD

**Discussion by davem-git** [envoyproxy/gateway#5594] [General]
going from nginx ingress to envoy gateway HTTPRoute, we have a lot of teams with annotations on the ingress.  Is there away to match this setup with envoy gateway?

```yaml
kind: Ingress
metadata:
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
            send_timeout              600s;                     
            proxy_ignore_client_abort on;                       
        nginx.ingress.kubernetes.io/proxy-body-size: 128m       
        nginx.ingress.kubernetes.io/proxy-buffer-size: 16k     
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "50" 
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"  
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"  
```

timeouts i think are replaced with 

```yaml
timeouts:
        request: 600s  # Replaces proxy-send-timeout + configuration-snippet send_timeout
        backendRequest: 600s # Combines proxy-connect-timeout + proxy-read-timeout
```

 can i add headers to support the rest

```yaml
filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
            - name: x-envoy-upstream-rq-timeout-ms
              value: "600000"
            - name: x-envoy-max-request-bytes
              value: "134217728"
            - name: x-envoy-buffer-limit-bytes
              value: "16384"
            - name: x-envoy-upstream-rq-per-try-timeout-ms
              value: "600000"
```
