### DISCUSSION TITLE
Setting global rate limit with request header

### DISCUSSION THREAD

**Discussion by Stephen-X** [envoyproxy/gateway#5600] [Q&A]
Hi there,

I'm inquiring if there's currently a way to set the global rate limit dynamically using a request header.

This is how we normally use Envoy Gateway to set a 3 RPH global rate limit on every unique users:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy 
metadata:
  name: policy-httproute
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: http-ratelimit
  rateLimit:
    type: Global
    global:
      rules:
      - clientSelectors:
        - headers:
          - type: Distinct
            name: x-user-id
        limit:
          requests: 3
          unit: Hour
```

In our use case, Envoy Gateway is used internally to protect an internal service, which is utilized only by an external service that hosts all the user configurations. Instead of building a delta user configuration reload pipeline for EG, we are wondering whether we could pass user configurations to EG via request headers instead.

For example, we could pass to EG this request header `x-envoy-ratelimit-global-limit-requests: 3hr`, which sets the RPH in the `BackendTrafficPolicy` or override the existing default configuration for a unique user ID value.

I came across the [Envoy Header-To-Metadata filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/header_to_metadata_filter#config-http-filters-header-to-metadata) and the concept of "dynamic metadata", which appears to be close to how it could be done generally but I'm currently unsure.
