### DISCUSSION TITLE
best practices for BackendTrafficPolicy on gateways

### DISCUSSION THREAD

**Discussion by davem-git** [envoyproxy/gateway#5663] [Q&A]
I'm looking for general guidance on whats considered best practices for 
BackendTrafficPolicy. https://gateway.envoyproxy.io/contributions/design/backend-traffic-policy/. When looking at the backend-traffic-policy. There's a line that stats `If multiple polices target the same resource, the oldest resource (based on creation timestamp) will attach to the Gateway Listeners, the others will not.` 

Does that mean if they are conflicting, like we had 2 different settings for circuitBreaker max connections the first one would win?
or does that mean we should only have 1 BackendTrafficPolicy per gateway, and need to attach all of our rules to this

for example option 1 would be mutiple policies based on different sections

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: max-connections
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  circuitBreaker:
    maxConnections: 49152
    maxParallelRequests: 1024
    maxParallelRetries: 1024
    maxPendingRequests: 1024
```
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: compression
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
   compression:
      - type: Brotli
      - type: Gzip
```

or option 2

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: eg-backendtraffic-policy
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  circuitBreaker:
    maxConnections: 49152
    maxParallelRequests: 1024
    maxParallelRetries: 1024
    maxPendingRequests: 1024
  compression:
      - type: Brotli
      - type: Gzip
```

thanks
