### DISCUSSION TITLE
How to Disable TLS Verification for a HTTPS Backend

### DISCUSSION THREAD

**Discussion by erismaster** [envoyproxy/gateway#5927] [Q&A] [answered]
Hi,

We are working on migrating from Istio to Envoy Gateway, and one setting that I am struggling to find a translation to is how to configure HTTPS/TLS to the backend service, but to disable TLS verification. 

I've found the docs on [Backend TLS](https://gateway.envoyproxy.io/docs/tasks/security/backend-tls/), but don't see anything on how to disable TLS verification. In our use-case, we don't care to validate, but the backend only serves traffic on a TLS enabled server. 

In Istio, we configured a DestinationRule that contained the following

```yaml
spec:
  host: {{ include "chart.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: {{ .Values.myapp.port}}
        tls:
          mode: SIMPLE
          insecureSkipVerify: true
```

I was able to find [this](https://github.com/envoyproxy/gateway/issues/4595#issuecomment-2649581665) GH issue comment which is leading me to believe this isn't supported yet.
