### DISCUSSION TITLE
Does the default envoy-gateway-config still need a patch for ratelimit image pull policy?

### DISCUSSION THREAD

**Discussion by nelljerram** [envoyproxy/gateway#6033] [General]
I'm working in the area of envoy-gateway-config customization, and so am interested in the current default, which includes:
```
          patch:
            type: StrategicMerge
            value:
              spec:
                template:
                  spec:
                    containers:
                    - imagePullPolicy: IfNotPresent
                      name: envoy-ratelimit
```
IIUC this comes from https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/templates/_helpers.tpl#L167-L175.

My question is whether this patch is still needed, because it seems to me that `expectedRateLimitContainers` already defines the `envoy-ratelimit` container with `imagePullPolicy: IfNotPresent`: https://github.com/envoyproxy/gateway/blob/main/internal/infrastructure/kubernetes/ratelimit/resource.go#L156

Obviously this isn't a huge deal, but for me it would be nicer if the default envoy-gateway-config could be more minimal.

**Comment by arkodg** [comment]
@nelljerram the helm template is needed, because there's an option to change the ratelimit image repo/tag in the helm values files, which was a popular user ask (for air gapped cases)

**Reply by nelljerram** [reply]
Thanks @arkodg.  I understand wanting to customize the image repo/tag.  But why the pull policy?

**Reply by arkodg** [reply]
cc @zhaohuabing, do you remember why it was added

**Reply by zhaohuabing** [reply]
The EG helm chart supports customizing both the image and pull policy for the ratelimit image.

```
{{- define "eg.default-envoy-gateway-config" -}}
provider:
  type: Kubernetes
  kubernetes:
    rateLimitDeployment:
      container:
        image: {{ include "eg.ratelimit.image" . }}
      {{- if (or .Values.global.imagePullSecrets .Values.global.images.ratelimit.pullSecrets) }}
      pod:
        {{- include "eg.ratelimit.image.pullSecrets" . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.images.ratelimit.pullPolicy }}
      patch:
        type: StrategicMerge
        value:
          spec:
            template:
              spec:
                containers:
                - name: envoy-ratelimit
                  imagePullPolicy: {{ . }}
      {{- end }}
 ```
