### DISCUSSION TITLE
Calls from Salesforce AgentForce die at the gateway

### DISCUSSION THREAD

**Discussion by davem-git** [envoyproxy/gateway#6127] [Q&A] [answered]
Trying to make simple api calls from sales force, AgentForce and they die at the gateway, We get a 400 error and the only logs i see is this 

```json
{
  "searchResults": "Error: 400 Bad Request"
}
```

```json
{
    "bytes_received": 0,
    "bytes_sent": 11,
    "cluster_name": "example-cluster",
    "container_name": "envoy",
    "duration": 0,
    "entity.guid": "MjM5MTMxMnxFWFR8U0VSVklDRXwtNTQ3NTc2NzA3NDY0MjI5NTg0",
    "entity.guids": "MjM5MTMxMnxFWFR8U0VSVklDRXwtNTQ3NTc2NzA3NDY0MjI5NTg0",
    "entity.name": "envoy",
    "entity.type": "SERVICE",
    "method": "null",
    "newrelic.source": "api.logs",
    "pod_labels.app.kubernetes.io/component": "proxy",
    "pod_labels.app.kubernetes.io/managed-by": "envoy-gateway",
    "pod_labels.app.kubernetes.io/name": "envoy",
    "pod_labels.gateway.envoyproxy.io/owning-gateway-name": "acme-gateway",
    "pod_labels.gateway.envoyproxy.io/owning-gateway-namespace": "envoy-gateway-system",
    "pod_labels.kubernetes.acme.com/role": "server",
    "pod_labels.kubernetes.acme.com/service": "envoy-gateway",
    "pod_labels.kubernetes.acme.com/team": "acme",
    "pod_labels.pod-template-hash": "7fc447488d",
    "pod_name": "acme-gateway-7fc447488d-qtth2",
    "pod_namespace": "envoy-gateway-system",
    "pod_node_name": "nodename",
    "pod_owner": "ReplicaSet/acme-gateway-7fc447488d",
    "response_code": 400,
    "response_flags": "DownstreamProtocolError",
    "route_name": "null",
    "service_name": "envoy",
    "source_type": "kubernetes_logs",
    "start_time": "2025-05-20T15:28:07.326Z",
    "timestamp": 1747754888299,
    "upstream_host": "null",
    "upstream_ssl_cipher": "null",
    "user_agent": "null",
    "vhost": "null",
    "x-envoy-original-path": "null",
    "x-forwarded-for": "null",
    "x-request-id": "null"
  }
```

When making the same call to nginx, it works and i get the following

```json
  {
    "bytes_sent": "458",
    "cluster_name": "example-cluster",
    "container_name": "nginx-ingress-controller",
    "duration": "0.511",
    "entity.guid": "MjM5MTMxMnxFWFR8U0VSVklDRXwtNzk2ODczMjAzNDcyODAzNDk1MQ",
    "entity.guids": "MjM5MTMxMnxFWFR8U0VSVklDRXwtNzk2ODczMjAzNDcyODAzNDk1MQ",
    "entity.name": "ingress-nginx",
    "entity.type": "SERVICE",
    "http_referrer": "",
    "http_user_agent": "SFDC-Callout/63.0",
    "ingress": "default/agent-ecosystem-gateway",
    "method": "POST",
    "newrelic.source": "api.logs",
    "path": "/aeg/api/v1/aura-search",
    "pod_name": "nginx-ingress-controller-74677fcd8-d64sl",
    "pod_node_name": "nodename",
    "remote_addr": "",
    "request_length": "2400",
    "request_proto": "HTTP/1.1",
    "request_query": "",
    "service_name": "ingress-nginx",
    "source_type": "kubernetes_logs",
    "ssl_cipher": "TLS_AES_256_GCM_SHA384",
    "status": "401",
    "time": "2025-05-20T14:57:53+00:00",
    "timestamp": 1747753081323,
    "traceparent": "",
    "upstream": "default-agent-ecosystem-gateway-5000",
    "upstream_connect_time": "0.001",
    "upstream_header_time": "0.511",
    "upstream_response_time": "0.512",
    "upstream_server": "10.101.71.167:5000",
    "vhost": "example.com",
    "x_auto_test": "",
    "x_forward_for": "IPADDDRESS"
    }
```
Is this a cipher mismatch? I've tried setting some client traffic policys to adjust it but with no luck

**Comment by arkodg** [comment]
any idea @rudrakhp ?

**Comment by rudrakhp** [comment]
@davem-git can you share your gateway configurations (both EG and NGINX)? Access log has no info, so Envoy wasn't able to parse anything from the request:
```
    "response_code": 400,
    "response_flags": "DownstreamProtocolError",
    "route_name": "null",
    "service_name": "envoy",
    "upstream_host": "null",
    "upstream_ssl_cipher": "null",
    "user_agent": "null",
    "vhost": "null",
    "x-envoy-original-path": "null",
    "x-forwarded-for": "null",
    "x-request-id": "null"
  ```
I think there is a mismatch between the protocol used by the caller and your gateway.

**Reply by davem-git** [reply]
by config i wasn't 100% sure what you mean do you want the dump config? I'd have to see what parts are sensitive and get back to you on that 

Here's the setup, were between 1.3.2 and 1.3.3 in testing 

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
    annotations:
    generation: 1
    name: acme-gateway
    namespace: envoy-gateway-system
spec:
    gatewayClassName: acme-envoy
    infrastructure:
    parametersRef:
        group: gateway.envoyproxy.io
        kind: EnvoyProxy
        name: custom-proxy-config
    listeners:
    - allowedRoutes:
        namespaces:
        from: All
    name: https
    port: 443
    protocol: HTTPS
    tls:
        certificateRefs:
        - group: ""
        kind: Secret
        name: acme-tls-secret
        mode: Terminate

    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyProxy
    metadata:
    name: custom-proxy-config
    namespace: envoy-gateway-system
    spec:
    logging:
        level:
        default: warn
    provider:
        kubernetes:
        envoyDeployment:
            container:
            image: acme-docker.jfrog.io/acme/envoy-proxy:1.33.3-1
            resources:
                limits:
                cpu: 4000m
                memory: 4000Mi
                requests:
                cpu: 30m
                memory: 300Mi
            patch:
            type: StrategicMerge
            value:
                metadata:
                labels:
                    app: acme-gateway
                    kubernetes.acme.com/role: server
                    kubernetes.acme.com/service: envoy-gateway
                    kubernetes.acme.com/team: eng-scrum-compute
                name: acme-gateway
                spec:
                template:
                    spec:
                    containers:
                    - name: shutdown-manager
                        resources:
                        limits:
                            cpu: 200m
                            memory: 1024Mi
                    imagePullSecrets:
                    - name: jfrog-pull-secret
                    terminationGracePeriodSeconds: 500
            pod:
            affinity:
                podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                        matchExpressions:
                        - key: app.kubernetes.io/name
                        operator: In
                        values:
                        - envoy
                    topologyKey: kubernetes.io/hostname
                    weight: 100
                - podAffinityTerm:
                    labelSelector:
                        matchExpressions:
                        - key: app.kubernetes.io/name
                        operator: In
                        values:
                        - envoy
                    topologyKey: topology.kubernetes.io/zone
                    weight: 90
            labels:
                kubernetes.acme.com/role: server
                kubernetes.acme.com/service: envoy-gateway
                kubernetes.acme.com/team: eng-scrum-compute
            replicas: 3
            strategy:
            rollingUpdate:
                maxSurge: 100%
                maxUnavailable: 0
            type: RollingUpdate
        envoyService:
            annotations:
            service.beta.kubernetes.io/azure-load-balancer-resource-group: <redacted>
            externalTrafficPolicy: Local
            loadBalancerIP: <redacted
            patch:
            type: StrategicMerge
            value:
                metadata:
                name: acme-gateway
            type: LoadBalancer
        type: Kubernetes
    shutdown:
        drainTimeout: 600s
        minDrainDuration: 60s
    telemetry:
        accessLog:
        settings:
        - format:
            json:
                bytes_received: '%BYTES_RECEIVED%'
                bytes_sent: '%BYTES_SENT%'
                duration: '%DURATION%'
                method: '%REQ(:method)%'
                response_code: '%RESPONSE_CODE%'
                response_flags: '%RESPONSE_FLAGS_LONG%'
                route_name: '%ROUTE_NAME%'
                start_time: '%START_TIME%'
                upstream_host: '%UPSTREAM_HOST%'
                upstream_ssl_cipher: '%UPSTREAM_TLS_CIPHER%'
                user_agent: '%REQ(USER-AGENT)%'
                vhost: '%REQ(:authority)%'
                x-envoy-original-path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
                x-forwarded-for: '%REQ(X-FORWARDED-FOR)%'
                x-request-id: '%REQ(X-REQUEST-ID)%'
            type: JSON
            sinks:
            - file:
                path: /dev/stdout
            type: File

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
    annotations:
    name: acme-gateway-backend-traffic-policy
    namespace: envoy-gateway-system
spec:
    circuitBreaker:
    maxConnections: 49152
    maxParallelRequests: 1024
    maxParallelRetries: 1024
    maxPendingRequests: 1024
    compression:
    - type: Brotli
    - type: Gzip
    targetRefs:
    - group: gateway.networking.k8s.io
    kind: Gateway
    name: acme-gateway
status:
    ancestors:
    - ancestorRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: acme-gateway
        namespace: envoy-gateway-system
    conditions:
    - lastTransitionTime: "2025-04-04T16:20:52Z"
        message: Policy has been accepted.
        reason: Accepted
        status: "True"
        type: Accepted
    controllerName: gateway.envoyproxy.io/acme-controller


apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
    name: acme-gateway-client-traffic-policy
    namespace: envoy-gateway-system
spec:
    targetRefs:
    - group: gateway.networking.k8s.io
        kind: Gateway
        name: acme-gateway
    healthCheck:
    path: /healthz
    


apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: agent-ecosystem-gateway
  labels:
    app.kubernetes.io/name: agent-ecosystem-gateway
    kubernetes.acme.com/team: eng-scrum-knowledge
    kubernetes.acme.com/service: aeg
spec:
  parentRefs:
  - name: acme-gateway
    namespace: envoy-gateway-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /aeg/
    backendRefs:
      - name: agent-ecosystem-gateway
        port: 5000
    timeouts:
        request: 30s
        backendRequest: 30s
```

here's our configmap for nginx

```yaml
apiVersion: v1
data:
  access-log-params: buffer=64k flush=1m
  allow-snippet-annotations: "true"
  brotli-level: "4"
  disable-access-log: "false"
  disable-ipv6: "true"
  disable-ipv6-dns: "true"
  enable-brotli: "true"
  enable-ocsp: "true"
  enable-opentracing: "false"
  enable-serial-reloads: "true"
  gzip-level: "2"
  hsts: "true"
  hsts-include-subdomains: "true"
  hsts-max-age: "63072000"
  keep-alive: "120"
  load-balance: ewma
  log-format-escape-json: "true"
  log-format-upstream: '{\"time\":\"$time_iso8601\",\"remote_addr\":\"$proxy_protocol_addr\",\"x_forward_for\":\"$proxy_add_x_forwarded_for\",\"ingress\":\"$namespace/$ingress_name\",\"bytes_sent\":\"$bytes_sent\",\"upstream\":\"$proxy_upstream_name\",\"upstream_server\":\"$upstream_addr\",\"status\":\"$status\",\"vhost\":\"$host\",\"request_proto\":\"$server_protocol\",\"path\":\"$uri\",\"request_query\":\"$args\",\"request_length\":\"$request_length\",\"duration\":\"$request_time\",\"method\":\"$request_method\",\"http_referrer\":\"$http_referer\",\"http_user_agent\":\"$http_user_agent\",\"ssl_cipher\":\"$ssl_cipher\",\"traceparent\":\"$http_traceparent\",\"upstream_connect_time\":\"$upstream_connect_time\",\"upstream_header_time\":\"$upstream_header_time\",\"upstream_response_time\":\"$upstream_response_time\",\"x_auto_test\":\"$http_x_auto_test\"}'
  nginx-status-ipv4-whitelist: 10.101.64.0/18
  proxy-body-size: 20m
  proxy-buffer-size: 16k
  proxy-buffering: "off"
  proxy-connect-timeout: "1"
  proxy-next-upstream: error timeout invalid_header http_502 http_503
  proxy-next-upstream-timeout: "5"
  proxy-next-upstream-tries: "2"
  proxy-read-timeout: "30"
  proxy-request-buffering: "off"
  proxy-send-timeout: "30"
  reuse-port: "true"
  ssl-ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  ssl-early-data: "true"
  ssl-protocols: TLSv1.3 TLSv1.2
  ssl-redirect: "false"
  ssl-session-cache-size: 100m
  ssl-session-tickets: "true"
  strict-validate-path-type: "false"
  upstream-keepalive-connections: "1024"
  upstream-keepalive-requests: "10000"
  upstream-keepalive-timeout: "120"
  use-geoip: "false"
  use-geoip2: "false"
  use-gzip: "true"
  use-http2: "true"
  worker-processes: "3"
  worker-shutdown-timeout: 240s
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: nginx-ingress-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.5.1
  name: nginx-configuration
  namespace: ingress-nginx

**Reply by davem-git** [reply]
https://help.salesforce.com/s/articleView?id=000380977&type=1 here's the TLS ciphers we've confirmed with support its the latest  docs

**Reply by rudrakhp** [reply]
Can you verify if the gateway resource was accepted under its status? Your config must be in accordance with HTTPS config for gateway: https://github.com/kubernetes-sigs/gateway-api/blob/main/examples/standard/simple-http-https/gateway.yaml

**Reply by davem-git** [reply]
here's the status of the http route and the config dump of the block 

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
  creationTimestamp: "2025-05-07T16:38:13Z"
  generation: 2
  name: agent-ecosystem-gateway
  namespace: default
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: acme-gateway
    namespace: envoy-gateway-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: agent-ecosystem-gateway
      port: 5000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /aeg/
    timeouts:
      backendRequest: 30s
      request: 30s
status:
  parents:
  - conditions:
    - lastTransitionTime: "2025-05-13T20:24:38Z"
      message: Route is accepted
      observedGeneration: 2
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-05-13T20:24:38Z"
      message: Resolved all the Object references for the Route
      observedGeneration: 2
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: gateway.envoyproxy.io/acme-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: acme-gateway
      namespace: envoy-gateway-system

```
```json
          {
          "match": {
           "path_separated_prefix": "/aeg"
          },
          "route": {
           "cluster": "httproute/default/agent-ecosystem-gateway/rule/0",
           "timeout": "30s",
           "idle_timeout": "3600s",
           "upgrade_configs": [
            {
             "upgrade_type": "websocket"
            }
           ]
          },
          "metadata": {
           "filter_metadata": {
            "envoy-gateway": {
             "resources": [
              {
               "kind": "HTTPRoute",
               "namespace": "default",
               "name": "agent-ecosystem-gateway"
              }
             ]
            }
           }
          },
          "typed_per_filter_config": {
           "envoy.filters.http.compressor.brotli": {
            "@type": "type.googleapis.com/envoy.extensions.filters.http.compressor.v3.CompressorPerRoute",
            "overrides": {
             "response_direction_config": {}
            }
           },
           "envoy.filters.http.compressor.gzip": {
            "@type": "type.googleapis.com/envoy.extensions.filters.http.compressor.v3.CompressorPerRoute",
            "overrides": {
             "response_direction_config": {}
            }
           }
          },
          "name": "httproute/default/agent-ecosystem-gateway/rule/0/match/0/*"
         }
        ],
        "metadata": {
         "filter_metadata": {
          "envoy-gateway": {
           "resources": [
            {
             "sectionName": "https",
             "name": "acme-gateway",
             "kind": "Gateway",
             "namespace": "envoy-gateway-system"
            }
           ]
          }
         }
        }
       }
      ],
      "ignore_port_in_host_matching": true
     },
     "last_updated": "2025-05-21T11:45:40.388Z"
    }
   ]
  },

```
