### DISCUSSION TITLE
Is it possible to remove BackendTrafficPolicy rules via mergeType?

### DISCUSSION THREAD

**Discussion by ahinh43** [envoyproxy/gateway#6143] [Q&A]
I'm trying to set up a BackendTrafficPolicy for an HTTPRoute object that merges into a policy object targeted towards a gateway. Let's say I have these policies set:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: foo-gateway-wide-policy
  namespace: kube-system
spec:
  compression:
  - type: Gzip
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: foo-gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bar-public
  namespace: bar-service
spec:
  hostnames:
  - bar.foo
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: foo-gateway
    namespace: kube-system
    sectionName: https
  rules:
  # ... rules ... #
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: bar-backendpolicy
  namespace: bar-service
spec:
  mergeType: JSONMerge
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: bar-public
```

On the bottom backendtrafficpolicy if I add `spec.compression` and set it to a different value the new value patches over the gateway-wide policy which seems expected, but if I wanted to remove the `compression` block and make the HTTPRoute object not subject to the compression policy how would I do so? Setting `compression: []` or `compression: null` in the bottom BackendTrafficPolicy object seems to have done nothing as the gateway-wide rule continues to apply.
