### DISCUSSION TITLE
i have created httproute.yaml, but not able to add timeout parameter it is giving error even though i have envoy gateway version more than 1.4.1

### DISCUSSION THREAD

**Discussion by RitishDN** [envoyproxy/gateway#6312] [Q&A]
httproute.yaml
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: graph-explorer-gateway
  namespace: default
spec:
  parentRefs:
    - name: envoy-gateway
  hostnames:
    - xyz.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1/graph/
      timeouts:
        request: 100s
        backendRequest: 50s
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - kind: Service
          name: graph-explorer
          namespace: default
          port: 8080
          weight: 1
```

Error i am getting 

```
The request is invalid: patch: Invalid value: "{\"apiVersion\":\"gateway.networking.k8s.io/v1\",\"kind\":\"HTTPRoute\",\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"
apiVersion\\\":\\\"gateway.networking.k8s.io/v1\\\",\\\"kind\\\":\\\"HTTPRoute\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"graph-explorer-gateway\\\",\\\"namespace\\\":\\\"default\\\"},\\\"spe
c\\\":{\\\"hostnames\\\":[\\\\\"],\\\"parentRefs\\\":[{\\\"name\\\":\\\"envoy-gateway\\\"}],\\\"rules\\\":[{\\\"backendRefs\\\":[{\\\"kind\\\":\\\"Service\\\",\\\"name\\\":\\\"graph-explore
r\\\",\\\"namespace\\\":\\\"default\\\",\\\"port\\\":8080,\\\"weight\\\":1}],\\\"filters\\\":[{\\\"type\\\":\\\"URLRewrite\\\",\\\"urlRewrite\\\":{\\\"path\\\":{\\\"replacePrefixMatch\\\":\\\"/\\\",\\\"type\\\"
:\\\"ReplacePrefixMatch\\\"}}}],\\\"matches\\\":[{\\\"path\\\":{\\\"type\\\":\\\"PathPrefix\\\",\\\"value\\\":\\\"/v1/graph/\\\"}}],\\\"timeouts\\\":{\\\"backendRequest\\\":\\\"50s\\\",\\\"request\\\":\\\"100s\
\\"}}]}}\\n\"},\"creationTimestamp\":\"2025-05-16T10:07:38Z\",\"generation\":3,\"managedFields\":[{\"apiVersion\":\"gateway.networking.k8s.io/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:status\":{\".\":{
},\"f:parents\":{}}},\"manager\":\"envoy-gateway\",\"operation\":\"Update\",\"subresource\":\"status\",\"time\":\"2025-06-09T13:40:43Z\"},{\"apiVersion\":\"gateway.networking.k8s.io/v1\",\"fieldsType\":\"Fields
V1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kubectl.kubernetes.io/last-applied-configuration\":{}}},\"f:spec\":{\".\":{},\"f:hostnames\":{},\"f:parentRefs\":{},\"f:rules\":{}}},\"manager\
":\"kubectl-client-side-apply\",\"operation\":\"Update\",\"time\":\"2025-06-15T07:41:08Z\"}],\"name\":\"graph-explorer-gateway\",\"namespace\":\"default\",\"resourceVersion\":\"27724878\",\"uid\":\"3be2b36b-8d8
9-4eab-9912-921861f4deeb\"},\"spec\":{\"hostnames\":[\"\"],\"parentRefs\":[{\"name\":\"envoy-gateway\"}],\"rules\":[{\"backendRefs\":[{\"kind\":\"Service\",\"name\":\"graph-explorer\",\"names
pace\":\"default\",\"port\":8080,\"weight\":1}],\"filters\":[{\"type\":\"URLRewrite\",\"urlRewrite\":{\"path\":{\"replacePrefixMatch\":\"/\",\"type\":\"ReplacePrefixMatch\"}}}],\"matches\":[{\"path\":{\"type\":
\"PathPrefix\",\"value\":\"/v1/graph/\"}}],\"timeouts\":{\"backendRequest\":\"50s\",\"request\":\"100s\"}}]},\"status\":{\"parents\":[{\"conditions\":[{\"lastTransitionTime\":\"2025-06-09T13:40:43Z\",\"message\
":\"Route is accepted\",\"observedGeneration\":3,\"reason\":\"Accepted\",\"status\":\"True\",\"type\":\"Accepted\"},{\"lastTransitionTime\":\"2025-06-09T13:40:43Z\",\"message\":\"Resolved all the Object referen
ces for the Route\",\"observedGeneration\":3,\"reason\":\"ResolvedRefs\",\"status\":\"True\",\"type\":\"ResolvedRefs\"}],\"controllerName\":\"gateway.envoyproxy.io/gatewayclass-controller\",\"parentRef\":{\"gro
up\":\"gateway.networking.k8s.io\",\"kind\":\"Gateway\",\"name\":\"envoy-gateway\"}}]}}": strict decoding error: unknown field "spec.rules[0].timeouts"
```
