### ISSUE TITLE
Implement File Provider

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#1001]
Currently, the EnvoyProxy API defines a File provider. This provider should be implemented or removed.

**Comment by lizj3624** [comment]
+1

**Comment by arkodg** [comment]
Jotting down some thoughts here
Today, EG provides a top level field called `Provider` https://github.com/envoyproxy/gateway/blob/2bf96076c697bbda2c6de6abb55dd175676fe81d/api/config/v1alpha1/envoygateway_types.go#L43 and supports `Kubernetes` as a provider.
The provider noun could be broken down into two parts
* Config Provider - which provides input config (from a file, kubernetes)
* Infra Provider - which provides an infrastructure to deploy the output resources (envoyproxy fleet) in

So by default we support
```
provider:
  type: Kubernetes
  kubernetes:
   ....
```

We can add support for  `custom` Provider type
```
provider:
  type: Custom
  custom:
    config:
      type: File
      file:
      ....
    infrastructure:
      type: Docker
      docker:
      .... 

```
