### ISSUE TITLE
Decision: Config API structure and design

### ISSUE THREAD

**Issue by youngnick** [envoyproxy/gateway#107]
As part of discussing #103, #105, and #106, we also discussed how we should design the configuration API.

Given that we think that everything will be subcommands in a single binary (#105), and that deployment models may be very different between platforms (#106), we believe that the best structure will be a structure with:

- a common core struct config, plus a `platform` union field. This common core will hold configuration like logging levels, debug, and other things that every deployment type will need.
- individual platform config structs, selected using the `platform` union field.

The union field pattern is described in the [Kubernetes API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#unions), but the design principle is useful anywhere.

That is, the config for any particular piece of Envoy Gateway (for example, the provisioner), should end up looking something like this (in YAML format, but will be written as Go types):
```yaml
loggingLevel: <something, depends on logging library>
debug: true|false
platform: kubernetes|local
kubernetes:
  # Kubernetes-specific config goes here
local:
  # local-specific config goes here
```

This allows flexibility to add platforms later, and allows us to design the platform config separately for each platform.

On a code level, this allows these structs to be embedded into various places (eg the `spec` of a Kubernetes CRD that can be used as a GatewayClass `paramsRef`), and have changes flow everywhere they're used automatically.

This decision is not final until this issue has received maintainer votes in the form of comments or reacts, and community feedback one way or the other.
