### ISSUE TITLE
Provide make targets to set image/tag default values

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1178]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

```
    image:
      repository: docker.io/envoyproxy/gateway-dev
      tag: latest
```

We need to make sure when officially release helm in v0.4.0, the release chart default values should be

1. repository = docker.io/envoyproxy/gateway
2. tag: ${RELEASE_TAG}

consider provide to make target `helm-release` to override the default values before package and push to docker hub.

https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/values.yaml#L4
https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/values.yaml#L5

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by chauhanshubham** [comment]
@Xunzhuo I can take this one

**Comment by Xunzhuo** [comment]
Thanks @chauhanshubham !

**Comment by misstick86** [comment]
hi, this issue just like configure dynamic generation of `iamge repository` and `image tag` in the values.yaml file. Does `${RELEASE_TAG}` and `${image.repository}` from environment variable?  May be we can use yaml env replace. 
just like this. 
```
export imageTag="v1" 
export imageTag="docker.io/envoyproxy/gateway-dev"

```
```
// yaml file define
deployment:
  envoyGateway:
    image:
      repository: $imageRepo
      tag: $imageTag
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
```
```
❯ envsubst < values.yaml | cat                                                                                                                                                                                                 
deployment:
  envoyGateway:
    image:
      repository: docker.io/envoyproxy/gateway-dev
      tag: v1
    imagePullPolicy: Always
```
