### ISSUE TITLE
Different listener in the same Gateway shouldn't have the same name

### ISSUE THREAD

**Issue by muyuan0** [envoyproxy/gateway#1180]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

According to https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.Listener

> Name is the name of the Listener. This name MUST be unique within a Gateway.

However, it seems eg doesn't check the name currently.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

A configuration like this can be accepted and generate (sometimes incorrect) xDS:
```
  kind: Gateway
  metadata:
    namespace: envoy-gateway
    name: gateway-1
  spec:
    gatewayClassName: envoy-gateway-class
    listeners:
    - name: http-1
      protocol: HTTP
      port: 8080
    - name: http-1
      protocol: HTTP
      port: 80

```

*Environment*:
>Include the environment like gateway version, envoy version and so on.

The latest gateway

*Logs*:
>Include the access logs and the Envoy logs.
