### ISSUE TITLE
Align EG and Istio to make sure they can work together

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#1299]
*Description*:

EG and Istio should be able to work together seamlessly. Users may start with EG at the edge and later want to evolve to Istio service mesh for traffic management, security, and obervablity inside mesh. I think it's crucial to bring this earlier to avoid any confilicts between these two projects and provide user a unified solution. 

To achieve this, I see two possible approaches:

1. If the user only uses Kubernetes Gateway API and no EG API or extension is required, they can easily switch to the Istio Ingress Gateway as both EG and Istio use the Gateway API to configure the edge proxy.

2. If the user has used EG API and custom extensions, they should be able to continue using EG at the edge while using sidecar/waypoint proxies inside the mesh.
 
Overall option 2 should be feasible since the two project already converge at the Gateway API, which sets the foundation for compatibility. However, some areas need to be aligned to ensure they can work together. Below ar some I can think of, but it's definitely not a full list:
* How EG distributes traffic among backends in a multiple-clusters mesh. I know both projects  (plan to) support multipe clusters, but the implementation details may differ. 
* How EG obtains the client certificates and CAs needed to communicate with the services in the mesh(in ambient mode, this may not be necessary since mtls is handled by ztunnel)

[optional *Relevant Links*:]

[Support Multi-Cluster Services using ServiceImport as a BackendRef](https://github.com/envoyproxy/gateway/issues/9)

**Comment by Xunzhuo** [comment]
Thanks for raising it. But this is related to the direction of Envoy Gateway, it is better to collect some ideas from steering-committee and maintainers.

cc @envoyproxy/gateway-steering-committee  @envoyproxy/gateway-maintainers

**Comment by zhaohuabing** [comment]
Sure, that's exactly why I raise this. IMO, keeping EG compatible with Istio is benificial for both projects, as well as the end users.

**Comment by arkodg** [comment]
hey @zhaohuabing can you please reframe the ask, does this issue pertain to
ensuring Envoy Gateway and Istio can run in the same cluster and the user can configure both the control planes using Gateway API (and different GatewayClasses), with a sidecar running next to Envoy Gateway ?

**Comment by AliceProxy** [comment]
:+1: being incompatible with major service meshes like Linkerd and Istio will be a massive problem for adoption. I would like to make sure we don't _only_ support istio's Ambient mode.

What we do in Emissary to integrate with Istio is (just pulling from the docs here):

1. have the users set these annotations on the Emissary pods:
```
  # These first two annotations tell Istio not to try to do port management for the
  # Emissary-ingress pod itself. Though these annotations are placed on the Emissary-ingress
  # pods, they are interpreted by Istio.
  traffic.sidecar.istio.io/includeInboundPorts: ""      # do not intercept any inbound ports
  traffic.sidecar.istio.io/includeOutboundIPRanges: ""  # do not intercept any outbound traffic


  # We use proxy.istio.io/config to tell the Istio proxy to write newly-generated mTLS certificates
  # into /etc/istio-certs, which will be mounted below. Though this annotation is placed on the
  # Emissary-ingress pods, it is interpreted by Istio.
  proxy.istio.io/config: |
    proxyMetadata:
      OUTPUT_CERTS: /etc/istio-certs


  # We use sidecar.istio.io/userVolumeMount to tell the Istio sidecars to mount the istio-certs
  # volume at /etc/istio-certs, allowing the sidecars to see the generated certificates. Though
  # this annotation is placed on the Emissary-ingress pods, it is interpreted by Istio.
  sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]'
```
2. Setup our volume mount for the Istio secrets:
```
# We define a single storage volume called "istio-certs". It starts out empty, and Istio
# uses it to communicate mTLS certs between the Istio proxy and the Istio sidecars (see the
# annotations above).
volumes:
  - emptyDir:
      medium: Memory
    name: istio-certs

# We also tell Emissary-ingress to mount the "istio-certs" volume at /etc/istio-certs in the
# Emissary-ingress pod. This gives Emissary-ingress access to the mTLS certificates, too.
volumeMounts:
  - name: istio-certs
    mountPath: /etc/istio-certs/
    readOnly: true
```
3. Emissary establishes a Filesystem watch on the mTLS certificates from /etc/istio-certs (per the AMBASSADOR_ISTIO_SECRET_DIR environment variable) and creates a Kubernetes `Secret` named `istio-certs`.
4. You can then use that Kuberentes `istio-certs` `Secret` when configuring Emissary to talk to upstreams that are using the istio sidecars.

It's been a long time since the Emissary integration with Istio was written and I don't keep up with the Istio development very much, but if there is a way to get Istio to create the mTLS Kubernetes `Secret(s)` for us without having to write them to the filesystem and do all that then that would be greatly preferred.
