### ISSUE TITLE
Dealing with `host:port` in Host header

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1368]
*Description*:
We need a way to support the use case when the `Host` header contains a port e.g. `example.com:1234` which is valid according to the [RFC](https://www.rfc-editor.org/rfc/rfc3986#section-3.2). This gets tricky because the Gateway API does not intend to allow 
(more in https://github.com/kubernetes-sigs/gateway-api/issues/1936) specifying `port` in the `Hostnames` field with `Gateway` and `HTTPRoute` .

3 options I can think of as a workaround
1) Strip the port from the `Host` header using a knob in Envoy https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.
This gets tricky because incoming service port and container port might differ so we might need to use `strip_any_host_port` instead of `strip_matching_host_port`.
2) Create another xds route with a match to `hostname:listener-port`
3) Circumvent the issue by not specifying any `Hostnames` in `Gateway` or `HTTPRoute` and instead relying 
on a header match to the `:authority` header
https://github.com/envoyproxy/gateway/pull/1311#issuecomment-1511980948

Relates to https://github.com/envoyproxy/gateway/pull/1311

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
vote for 1. [strip_any_host_port](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto) since its less complex, and easier to maintain, although its a wider match, the user can add an extra `match` to tighten it. e.g.
```
      rules:
        - matches:
              headers:
                - name: ":authority"
                  value: "example.com:1234"
```

**Comment by AliceProxy** [comment]
Prefer setting `strip_any_host_port` automatically whenever we have an `HTTPRoute/etc.` that sets a hostname. CIrcumventing it via the provided workaround will also enable users who may not want to have the port stripped from the header for whatever reason.

**Comment by jackkleeman** [comment]
```
      rules:
        - matches:
              headers:
                - name: ":authority"
                  value: "example.com:1234"
```

This doesn't work actually due to CRD valuation on the `name` field which doesn't allow :
