### ISSUE TITLE
TLS Termination support for TLS listener

### ISSUE THREAD

**Issue by rkosyk** [envoyproxy/gateway#1391]
Is TLS Termination for TLS listener for Downstream connections supported with Envoy Gateway as described in this document?
https://gateway-api.sigs.k8s.io/v1alpha2/guides/tls

I mean the second case of the table where:
Listener Protocol = TLS
TLS Mode = Terminate
Route Type =TCPRoute

At the moment when trying to apply the below config (may be doing something wrong) getting the message in the Gateway status:
"**TLS mode "Terminate" is not supported, TLS mode must be Passthrough**"

```
cat <<EOF | kubectl apply -f -
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: eg
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  listeners:
    - name: tls
      protocol: TLS
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: envoy-gateway
EOF
```

*Note*:
Used helm to install Envoy Gateway:
```
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.4.0 -n envoy-gateway-system --create-namespace
```
