### ISSUE TITLE
Support Node Affinity and Tolerations for EnvoyProxy Pods

### ISSUE THREAD

**Issue by Gentoli** [envoyproxy/gateway#1396]
#### *Description*:

I am trying to run a set of proxy on a restricted node pool. The pod needs `affinity` and `tolerations` set to be correctly scheduled.

I would assume it would look something like this:
``` yaml
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: router-public
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: cloud.google.com/gke-nodepool
                        operator: In
                        values:
                          - router-node
          tolerations:
            - effect: NoSchedule
              key: node-type
              operator: Exists
              value: "router"
``` 
Where `affinity` and `tolerations`  are propagated to the pod spec in the deployment.

In general, would it be better to allow any fields under `spec.provider.pod` but exclude anything eg controls? i.e. A user can add anything there and the will be merged to the deployment, but certain fields (such as `containers`, `initContainer`) will not be allowed. 

#### *Relevant Links*:
- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
- https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
