### ISSUE TITLE
AuthenticationFilter being skipped for `/`

### ISSUE THREAD

**Issue by vic3lord** [envoyproxy/gateway#1438]
*Description*:
We've created a httproute that matches pathprefix of `/` and an extentionref pointing to an authentication filter but seems like it's being skipped and we get the backend errors directly without being blocked by envoy asking for a JWT

*Repro steps*:
```yaml
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: AuthenticationFilter
metadata:
  name: example-jwt
  namespace: default
spec:
  type: JWT
  jwtProviders:
    - name: example
      issuer: https://login.example.io
      remoteJWKS:
        uri: https://login.example.io/.well-known/jwks.json
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: backend
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway
  hostnames:
    - api.example.com
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 8080
          weight: 1
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.envoyproxy.io
            kind: AuthenticationFilter
            name: example-jwt
      matches:
        - path:
            type: PathPrefix
            value: /
```

*Environment*:
GKE 1.26 container optimized OS with envoy-gateway v0.4.0 helm chart installed 

*Logs*:
```
[2023-05-22T07:06:41.840Z] "GET /v1/inventory/resources/count HTTP/1.1" 400 - 0 28 1 1 "someip" "curl/7.88.1" "ed935043-0ecb-4526-9192-31d4772fb028" "*****" "10.6.191.6:8080"
```
