### ISSUE TITLE
proposal: TrafficPolicy

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1492]
*Description*:
Introduce a [hierarchical policy attachment](https://gateway-api.sigs.k8s.io/references/policy-attachment/) called `TrafficPolicy` that can be applied to the `Gateway` and `HTTPRoute` / `xRoute` resources to further configure the traffic ingressing in which can be applied either for the `downstream` connection or `upstream` connection.

```
kind: TrafficPolicy
spec:
  default:
    downstream:
      keepalive: .....
    upstream:
      keepalive: .....
      cors:
      loadBalancer:
      tls:
  targetRef:
    kind: Gateway
    name: example
```    

Relates to

* https://github.com/envoyproxy/gateway/issues/1105
* https://github.com/envoyproxy/gateway/issues/1031
* https://github.com/envoyproxy/gateway/issues/877
* https://github.com/envoyproxy/gateway/issues/837
* https://github.com/envoyproxy/gateway/issues/731
* https://github.com/envoyproxy/gateway/issues/567
* https://github.com/envoyproxy/gateway/issues/671
* https://github.com/envoyproxy/gateway/issues/492
* https://github.com/envoyproxy/gateway/issues/1328
