### ISSUE TITLE
Optimize the connection between Envoy and gateway to ensure the reliability of the connection

### ISSUE THREAD

**Issue by tmsnan** [envoyproxy/gateway#1565]
*Description*:
>Add the following settings in the bootstrap configuration to ensure the reliability of the connection
```
static_resources:
  clusters:
  - connect_timeout: 10s
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 300
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: {{ .XdsServer.Address }}
                port_value: {{ .XdsServer.Port }}

```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
+1 apart from upstream keep alive, are there other knobs we should be setting for the `xds_cluster` ?

**Comment by tmsnan** [comment]
> +1 apart from upstream keep alive, are there other knobs we should be setting for the `xds_cluster` ?

I think keep alive is enough to ensure that the network connection is available when there is no configuration update for a long time. I don't know about other scene problems so far?

**Comment by zirain** [comment]
we can reuse configuration from istio?

```yaml
      - circuit_breakers:
          thresholds:
          - max_connections: 100000
            max_pending_requests: 100000
            max_requests: 100000
          - max_connections: 100000
            max_pending_requests: 100000
            max_requests: 100000
            priority: HIGH
        connect_timeout: 1s
        http2_protocol_options: {}
        load_assignment:
          cluster_name: xds-grpc
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  pipe:
                    path: ./etc/istio/proxy/XDS
        max_requests_per_connection: 1
        name: xds-grpc
        type: STATIC
        upstream_connection_options:
          tcp_keepalive:
            keepalive_time: 300
```
