### ISSUE TITLE
Add readinessProbes for envoy proxy deployment

### ISSUE THREAD

**Issue by psinghal20** [envoyproxy/gateway#1567]
*Description*:
Envoy-gateway should add readiness probes in envoy proxy deployments to allow in-place upgrades(and proxy configurations) without traffic drop. Without any readiness probes, the proxy is immediately marked ready for traffic. This leads to traffic drops in case of in-place upgrades or proxy configurations.

Steps to reproduce:
- Install EG with quickstart yaml and configure multiple replicas using EnvoyProxy configuration:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: config.gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        pod:
          annotations:
            custom: deploy-annotation
```
- Check that pods are ready and traffic is getting routed
- Generate continuous traffic for quickstart backend service. 
- Change the annotations in EnvoyProxy configuration to `custom1: deploy-annotation1`

Expected Behaviour:
No traffic drop as the gateway has replicas, and rolloutStrategy is configured on gateway deployment.

Current Behaviour:
Traffic drops due to pods not being ready to receive traffic.
