### ISSUE TITLE
Configule ALB for Aws and SSL handshake

### ISSUE THREAD

**Issue by quyenhoang96** [envoyproxy/gateway#1581]
*Description*:
For now, I configure my gateway as below

```
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          image: envoyproxy/envoy:v1.26-latest
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 150m
              memory: 640Mi
      envoyService:
        type: LoadBalancer
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: config.gateway.envoyproxy.io
    kind: EnvoyProxy
    name: config
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: shared-gw
  namespace: dev
spec:
  gatewayClassName: gateway-class
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "*.dev.io"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: dev-secret
```

And my infrastructure is aws. By default, it generates Classic LoadBalancer. If I want it to generate ALB, what should I do? And if I want to do SSL at ALB, not on envoy as in Gateway's configuration (It requires a certificate, but I don't want to manage SSL manual, I want to aws manage for me). So how do I configure it?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
@quyenhoang96 EG allows you to update service annotations outlined here https://gateway.envoyproxy.io/latest/user/customize-envoyproxy.html#customize-envoyproxy-service-annotations and you can use specific annotation thats enable AWS infrastructure outlined here https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html

**Comment by quyenhoang96** [comment]
> 

Tks for your support. I trying it.

**Comment by arkodg** [comment]
@quyenhoang96 any update ? can we close this issue ?

**Comment by quyenhoang96** [comment]
> @quyenhoang96 any update ? can we close this issue ?

Yes. It work well with NLB. W can close this issue. Thank you.

**Comment by arkodg** [comment]
Thanks for confirming @quyenhoang96, would be great if you could also share the service annotations / EnvoyProxy config that worked for the NLB integration.

**Comment by quyenhoang96** [comment]
> 

Yes. The configure bellow work on my production:
```
apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 3
        container:
          image: envoyproxy/envoy:v1.26-latest
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 150m
              memory: 640Mi
      envoyService:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:xxx:certificate/xxx
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-3-2021-06
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: config.gateway.envoyproxy.io
    kind: EnvoyProxy
    name: config
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: shared-gw
  namespace:infra
spec:
  gatewayClassName: gateway-class
  listeners:
    - name: https
      port: 443
      protocol: HTTP
      hostname: "*.xx.xx.com"
      allowedRoutes:
        namespaces:
          from: All

```
