### ISSUE TITLE
Pass envoy gateway config from values.yaml to helm chart configmap

### ISSUE THREAD

**Issue by psinghal20** [envoyproxy/gateway#1607]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

The values configured in values.yaml for configuring envoy gateway config are not propagated to `envoy-gateway-config.yaml`.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Install helm chart using values.yaml with envoyGateway configuration as below:
```yaml
config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    provider:
      type: Kubernetes
      kubernetes:
        rateLimitDeployment:
          replicas: 2
    rateLimit:
      backend:
        type: Redis
        redis:
          url: redis.redis-system.svc.cluster.local:6379
```

The expected behavior is the propagation of the above configuration to `envoy-gateway-config.yaml` config map but only the controllerName and provider.type are propagated to the install config map manifest.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.
