### ISSUE TITLE
Cannot connect to ratelimit

### ISSUE THREAD

**Issue by quyenhoang96** [envoyproxy/gateway#1623]
Sometimes, when I redeploy the envoy proxy, the envoy proxy don't have a check rate limit rule.
Although the rate limit service is still running

<img width="1720" alt="Screenshot 2023-07-04 at 22 10 06" src="https://github.com/envoyproxy/gateway/assets/120354221/e3a65084-b91d-45bf-ab12-1511fc3e4ffd">

**Comment by shawnh2** [comment]
hi @quyenhoang96 , thanks for reporting.

can you elaborate more about how you operate to produce this bug? and what you expect to see? so i can help you to take a look at this.

**Comment by quyenhoang96** [comment]
Hi @shawnh2 Yes.
In this context, I config my cluster as bellow:
```
apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 3
        container:
          image: envoyproxy/envoy:v1.26-latest
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 150m
              memory: 640Mi
      envoyService:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:xxx:certificate/xxx
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-3-2021-06
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: config.gateway.envoyproxy.io
    kind: EnvoyProxy
    name: config
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: shared-gw
  namespace:infra
spec:
  gatewayClassName: gateway-class
  listeners:
    - name: https
      port: 443
      protocol: HTTP
      hostname: "*.xx.xx.com"
      allowedRoutes:
        namespaces:
          from: All
```
And helm values:
```
deployment:
  envoyGateway:
    imagePullSecret: artifactory-reader
    image:
      repository: xxxx/envoyproxy/gateway-dev
      tag: v0.4.1
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.11.0
    resources:
      limits:
        cpu: 50m
        memory: 56Mi
      requests:
        cpu: 50m
        memory: 56Mi
  ports:
  - name: grpc
    port: 18000
    targetPort: 18000
  - name: ratelimit
    port: 18001
    targetPort: 18001
  replicas: 2
rootNamespace: envoy-gateway-system
config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    provider:
      type: Kubernetes
    logging:
      level:
        default: info
    rateLimitDeployment:
      replicas: 3
      container:
        image: envoyproxy/ratelimit:master
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false
    rateLimit:
      backend:
        type: Redis
        redis:
          url: master.xxxx.cache.amazonaws.com:6379
          tls:
            certificateRef:
              name: ratelimit-cert
              namespace: envoy-gateway-system
          
envoyGatewayMetricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https

createNamespace: false

kubernetesClusterDomain: cluster.local
```

For the first init cluster, I config rate-limit and it works well.
Then, I change configure of gateway to:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: shared-gw
  namespace: infra
spec:
  gatewayClassName: gateway-class
  listeners:
    - name: https
      port: 443
      protocol: HTTP
      hostname: "*.xx.xx.com"
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      port: 80
      protocol: HTTP
      hostname: "*.xx.xx.com"
      allowedRoutes:
        namespaces:
          from: All
```

Then envoy proxy redeploy. But when deploy finish, Ratelimit rule cannot work

**Comment by arkodg** [comment]
* updating the `Gateway` shouldnt cause a rollout of the Envoy Proxy deployment
* can you also attach the complete `config_dump` with `listener` and `route` info as well

**Comment by quyenhoang96** [comment]
> 



> Hi @arkodg 

My listener:
```
{
             "name": "envoy.filters.http.ratelimit",
             "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit",
              "domain": "ubo-dev-infra-shared-gw-https",
              "rate_limit_service": {
               "grpc_service": {
                "envoy_grpc": {
                 "cluster_name": "ratelimit_cluster"
                }
               },
               "transport_api_version": "V3"
              },
              "enable_x_ratelimit_headers": "DRAFT_VERSION_03"
             }
            }
```
And my route:
```
{
           "cluster": "xxxx-svc-rule-0-match-0-xxxxxxxx.com",
           "rate_limits": [
            {
             "actions": [
              {
               "generic_key": {
                "descriptor_value": "xxxx-svc-rule-0-match-0-xxxxxxxx.com-value-rule-0-match--1",
                "descriptor_key": "xxxx-svc-rule-0-match-0-xxxxxxxx.com-key-rule-0-match--1"
               }
              }
             ]
            }
           ]
          },
          "name": "xxxx-svc-rule-0-match-0-xxxxxxxx.com"
         }
```

**Comment by arkodg** [comment]
@quyenhoang96 your envoy config looks good

* any errors in the `envoy-ratelimit` pods ? in your issue, it looks like there is an error connecting to xds server (envoy gateway) which eventually gets fixed, and the client can connect
* is the ratelimit - redis connection working well ? can you see data getting updated in `redis` ?

**Comment by quyenhoang96** [comment]
> @quyenhoang96 your envoy config looks good
> 
> * any errors in the `envoy-ratelimit` pods? in your issue, it looks like there is an error connecting to xds server (envoy gateway), which eventually gets fixed, and the client can connect
> * is the rate-limit - redis connection working well? Can you see data getting updated in `redis` ?

I performed some of the checks:
1. Check to get data from Redis -> It works well
2. Check the connection from envoy-rate-limit to Redis (In this context, Redis I using Elasticcache Redis of AWS) (Using telnet) -> It works well
3. Check get data from envoy-rate-limit to redis -> It work well
4. Check the connection from envoy-proxy to  envoy-rate-limit -> It works well
5. Check the connection from envoy-rate-limit -> envoy-gateway -> It works well
6. Try to restart the envoy-rate-limit pod, and the pod runs success -> Still not working
7. Try to remove the listener in the config gateway:
```
- name: http
      port: 80
      protocol: HTTP
      hostname: "*.xx.xx.com"
      allowedRoutes:
        namespaces:
          from: All
```
-> The Rate limit works again.

What's so magical here?

**Comment by arkodg** [comment]
interesting anything in the Gateway or HTTPRoute Status that points to misconfiguration?

**Comment by quyenhoang96** [comment]
> interesting anything in the Gateway or HTTPRoute Status that points to misconfiguration?

Configure of HTTPRoute and log it very well.
And it transforms to result is ->
```
{
          "match": {
           "path": "/v1/xxxx",
           "headers": [
            {
             "name": ":authority",
             "string_match": {
              "exact": "xxxxxxxx.com"
             }
            }
           ]
          },
          "route": {
           "cluster": "xxxx-svc-rule-0-match-0-xxxxxxxx.com",
           "rate_limits": [
            {
             "actions": [
              {
               "generic_key": {
                "descriptor_value": "xxxx-svc-rule-0-match-0-xxxxxxxx.com-value-rule-0-match--1",
                "descriptor_key": "xxxx-svc-rule-0-match-0-xxxxxxxx.com-key-rule-0-match--1"
               }
              }
             ]
            }
           ]
          },
          "name": "xxxx-svc-rule-0-match-0-xxxxxxxx.com"
         }
```

**Comment by arkodg** [comment]
anything in 'kubectl get gateways -A -o yaml' or 'kubectl get httproutes -A -o yaml'' ?

**Comment by quyenhoang96** [comment]
kubectl get gateways -A -o yaml
```
 - lastTransitionTime: "2023-07-06T05:47:59Z"
        message: Sending translated listener configuration to the data plane
        observedGeneration: 1
        reason: Programmed
        status: "True"
        type: Programmed
      - lastTransitionTime: "2023-07-06T05:47:59Z"
        message: Listener has been successfully translated
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      name: https
      supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
      - group: gateway.networking.k8s.io
        kind: GRPCRoute
```
kubectl get httproutes -A -o yaml
```
parents:
    - conditions:
      - lastTransitionTime: "2023-07-06T05:47:59Z"
        message: Route is accepted
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2023-07-06T05:47:59Z"
        message: Resolved all the Object references for the Route
        observedGeneration: 1
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
      parentRef:
```

I saw it very well.
