### ISSUE TITLE
Support Envoy Proxy pod labels configuration

### ISSUE THREAD

**Issue by rkosyk** [envoyproxy/gateway#1626]
*Description*:
>Be able to set custom labels on the Envoy Proxy pod

```
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        pod:
          labels:
            key1: val1
            key2: val2
```
