### ISSUE TITLE
Support Envoy Gateway pod labels and annotations configuration in Helm

### ISSUE THREAD

**Issue by rkosyk** [envoyproxy/gateway#1633]
*Description*:
>Be able to set custom labels and annotations on the Envoy Gateway pod using Helm
   
   
Helm values.yaml file
```
deployment:
  envoyGateway:
  kubeRbacProxy:
  ports:
  replicas: 1
  pod:
    annotations:
      key1: val1
      key2: val2
    labels:
      key1: val1
      key2: val2
```
