### ISSUE TITLE
Allowing matching a filterchain when applying EnvoyPatchPolicy

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#1686]
EnvoyPatchPolicy utilities [JSON Patch](https://jsonpatch.com/) for applying patches to XDS resources, but JSON Patch lacks the ability to select a specific member in an array based on conditions other than its index.

For example: assuming there're two filter chains in a listener, there's no way that we could target the second filter chain based on its serverName `www.bar.com` when applying a patch.  

We won't be able to know the index of the targeted filter chain without inspecting the generated Envoy configuration, which is impossible when we want to use a controller to generate the patch. We could possibly create that patch manually, but it's cumbersome and unreliable, and the index might change with updates to the EG releases.

```yaml
      - address:
          socketAddress:
            address: 0.0.0.0
            portValue: 10443
        filterChains:
        - filterChainMatch:
            serverNames:
            - www.foo.com
          filters:
          - name: envoy.filters.network.http_connection_manager
            typedConfig:
              ......          
        - filterChainMatch:
            serverNames:
            - www.bar.com
          filters:
          - name: envoy.filters.network.http_connection_manager
            typedConfig:
              ......

```
