### ISSUE TITLE
Support regex based path rewrites

### ISSUE THREAD

**Issue by borederman** [envoyproxy/gateway#1794]
https://github.com/envoyproxy/gateway/blob/677cf033f74babcab70670d87a1cf1cd105e4b48/internal/xds/translator/route.go#L258

**Comment by arkodg** [comment]
@borederman can you share the gateway API config / filter you are trying to apply ?

**Comment by borederman** [comment]
For example with the following config:  

would transform `http://www.example.com/gw/api/get`  into  `http://www.example.com/get/api`

``` yaml
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: /\2/\1 
          type: ReplaceFullPath
    matches:
    - path:
        type: RegularExpression
        value: ^/gw/(api)/(.+)$  # as `RegexMatchAndSubstitute.pattern`
```

**Comment by borederman** [comment]
> @borederman can you share the gateway API config / filter you are trying to apply ?

For example with the following config:  

would transform `http://www.example.com/gw/api/get`  into  `http://www.example.com/get/api`

``` yaml
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: /\2/\1 
          type: ReplaceFullPath
    matches:
    - path:
        type: RegularExpression
        value: ^/gw/(api)/(.+)$  # as `RegexMatchAndSubstitute.pattern`
```
