### ISSUE TITLE
Opt in to per Hostname metrics

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1822]
*Description*:

As an end user, I'd like to get more fine grained metrics per Hostname.

* EG creates a xds VirtualHost per GatewayAPI listener per Hostname
* Envoy provides [stats](https://www.envoyproxy.io/docs/envoy/v1.23.0/configuration/http/http_filters/router_filter#virtual-clusters)  per VirtualHost using the [VirtualCluster](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-virtualcluster) field
* This can be populated if user opts in (since these stats bump memory usage) using the [EnvoyProxy](https://github.com/envoyproxy/gateway/blob/91c0888ad63631440286264f18f1bd8d2ccab4cd/api/config/v1alpha1/metric_types.go#L8) API

Another enhancement in the future could be opting in to generate per xRoute per Rule per Match metrics
* EG creates a xds Route per HTTPRoute per rule per match per hostname
* Envoy provides a [stats_prefix](https://www.envoyproxy.io/docs/envoy/v1.24.0/api-v3/config/route/v3/route_components.proto.html?highlight=we%20do%20recommend%20setting%20up%20stat%20prefix#envoy-v3-api-msg-config-route-v3-route) field in the xds Route to create per route stats

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers

**Comment by tmsnan** [comment]
It sounds great. The reasons why we don't consider using `VirtualCluster` in our existing practice are: 
1. It is complicated to use (`VirtualCluster` must be created on each route). 
2. Performance issues.
 If the gateway control plane implements it, it will solve the first problem. Performance issues can be acceptable for some occasions, of course, this requires data support.

**Comment by arkodg** [comment]
@psinghal20 mentioned he was interested in picking this one up, assigning it to him, thanks !

**Comment by psinghal20** [comment]
Hey @arkodg, Thanks for assigning!

I thought about how the API can look to control these metrics. Here is what I propose:
```yaml
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: Metrics
  namespace: envoy-gateway-system
spec:
  telemetry:
    metrics:
      # Cluster is the default cluster stats emitted by the envoy
      # VirtualHost is the virtual host-based metrics exposed by adding virtual cluster configuration
      # In the future, we can target Path based metrics(if required)
      granularity: Enum(Cluster/VirtualHost/Route[for path based metrics in future])
```

For implementation, I successfully generated the Virtual Cluster configuration as part of the xDS translator. I can raise a draft PR for some early feedback if the API sounds good. Thanks!
