### ISSUE TITLE
Support initContainers for Envoy Proxy deployment

### ISSUE THREAD

**Issue by ardikabs** [envoyproxy/gateway#1829]
*Description*:
Was there any plan to support `initContainers` for Envoy Proxy deployment? 

I have a use case to leverage the HTTP golang filter for the envoy, which requires me to use envoy-contrib image. The current workaround is to rebuild a new image from envoy-contrib and add the golang `.so` file, but back to the Kubernetes implementation, this should be able to minimize the effort without rebuilding a new image by download the `.so` file through `initContainers`.

**Comment by arkodg** [comment]
can't this also be achieved using a volume mount ?

**Comment by ardikabs** [comment]
> can't this also be achieved using a volume mount ?

didn't get this one, or you mean with predefined the `.so` file to some volume then attached it through container via `volumeMounts`? if yes, it it possible, but not that flexible for the use case. For me, it would be better with rebuild the image for the sake of versioning. But again, wonder if the EnvoyGateway able to provide this flexibility through defining `initContainers` for the Envoy Proxy deployment.

**Comment by arkodg** [comment]
@ardikabs you can also pass your own custom Envoy Proxy image (using `EnvoyProxy` API) and also bake in the `.so` into it
https://gateway.envoyproxy.io/v0.5.0/api/config_types.html#kubernetescontainerspec

**Comment by ardikabs** [comment]
Yes, that's what I did now @arkodg, but my question actually wonder that EnvoyProxy could provide below approach

```yaml
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: default
  namespace: envoy-gateway-system
spec:
  provider:
    kubernetes:
      envoyDeployment:
        container:
          image: envoyproxy/envoy:contrib-v1.26-latest
          volumeMounts:
            - name: custom-libs
              mountPath: /lib/http_filter_with_go.so
        initContainers:
          - name: install-filter
            image: alpine:3.11.3
            command: ["/bin/sh", "-c"]
            args:
              - echo "Installing Go filter";
                set -e;
                wget -q https://example.com/download/filter_v1.0.0.tgz -O - | tar -xz --directory=/lib http_filter_with_go.so;
                echo "Done";
            volumeMounts:
              - name: custom-libs
                mountPath: /lib
        pod:
          volumes:
            - emptyDir: {}
              name: "custom-libs"
        replicas: 2
    type: Kubernetes
```
