### ISSUE TITLE
proposal: OIDCAuthenticationPolicy

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#1853]
## Relates to

https://github.com/envoyproxy/gateway/issues/881
https://github.com/envoyproxy/gateway/issues/1845

## What is this?
OIDCAuthenticationPolicy is a proposal for a new policy attachment resource that can be applied to `Gateway` resources. It allows the users to configure [OIDC authentication](https://openid.net/specs/openid-connect-core-1_0.html) for a `Gateway`.

## How would I use this resource?
You can attach an `OIDCAuthenticationPolicy` to a `Gateway` `Listener` after https://github.com/kubernetes-sigs/gateway-api/pull/2283 becomes available.  You can also link an `OIDCAuthenticationPolicy` to the entire `Gateway`. In this scenario, the policy will apply to all the `Listeners` in that `Gateway`. It may not always be a valid use case, as it depends on whether the backends behind multiple `Listeners` share the same OIDC client ID or not.
  
## API outline

```yaml
apiVersion:gateway.envoyproxy.io/v1alpha1
kind: OIDCAuthenticationPolicy
metadata:
  name: test-authn-policy
spec:
  targetRef:
    name: foo-gateway
    sectionName: https
  provider:
    issuer: string # example "https://accounts.google.com"
    AuthorizationEndpoint: string # optional  If not provided, EG will try to auto discover it from the provider's Well-Known Configuration Endpoin
    TokenEndpoint: string  # optional  If not provided, EG will try to auto discover it from the provider's Well-Known Configuration Endpoin
  clientID: string # example "xxx.apps.googleusercontent.com"
  clientSecret:
    name: "oidc-client-secret"
    namespace:  string # optional
  scopes: []string # optional, if not specified, "openid" is used.
 
```
## Open questions
* This policy can either be a standalone resource or be incorporated into the [AuthPolicy](https://github.com/envoyproxy/gateway/issues/1845) API proposed by @AliceProxy . Currently, I don't have any specific preference.  However, I would like to emphasize that I prefer a consistent approach: all Auth-related resources should either be stand-alone CRDs or part of a single mega CRD, but not a combination of both.
