### ISSUE TITLE
Support routing to Service Cluster IP

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1900]

**Comment by arkodg** [comment]
two ways to solve this
* add a field within `EnvoyProxy` called `disableEndpointRouting` / `enableClusterIPRouting` which allows us to fallback to routing using Service Cluster IP
* incorporate this into the [load balancing](https://github.com/envoyproxy/gateway/issues/1105) API

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
chatted with @kflynn the other day about this and we both feel adding it in the load balancing API is more suitable
* if we added it another API, userX may enable `serviceIP` at the `EnvoyProxy` level, user Y may set the LB Policy and then wonder why the LB policy isn't working. Adding it inside the LB Policy forces the user to be aware of the lb & routing decision to endpoints

**Comment by Xunzhuo** [comment]
I am +1 on load balancing api, if we set this in EnvoyProxy, IMHO, this is on GC level and working for all managed Gateways, but if people just want this to work in specific Gateways, a Policy is more suitable.

**Comment by arkodg** [comment]
this new `ClusterIP` load balancing type should live in https://github.com/envoyproxy/gateway/blob/main/api/v1alpha1/loadbalancer_types.go

**Comment by yeedove** [comment]
Hi @arkodg, i think this use case can be achieved by adding a `fallbackToClusterIP` field
 
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  namespace: default
  name: policy-for-route1
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: httproute-1
    namespace: default
  loadBalancer:
    type: LeastRequest
    slowStart:
      window: 300s
    fallbackToClusterIP: true # Enables fallback to service's cluster IP
```
