### ISSUE TITLE
Helm Chart compatibility with ArgoCD via supporting annotations for jobs

### ISSUE THREAD

**Issue by chicco785** [envoyproxy/gateway#1954]
*Description*:

Currently jobs created by the helm chart to bootstrap the gateway includes 
`helm.sh/hook: pre-install` and `ttlSecondsAfterFinished: 0`, this is a particularly bad combination for argocd that cannot recognise the completion of the pre-install hook.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v0.5.0
    helm.sh/chart: gateway-helm-v0.5.0
  name: release-name-gateway-helm-certgen
  namespace: default
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: certgen
    spec:
      containers:
      - command:
        - envoy-gateway
        - certgen
        env:
        - name: ENVOY_GATEWAY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: cluster.local
        image: docker.io/envoyproxy/gateway:v0.5.0
        imagePullPolicy: Always
        name: envoy-gateway-certgen
      restartPolicy: Never
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: release-name-gateway-helm-certgen
  ttlSecondsAfterFinished: 0
```

This can be easily solved by adding some argocd annotations, e.g.:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v0.5.0
    helm.sh/chart: gateway-helm-v0.5.0
  name: release-name-gateway-helm-certgen
  namespace: default
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: certgen
    spec:
      containers:
      - command:
        - envoy-gateway
        - certgen
        env:
        - name: ENVOY_GATEWAY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: cluster.local
        image: docker.io/envoyproxy/gateway:v0.5.0
        imagePullPolicy: Always
        name: envoy-gateway-certgen
      restartPolicy: Never
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: release-name-gateway-helm-certgen
```

Unfortunately the only way to achieve this, given that the helm chart does not support annotations, is adding kustomize to the deployment chain, which makes the flow quite unclean.

Ideally, it should be possible to pass such annotations directly to the helm chart without the need for kustomize.

*Relevant Links*:
https://github.com/argoproj/argo-cd/issues/8586
