### ISSUE TITLE
GRPCRoute failing validation tests for HTTPRoute

### ISSUE THREAD

**Issue by KaloyanMarshalov** [envoyproxy/gateway#1958]
*Description*:
Hey folks!

I'm currently trying to set up an Envoy Gateway to proxy gRPC requests to an OpenTelemetry collector. I am roughly following the guide in the [docs](https://gateway.envoyproxy.io/v0.5.0/user/grpc-routing/) but I'm applying some additional options as well based on the k8s Gateway API. I'm running into some issues getting the GRPCRoute to work, which I suspect is linked to validation errors judging by the gateway logs.

I installed Envoy Gateway like so:

``` bash
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.0.0-latest -n envoy-testing --create-namespace
```

and I'm trying to apply the following configuration:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: envoy-testing-gateway-class
  namespace: envoy-testing
  labels:
    example: grpc-routing
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: envoy-testing-gateway
  namespace: envoy-testing
  labels:
    example: grpc-routing
spec:
  gatewayClassName: envoy-testing-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 4317
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: envoy-testing-grpc-route
  namespace: envoy-testing
  labels:
    example: grpc-routing
spec:
  parentRefs:
    - name: envoy-testing-gateway
  rules:
    - matches:
      - method:
          type: Exact
          service: opentelemetry.proto.collector.logs.v1.LogsService
          method: Export
    - backendRefs:
      - name: otel-collector-opentelemetry-collector
        kind: Service
        port: 4317
        weight: 1
        group: ""
```

My OTEL collector has a `Service` listening on port 4317 in the same `envoy-testing` namespace for OTLP/gRPC signals. 

I tried to send a request to the Envoy Gateway host and I saw the following log line at the provisioned Gateway
``` json
{
  ":authority": "localhost:4317",
  "bytes_received": "0",
  "bytes_sent": "0",
  "connection_termination_details": "-",
  "downstream_local_address": "127.0.0.1:4317",
  "downstream_remote_address": "127.0.0.1:59916",
  "duration": "0",
  "method": "POST",
  "protocol": "HTTP/2",
  "requested_server_name": "-",
  "response_code": "200",
  "response_code_details": "route_not_found",
  "response_flags": "NR",
  "route_name": "-",
  "start_time": "2023-10-12T16:11:58.461Z",
  "upstream_cluster": "-",
  "upstream_host": "-",
  "upstream_local_address": "-",
  "upstream_transport_failure_reason": "-",
  "user-agent": "grpc-node-js/1.9.1",
  "x-envoy-origin-path": "/opentelemetry.proto.collector.logs.v1.LogsService/Export",
  "x-envoy-upstream-service-time": "-",
  "x-forwarded-for": "10.192.1.201",
  "x-request-id": "1089c5fb-a9fd-47ef-b2f8-aa892cae2815"
}
```

Looking at the logs from the time I applied the yaml configuration, I found this error log:
`2023-10-12T15:47:59.417Z	ERROR	gateway-api	runner/runner.go:104	unable to validate xds ir, skipped sending it	{"runner": "gateway-api", "error": "either PathMatch, HeaderMatches or QueryParamMatches fields must be specified"}`

Taking a further look at the [k8s API Spec](https://gateway-api.sigs.k8s.io/references/spec/), I couldn't see those types being used for `GRPCRoute`. Following the `runner.go` l found the xds-ir validation logic [here](https://github.com/envoyproxy/gateway/blob/release/v0.5/internal/ir/xds.go#L274), which didn't have anything relating to `GRPCRoute` either.

I believe that the reason my requests are not reaching the collector is that the `GRPCRoute` config is validated against the `HTTPRoute` schema and thus I can't ever use the gateway as a gRPC proxy. Have I misconfigured something or is this a genuine bug that needs to be fixed?

*Repro steps*:
1. Deploy the configuration mentioned further up
2. Configure a OTEL-gRPC SDK to make a request to the Envoy Gateway

*Environment*:
`v0.0.0-latest` - at the time of writing, it pointed [here](https://github.com/envoyproxy/gateway/commit/76704d1124eccaf06b81634a96390c95722a0554)

*Logs*:
Have done so in the description, let me know if I need anything extra.

**Comment by arkodg** [comment]
thank for adding so much context on the issue, makes it so much easier to understand the problem !

Issue 1 - Config intent is probably incorrect
Instead of 
```
  rules:
    - matches:
      - method:
          type: Exact
          service: opentelemetry.proto.collector.logs.v1.LogsService
          method: Export
    - backendRefs:
      - name: otel-collector-opentelemetry-collector
        kind: Service
        port: 4317
        weight: 1
        group: ""
```        

You probably want
```
  rules:
    - matches:
      - method:
          type: Exact
          service: opentelemetry.proto.collector.logs.v1.LogsService
          method: Export
      backendRefs:
      - name: otel-collector-opentelemetry-collector
        kind: Service
        port: 4317
        weight: 1
        group: ""
 ```       
 
 which only creates 1 rule and adds the `matches` and `backendRefs` into that single rule
 
 Issue 2 - Envoy Gateway has an incorrect internal validation
 
 Your config exposed a side issue where you created an extra rule with an empty `matches`.
 Above config is valid https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1alpha2.GRPCRouteRule
 and we also support it in the [gateway-api](https://github.com/envoyproxy/gateway/blob/76704d1124eccaf06b81634a96390c95722a0554/internal/gatewayapi/route.go#L429) layer as well as in the [xds translator ](https://github.com/envoyproxy/gateway/blob/76704d1124eccaf06b81634a96390c95722a0554/internal/xds/translator/route.go#L91) layer but we add this extra intermediate validation https://github.com/envoyproxy/gateway/blob/76704d1124eccaf06b81634a96390c95722a0554/internal/ir/xds.go#L320 which needs to be removed
