### ISSUE TITLE
Connection failure when running services/pods on separate nodes/subnets

### ISSUE THREAD

**Issue by hockic** [envoyproxy/gateway#1962]
*Description*: <br>
The following error is shown in the browser when services referenced in HTTPRoute are targeting pods running on nodes that are not running the gateway
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

*Repro steps*:<br>
1. Create a cluster with at least 2 nodes (observed on eks in this scenario)
2. Deploy the Gateway
```
# Note: the ReferenceGrant was created but excluded from example for the sake of brevity
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: northsouth-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: api.example.com
    name: https-1de4e9455
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: https-1de4e9455
        namespace: dashboard
      mode: Terminate
```
3. Deploy the HTTPRoute
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: example-backend-route
  namespace: example
spec:
  hostnames:
  - api.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: northsouth-gateway
    namespace: envoy-gateway-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: example-backend
      namespace: example
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```
4. Set the node affinity on the pod running the `example-backend` to the node that's not running the Gateway pod
5. Open `api.example.com` and observe the `connection failure`
6. Set the node affinity on the pod running the `example-backend` to the node that IS running the Gateway pod
7. Now it works

In short, this works
```
gateway on node-1
example-backend on node-1
```
and this does not
```
gateway on node-1
example-backend on node-2
```

*Environment*:<br>
Running EnvoyGateway v0.5.0 on infrastructure was created with terraform which basically boils down to this:
```
data "aws_availability_zones" "available" {
  state = "available"
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "5.1.2"

  name = "network-main"
  cidr = "10.0.0.0/16"
  azs  = slice(data.aws_availability_zones.available.names, 0, 3)

  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  public_subnet_tags = {
    "kubernetes.io/role/elb" = 1
  }

  private_subnet_tags = {
    "kubernetes.io/role/internal-elb" = 1
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.15.1"

  cluster_name    = "cluster-main"
  cluster_version = "1.26"

  vpc_id                         = module.vpc.vpc_id
  subnet_ids                     = flatten([module.vpc.public_subnets, module.vpc.private_subnets])
  cluster_endpoint_public_access = true

  eks_managed_node_group_defaults = {
    subnet_ids = module.vpc.private_subnets
  }

  eks_managed_node_groups = {
    default = {
      name           = "cluster-main-node-group"
      instance_types = ["t3.large"]
      min_size       = 2
      max_size       = 3
      desired_size   = 2
    }
  }
}
```
Note: the provisioned nodes are running in different subnets<br>

*Logs*:<br>
The logs don't reveal much; no errors, all routes are loaded, all listeners are loaded. The only error so far seems unrelated:
```
ERROR infrastructure runner/runner.go:70 failed to create new infra {"runner": "infrastructure", "error": "failed to create or update deployment envoy-gateway-system/envoy-envoy-gateway-system-northsouth-gateway-656e766f: for Update: Deployment.apps \"envoy-envoy-gateway-system-northsouth-gateway-656e766f\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app.kubernetes.io/component\":\"proxy\", \"app.kubernetes.io/managed-by\":\"envoy-gateway\", \"app.kubernetes.io/name\":\"envoy\"
```

**Comment by hockic** [comment]
Issue not related to envoy or the gateway api after all. Will add the resolution if I find one.

**Comment by zirain** [comment]
For eks user, please check your VPC firewall settings first.

**Comment by hockic** [comment]
> For eks user, please check your VPC firewall settings first.

I tried allowing all traffic between the cluster and node security group to make sure it isn't some control-plane communication issue but still experiencing the issue. Anything else I could look for?

**Comment by arkodg** [comment]
closing as this is not related to any issue within EG

**Comment by hockic** [comment]
If anyone comes across this issue, changing my service spec from
```
apiVersion: v1
kind: Service
metadata:
  name: example-backend
  namespace: example
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    ...
```
to
```
apiVersion: v1
kind: Service
metadata:
  name: example-backend
  namespace: example
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    ...
```
resolved the issue. I'm not sure why this fixes it.
@arkodg Can you confirm it's still not related to envoy/gateway
