### ISSUE TITLE
Decision: Envoy Gateway Control Plane Ports Allocation

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1980]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

When I am implementing Control Plane Observability, I realized that we need further discussion on port allocation.

### Current State

| Envoy Gateway          | Address   |  Port  | Configurable |
|:----------------------:|:---------:|:------:|  :------:|
| Xds EnvoyProxy Server  | 0.0.0.0   | 18000  | Yes |
| Xds RateLimit Server   | 0.0.0.0   | 18001  | Yes |
| Admin Server           | 127.0.0.1 | 19000  | Yes |
| Health Check           | 127.0.0.1 | 8081  | Not Yet |
| Monitoring           | ? | ?  | Not Desided |

#### Note

Health check is configured statically in controller runtime manager:

```go
mgrOpts := manager.Options{
  Scheme:                 envoygateway.GetScheme(),
  Logger:                 svr.Logger.Logger,
  LeaderElection:         false,
  HealthProbeBindAddress: ":8081",
  LeaderElectionID:       "5b9825d2.gateway.envoyproxy.io",
}
```

### Some questions

+ Is current port allocation reasonable?
+ Where should we put the metrics(monitoring port) to?
    + Option 1: **Use a new port** for metrics like 19010 and it is configurable via Envoy Gateway Config.
    + Option 2: **Reuse admin port** with endpoint `/metrics`, it is configured along with admin config, so it is configurable.
    + Option 3: **Reuse health check port** with endpoint `/metrics`, it is configured along with healthcheck config, so it is not configurable not, and also if we use health-check port, we need to implement health-check ourselves instead of using controller-runtime, because there are no places to register http handler in manager options on health check port. And the health check port is related to our helm installation resources too, it is not easy to make it configurable.

```yaml
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: envoy-gateway
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
```

I am on option 1 and 2.
