### ISSUE TITLE
Add E2E for the MergeGateways feature

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2029]
*Description*:
>Describe the issue.

Add an E2E in https://github.com/envoyproxy/gateway/tree/main/test/e2e for the MergeGateway features
Relates to https://github.com/envoyproxy/gateway/pull/1938

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by shawnh2** [comment]
it seems a little tricky to implement this e2e test case.

our e2e test env deploys eg with controller name:
https://github.com/envoyproxy/gateway/blob/c85f0e438ec3c41048739e794f27f3a33e853df0/test/config/gatewayclass.yaml#L6

if we have `mergeGateways` feature enabled, **it's better to create a new gatewayclass, not reuse the exist one**:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg-merge-gateways
spec:
  controllerName: gateway.envoyproxy.io/merge-gateways-controller  # needs another controller name
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  mergeGateways: true  # enable
```

but that requires to deploy eg one more time, it's not worthy!
