### ISSUE TITLE
How is the envoy gateway kubernetes service name defined?

### ISSUE THREAD

**Issue by bholland-bh** [envoyproxy/gateway#2141]
I would like to be able to set a name for the generated envoy service, or at least make sure the name doesn't ever change.

```
➜ kubectl get service -n envoy-gateway-system
NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)               AGE
envoy-envoy-gateway-system-eg-656e766f   ClusterIP   172.20.249.184   <none>        80/TCP                27d
envoy-gateway                            ClusterIP   172.20.94.26     <none>        18000/TCP,18001/TCP   28d
envoy-gateway-metrics-service            ClusterIP   172.20.0.145     <none>        8443/TCP              28d
```

Here the name of my eg service, is `envoy-envoy-gateway-system-eg-656e766f` What components make up this service name? Will it always be the same value?

**Comment by cnvergence** [comment]
hi @bholland-bh, currently it is generated by this function
https://github.com/envoyproxy/gateway/blob/71c09f285fcc88ddaf234a7c3864263d8a5bbbd0/internal/infrastructure/kubernetes/proxy/resource.go#L54-L57
It will be the same value, its format consists of a prefix(envoy), gateway namespace, gateway name, and 8 characters of the hashed name.

**Comment by zirain** [comment]
you'd better query by labels.

**Comment by bholland-bh** [comment]
> hi @bholland-bh, currently it is generated by this function
> 
> https://github.com/envoyproxy/gateway/blob/71c09f285fcc88ddaf234a7c3864263d8a5bbbd0/internal/infrastructure/kubernetes/proxy/resource.go#L54-L57
> 
> It will be the same value, its format consists of a prefix(envoy), gateway namespace, gateway name, and 8 characters of the hashed name.

Thank you so much for the direct link.

> you'd better query by labels.

Due to requirements beyond my control, I've got to tuck Envoy Gateway behind EKS ALB ingress. Which uses service names as the destination. 

I'm interacting with the resources via labels, but the ALB uses service names

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: <arn>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/tags: environment=dev,Name=eg-public,application=eg,client=shared
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/waf-acl-id: <WAF>
    kubernetes.io/ingress.class: alb
  name: eg-ingress
  namespace: envoy-gateway-system
  labels:
    environment: dev
    team: blue
spec:
  defaultBackend:
    resource:
      kind: Service
      name: envoy-envoy-gateway-system-eg-656e766f
```

**Comment by arkodg** [comment]
I think this is a valid use case
need someone from the community to brainstorm on the drawbacks of exposing this knob apart from naming collisions (which should fall on the user)

**Comment by mingshun** [comment]
I also want to put Envoy Gateway behind EKS ALB ingress. And I encounter the same problem. Is there any update here?

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers 
I'm a +1 on this, it makes it easier to author infra intent

**Comment by cnvergence** [comment]
+1 even for multiple envoys per gateway deployments

**Comment by quyenhoang96** [comment]
+1

**Comment by arkodg** [comment]
can be solved using the newly added `patch` field in https://github.com/envoyproxy/gateway/issues/2716
```
apiVersion: http://gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  logging:
    level:
      default: warn
  provider:
    kubernetes:
      envoyService:
        patch:
          value:
            metadata:
              name: custom-name
        type: ClusterIP
    type: Kubernetes
```

**Comment by davem-git** [comment]
When i specify a name, my gateway doesn't standup.

**Comment by davem-git** [comment]
Sure thing. I applied 

```yaml
apiVersion: http://gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  logging:
    level:
      default: warn
  provider:
    kubernetes:
      envoyService:
        patch:
          value:
            metadata:
              name: custom-name
        type: Loadbalancer
    type: Kubernetes
```
The service standup fine with the propername. When I go to deploy the gateway, it doesn't work 
I get 

```sh
❯ kubectl get gateway
NAME            CLASS           ADDRESS   PROGRAMMED   AGE
envoy   envoy             False        3m52s
```
I revert the changes and it creates the standard loadblancer with the long name

```sh
❯ kubectl get gateway
NAME            CLASS           ADDRESS         PROGRAMMED   AGE
envoy   envoy   13.64.208.227   True         34m
```
