### ISSUE TITLE
Multiple Reference Grant for specific service in the same namespace didn't work as expected.

### ISSUE THREAD

**Issue by ardikabs** [envoyproxy/gateway#2149]
*Description*:
If we separate `HTTPRoute` into a central namespace and place all related backends into their respective namespaces, this will necessitate the use of a `ReferenceGrant`. In our scenario, we include a `ReferenceGrant` as part of each application deployment, that refers to its Kubernetes Service. 
Everything seems working fine, but as soon as we add another application deployment in the existing namespace (that is contains an existing application with its `ReferenceGrant`), HTTPRoute starts showing an inconsistent status that shows `Backend ref to service <namespace>/<service_name> not permitted by any ReferenceGrant`.

*Initial Finding*:

We think this is because of inconsistent steps between these line of code:
* For finding the reference of `ReferenceGrant` for the associated service.
https://github.com/envoyproxy/gateway/blob/defed574484e2708933d5f911b8bfc35e7ac8ee2/internal/provider/kubernetes/controller.go#L496-L504

* For validating when referring to `ReferenceGrant` for the HTTPRoute.
https://github.com/envoyproxy/gateway/blob/defed574484e2708933d5f911b8bfc35e7ac8ee2/internal/gatewayapi/validate.go#L678-L682

The filtering mechanism only checks after the From spec, meaning, the first match with its `From` will be used. While on validation, it will check thoroughly on the `To` spec.

*Repro steps*:
Assuming you have deployed 3 services of Echoserver in the `testing` namespace.

Apply these `ReferenceGrant` manifests:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: echoserver-1-rg
  namespace: testing
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Service
      name: echoserver-1
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: echoserver-2-rg
  namespace: testing
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Service
      name: echoserver-2
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: echoserver-3-rg
  namespace: testing
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Service
      name: echoserver-3
```

Apply these for HTTPRoute manifests,

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: sample-01
  namespace: envoy-gateway-system
spec:
  hostnames:
  - playground.internal
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gateway
    namespace: envoy-gateway-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: echoserver-1
      namespace: testing
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /echo1a
  - backendRefs:
    - group: ""
      kind: Service
      name: echoserver-2
      namespace: testing
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /echo2
  - backendRefs:
    - group: ""
      kind: Service
      name: echoserver-3
      namespace: testing
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /echo3
```

*Environment*:
v0.5.0 Envoy Gateway, but a similar code still exists in the recent version.
