### ISSUE TITLE
Question regarding HTTPS listeners

### ISSUE THREAD

**Issue by root-io** [envoyproxy/gateway#2159]
*Description*:
I am having issue using Gateway, I've bee using version from v0.5.0 to latest, today I tried v0.6.0 but still not able to make it work.

My services are accessible with HTTP but not HTTPS.

The same exact config works days/weeks ago using latest but I had CORS errors, then realized it was not CORS because my services returns correct CORS headers but it was because the endpoint was offline randomly. Am I doing something wrong? Thanks!

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/common-name: example.com
spec:
  gatewayClassName: eg
  listeners:
    - name: http-web
      protocol: HTTP
      hostname: example.com
      port: 80
    - name: http-subdomain1
      protocol: HTTP
      hostname: subdomain1.example.com
      port: 80
    - name: http-subdomain1-alias
      protocol: HTTP
      hostname: subdomain1-alias.example.com
      port: 80
    - name: http-subdomain2
      protocol: HTTP
      hostname: subdomain2.example.com
      port: 80
    - name: https-web
      protocol: HTTPS
      port: 443
      hostname: example.com
      tls:
        certificateRefs:
        - kind: Secret
          group: ""
          name: eg-https
    - name: https-subdomain1
      protocol: HTTPS
      port: 443
      hostname: subdomain1.example.com
      tls:
        certificateRefs:
        - kind: Secret
          group: ""
          name: eg-https
    - name: https-subdomain1-alias
      protocol: HTTPS
      port: 443
      hostname: subdomain1-alias.example.com
      tls:
        certificateRefs:
        - kind: Secret
          group: ""
          name: eg-https
    - name: https-subdomain2
      protocol: HTTPS
      port: 443
      hostname: subdomain2.example.com
      tls:
        certificateRefs:
        - kind: Secret
          group: ""
          name: eg-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo
spec:
  parentRefs:
    - name: eg
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: foo
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
            hostname: subdomain1.example.com
            port: 443
  hostnames:
    - subdomain1.example.com
    - subdomain1-alias.example.com
---
apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
    service: foo
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
      version: v1
  template:
    metadata:
      labels:
        app: foo
        version: v1
    spec:
      serviceAccountName: foo
      containers:
        - image: example/foo
          name: foo
          ports:
            - containerPort: 3000
```

**Comment by ionutvilie** [comment]
@arkodg  I ended up here searching for https in the issues. At first, this infinite loop looked like a bug but apparently, it is the desired behavior and documented in the API specs.

I have found a working example:

- one HTTPRoute is bound to the HTTP listener by configuring the `sectionName` in `spec.parentRefs`
https://github.com/kubernetes-sigs/gateway-api/blob/main/examples/standard/http-redirect.yaml#L45
- the second HTTPRoute must be bound to the HTTPS listener using the same configuration otherwise it won't work.
https://github.com/kubernetes-sigs/gateway-api/blob/main/examples/standard/http-redirect.yaml#L62


My working example.

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: tls-redirect
  namespace: prod
spec:
  parentRefs:
    - kind: Gateway
      name: envoy-gateway
      namespace: kube-public
      sectionName: http
  hostnames:
    - "*.ak1pro.n1l.ro"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: homarr-prod
  namespace: prod
spec:
  parentRefs:
    - kind: Gateway
      name: envoy-gateway
      namespace: kube-public
      sectionName: https
  hostnames:
    - "homarr.ak1pro.n1l.ro"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: homarr
          port: 80
```
