### ISSUE TITLE
AND NOT style matches for RateLimiting

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2193]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Consider this config
```
cat <<EOF | kubectl apply -f -
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: jwt-backend
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend
  jwt:
    providers:
    - name: example
      remoteJWKS:
        uri: https://test.eu.auth0.com/.well-known/jwks.json
      claimToHeaders:
      - claim: email
        header: x-user-email
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy 
metadata:
  name: policy-httproute
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend
    namespace: envoy
  rateLimit:
    type: Global
    global:
      rules:
      - clientSelectors:
        - headers:
          - name: x-user-email
            value: myemail@gmail.com
        limit:
          requests: 10
          unit: Minute
    - clientSelectors:
      - headers:
        - type: Distinct
          name: x-claim-email
      limit:
        requests: 5
        unit: Minute
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: eg
      namespace: envoy
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
EOF
```

I want to allow [myemail@gmail.com](mailto:myemail@gmail.com) user to 10 req/min but all other user 5 req/min.
But with this config [myemail@gmail.com](mailto:myemail@gmail.com) user is getting 429 after 5 requests.

Relates to https://envoyproxy.slack.com/archives/C03E6NHLESV/p1699784524023299

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
thinking out loud, this use case can be achieved in two ways
1.  by adding a `dontMatch` field

```
    - clientSelectors:
      - headers:
        - type: Distinct
          name: x-claim-email
        - type: Exact
           name: x-claim-email
           dontMatch: true
           value: myemail@gmail.com
```

2. by adding a `except` field
```
    - clientSelectors:
      - headers:
        - type: Distinct
          name: x-claim-email
         except:
           headers:    
           - type: Exact
              name: x-claim-email
              value: myemail@gmail.com
```

**Comment by slayer321** [comment]
I'm new to this part of the code , will like to learn an implement this feature. 
/assign

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
hey @slayer321 still planning on working on this issue ?

**Comment by slayer321** [comment]
Hey @arkodg , currently stuck with some other stuff .. will not be able to work on this issue as of now.

**Comment by rudrakhp** [comment]
@arkodg interested in picking up this issue, thanks!

**Comment by arkodg** [comment]
great thanks @rudrakhp, suggest breaking up the work into multiple PRs (API, Implementation, Docs/E2E)

**Comment by rudrakhp** [comment]
@arkodg raised API PR to support this in both header and source matches. Preferred the `dontMatch` approach, went with another name though.

**Comment by arkodg** [comment]
keeping this issue open to track completion of docs and e2e

**Comment by rudrakhp** [comment]
@arkodg E2E tests in PR #4452 is failing with following reason:
```
2024-10-16T11:30:45.0052006Z          Error:        Received unexpected error:
2024-10-16T11:30:45.0055244Z                        BackendTrafficPolicy.gateway.envoyproxy.io "ratelimit-anded-headers-with-invert" is invalid: spec.rateLimit.global.rules[0].clientSelectors[0].headers[1]: Duplicate value: map[string]interface {}{"name":"x-user-name"}
```
I noticed that the `HeaderMatch` list is defined as a `+listType=map` in CEL validations, with `+listMapKey=name`. This restricts rate limit filters with multiple header match filters with same `name` (example below).
```
  rateLimit:
    type: Global
    global:
      rules:
        - clientSelectors:
            - headers:
                - name: x-user-name
                  type: Distinct
                - name: x-user-name
                  type: Exact
                  value: admin
                  invert: true
          limit:
            requests: 3
            unit: Hour
```
I think a API fix is needed to change the `+listType=set`, unless there was a specific reason `map` was chosen?

PS: I would also remove `invert` in `SourceCIDRMatch` since the xDS APIs don't provide a means to do that today. Playing around with CIDR ranges would probably render invert redundant in this case.
