### ISSUE TITLE
Invalid naming for merged gateway container ports

### ISSUE THREAD

**Issue by TasdidurRahman** [envoyproxy/gateway#2221]
*Description*:
envoy deployment is not being created properly. container port name is invalid. 
*  error msg is attached to the logs section *

*Repro steps*:
```yaml
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  mergeGateways: true
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: my-gw
  namespace: envoy-pg
spec:
  gatewayClassName: eg
  listeners:
  - name: foo
    protocol: TCP
    port: 8088
    allowedRoutes:
      kinds:
      - kind: TCPRoute
```

the above yamls will reproduce the error 

* diagnosis 
in case of `merged-gateway=true`, while creating the deployment the container port name is created with by truncateToSixChars(`gw-namespace`+`-`+`gw-name`) + `-` + some_hash (i observed this to be six, not sure) . the case is , in this process the last char after truncate can be `-` and as the next is always `-` it creates an invalid name! 
>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
envoygateway release 0.6.0

*Logs*:
```
2023-11-20T09:03:12.366Z	ERROR	infrastructure	runner/runner.go:70	failed to create new infra	{"runner": "infrastructure", "error": "failed to create or update deployment envoy-gateway-system/envoy-eg-d8c59e83: for Create: Deployment.apps \"envoy-eg-d8c59e83\" is invalid: spec.template.spec.containers[0].ports[0].name: Invalid value: \"envoy--3d04c434\": must not contain consecutive hyphens", "errorVerbose": "Deployment.apps \"envoy-eg-d8c59e83\" is invalid: spec.template.spec.containers[0].ports[0].name: Invalid value: \"envoy--3d04c434\": must not contain consecutive hyphens\nfor Create\ngithub.com/envoyproxy/gateway/internal/infrastructure/kubernetes.(*InfraClient).CreateOrUpdate.func1\n\t/home/runner/work/gateway/gateway/internal/infrastructure/kubernetes/infra_client.go:34\nk8s.io/client-go/util/retry.OnError.func1\n\t/home/runner/go/pkg/mod/k8s.io/client-go@v0.28.3/util/retry/util.go:51\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/wait.go:145\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/backoff.go:461\nk8s.io/client-go/util/retry.OnError\n\t/home/runner/go/pkg/mod/k8s.io/client-go@v0.28.3/util/retry/util.go:50\nk8s.io/client-go/util/retry.RetryOnConflict\n\t/home/runner/go/pkg/mod/k8s.io/client-go@v0.28.3/util/retry/util.go:104\ngithub.com/envoyproxy/gateway/internal/infrastructure/kubernetes.(*InfraClient).CreateOrUpdate\n\t/home/runner/work/gateway/gateway/internal/infrastructure/kubernetes/infra_client.go:29\ngithub.com/envoyproxy/gateway/internal/infrastructure/kubernetes.(*Infra).createOrUpdateDeployment\n\t/home/runner/work/gateway/gateway/internal/infrastructure/kubernetes/infra_resource.go:77\ngithub.com/envoyproxy/gateway/internal/infrastructure/kubernetes.(*Infra).createOrUpdate\n\t/home/runner/work/gateway/gateway/internal/infrastructure/kubernetes/infra.go:63\ngithub.com/envoyproxy/gateway/internal/infrastructure/kubernetes.(*Infra).CreateOrUpdateProxyInfra\n\t/home/runner/work/gateway/gateway/internal/infrastructure/kubernetes/proxy_infra.go:27\ngithub.com/envoyproxy/gateway/internal/infrastructure/runner.(*Runner).subscribeToProxyInfraIR.func1\n\t/home/runner/work/gateway/gateway/internal/infrastructure/runner/runner.go:69\ngithub.com/envoyproxy/gateway/internal/message.HandleSubscription[...]\n\t/home/runner/work/gateway/gateway/internal/message/watchutil.go:76\ngithub.com/envoyproxy/gateway/internal/infrastructure/runner.(*Runner).subscribeToProxyInfraIR\n\t/home/runner/work/gateway/gateway/internal/infrastructure/runner/runner.go:57\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/asm_amd64.s:1650\nfailed to create or update deployment envoy-gateway-system/envoy-eg-d8c59e83\ngithub.com/envoyproxy/gateway/internal/infrastructure/kubernetes.(*Infra).createOrUpdate\n\t/home/runner/work/gateway/gateway/internal/infrastructure/kubernetes/infra.go:64\ngithub.com/envoyproxy/gateway/internal/infrastructure/kubernetes.(*Infra).CreateOrUpdateProxyInfra\n\t/home/runner/work/gateway/gateway/internal/infrastructure/kubernetes/proxy_infra.go:27\ngithub.com/envoyproxy/gateway/internal/infrastructure/runner.(*Runner).subscribeToProxyInfraIR.func1\n\t/home/runner/work/gateway/gateway/internal/infrastructure/runner/runner.go:69\ngithub.com/envoyproxy/gateway/internal/message.HandleSubscription[...]\n\t/home/runner/work/gateway/gateway/internal/message/watchutil.go:76\ngithub.com/envoyproxy/gateway/internal/infrastructure/runner.(*Runner).subscribeToProxyInfraIR\n\t/home/runner/work/gateway/gateway/internal/infrastructure/runner/runner.go:57\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/asm_amd64.s:1650"}
```
