### ISSUE TITLE
Two or more BackendTrafficPolicy cause collision for ratelimit

### ISSUE THREAD

**Issue by mazzy89** [envoyproxy/gateway#2225]
*Description*:

When two TrafficBackendPolicy are applied for rate limiting a GRPCROUTE. rate limit service reports several error `Error loading configuration: duplicate descriptor composite key`

*Repro steps*:

```yaml

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: serviceA-ratelimit-all-ips
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GRPCRoute
    name: serviceA
    namespace: default
  rateLimit:
    type: Global
    global:
      rules:
        - clientSelectors:
            - sourceCIDR:
                value: 0.0.0.0/0
                type: distinct
          limit:
            requests: 15
            unit: Hour
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: serviceB-ratelimit-all-ips
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GRPCRoute
    name: serviceB
    namespace: default
  rateLimit:
    type: Global
    global:
      rules:
        - clientSelectors:
            - sourceCIDR:
                value: 0.0.0.0/0
                type: distinct
          limit:
            requests: 300
            unit: Hour
```

*Environment*:
v0.6.0 envoy gateway release + rate limiter deployed with redis 

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by ardikabs** [comment]
We are facing this one as well, which happening for the `Exact` type for the same CIDR on multiple HTTP Routes.

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: route-1-ratelimit-specific-ip
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: route-1
    namespace: envoy-gateway-system
  rateLimit:
    type: Global
    global:
      rules:
        - clientSelectors:
            - sourceCIDR:
                value: 192.168.0.10/32
                type: Exact
          limit:
            requests: 15
            unit: Hour
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: route-2-ratelimit-specific-ip
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: route-2
    namespace: envoy-gateway-system
  rateLimit:
    type: Global
    global:
      rules:
        - clientSelectors:
            - sourceCIDR:
                value: 192.168.0.10/32
                type: Exact
          limit:
            requests: 300
            unit: Hour

```

Apparently, it seems that because EG uses the same descriptor key for the `CIDRMatch`, and apply it to the same rate-limit domain, in this case, the gateway's listener name.

https://github.com/envoyproxy/gateway/blob/ae523a8ccb3219f44e34320e9300f82068853501/internal/xds/translator/ratelimit.go#L357-L371

Given the gateway's listener name with `envoy-gateway-system/eg/http`, and either `distinct` or `exact` type, the descriptor key will be generated like `envoy-gateway-system/eg/http.masked_remote_address_192.168.0.10/32`, and as because the `BackendTrafficPolicy` bounded to each `HTTPRoute`, then the descriptor key will be generated more than once.
