### ISSUE TITLE
Conflic control plan with linkerd 

### ISSUE THREAD

**Issue by quyenhoang96** [envoyproxy/gateway#2248]
When I config Envoy-Gateway https://github.com/envoyproxy/gateway.
Then I apply HTTPRoute, the control plan of linkerd watch resource of envoy-gateway, and change it. So it make the envoy-gateway error. Help me how to fix it.

```
name: linkerd-crds
repository: "https://helm.linkerd.io/stable"
version: 1.8.0
name: linkerd-control-plane
repository: https://helm.linkerd.io/stable
version: 1.16.6
```

**Comment by arkodg** [comment]
Can you share the config and status o/p ?
cc @kflynn

**Comment by kflynn** [comment]
@quyenhoang96 Hi, thanks for speaking up! 

It would be a big help to see the output of `kubectl get crds` as well as `kubectl get -o yaml httproute` for the Route that's being complained about. Thanks!!

**Comment by quyenhoang96** [comment]
Hi @arkodg @kflynn 
I install linkerd + envoy-gateway by argocd with config:
Linkerd config:
- Chart
```
  - name: linkerd-crds
    repository: "https://helm.linkerd.io/stable"
    version: 1.8.0
  - name: linkerd-control-plane
    repository: https://helm.linkerd.io/stable
    version: 1.16.6
```
values.yaml
```
linkerd-control-plane:
  highAvailability: false
  clusterDomain: cluster.local
  imagePullPolicy: IfNotPresent
  controllerLogLevel: info
  controllerLogFormat: plain
  controlPlaneTracing: false
  controlPlaneTracingNamespace: linkerd-jaeger
  linkerdVersion: stable-2.14.1
  enableEndpointSlices: true
  enablePodAntiAffinity: false
  enablePprof: false
  enablePodDisruptionBudget: false
  cniEnabled: false
  
linkerd-crds:
  enableHttpRoutes: false
```

Envoy-gateway config:
Chart.yaml
```
dependencies:
  - name: gateway-helm
    version: v0.0.0-latest
    repository: oci://docker.io/envoyproxy

apiVersion: v2
name: gateway-helm
description: The Helm chart for Envoy Gateway
type: application

version: v0.0.0-latest
appVersion: "latest"
```
values.yaml
```
gateway-helm:
  deployment:
    envoyGateway:
      image:
        repository: docker.io/envoyproxy/gateway-dev
        tag: 'latest'
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    ports:
      - name: grpc
        port: 18000
        targetPort: 18000
      - name: ratelimit
        port: 18001
        targetPort: 18001
    replicas: 1
    pod:
      annotations: {}
      labels: {}

  config:
    envoyGateway:
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      provider:
        type: Kubernetes
      logging:
        level:
          default: info
    extensionApis:
      enableEnvoyPatchPolicy: true

  envoyGatewayMetricsService:
    ports:
      - name: http
        port: 19001
        protocol: TCP
        targetPort: 19001

  createNamespace: false

  kubernetesClusterDomain: cluster.local

  certgen:
    job:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
      ttlSecondsAfterFinished: 50
    rbac:
      annotations: {}
      labels: {}
```
gateway + route config:
```
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: config
  namespace: envoy-gateway-system
spec:
  logging:
    level:
      default: info
  telemetry:
    tracing:
      provider:
        host: grafana-agent-traces.monitoring.svc.cluster.local
        port: 4317
        type: OpenTelemetry
      samplingRate: 100  # sample 100% of requests
    accessLog:
      settings:
        - format:
            type: Text
            text: |
              [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
          sinks:
            - type: File
              file:
                path: /dev/stdout
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
        container:
          image: envoyproxy/envoy:v1.28-latest
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
      envoyService:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "0"
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-3-2021-06
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: TCP
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "2"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "5"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.connection_termination.enabled=true
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-admin
  namespace: envoy-gateway-system
spec:
  ports:
    - protocol: TCP
      port: 19000
      targetPort: 19000
      name: admin
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: shared-gw
    gateway.envoyproxy.io/owning-gateway-namespace: gateway
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: config
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: shared-gw
  namespace: gateway
spec:
  gatewayClassName: gateway-class
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: "*.xxx.xxx.io"
      allowedRoutes:
        namespaces:
          from: All
```
And when I apply HTTPRoute, it show as bellow
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"HTTPRoute","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"bookstore"},"name":"bar-route","namespace":"engine"},"spec":{"hostnames":["api-v2.engine.dev.g7y.io"],"parentRefs":[{"name":"shared-gw","namespace":"gateway"}],"rules":[{"backendRefs":[{"name":"bookstore","port":8081,"weight":1}],"matches":[{"path":{"type":"PathPrefix","value":"/v1/books"}}]}]}}
  creationTimestamp: '2023-11-28T16:10:27Z'
  generation: 1
  labels:
    argocd.argoproj.io/instance: bookstore
  name: bar-route
  namespace: xxxx
  resourceVersion: '10689339'
  uid: 87a083f4-852a-4d4f-a0bf-3674e5b822db
spec:
  hostnames:
    - "api.xxx.xxx.io"
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-gw
      namespace: gateway
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: bookstore
          port: 8081
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /v1/books
status:
  parents: []
```

parent of status It has been overwritten

And log of linked:
<img width="1455" alt="Screenshot 2023-11-29 at 06 57 59" src="https://github.com/envoyproxy/gateway/assets/120354221/f5c71722-d71c-4a33-ab45-92529fc8d587">
