### ISSUE TITLE
Support fined-grained access control in SecurityPolicy 

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#2250]
## Relates to
https://github.com/envoyproxy/gateway/issues/1845

## What is this?
EG can leverage [RBAC](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/rbac) for implementing fine-grained access control, at both the `Gateway` and `xRoute` level.

The principal, obtained through the authentication process (such as OIDC, JWT, etc.), serves as the basis for defining access control policies.  Source IP-based access control can also be supported in this model.

The below is roughly how API will look like, but it's just an initial idea and definitely needs more input.
## API outline

```yaml
kind: SecurityPolicy
metadata:
  name: rbac-example
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: http-route
  jwt:   # a jwt or oidc configuration is needed to obtain the principal
  ......  
  authorization:
  - principals: ["john"]
    permissions:
      methods: ["GET", "POST"]
      paths: ["/foo", "/bar"]

```
Reference:https://github.com/envoyproxy/envoy/issues/7913

- [x] [Allow/Deny IP Subnets](https://github.com/envoyproxy/gateway/issues/2462)
- [x] [Authorization based on JWT claim ](https://github.com/envoyproxy/gateway/issues/3367)
- [ ] [Authorization based on Basic Auth Username](https://github.com/envoyproxy/gateway/issues/3624) https://github.com/envoyproxy/gateway/issues/2947
- [ ] Authorization based on client cert
- [ ] Authorization based on identity extracted from an arbitrary HTTP header

**Comment by arkodg** [comment]
@zhaohuabing 
* can't the `paths` and `methods` be limited by the `HTTPRoute` match fields ?
* can't the `principal` be limited by the `issuer` field in JWT https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#jwtprovider ?

**Comment by zhaohuabing** [comment]
> @zhaohuabing
> 
> * can't the `paths` and `methods` be limited by the `HTTPRoute` match fields ?

I would suggest not to go this route because:
* It could get tricky, especially when the policy targets a gateway.  
* Separate of concerns:  `SecurityPolicy`  and `HTTPRoute` may be created by different roles, such as app developers and administrators

> * can't the `principal` be limited by the `issuer` field in JWT https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#jwtprovider ?

You mean `sub`  field?

**Comment by zetaab** [comment]
@zhaohuabing if you use api outline that is mentioned in first post, it does not support "action" mentioned in https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#config-rbac-v3-rbac

so instead the api spec should be something like

```
kind: SecurityPolicy
metadata:
  name: rbac-example
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: http-route
  jwt:   # a jwt or oidc configuration is needed to obtain the principal
  ......  
  authorization:
  - action: ALLOW
    policies:
    - principals:
      - <array of https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#envoy-v3-api-msg-config-rbac-v3-policy >
      permissions:
      - <array of https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#envoy-v3-api-msg-config-rbac-v3-permission >
      condition: # is this needed?
```
