### ISSUE TITLE
MergeGateways: nil pointer dereference

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#2282]
*Description*:
When using using the `MergeGateways` feature, the K8s provider's Deployment and Service reconciliations fail after restarting Envoy Gateway. The implementation assumes that the owning GatewayClass of these resources is already present in the resource tree: [service](https://github.com/envoyproxy/gateway/blob/52af65e2d35d6d8cbd02e3b8257d1784b0f31dd6/internal/provider/kubernetes/predicates.go#L183C26-L183C26), [deployment](https://github.com/envoyproxy/gateway/blob/52af65e2d35d6d8cbd02e3b8257d1784b0f31dd6/internal/provider/kubernetes/predicates.go#L316). It's possible that during the initial reconciliation of core resources, the Gateway API resources tree is not yet synced. 

*Repro steps*:
Apply the [quickstart config](https://github.com/envoyproxy/gateway/releases/download/latest/quickstart.yaml) with the following modifications to Gateway and EnvoyProxy resources: 

```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy-proxy
    namespace: envoy-gateway-system
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  namespace: envoy-gateway-system
  name: envoy-proxy
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
  mergeGateways: true
```

Wait for envoy deployment and service to be ready. Restart Envoy Gateway and observe panic. 

*Environment*:
K8s: kind cluster, v1.27.3
Envoy Gateway: v0.0.0-latest

*Logs*:
```
[...]
runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 362 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1045d6420?, 0x105fca6c0})
        /workspace/go/src/github.com/envoyproxy/gateway/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x10?})
        /workspace/go/src/github.com/envoyproxy/gateway/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x78
panic({0x1045d6420?, 0x105fca6c0?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/envoyproxy/gateway/internal/provider/kubernetes.(*gatewayAPIReconciler).validateServiceForReconcile(0x140001ce9c0, {0x104a69df8?, 0x14000263180?})
        /workspace/go/src/github.com/envoyproxy/gateway/internal/provider/kubernetes/predicates.go:183 +0xb0
[...]

```
