### ISSUE TITLE
Support setting common TLS properties on downstream listeners

### ISSUE THREAD

**Issue by liorokman** [envoyproxy/gateway#2286]
*Description*:

Support the following attributes in `ClientTrafficPolicy`:

```yaml
 tls: # optional
    version: # optional
      min: string # optional
      max: string # optional
    ciphers: []Enum(list of supported cipher suites...) # optional
    ecdhCurves: []string # optional
    alpnProtocols: []Enum(h2/http-1.1) # optional
```

These are all part of the proposed content of the `ClientTrafficPolicy` specified in #1846 ( proposal: ClientTrafficPolicy ).

Since all of these attributes are optional, not specifying any of them would translate to the same Envoy configuration as before this feature.

*Relevant Links*:

The configuration provided in the `ClientTrafficPolicy` would be translated to Envoy's [TlsParameters](https://www.envoyproxy.io/docs/envoy/v1.28.0/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlsparameters) configuration.
