### ISSUE TITLE
support EnvoyPatchPolicy when enabling mergeGateways

### ISSUE THREAD

**Issue by apjoseph** [envoyproxy/gateway#2308]
*Description*:
when mergeGateways is true, EnvoyPatchPolicies will not be picked up.

*Repro steps*:
set mergeGateways to true, create an EnvoyPatchPolicy. 

*Environment*:
> 0.0.0-latest (12/12/2023)

**Comment by shawnh2** [comment]
It seems EnvoyPatchPolicy feature is not supported when `mergeGateways` is enabled.

https://github.com/envoyproxy/gateway/blob/52946bef5132a302b6f5edd6d154062f35906e22/internal/gatewayapi/envoypatchpolicy.go#L40

Currently, EnvoyPatchPolicy can be only applied for per Gateway. I am not sure whether MergeGateways should support EnvoyPatchPolicy? cc @arkodg @cnvergence 

If we do, the `targetRef` of EnvoyPatchPolicy should be `GatewayClass` instead of `Gateway`, it makes more sense to me.

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: custom-response-patch-policy
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass # Gateway
    name: eg
    namespace: default
```

**Comment by zirain** [comment]
@kflynn PTAL

**Comment by apjoseph** [comment]
As a side comment on patching, I think the generic EnvoyPatchPolicy would benefit from being split up into more targeted CRDs

I'd prefer something like

`HttpRoutePatchPolicy`
`HttpListenerPolicy`

with name/namespace/label-based selectors so that you can target specific HttpRoutes and listeners to patch. I think ~95% of users will mostly be patching filters. So you could have the following  

EnvoyHTTPRoutePatchPolicy

```yaml
filterPatches:
  match:
   - type: type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
     replace:
       - op: add 
         path: /typed_per_filter_config/allow_credentials
         value:  true 
``` 

EnvoyHttpListenerPatchPolicy

```yaml
filterPatches:
  match:
   - type: type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
      - op: add
         path: /typed_filter_config/bypass_cors_preflight
         value:  true 
``` 

The current approach has the RouteConfiguration as the most granular patch level -which is highly problematic since it requires the user to know the order of the routes -and there is no obvious mechanism to enforce/determine the specific order for routes -so that's going to result in people resorting to all kinds of nasty hacks to attempt to apply route-specific functionality. 

Just yesterday, I needed to make a patch to specify `bypass_cors_preflight: true ` That's not some edge-case esoteric configuration tweak - it's basically required in order to use an OIDC frontend with a JWT backend API. To do this I needed to apply a listener patch at:
`/filter_chains/0/filters/0/typed_config/http_filters/0/typed_config/bypass_cors_preflight` Such a patch is extremely fragile and fills me with dread. yet there is no way for me to avoid it. 

A targeted selector based approach would be:

1) be much more powerful 
2) provide a dramatically improved user experience (I am new to envoy and can attest that it took me a quite a bit of trial and error to correctly apply a patch.)    
3) produce dramatically more stable configurations. 

I realize the EnvoyPatchPolicy is intended more as an escape hatch than as a permanent solution (hence why it's disabled by default), but if even the webdev 101 JWT + OIDC case requires a patch to work right now -then I think its safe most gateway users are going to heavily be heavily reliant on patches in the short to medium term. Thus I think it is better to address that reality head on with a more targeted approach.
