### ISSUE TITLE
Cannot listen host 80/443 when set `hostNetwork=true`

### ISSUE THREAD

**Issue by zzjin** [envoyproxy/gateway#2310]
*Description*:
When use eg at bare-metal env but without any other lb support, we can set `hostNetwork=true` to listen node machine's port.
But at previous commit, we cannot listen port below 1024.

*Repro steps*:
Setup eg with `mergeGateways=true` and `hostNetwork=true`, and apply demo GatewayClass&Gateway, 

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        pod:
          hostNetwork: true
      envoyService:
        type: NodePort
  mergeGateways: true
---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: sealos-system
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: wildcard-cert
```

*Environment*:
envoy gateway version: main(9aebfdc)

*logs*

Deployment gateway listen on host port 10080&10443

May be fixed by: #2309

**Comment by arkodg** [comment]
@zzjin the deployment should be reached only via the service, and not directly. The service is still exposed on `80`. What IP are you using ? NodeIP or Svc Cluster IP ?

**Comment by zzjin** [comment]
> @zzjin the deployment should be reached only via the service, and not directly. The service is still exposed on `80`. What IP are you using ? NodeIP or Svc Cluster IP ?

NodeIP.

Just want it works like `ingress-nginx`, which can listen host's port when there have no working load-balancers environment like k3s/kind.

**Comment by ilnurkhal** [comment]
>we can set hostNetwork=true

[ It looks ](https://github.com/envoyproxy/gateway/blob/main/api/v1alpha1/shared_types.go#L119)like we can't.  

I bet this setting hadn't any effect
```yaml
envoyDeployment:
  pod:
    hostNetwork: true
```

**Comment by arkodg** [comment]
closing this issue, since it can be worked around with above patch
@ilnurkhal you are most likely hitting https://github.com/envoyproxy/gateway/issues/3226

**Comment by ilnurkhal** [comment]
> > we can set hostNetwork=true
> 
> [ It looks ](https://github.com/envoyproxy/gateway/blob/main/api/v1alpha1/shared_types.go#L119)like we can't.
> 
> I bet this setting hadn't any effect
> 
> ```yaml
> envoyDeployment:
>   pod:
>     hostNetwork: true
> ```
> 
> Try this
> 
> ```yaml
> envoyDeployment:
>   patch:
>     value:
>       spec:
>         template:
>           spec:
>             hostNetwork: true
> ```

After short digging and running envoyProxy with `hostNetwork: true`, I've got this log in envoy data plane pods
```bash
2024-05-03 14:28:24.229][1][warning][config] [./source/extensions/config_subscription/grpc/grpc_stream.h:193] DeltaAggregatedResources gRPC config stream to xds_cluster closed since 48s ago: 14, no healthy upstream
[2024-05-03 14:28:33.481][1][warning][config] [./source/extensions/config_subscription/grpc/grpc_stream.h:193] DeltaAggregatedResources gRPC config stream to xds_cluster closed since 57s ago: 14, no healthy upstream
[2024-05-03 14:29:02.662][1][warning][config] [./source/extensions/config_subscription/grpc/grpc_stream.h:193] DeltaAggregatedResources gRPC config stream to xds_cluster closed since 87s ago: 14, no healthy upstream
[2024-05-03 14:29:28.067][1][warning][config] [./source/extensions/config_subscription/grpc/grpc_stream.h:193] DeltaAggregatedResources gRPC config stream to xds_cluster closed since 112s ago: 14, no healthy upstream
```

I think it happens because of this `address` dataplane setting
```yaml
  endpoint:
    address:
      socket_address:
        address: envoy-gateway
        port_value: 18000
```

Perhaps host's network ns cannot resolve short k8s service name (`envoy-gateway`).  I think you can workaround this problem by using service ip address instead of service name
