### ISSUE TITLE
JWT SecurityPolicy blocks CORS preflight requests, breaking OIDC + JWT flow

### ISSUE THREAD

**Issue by apjoseph** [envoyproxy/gateway#2312]
*Description*:
the JWT configuration in the Security filter does not include the `bypass_cors_preflight` [configuration option](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-jwtauthentication). Without this setting, OPTIONS requests are blocked unless the JWT is provided. 

If the JWT is being passed through cookies with a standard OIDC frontend / JWT backend setup then the credentials won't be included since the preflight request needs to include the   `Access-Control-Allow-Credentials: true` response header` before credentials will be sent.

I think bypass_cors_preflight should be set to true by default. I can't think of a good reason why someone would want to require a JWT for OPTIONS requests since Envoy doesn't even send OPTIONS requests down to the backend service. As a result the backend application can't customize the response. So blocking by default will just confuse people while providing no real benefit.

**Comment by zirain** [comment]
cc @zhaohuabing

**Comment by zhaohuabing** [comment]
I agree that `bypass_cors_preflight` should be set by true by default. But I'm not 100% if there're any security concerns on this. Would love more inputs from@arkodg @envoyproxy/web-maintainers .

**Comment by apjoseph** [comment]
@zhaohuabing Another potential solution is to allow different security policies to be applied when a different method is specified with the same path. This was actually my attempted workaround when I first encountered the issue. I created two http routes:

`api-route`

```
        matches:
          - path:
              type: PathPrefix
              value: /
```

api-route-cors
```
        matches:
          - path:
              type: PathPrefix
              value: /
           method: OPTIONS
```              

and then created corresponding SecurityPolicies for both HttpRoutes. I only included the JWT section in the SecurityPolicy for `api-route`.  I assumed this would prevent OPTIONS requests from being blocked; however when looking at the response from egctl I found that it was being applied to both HttpRoutes BUT only in some instances. Other times it would remove JWT auth from BOTH HttpRoutes -depending on which security policy was applied last. 

I am not sure whether this is intended behavior or not, but it was counter intuitive to me as I would have expected all attributes of a match to be taken into account when applying a security policy if they are in separate routes -especially since the security policy is explicitly bound to an HTTPRoute

I like your approach of just turning the `bypass_cors_preflight` on by default though. It would be highly annoying to need to configure separate HttpRoute objects just for CORS.

**Comment by ardikabs** [comment]
> We can either:
> 
> * set `bypass_cors_preflight` as true by default, or
> * leave the envoy false default, and expose `bypass_cors_preflight` knob to the API
> 
> I prefer to just set `bypass_cors_preflight` as true by default. But I'm not 100% sure if there are any security concerns on this. Would love more inputs from @arkodg @envoyproxy/gateway-maintainers

I was once concerned with `bypass_cors_preflight` https://github.com/envoyproxy/gateway/issues/1930, but as per @arkodg https://github.com/envoyproxy/gateway/issues/1930#issuecomment-1789452101, it seems that it is intended to have it disabled by default, and configured through CORS policy.

**Comment by arkodg** [comment]
@apjoseph can you also set the `cors` config within `BackendTrafficPolicy` and try ?
we should make a note of this in the docs so others dont hit this issue

**Comment by apjoseph** [comment]
@arkodg confirmed that the field is missing when defining the cors block in SecurityPolicy :

```yaml
            typedPerFilterConfig:
              envoy.filters.http.cors:
                '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                allowCredentials: true
                allowHeaders: '*'
                allowMethods: '*'
                allowOriginStringMatch:
                - suffix: web.dev.example.io
                maxAge: "600"

```

**Comment by arkodg** [comment]
@apjoseph not sure I understand.

if you setup cors in the `SecurityPolicy` https://gateway.envoyproxy.io/latest/user/cors/#configuration with `allowCredentials` set to `true` https://gateway.envoyproxy.io/latest/api/extension_types/#cors you should be pass the JWT back from the browser to the backend

**Comment by apjoseph** [comment]
@arkodg I would be able to -but without  `bypass_cors_preflight` enabled, the OPTIONS request for the route I'm trying to pass it to returns a 401 response that doesnt't contain the allow credentials CORS header. So the browser will never make the request in the first place.

The same issue is reported in multiple places, for instance in istio/istio/issues/36911 

In the pull request adding the flag on EnvoyProxy, the contributors specifically state that it [has to be explicitly enabled](https://github.com/envoyproxy/envoy/pull/9004#issuecomment-553541237) but frustratingly don't mention what the default setting is in the official documentation.

As you can see from [this comment](https://github.com/istio/istio/issues/36911#issuecomment-1020230989) I think most people assume it is enabled by default when CORS is enabled and are deeply confused as to why Envoy's default behavior is to break any oauth2 application that uses an API with a different subdomain.

**Comment by zhaohuabing** [comment]
@apjoseph JWT filter is placed after CORS filter in the filterchain.  According to Envoy doc, "This filter will be used to respond to preflight OPTIONS requests. Any legal OPTIONS requests will be responded directly by the filter and will not be passed to the next filter in the filter chain."  So a preflight request should not reach the JWT filter and get authenticated?

https://github.com/envoyproxy/gateway/blob/d7d411c37ca07a289bee9ac9c80e2ffa748ce1aa/internal/xds/translator/httpfilters.go#L89-L103

**Comment by arkodg** [comment]
@zhaohuabing I think its worth further debugging https://github.com/envoyproxy/gateway/issues/2312#issuecomment-1866051928 to understand why the `OPTIONS` request is getting a `401` in your test above instead of returning after hitting the cors filter because it doesnt match with https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/cors_filter#cors

**Comment by zhaohuabing** [comment]
@apjoseph @arkodg 

I verified the below SecurityPolicy with cors and jwt works.

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: cors-example
  namespace: default
spec:
  cors:
    allowHeaders:
    - x-header-1
    - x-header-2
    allowMethods:
    - GET
    - POST
    allowOrigins:
    - type: RegularExpression
      value: .*\.foo\.com
    exposeHeaders:
    - x-header-3
    - x-header-4
  jwt:
    providers:
    - name: example
      remoteJWKS:
        uri: https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/jwt/jwks.json
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend
```

```bash
$ curl -H "Origin: http://www.foo.com" \
>   -H "Host: www.example.com" \
>   -H "Access-Control-Request-Method: GET" \
>   -X OPTIONS -v -s \
>   http://$GATEWAY_HOST/ \
>   1> /dev/null
*   Trying ::1:8888...
* TCP_NODELAY set
* Connected to localhost (::1) port 8888 (#0)
> OPTIONS / HTTP/1.1
> Host: www.example.com
> User-Agent: curl/7.68.0
> Accept: */*
> Origin: http://www.foo.com
> Access-Control-Request-Method: GET
> 
Handling connection for 8888
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< access-control-allow-origin: http://www.foo.com
< access-control-allow-methods: GET, POST
< access-control-allow-headers: x-header-1, x-header-2
< access-control-expose-headers: x-header-3, x-header-4
< date: Fri, 22 Dec 2023 02:56:29 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host localhost left intact
```

The CORS user doc is misleading, the cors setting in the user doc is 

```yaml
  cors:
    allowOrigins:
    - type: Exact
      value: "www.foo.com"
```

but the test command is 

```bash
curl -H "Origin: http://www.foo.com" \
  -H "Host: www.example.com" \
  -H "Access-Control-Request-Method: GET" \
  -X OPTIONS -v -s \
  http://$GATEWAY_HOST \
  1> /dev/null
``` 

Since the  `http://www.foo.com` origin in the test command doesn't match the `www.foo.com` in the SecurityPolicy, the CORS filter ignores this OPTION request and passes it down to the JWT filter. That's why it gets a `401 Unauthorized` response. 

I'll raise a PR to fix the doc.

@apjoseph I suspect your preflight request failed for a similar reason. Could you please try to verify with `curl` and share the SecurityPolicy and the curl command you use?
