### ISSUE TITLE
Using backendTrafficPolicies to patch  route resources may lead to unexpected results.

### ISSUE THREAD

**Issue by tmsnan** [envoyproxy/gateway#2366]
*Description*:

Using backendTrafficPolicies to patch  httproute resources may lead to unexpected results.

For example:
```
- apiVersion: gateway.networking.k8s.io/v1
  kind: Gateway
  metadata:
    namespace: envoy-gateway
    name: gateway-1
  spec:
    gatewayClassName: envoy-gateway-class
    listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
httpRoutes:
- apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    namespace: default
    name: httproute-1
  spec:
    hostnames:
    - gateway.envoyproxy.io
    parentRefs:
    - namespace: envoy-gateway
      name: gateway-1
      sectionName: http
    rules:
    - matches:
      - path:
          value: "/"
      backendRefs:
      - name: service-1
        port: 8080
- apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    namespace: default
    name: httproute-1-mirror
  spec:
    hostnames:
    - gateway.envoyproxy.io
    parentRefs:
    - namespace: envoy-gateway
      name: gateway-1
      sectionName: http
    rules:
    - matches:
      - path:
          value: "/mirror"
      backendRefs:
      - name: service-1
        port: 8080
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: BackendTrafficPolicy
  metadata:
    namespace: default
    name: policy-for-route
  spec:
    targetRef:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: httproute-1
      namespace: default
    rateLimit:
      type: Global
      global:
        rules:
        - clientSelectors:
          - sourceCIDR:
              type: "Distinct"
              value: 192.168.0.0/16
          limit:
            requests: 20
            unit: Hour
```
backendTrafficPolicies will be patched to `httproute-1` and `httproute-1-mirror`

Reason:
https://github.com/envoyproxy/gateway/blob/bda0055a2cc53af10bbf7ca9b1834bb960e37a07/internal/gatewayapi/helpers.go#L381
https://github.com/envoyproxy/gateway/blob/bda0055a2cc53af10bbf7ca9b1834bb960e37a07/internal/gatewayapi/backendtrafficpolicy.go#L270

Maybe add `/`  to the prefix `%s/%s/%s/`
