### ISSUE TITLE
Cannot apply EnvoyPatchPolicy when enabling mergeGateways with custom namespace gateway.

### ISSUE THREAD

**Issue by zzjin** [envoyproxy/gateway#2375]
*Description*:
When `MergeGateway` is set to true, and apply oen gateway cr other than default ns, `EnvoyPatchPolicy` do not work.

*Repro steps*:
Using latest main branch's image, and apply crds below:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  mergeGateways: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: envoy-gateway-system
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    provider:
      type: Kubernetes
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    extensionApis:
      enableEnvoyPatchPolicy: true

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: sealos-system
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: wildcard-cert

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: test-policy
  namespace: sealos-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: eg
    namespace: sealos-system
  type: JSONPatch
  jsonPatches:
  - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
    name: "sealos-system/eg/http"
    operation:
      op: add
      path: "/default_filter_chain/filters/0/typed_config/local_reply_config"
      value:
        mappers:
        - filter:
            status_code_filter:
              comparison:
                op: EQ
                value:
                  default_value: 404
                  runtime_key: key_b
          status_code: 406
          body:
            inline_string: "not acceptable"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sealos-desktop
  namespace: sealos
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
      sectionName: https
      namespace: sealos-system
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
      sectionName: http
      namespace: sealos-system
  hostnames:
    - "34.84.109.10.nip.io"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: desktop-frontend
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```

*Environment*:
eg main branch (2023-12-29)

*Logs*:
```
message: "unable to find xds resource
        type.googleapis.com/envoy.config.listener.v3.Listener: sealos-system/eg/http"
      reason: ResourceNotFound
      status: "False"
      type: Programmed
```

The namespace here is `sealos-system`, not the default `default` ns.
I've tested `EnvoyPatchPolicy`'s `spec.targetRef.namespace` to 'sealos-system','default','', but each fail with same error.

**Comment by cnvergence** [comment]
Isn't the https://github.com/envoyproxy/gateway/issues/2380 same issue?

**Comment by zhaohuabing** [comment]
@zzjin I successfully applied the EPP using the same resources that you shared in this issue.

I verified this in v1.4.1. Could you please test it again and verify that if it works for you?

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: test-policy
  namespace: sealos-system
spec:
  jsonPatches:
  - name: sealos-system/eg/http
    operation:
      op: add
      path: /default_filter_chain/filters/0/typed_config/local_reply_config
      value:
        mappers:
        - body:
            inline_string: not acceptable
          filter:
            status_code_filter:
              comparison:
                op: EQ
                value:
                  default_value: 404
                  runtime_key: key_b
          status_code: 406
    type: type.googleapis.com/envoy.config.listener.v3.Listener
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: eg
  type: JSONPatch
status:
  ancestors:
  - ancestorRef:
      group: gateway.networking.k8s.io
      kind: GatewayClass
      name: eg
    conditions:
    - lastTransitionTime: "2025-06-10T02:30:57Z"
      message: Policy has been accepted.
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-06-10T02:30:57Z"
      message: Patches have been successfully applied.
      reason: Programmed
      status: "True"
      type: Programmed
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
```

The patched xDS in envoy config dump:

```yaml
            defaultFilterChain:
              filters:
              - name: envoy.filters.network.http_connection_manager
                typedConfig:
                  '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager

                  ....

                  httpFilters:
                  - name: envoy.filters.http.router
                    typedConfig:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                      suppressEnvoyHeaders: true
                  localReplyConfig:
                    mappers:
                    - body:
                        inlineString: not acceptable
                      filter:
                        statusCodeFilter:
                          comparison:
                            value:
                              defaultValue: 404
                              runtimeKey: key_b
                      statusCode: 406
                  mergeSlashes: true
                  normalizePath: true
                  pathWithEscapedSlashesAction: UNESCAPE_AND_REDIRECT
                  rds:
                    configSource:
                      ads: {}
                      resourceApiVersion: V3
                    routeConfigName: sealos-system/eg/http
                  serverHeaderTransformation: PASS_THROUGH
                  statPrefix: http-10080
                  useRemoteAddress: true
              name: sealos-system/eg/http
```
