### ISSUE TITLE
EnvoyPatchPolicy failed when there is no httpRoute under gateway CR's namespace, with mergeGateway is enabled

### ISSUE THREAD

**Issue by zzjin** [envoyproxy/gateway#2380]
*Description*:
When using eg with `mergeGateway=true` and `enableEnvoyPatchPolicy=true`
There have some bug witch cause `EnvoyPatchPolicy` return error.

*Repro steps*:
1. Install latest eg from main branch.
2. Use aill-in-one yaml described below:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  mergeGateways: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: envoy-gateway-system
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    provider:
      type: Kubernetes
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    extensionApis:
      enableEnvoyPatchPolicy: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealos-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: sealos-system
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: test-policy
  namespace: sealos-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: eg
    namespace: sealos-system
  type: JSONPatch
  jsonPatches:
  - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
    name: "sealos-system/eg/http"
    operation:
      op: add
      path: "/default_filter_chain/filters/0/typed_config/local_reply_config"
      value:
        mappers:
        - filter:
            status_code_filter:
              comparison:
                op: EQ
                value:
                  default_value: 404
                  runtime_key: key_b
          status_code: 406
          body:
            inline_string: "not acceptable"
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealos-backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: sealos-backend
  labels:
    app: backend
    service: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sealos-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      serviceAccountName: backend
      containers:
      - image: nginx
        name: backend
        ports:
          - containerPort: 80
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: sealos-backend
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
      namespace: sealos-system
      sectionName: http
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /


```

The main issue is here:
* first of all, we defined a `GatewayClass` and set `mergeGateway` and `enableEnvoyPatchPolicy`
* then we define one system level `Gateway`(witch allows other namespaces use this gateway) and set it's `EnvoyPatchPolicy` under namespace `sealos-system`
* last we define one product `deployment`, `service` and `HTTRoute` under it's own namespace `sealos-backend`(witch parentRef is pointing to `sealos-system`)

The error occurred.

**Note** 
At our use case, there is one gateway for our backends use(and many more gateway for their backends), but gateway's namespace have no HTTPRoute CR, all HTTPRoute CR are under it's own namespace.

**Updated**
When applying `deployment`, `service` and `HTTRoute` Under `Gateway`'s same namespace, all works fine. But I think there problem must be resolved.

*Environment*:
latest main branch's eg (2023-12-29)

*Logs*:
```
message: "unable to find xds resource
        type.googleapis.com/envoy.config.listener.v3.Listener: sealos-system/eg/http"
      reason: ResourceNotFound
      status: "False"
      type: Programmed
```
