### ISSUE TITLE
Support Compression

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2451]
*Description*:
Support Payload Compression

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

Envoy - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/compression/compression.html#compression

Upstream Issue - https://github.com/kubernetes-sigs/gateway-api/issues/1799

Relates to https://envoyproxy.slack.com/archives/C03E6NHLESV/p1705084783438099

**Comment by arkodg** [comment]
`BackendTrafficPolicy` seems like a good home for `compression` , and Envoy does have support for per route compression filters

**Comment by akhenakh** [comment]
For refs  here is a working patch for HTTPS, (warning the path to patch is different for HTTP `"/default_filter_chain/filters/0/typed_config/http_filters/0"`)

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: compressor-patch-policy
  namespace: envoy-gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
    namespace: envoy-gateway-system
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: envoy-gateway-system/eg/https
      operation:
        op: add
        path: "/filter_chains/0/filters/0/typed_config/http_filters/0"
        value:
          name: "envoy.filters.http.compressor"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor"
            compressor_library:
              name: text_optimized
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip"
                compression_level: BEST_SPEED
                compression_strategy: DEFAULT_STRATEGY
                memory_level: 8
                window_bits: 15
                chunk_size: 4096
            response_direction_config:
              remove_accept_encoding_header: true
              common_config:
                enabled:
                  default_value: true
                  runtime_key: response_direction_config_enabled
                content_type:
                  - "application/javascript"
                  - "application/json"
                  - "application/x-web-app-manifest+json"
                  - "application/xhtml+xml"
                  - "application/xml"
                  - "font/opentype"
                  - "image/svg+xml"
                  - "image/x-icon"
                  - "text/css"
                  - "text/html"
                  - "text/plain"
                  - "text/xml"
                min_content_length: 60
            request_direction_config:
              common_config:
                enabled:
                  default_value: false
                  runtime_key: request_direction_config_enabled
```

you should see a response with an `content-encoding: gzip` header for an HTTP/1.1 request with a `Accept-Encoding: deflate, gzip` header.
