### ISSUE TITLE
Support complete label in namespaceSelectorwatch

### ISSUE THREAD

**Issue by yeedove** [envoyproxy/gateway#2481]
*Description*:
`EnvoyGateway.Provider.Kubernetes.Wach.NamespaceSelectors`
NamespaceSelectors holds a list of labels that namespaces have to have in order to be watched.

The namespaceSelector can watch the namespace that has some key of label,  I think it might be better to use a map to achieve a complete label.

--

[optional *Relevant Links*:]
#1622

**Comment by arkodg** [comment]
yes `map` sounds good, any advantage of directly using the `metav1.LabelSelector` type https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#LabelSelector ?

**Comment by yeedove** [comment]
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: default
    env: foo
  name: foo
spec:
...
```

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: default
    env: bar
  name: bar
spec:
...
```
The current namespaceSelectors watch mode for Kubernetes provider only Support `env` label, not `env:bar` or `env:foo` label, and `metav1.LabelSelector` type or  `map[string]string` type can do it.
