### ISSUE TITLE
Filters for OIDC authentication mechanisms

### ISSUE THREAD

**Issue by sadovnikov** [envoyproxy/gateway#2496]
*Description*:

Currently, when OIDC and JWT authentication mechanisms are configured in the same `SecurityPolicy`, the OIDC is applied first. It ensures the presence of the bearer and refresh tokens in cookies, and adds the `Authorisation` header to the request. Then JWT is applied, validating the added header.

This setup works perfectly for browser requests. However, it prevents monitoring systems and regression tests, which provide a valid `Authorisation` header in the requests, from accessing the services on the same URLs. The OIDC mechanism kicks in first and redirects the requests to the login pages because of the missing cookies.

We suggest extending the configuration of, at least, the OIDC mechanism with the possibility of adding a header-based filter.
When implemented, the OIDC can be skipped if the `Authorization` header is present.

An example of the configuration:

```
  oidc:
    provider: {}
    clientID: ""
    scopes: []
    clientSecret: {}
    matches:
    - ifRequestHeader:
        name: Authorization
        valueRegex: Bearer.*
      onMatch: skip
```

Envoy Proxy supports Composite Filters, which support such decisions and therefore can be used to implement this functionality.

*Relevant Links*:

* The [Combining OIDC and JWT authentication](https://github.com/envoyproxy/gateway/discussions/2425) discussion
* Envoy [Composite Filters](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/composite_filter)

**Comment by zetaab** [comment]
@arkodg any comments to this one? As I see this is quite important feature to have possibility to use service with human users and machines.

**Comment by arkodg** [comment]
@zetaab @sadovnikov my hesitance is with including another field like `matches` within `oidc` . Today the request is matching header attributes defined within the `HTTPRoute` and the `SecurityPolicy` is applied to a `HTTPRoute`. Adding another `matches` within `oidc` is not required imo.

You could implement the same logic (https://github.com/envoyproxy/gateway/discussions/2425#discussioncomment-8141456) with 2 HTTPRoutes today
* Security Policy 1 with a `oidc` config that applies to a HTTPRoute1 which has your routing rules
* Security Policy 2 with a `jwt` config that applies to a HTTPRoute2 which has your routing rules along with extra matches such as  `BearerToken` is set && `OauthHMAC` is empty && `OauthExpires` is empty (will take precedence to the extra matches)

This should unblock you for now, but will end up causing some duplicate configuration for you.

You could also use a EnvoyPatchPolicy with a `pass_through_matcher` defined in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/oauth2/v3/oauth.proto#extensions-filters-http-oauth2-v3-oauth2config

A more long term would be to to figure out the right UX / field for this use case.

**Comment by sadovnikov** [comment]
@arkodg From my [discussion](https://github.com/envoyproxy/gateway/discussions/2425) with @zhaohuabing I understood that two HTTP Routes cannot be applied to the same host/path. It seems I read it wrong, it's just necessary to ensure the uniqueness of the "matches" in the routes. We'll give it a try

**Comment by zetaab** [comment]
here is the example of how it can be used currently https://gist.github.com/zetaab/31b835bfed5bdc7b2a3e29bc6557e3c1

What that does?
- it can have public paths which is allowed to everyone
- it have /login path which will make the OIDC flow and create cookies
- /api path which will work for both: humans (with token) and machines (with bearer token) (with two different identity providers)

However, if its used like this it means that application should have the logic to redirect to /login when its needed to use refresh token / create new token. 

tl;dr it works but its not pretty

**Comment by arkodg** [comment]
rethinking this one, if we add introduce a field - `skipIfJWTExists`, we can solve this, we may also need to then add another field `myJWTLivesInThisHeader`

**Comment by zhaohuabing** [comment]
Yeah, this sounds reasonable to me. I'll raise an issue in Envoy and try to support this in v1.3.0.

**Comment by arkodg** [comment]
@zhaohuabing envoy already supports this as highlighted in https://github.com/envoyproxy/gateway/issues/2496#issue-2097680500

A. API field is needed in EG that solves the use case

**Comment by StephenRobin** [comment]
It looks like the `pass_through_matcher` option in Envoy's oauth2 filter can be used to make this work.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/oauth2/v3/oauth.proto#envoy-v3-api-msg-extensions-filters-http-oauth2-v3-oauth2

I've tried the following patch and it appears to be working. 

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: oidc-and-jwt-patch
  namespace: example
spec:
  jsonPatches:
    - name: example/eg/https
      operation:
        op: add
        path: >-
          /filter_chains/0/filters/0/typed_config/http_filters/0/typed_config/config/pass_through_matcher
        value:
          - name: Authorization
            prefix_match: Bearer
      type: type.googleapis.com/envoy.config.listener.v3.Listener
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  type: JSONPatch
```

I guess the fix for this issue is to change the [xds translator](https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/oidc.go#L135) so that if jwt auth is also specified in the gateway CRD then `pass_through_matcher` is added to the xDS.

It would be nice if oidc and basic auth also worked well together. In this case the logic would need extending to pass through when "Authorization: Basic...." is in the headers, but the default filter order would also need changing to put the basic auth filter after oidc.
