### ISSUE TITLE
Security policy from different route interferes authentication

### ISSUE THREAD

**Issue by sadovnikov** [envoyproxy/gateway#2507]
*Description*:

Reusing the same `Gateway`, we created two pairs of `HTTPRoute` with matching `SecurityPolicy`, which use identical IDP settings for OIDC. The HTTP Routes are on different hosts. Both hosts are CNAMEs to the same A-record, with the IP address of the Gateway service

| hostname | path | http route | security policy |
| --- | --- | --- | --- |
| reference-apps-twin.platform-staging.gcp.internal.xxx.org | /cbdp-k8s-sample-eg | cbdp-k8s-sample-web-eg | cbdp-k8s-sample-web-eg |
| reference-apps.platform-staging.gcp.internal.xxx.org | /cbdp-k8s-sample-pr-195 | cbdp-k8s-sample-web-pr-195 | cbdp-k8s-sample-web-pr-195 |

Opening of https://reference-apps.platform-staging.gcp.internal.xxx.org/cbdp-k8s-sample-pr-195 in an incognito tab goes through the login process and the application page gets opened.

However, the opening of https://reference-apps-twin.platform-staging.gcp.internal.xxx.org/cbdp-k8s-sample-eg/ in a new incognito tab gives "too many redirects" after the login page. This link starts working when the `cbdp-k8s-sample-web-pr-195` Security Policy, which belongs to a different HTTP Route, is deleted.

*Repro steps*:

* the `envoy-proxy-min-err.json` is the Envoy configuration with both Security Policies present
* the `envoy-proxy-min-ok.json` is the Envoy configuration without the `cbdp-k8s-sample-web-pr-195` Security Policy
* YAML of HTTP Routes and Security Policies will be added in the issue comment 

[envoy-proxy-min-err.json](https://github.com/envoyproxy/gateway/files/14065885/envoy-proxy-min-err.json)
[envoy-proxy-min-ok.json](https://github.com/envoyproxy/gateway/files/14065886/envoy-proxy-min-ok.json)

*Environment*:

Envoy Gateway is deployed using the `v0.0.0-latest` Helm chart. 

```
dependencies:
- name: gateway-helm
  version: v0.0.0-latest
  repository: oci://docker.io/envoyproxy
  alias: eg
```

Container 

```
Containers:
  envoy:
    Container ID:  containerd://b8648147d345bcf50d6f68aab09149ece2737c29d72fb0c6fb18115cb946699d
    Image:         envoyproxy/envoy-dev:latest
    Image ID:      docker.io/envoyproxy/envoy-dev@sha256:9d9493167f9b35e0047ce1463df8b679bb5847f1d2b7bbb9d8fb432b08e97bab
```

*Logs*:

* attached `envoy-log.txt` is the envoy proxy log from "too many redirects"

[envoy-log.txt](https://github.com/envoyproxy/gateway/files/14065884/envoy-log.txt)

**Comment by sadovnikov** [comment]
HTTP Routes

```
apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    labels:
      app.kubernetes.io/instance: reference-apps-spring-boot-eg
    name: cbdp-k8s-sample-web-eg
    namespace: reference-apps
  spec:
    hostnames:
    - reference-apps-twin.platform-staging.gcp.internal.xxx.org
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-host-default
      namespace: envoy-gateway-system
    rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: cbdp-k8s-sample-web-eg
        port: 80
        weight: 1
      matches:
      - path:
          type: PathPrefix
          value: /cbdp-k8s-sample-eg
      timeouts:
        request: 10s
- apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    annotations:
      meta.helm.sh/release-name: cbdp-k8s-sample-pr-195-preemptible
      meta.helm.sh/release-namespace: reference-apps
    labels:
      app.kubernetes.io/managed-by: Helm
    name: cbdp-k8s-sample-web-pr-195
    namespace: reference-apps
  spec:
    hostnames:
    - reference-apps.platform-staging.gcp.internal.xxx.org
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-host-default
      namespace: envoy-gateway-system
    rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: cbdp-k8s-sample-web-pr-195
        port: 80
        weight: 1
      matches:
      - path:
          type: PathPrefix
          value: /cbdp-k8s-sample-pr-195
      timeouts:
        request: 10s
kind: List
```

Security Policies

```
apiVersion: v1
items:
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: SecurityPolicy
  metadata:
    labels:
      app.kubernetes.io/instance: reference-apps-spring-boot-eg
    name: cbdp-k8s-sample-web-eg
    namespace: reference-apps
  spec:
    oidc:
      clientID: d8c0c5a5-5b45-4566-9fb2-367e62c397ee
      clientSecret:
        group: ""
        kind: Secret
        name: oauth2-secret-eg
      provider:
        issuer: https://login.microsoftonline.com/a87b6d3d-d85e-4d9b-8704-6aed76a49444/v2.0
      scopes:
      - api://d8c0c5a5-5b45-4566-9fb2-367e62c397ee/oidc
      - offline_access
    targetRef:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: cbdp-k8s-sample-web-eg
      namespace: reference-apps
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: SecurityPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: cbdp-k8s-sample-pr-195-preemptible
      meta.helm.sh/release-namespace: reference-apps
    labels:
      app.kubernetes.io/managed-by: Helm
    name: cbdp-k8s-sample-web-pr-195
    namespace: reference-apps
  spec:
    oidc:
      clientID: d8c0c5a5-5b45-4566-9fb2-367e62c397ee
      clientSecret:
        group: ""
        kind: Secret
        name: oauth2-secret-eg
      provider:
        issuer: https://login.microsoftonline.com/a87b6d3d-d85e-4d9b-8704-6aed76a49444/v2.0
      scopes:
      - api://d8c0c5a5-5b45-4566-9fb2-367e62c397ee/oidc
      - offline_access
    targetRef:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: cbdp-k8s-sample-web-pr-195
      namespace: reference-apps
kind: List
```

**Comment by akhenakh** [comment]
I can confirm it happened on our installations as well, while applying an ODIC security policy to on isolated httproute (hostname + path prefix)

```yaml
  hostnames:
  - xxxxx.aaaa.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
    namespace: envoy-gateway-system
  rules:
  - backendRefs:
    - kind: Service
      name: auth-generator-api
      port: 8085
    matches:
    - path:
        type: PathPrefix
        value: /
```
the OIDC redirection triggered on some others HTTPRoute

for example a route supposed to match /v1/users triggered the OIDC redirect with the url /v1/users/ (trailing slash)rather than the usual 404.

When removing the security policy on xxxxx.aaaa.com, the expected 404 on zzzzzz.aaaa.com reappeared.
