### ISSUE TITLE
Consider splitting up health check into active and passive to accommodate outlier detection

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2511]
*Description*:
>Describe the issue.

Active health checking was recently added https://gateway.envoyproxy.io/latest/api/extension_types/#healthcheck as a `healthCheck` field within `BackendTrafficPolicy`

Should we move this field into `healthCheck.active` allowing us to also accommodate outlier detection (passive health checks )under the same `healthCheck` field https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier, else we'd have to create another top level field for outlier detection

Option 1 (Current)
```
healthCheck:
  timeout:
  interval:
  type: HTTP
  http:
    path: /healthz
outlierDetection:
  consecutive5xxErrors: 7      
```
Option 2
```
healthCheck:
  active:
    timeout:
    interval:
    type: HTTP
    http:
      path: /healthz
  passive:
    consecutive5xxErrors: 7      
```    

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers @envoyproxy/gateway-reviewers

**Comment by zirain** [comment]
can you give a example about the API your proposal?

**Comment by arkodg** [comment]
Option 1 (Current)
```
healthCheck:
  timeout:
  interval:
  type: HTTP
  http:
    path: /healthz
outlierDetection:
  consecutive5xxErrors: 7      
```


Option 2
```
healthCheck:
  active:
    timeout:
    interval:
    type: HTTP
    http:
      path: /healthz
  passive:
    consecutive5xxErrors: 7      
```
