### ISSUE TITLE
envoyproxy needs restart before securitypolicy takes action

### ISSUE THREAD

**Issue by zetaab** [envoyproxy/gateway#2521]
*Description*:
I am trying to add oidc+jwt authentication to single HTTPRoute. However, after the configuration is in place, it does not take action before the envoyproxy is restarted.

*Repro steps*:

first create httproute

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echoserver-ext
  namespace: echoserver
spec:
  parentRefs:
  - name: external
    namespace: envoy-gateway-system-external
    sectionName: https
  hostnames:
  - eg-ext.example.com
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: echoserver
      port: 80
      weight: 1
    matches:    
    - path:
        type: PathPrefix
        value: /
```

```
% curl https://eg-ext.example.com -I
HTTP/2 200 
```

Works like should. Then apply securitypolicy:

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: echoserver-ext-oidc
  namespace: echoserver
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: echoserver-ext
  oidc:
    provider:
      issuer: https://xxx
    clientID: yy
    scopes:
    - openid
    - email
    - profile
    - groups
    clientSecret:
      group: ""
      kind: Secret
      name: my-app-client-secret
  jwt:
    providers:
    - name: kaas
      claimToHeaders:
      - claim: email
        header: x-email
      - claim: groups
        header: x-groups
      - claim: name
        header: x-name
      - claim: sub
        header: x-sub
      remoteJWKS:
        uri: https://xxx/.well-known/jwks.json
```

```
% kubectl apply -f external/app.yaml -n echoserver
httproute.gateway.networking.k8s.io/echoserver-ext configured
securitypolicy.gateway.envoyproxy.io/echoserver-ext-oidc created
 % kubectl get securitypolicy -n echoserver
NAME                  STATUS     AGE
echoserver-ext-oidc   Accepted   7s
```

Still target working without authentication?
```
% curl https://eg-ext.example.com -I
HTTP/2 200 
```

Restarting envoy and trying again:
```
% kubectl delete pod -l gateway.envoyproxy.io/owning-gateway-name=external  -n envoy-gateway-system-external 
pod "envoy-envoy-gateway-system-external-external-ad2cc5d0-dd7b5ghtl" deleted
% curl https://eg-ext.example.com -I
HTTP/2 302
```

Works like should. Why the restart is needed? 

*Environment*:
kube 1.29.1

*Logs*:
