### ISSUE TITLE
AND Header matches in ratelimiting not working

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2564]
*Description*:

Looks like a regression, unable to get ratelimiting to work when multiple header matches are ANDed together

Followed https://gateway.envoyproxy.io/latest/user/global-rate-limit/ and updated the `policy-httproute` to add 2 header matches

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: policy-httproute
  namespace: default
spec:
  rateLimit:
    global:
      rules:
      - clientSelectors:
        - headers:
          - name: x-user-id
            type: Exact
            value: one
          - name: x-user-org
            type: Exact
            value: acme
        limit:
          requests: 3
          unit: Hour
    type: Global
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: http-ratelimit
    namespace: default
```

```
for i in {1..4}; do curl -I --header "Host: ratelimit.example" --header "x-user-id: one" --header "x-user-org: acme" http://localhost/get ; sleep 1; done
HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Mon, 05 Feb 2024 17:31:18 GMT
content-length: 577
x-envoy-upstream-service-time: 0
server: envoy

HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Mon, 05 Feb 2024 17:31:19 GMT
content-length: 577
x-envoy-upstream-service-time: 0
server: envoy

HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Mon, 05 Feb 2024 17:31:20 GMT
content-length: 577
x-envoy-upstream-service-time: 0
server: envoy

HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Mon, 05 Feb 2024 17:31:21 GMT
content-length: 577
x-envoy-upstream-service-time: 0
server: envoy
```

The last  request should have been ratelimited
