### ISSUE TITLE
Configure Envoy Proxy fleet in different namespaces

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2629]
thinking out loud, potential API could look like
```
deploymentMode:
  watch:
    namespaces: .........
  deploy:
    envoy:
      namespaceType: GatewayNamespace  
```

* By default (when this field is unset), EG watches all resources in all namespaces, and depoys infra in the namespace where EG is running (`ControllerNamespace`)
* `watch.namespaces` can be used to set the specific namespaces to watch resources (Gateway, xRoute, Service etc)
* `deploy.envoy.namespaceType` can be used to specify to EG to deploy proxy infra to deploy envoy deployments in the namespace where the Gateway is created in. This option will need a helm knob too, to configure added permissions to be able to create deployments and services in other namespaces

_Originally posted by @arkodg in https://github.com/envoyproxy/gateway/issues/1117#issuecomment-1492387115_
