### ISSUE TITLE
Configure a limit in `envoy.resource_monitors.downstream_connections` resource monitor

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#2706]
> [2024-02-26 06:44:38.185][1][warning][main] [source/server/server.cc:923] There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.downstream_connections` resource monitor.

**Comment by yeedove** [comment]
To silence the warning log about not having a limit on active downstream connections in Envoy, we can consider setting a high default value.
```yaml
- name: envoy.resource_monitors.downstream_connections
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig
    max_downstream_connections: 2147483647
```
