### ISSUE TITLE
Question: Chrome Behavior With Traffic Splitting

### ISSUE THREAD

**Issue by mattbrandman** [envoyproxy/gateway#2809]
*Description*:
I have a configuration where traffic is split between two services 50/50. On every browser and curl this works except chrome. It seems that chrome somehow pins to a service even with splitting and then when the socket closes it might pin to the other service. 

```
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-stable
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8004
  selector:
    app: helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-canary
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8004
  selector:
    app: helloworld
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: helloworld-route
spec:
  parentRefs:
    - name: apps
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - hello.test.com
  rules:
  - backendRefs:
    - name: helloworld-service-stable
      namespace: helloworld
      port: 80
      weight: 50
    - name: helloworld-service-canary
      namespace: helloworld
      port: 80
      weight: 50
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-redirect
spec:
  parentRefs:
    - name: apps
      namespace: envoy-gateway
      sectionName: http
  hostnames:
    - hello.test.com
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
```

Not sure if this is expected or known behavior but makes it a bit hard to test canary rollouts locally. If anyone has ideas how to workaround would be very appreciated.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
