### ISSUE TITLE
Supression of X-Envoy headers breaks expected output of default log format

### ISSUE THREAD

**Issue by davidalger** [envoyproxy/gateway#2903]
*Description*:

After the changes in #2500 and #2585 logs no longer include the proper request path where path rewrites are used.
*Repro steps*:
If you apply the quickstart demo and then add a rule to the HTTPRoute:

```
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /rewrite
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /123
```

This request

```
curl -sv -H "Host: www.example.com" 'http://172.18.255.200/rewrite/something?foo=bar'
```

> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.
