### ISSUE TITLE
Generated yaml for installation carries unnecessary empty documents

### ISSUE THREAD

**Issue by wimnat** [envoyproxy/gateway#2927]
*Description*:

This ticket is created off the back of https://github.com/envoyproxy/gateway/issues/2860.

The YAML that is generated for installation of Envoy Gateway contains unnecessary empty YAML documents because the comment that describes each envoygateway CRD is put in to a separate YAML document than the CRD itself.

See the screenshot below.

![Screenshot 2024-03-12 at 12 26 54](https://github.com/envoyproxy/gateway/assets/7425606/5da9b46d-b325-44c0-9762-270e9ba6d70d)

>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Generally, these empty docs don't cause a problem when installing via Helm or with a direct `kubectl apply -f ...` because the empty docs get ignored.  However, it did cause an issue when trying to install via Jsonnet as the empty doc will cause std.parseYaml to error out.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Just download the latest https://github.com/envoyproxy/gateway/releases/download/latest/install.yaml file and scroll through until you find the envoygateway CRD comments.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

Observed in v0.6.0

*Logs*:
>Include the access logs and the Envoy logs.

N/A

**Comment by zirain** [comment]
@wimnat would like send a fix?

**Comment by zirain** [comment]
the root cause of this is the first line of generated crd file?
https://github.com/envoyproxy/gateway/blob/975ef6e8498e1fda635cf70d477c7370093fb645/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml#L1

these files generated by `controller-gen`, so I think jsonnet should fix this?

**Comment by wimnat** [comment]
@zirain can you link me `controller-gen` implementation and I can take a look.

We need to find whatever is inserting the comments in to the generated yaml because that's where the problem lies - if we remove the comment insertion the problem goes away.

Problem comment example:

```
---
# Source: gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: securitypolicies.gateway.envoyproxy.io
```
