### ISSUE TITLE
CORS: Enable strict CORS enforcement with direct preflight response option

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#2953]
The current `SecurityPolicy` CORS implementation forwards preflight requests down to the backend services if a request doesn't match its configured condition(origins, methods, headers, etc.) .  This makes the preflight response unpredictable, potentially allowing cross-origin requests even when they should be disallowed. 

Adding a configuration option to the CORS configuration, enabling direct preflight responses, would allow enforcement of strict CORS rules regardless of the backend behavior.

```
    cors:
      directResponse: true             // Send a direct response and disallow the cross-origin request when the request doesn't match
      allowOrigins:
      - "http://*.example.com"
      - "http://foo.bar.com"
      - "https://*"
      allowMethods:
      - GET
      - POST
      allowHeaders:
      - "x-header-1"
      - "x-header-2"
      exposeHeaders:
      - "x-header-3"
      - "x-header-4"
    
```

This depends on the upstream issue: https://github.com/envoyproxy/envoy/issues/14233
