### ISSUE TITLE
bug: duplicate port definition when using mergeGateway

### ISSUE THREAD

**Issue by zetaab** [envoyproxy/gateway#2964]
*Description*:
When using mergeGateway and creating multiple gateways which uses 10443 (https), it will lead to error

*Repro steps*:
1) create new gatewayclass with merge gateways enabled
2) create two different gateways to that gatewayclass

*Environment*:
eg 1.0.0

*Logs*:
```
 % kubectl rollout restart deployment/envoy-eg-internal-7f4ff7e4
Warning: spec.template.spec.containers[0].ports[2]: duplicate port definition with spec.template.spec.containers[0].ports[1]
```

when taking a look for the configuration:
```
        ports:
        - containerPort: 10080
          name: envoy-cfc433c8
          protocol: TCP
        - containerPort: 10443
          name: envoy-938fd695
          protocol: TCP
        - containerPort: 10443
          name: echose-ebb62894
          protocol: TCP
        - containerPort: 19001
          name: metrics
          protocol: TCP
```

that is incorrect, the containerport is unique it seems.
