### ISSUE TITLE
ReplacePrefixMatch not working 

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#2976]
```
  - filters:
    - requestRedirect:
        path:
          replacePrefixMatch: /
          type: ReplacePrefixMatch
        port: 8080
        scheme: https
        statusCode: 301
      type: RequestRedirect
    matches:
    - path:
        type: PathPrefix
        value: /api/foo/public/
```        

In the given example we want to simply delete the whole Prefix, replace it with /. However, what we see happening is a double slash:

GET https://REDACTED/api/foo/public/bar
      accept: application/json
      accept-encoding: gzip,deflate,br
    ← 301 Moved Permanently
      transfer-encoding: chunked
      connection: close
      location: https://REDACTED:8080//bar
