### ISSUE TITLE
Fix TCPKeepAlive config for TCPRoute

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3032]
The TCP keep-alive setting is specified in the IR, resulting in a keep-alive configuration for the TCP listener cluster. Typically, such settings are adjusted through a traffic policy, i'm not certain if this make sense in this context.

```
- name: "fourth-listener"
  address: "0.0.0.0"
  tcpKeepalive:
    probes: 10
  port: 10083
  destination:
    name: "tcp-route-dest"
    settings:
    - endpoints:
      - host: "1.2.3.4"
        port: 50000
```

_Originally posted by @alexwo in https://github.com/envoyproxy/gateway/pull/3004#discussion_r1538927285_
