### ISSUE TITLE
Envoy Gateway v1.0 should allow rate limiting to multiple hostnames

### ISSUE THREAD

**Issue by jbennett7** [envoyproxy/gateway#3079]
*Description*:
Envoy Gateway v1.0 should allow rate limiting to multiple hostnames. 

If the `httproute` specifies multiple `hostnames` and a `backendtrafficpolicy` with a global rate limit is assigned, via `targetRef`, to the `httproute`. Everything appears good. the policy is Accepted and True, however the rate limit will only work for one route and not the other.

Here is the manifests for the httproute and the backendtraffic policy
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: default-btp
  namespace: foobar
spec:
  rateLimit:
    global:
      rules:
      - limit:
          requests: 30
          unit: Second
    type: Global
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: default-route
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: default-route
  namespace: foobar
spec:
  hostnames:
  - route-one.domain.io
  - route-two.domain.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    namespace: envoy-gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: my-service
      port: 80
      weight: 1
    filters:
    - responseHeaderModifier:
        remove:
        - server
      type: ResponseHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /
```
When running the curl command for both routes, notice that the x-ratelimit is applied to the `.com` domain and not the `.io` domain:

```
19:27 Tue 2 $ curl -I https://route-two.domain.com
HTTP/2 200
content-type: application/json
date: Tue, 02 Apr 2024 23:27:26 GMT
cache-control: no-store, no-cache
expires: Thu, 01 Jan 1970 00:00:00 GMT
pragma: no-cache
x-ratelimit-limit: 30, 30;w=1
x-ratelimit-remaining: 29
x-ratelimit-reset: 1

19:27 Tue 2 $ curl -I https://route-one.domain.io
HTTP/2 200
content-type: application/json
date: Tue, 02 Apr 2024 23:27:39 GMT
cache-control: no-store, no-cache
expires: Thu, 01 Jan 1970 00:00:00 GMT
pragma: no-cache
```
Gateway Version

```
19:46 Tue 2 $ egctl version
client: v1.0.0
server:
- Name: envoy-gateway-7866f66c85-80396
  Namespace: envoy-gateway
  envoyGatewayVersion: v1.0.0
  envoyProxyVersion: distroless-v1.29.2
  gatewayAPIVersion: v1.0.0
  gitCommitID: 72c0cc757c7c4703dfc14345dbd995240af663d7
  shutdownManagerVersion: 72c0cc7
- Name: envoy-gateway-7866f66c85-k0rye
  Namespace: envoy-gateway
  envoyGatewayVersion: v1.0.0
  envoyProxyVersion: distroless-v1.29.2
  gatewayAPIVersion: v1.0.0
  gitCommitID: 72c0cc757c7c4703dfc14345dbd995240af663d7
  shutdownManagerVersion: 72c0cc7
```

*Repro steps*:
1. Create a httproute with multiple hostnames and a path.
2. Assign the httproute to a backendtrafficpolicy with a rate limit.
3. Curl both routes, observe the response x-ratelimit.

**Comment by arkodg** [comment]
can you also share the ` envoy-gateway` Gateway ?

**Comment by arkodg** [comment]
Cannot repro this one @jbennett7 

here's what I did

* Followed the quick start to install Envoy Gateway https://gateway.envoyproxy.io/v1.0.0/user/quickstart/
* Followed the first few steps in https://gateway.envoyproxy.io/v1.0.0/user/traffic/global-rate-limit/ to enable RateLimiting and install Redis
* Added a similar BTP and Route (updated `namespace`, `service`, and `gateway`)
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: default-btp
  namespace: default
spec:
  rateLimit:
    global:
      rules:
      - limit:
          requests: 30
          unit: Second
    type: Global
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: default-route
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: default-route
  namespace: default
spec:
  hostnames:
  - route-one.domain.io
  - route-two.domain.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
    namespace: default
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: backend
      port: 3000 
      weight: 1
    filters:
    - responseHeaderModifier:
        remove:
        - server
      type: ResponseHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /
 ```
 
 here are the traffic tests, you can see the RateLimit headers for both the hostnames
 ```
$ for i in {1..4}; do curl -I --header "Host: route-one.domain.io" http://${GATEWAY_HOST}/get ; sleep 1; done
HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Fri, 05 Apr 2024 09:50:59 GMT
content-length: 461
x-ratelimit-limit: 30, 30;w=1
x-ratelimit-remaining: 29
x-ratelimit-reset: 1

HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Fri, 05 Apr 2024 09:51:00 GMT
content-length: 461
x-ratelimit-limit: 30, 30;w=1
x-ratelimit-remaining: 29
x-ratelimit-reset: 1

HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Fri, 05 Apr 2024 09:51:01 GMT
content-length: 461
x-ratelimit-limit: 30, 30;w=1
x-ratelimit-remaining: 29
x-ratelimit-reset: 1

HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Fri, 05 Apr 2024 09:51:02 GMT
content-length: 461
x-ratelimit-limit: 30, 30;w=1
x-ratelimit-remaining: 29
x-ratelimit-reset: 1

$ for i in {1..4}; do curl -I --header "Host: route-two.domain.com" http://${GATEWAY_HOST}/get ; sleep 1; done
HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Fri, 05 Apr 2024 09:51:21 GMT
content-length: 462
x-ratelimit-limit: 30, 30;w=1
x-ratelimit-remaining: 29
x-ratelimit-reset: 1

HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Fri, 05 Apr 2024 09:51:22 GMT
content-length: 462
x-ratelimit-limit: 30, 30;w=1
x-ratelimit-remaining: 29
x-ratelimit-reset: 1

HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Fri, 05 Apr 2024 09:51:23 GMT
content-length: 462
x-ratelimit-limit: 30, 30;w=1
x-ratelimit-remaining: 29
x-ratelimit-reset: 1

HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Fri, 05 Apr 2024 09:51:24 GMT
content-length: 462
x-ratelimit-limit: 30, 30;w=1
x-ratelimit-remaining: 29
x-ratelimit-reset: 1

 ```
        
Suggest looking into the `status` of different resources to see if you are hitting any configuration issues
