### ISSUE TITLE
Support optional JWT authentication for an endpoint

### ISSUE THREAD

**Issue by ardikabs** [envoyproxy/gateway#3081]
*Description*:
There is a use case when both authenticated and non-authenticated users can access an endpoint, it would help like when it is intended to apply a rate limit based on the user login, say authenticated users will have a dedicated rate limit threshold compared to non-authenticated users.

For example on integrating optional JWT authentication with rate limit:

1. `/api/v1/auth/generate-otp` (authenticated): 100 requests per hour per user login
2. `/api/v1/auth/generate-otp` (non-authenticated): 10 requests per hour per originating IP address

Since our implementation is built upon the specifications outlined in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-jwtrequirement, accomplishing this can be done using the following configuration:

```
name: envoy.filters.http.jwt_authn
typed_config:
  '@type': type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
  providers:
    provider_example:
      forward: true
      remote_jwks:
        cache_duration: 300s
        http_uri:
          cluster: raw_githubusercontent_com_443
          timeout: 10s
          uri: https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/jwt/jwks.json
  requirement_map:
    optional_auth:
      requires_any:
        requirements:
          - provider_name: provider_example
          - allow_missing: {}
```

**Proposal**
Therefore in the Envoy Gateway implementation, we can add a new field such as `allowMissing` to the `SecurityPolicy` to support this case, like below:

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: jwt-example
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: foo
  jwt:
    providers:
    - name: example
      remoteJWKS:
        uri: https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/jwt/jwks.json
    allowMissing: true
```

Luckily, as we already have the `requiresAny` implementation in the code, integrating it above should be straightforward.
https://github.com/envoyproxy/gateway/blob/941679847a80caa4dda9783cf94aa153bb2837b8/internal/xds/translator/jwt.go#L168-L176

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
