### ISSUE TITLE
Single listener is considered for rate limiting

### ISSUE THREAD

**Issue by pratik705** [envoyproxy/gateway#3086]
*Description*:
I deployed a gateway with two listeners - HTTP and HTTPS. My intention is to configure rate limiting. However, upon configuring rate limiting, it is only configured for the last listener from the list.

For example: For following gateway[1], rate limiting is only configured for "http" listener. Please find[2]. 

[1]
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: osh-gateway
  namespace: openstack
  annotations:
    cert-manager.io/issuer: ca-issuer
spec:
  gatewayClassName: osh-gatewayclass
  listeners:
    - name: https
      protocol: HTTPS
      hostname: "*.pbandark.com"
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: osh-https
    - name: http
      protocol: HTTP
      port: 80
```

[2]
```
openstack/osh-gateway/http.httproute/openstack/nova-api-post-keypairs/rule/0/match/0/nova-api_pbandark_com_httproute/openstack/nova-api-post-keypairs/rule/0/match/0/nova-api_pbandark_com.masked_remote_address_0.0.0.0/0.remote_address: unit=MINUTE requests_per_unit=5, shadow_mode: false
```
*Repro steps*:
- Deploy envoy-gateway with version: 1.0.0
- Create gateway with multiple listeners
- Create BackendTrafficPolicy

*Environment*:
Envoy Gateway version: 1.0.0
K8s version: v1.26.11
