### ISSUE TITLE
Update Install docs to show how to install EG where the infrastructure/cluster provider is installing Gateway API CRD

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3094]
I looked into this. The gateway api maintainers [do not provide an upstream helm chart](https://github.com/kubernetes-sigs/gateway-api/issues/1590) that we can source as a dependency. 

Personally, I think that the envoy-gateway helm chart should leave the installation of these CRDs to the users: Just list it as a requirement, and link to their [installation docs](https://gateway-api.sigs.k8s.io/guides/#installing-gateway-api).

Due to this bundling of Gateway API  CRDs and envoy-gateway CRDs, using the helm chart gets a bit fiddly for us when installing into our Google Kubernetes Engine clusters:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway-system

helmCharts:
  - name: gateway-helm
    releaseName: envoy-gateway
    # The helm chart includes Gateway API, which we already install through a GKE Addon
    includeCRDs: false
    # GKE uses an older version of Gateway API than the latest helm chart
    # https://gateway.envoyproxy.io/v1.0.0/install/matrix/
    version: v0.5.0
    repo: oci://registry-1.docker.io/envoyproxy
    valuesFile: ./values.yaml

resources:
  - https://raw.githubusercontent.com/envoyproxy/gateway/v0.5.0/charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
  - https://raw.githubusercontent.com/envoyproxy/gateway/v0.5.0/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_authenticationfilters.yaml
  - https://raw.githubusercontent.com/envoyproxy/gateway/v0.5.0/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml
  - https://raw.githubusercontent.com/envoyproxy/gateway/v0.5.0/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_ratelimitfilters.yaml
```

_Originally posted by @djfinnoy in https://github.com/envoyproxy/gateway/issues/1721#issuecomment-2035558087_
