### ISSUE TITLE
Override default Envoy Proxy Bootstrap Configuration

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#31]
https://github.com/envoyproxy/gateway/issues/24 highlights the need for users to override xDS resources configured by
Envoy Gateway. Raising this issue to track how do you express this intent for the [Envoy Proxy Bootstrap Config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#config-bootstrap-v3-bootstrap) using the[ Gateway API](https://gateway-api.sigs.k8s.io)

here's how popular OSS projects do it
* Istio - [this](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ApplyTo) & [this](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ApplyTo)
* Contour allows the user to [attach a new bootstrap file](https://projectcontour.io/docs/v1.20.1/configuration/#bootstrap-config-file)
* Emissary allows the user to override a [subset of the bootstrap resources](https://www.getambassador.io/docs/emissary/2.2/topics/running/statistics/envoy-statsd/#envoy-statistics-with-statsd) 

Updated
- [x] Design doc https://github.com/envoyproxy/gateway/pull/1070
- [x] API Design https://github.com/envoyproxy/gateway/pull/1070
- [x] EnvoyProxy Bootstrap validation https://github.com/envoyproxy/gateway/pull/1109
- [x] Implement API https://github.com/envoyproxy/gateway/pull/1094
- [x] Update GatewayClass Status  based on EnvoyProxy validation https://github.com/envoyproxy/gateway/pull/1107
- [x] Implement `egctl` subcommand to generate default `bootstrap` https://github.com/envoyproxy/gateway/pull/1281
- [x] Docs https://github.com/envoyproxy/gateway/pull/1333

**Comment by danehans** [comment]
> Raising this issue to track how do you express this intent for the [Envoy Proxy Bootstrap Config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#config-bootstrap-v3-bootstrap) using the[ Gateway API](https://gateway-api.sigs.k8s.io/)

Currently, the bootstrap config is managed as a go template rendered by the Infra Manager and referenced as `--config-yaml` by the Envoy pod.  As the Envoy Gateway [Configuration API Design](https://github.com/envoyproxy/gateway/blob/main/docs/design/config-api.md#configuration-api-design) states:

> ... the managed Envoy proxies are configured dynamically through Kubernetes resources, primarily Gateway API objects. Optionally, the Envoy proxies can be configured by referencing the `EnvoyProxy` custom resource (CR) through `spec.parametersRef` of the managed GatewayClass.

I suggest extending the `EnvoyProxy` API type to support this use case. For example:

```go
// EnvoyProxySpec defines the desired state of EnvoyProxy.
type EnvoyProxySpec struct {
	// Bootstrap defines the desired state of the Envoy bootstrap config file.
        // If unspecified, default bootstrap config parameters are used.
	//
	// +optional
	Bootstrap *Bootstrap `json:"bootstrap,omitempty"`
}

// Bootstrap defines the desired state of the Envoy bootstrap configuration file.
type Bootstrap struct {
	// Xds defines xDS configuration parameters...
        // If unspecified, default bootstrap config parameters are used.
	//
	// +optional
	Xds *Xds `json:"xds,omitempty"`
}

// Xds defines desired xDS configuration parameters.
type Xds struct {
	// Address defines the address of the xDS server...
        // If unspecified, "envoy-gateway" is used.
	//
	// +optional
	Address *XdsAddress `json:"address,omitempty"`

	// Port defines the port of the xDS server...
        // If unspecified, 18000 is used.
	//
	// +optional
	Port *XdsPortNumber `json:"port,omitempty"`
}

type XdsAddress string
type XdsPortNumber int32
```

A user would then create the EnvoyProxy CRD and a GatewayClass that references it. For example:
```
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: example
  namespace: envoy-gateway-system
spec:
  bootstrap:
    xds:
      address: host.docker.internal # used to run EG locally
      port: 1234
  ...
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: config.gateway.envoyproxy.io
    kind: EnvoyProxy
    name: example
    namespace: envoy-gateway-system
```

Envoy Gateway will need to add support for `gatewayclass.spec.parametersRef`, get the referrenced EnvoyProxy, and validate its fields. For example, the EnvoyProxy should be rejected and surface appropriate status conditions if `bootstrap.xds.address` and/or `bootstrap.xds.port` do not match Envoy Gateway's config.

A drawback of this approach is that EG manages only one GatewayClass and all Gateways will use the same bootstrap config.
