### ISSUE TITLE
[Helm template] Support to define additional annotations for CRDS

### ISSUE THREAD

**Issue by daidv94** [envoyproxy/gateway#3280]
*Description*:
The problem is when ArgoCD deploys Envoy Gateway ( using the helm chart). This error is happening during the kubectl apply phase for your CRDs. It stores the entire spec as an annotation in the object, likely exceeding `262144 bytes` enforced by the K8s API server.

*Repro steps*:
- Deploy Envoy Gateway in K8s by using ArgoCD
- Press sync several time

*Screenshot*:
<img width="1319" alt="image" src="https://github.com/envoyproxy/gateway/assets/45174998/9c5abcd3-6e6a-413d-bf75-e570d301d3d8">
<img width="1179" alt="image" src="https://github.com/envoyproxy/gateway/assets/45174998/65a4e280-db2c-4dcd-a1aa-0748da62c0d2">

*Expectation*:
Could we add an option for users to define additional annotations for CRDs. For this corner case, it would be the `argocd.argoproj.io/sync-options: Replace=true`, maybe the CRDs could be defined like
```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
{{- with .Values.crds.additionAnnotations }}
{{- toYaml . | nindent 4 }}
{{- end }}
    controller-gen.kubebuilder.io/version: v0.15.0
  name: backendtrafficpolicies.gateway.envoyproxy.io
```
