### ISSUE TITLE
Unable to remove XRateLimitHeaders

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3400]
*Description*:
>Describe the issue.

Unable to remove the `x-ratelimit-*` headers using the `responseHeaderModifier` filter in HTTPRoute

```
    - responseHeaderModifier:
        remove:
        - x-ratelimit-limit
        - x-ratelimit-remaining
        - x-ratelimit-reset
      type: ResponseHeaderModifier
```

chatted with @cpakulski and @evacchi  who mentioned that these headers are special and are created by the ratelimit filter which add these [headers](https://github.com/envoyproxy/envoy/blob/4e51ba92fe9effd943f68568762c3b213ec818bd/api/envoy/extensions/common/ratelimit/v3/ratelimit.proto#L20C1-L35C2) after going through the hcm setting (route config) to [remove headers ](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#config-route-v3-routeconfiguration)
