### ISSUE TITLE
How to add context_extensions for ext-auth grpc

### ISSUE THREAD

**Issue by quyenhoang96** [envoyproxy/gateway#3460]
I use the ext-auth grpc to auth + authz for my service. But it need to some custom data. How can I push that data into ext-auth via header or context_extensions

Example.
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ext-auth-example
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: myapp
  extAuth:
    grpc:
      backendRef:
        name: grpc-ext-auth
        port: 9002
     headersForAuth:
       - x-user: abc
       - x-product-id: 123
       - x-provider: um
```

or
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ext-auth-example
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: myapp
  extAuth:
    grpc:
      backendRef:
        name: grpc-ext-auth
        port: 9002
     contextExtensions:
       - x-user: abc
       - x-product-id: 123
       - x-provider: um
```
