### ISSUE TITLE
Infra IR was updated, but no listeners were found

### ISSUE THREAD

**Issue by SerheoReutty** [envoyproxy/gateway#3491]
Greetings. Help me please. What am I doing wrong. 
I deployed envoy-gateway. 
Deployed custom-envoy-proxy-config, which says to create services with NodePort type.
I deployed gateway-class
And deployed gateway using tlc terminating, specifying my cluster-issuer.
But in namespace envoy I have no service or feed for my deployment. 
In the controller logs I see the following.

```
2024-05-27T09:30:22.088Z	INFO	xds-translator	runner/runner.go:55	received an update	{"runner": "xds-translator"}
2024-05-27T09:30:22.088Z	INFO	infrastructure	runner/runner.go:78	received an update	{"runner": "infrastructure"}
2024-05-27T09:30:22.088Z	INFO	xds-server	runner/runner.go:140	received an update	{"runner": "xds-server"}
2024-05-27T09:30:22.088Z	INFO	infrastructure	runner/runner.go:89	Infra IR was updated, but no listeners were found. Skipping infra creation.	{"runner": "infrastructure"}
2024-05-27T09:30:22.088Z	INFO	provider	kubernetes/status_updater.go:140	received a status update	{"runner": "provider", "namespace": "test-envoy", "name": "test-gateway"}
```
As far as I understand, it's complaining that it didn't find the necessary listeners that I specified in my gateway. But I don't understand how this should work. I think in my gateway I specify which port and host is being listened to. I must be wrong!?

Attached below is the manifest text of my custom config, gateway-class and gateway manifests

Custom-config
```---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
```

gateway-class
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: envoy-gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
```

gateway
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: test-gateway
  annotations:
    cert-manager.io/cluster-issuer: "my-cert-manager"
spec:
  gatewayClassName: envoy-gateway-class
  listeners:
  - name: example-https
    protocol: HTTPS
    hostname: www.example.com
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: test-gateway-https
```

**Comment by SerheoReutty** [comment]
I tried adding in gateway listeners on port 80. And the infrastructure is created for it. The required pod and service on NodePort appears, but the forwarding only happens on port 80. My example-http listener seems to be ignored. 

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: test-gateway
  annotations:
    cert-manager.io/cluster-issuer: "my-cert-manager"
spec:
  gatewayClassName: envoy-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: example-https
      protocol: HTTPS
      hostname: www.example.com
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: test-gateway-https
```
