### ISSUE TITLE
Not possible to override host with requestHeaderModifier

### ISSUE THREAD

**Issue by zetaab** [envoyproxy/gateway#3505]
*Description*:
I am trying to override `host` header that is sent forward from the envoy. However, it seems to not work. If the rules contains `host` header nothing will be applied, I cannot see any errors either in logs. How I could replace the hostname?

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echoserver-int
  namespace: echoserver
spec:
  hostnames:
  - eg-int.xxxx
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal
    namespace: envoy-gateway-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: echoserver
      port: 80
      weight: 1
    filters:
    - requestHeaderModifier:
        add:
        - name: myheader
          value: value
        set:
        - name: host
          value: foobar.com
      type: RequestHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by zetaab** [comment]
if I use 

```
    filters:
    - requestHeaderModifier:
        set:
        - name: hostname
          value: v22alue.com
      type: RequestHeaderModifier
```

it works, but if I try `host` it does not work. How I can override upstream vhost? Similar feature in nginx https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#custom-nginx-upstream-vhost

**Comment by arkodg** [comment]
looks like internally we'd need to use https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-host-rewrite-literal instead of `requestHeadersToAdd` when `name` is set to `case-insensitive(host)`

**Comment by guydc** [comment]
Maybe I'm missing something, but there is a dedicated filter for rewriting the host header. You need to use a URLRewrite filter for that, as in this example: https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#rewrites
 
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-rewrite
spec:
  hostnames:
    - rewrite.example
  rules:
    - filters:
        - type: URLRewrite
          urlRewrite:
            hostname: elsewhere.example
      backendRefs:
        - name: example-svc
          weight: 1
          port: 80
```

It’s implemented in EG using the envoy host rewrite literal feature, so it should work: https://github.com/envoyproxy/gateway/blob/519eb70a08c6e78520fb5eae7b32516bb5b5f87b/internal/xds/translator/route.go#L373
