### ISSUE TITLE
Support Dynamic HTTP Forward Proxy

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#3560]
*Description*:
In some cases, the backend address is not known in advance and must be inferred from request/connection attributes (such as a user-provided host header, jwt claim, TLS SNI, etc.). 

The Envoy Dynamic Forward proxy feature can be used to achieve dynamic routing. EG can support Dynamic Forward Proxy in the following manner:
- The EG Backend API can be extended to support a "dynamic" endpoint type, representing a dynamic envoy cluster. This is mostly required for BTLS policy attachment. 
- The EG BackendTrafficPolicy can be used to enable dynamic routing: 
  - Injecting the appropriate HCM filter
  - Defining the strategy for inferring the upstream address
  - Configuring a DNS cache policy

- [x]  Implement Dynamic Resolver
- [x]  E2E
- [ ]  Docs
- [ ]  Add warnings for Dynamic Resolver in docs
- [ ]  Support appProtocol for Dynamic Resolver

[optional *Relevant Links*:]
- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy
- https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/clusters/dynamic_forward_proxy/v3/cluster.proto#envoy-v3-api-msg-extensions-clusters-dynamic-forward-proxy-v3-clusterconfig

**Comment by arkodg** [comment]
+1 to this

**Comment by arkodg** [comment]
@guydc what would the UX of this be like ? a filter like `Redirect` and `DirectResponse` or a `Backend` with a special field set

**Comment by rudrakhp** [comment]
Maybe a new [ `BackendEndpoint`](https://gateway.envoyproxy.io/docs/api/extension_types/#backendendpoint) type for dynamic usecases, something like `DynamicEndpoint`?

**Comment by guydc** [comment]
Yea, `DynamicEndpoint` sound ok to me. We need the ability to attach BTLSP and BTP for various cluster-level options, so I think that a filter won't be enough. 

However, we also need to inject and configure an HTTP Filter: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/dynamic_forward_proxy/v3/dynamic_forward_proxy.proto#envoy-v3-api-msg-extensions-filters-http-dynamic-forward-proxy-v3-filterconfig

So, we maybe also want to make those settings part of BTP/DynamicEndpoint... BTP is generally better since it's cluster equivalent, while an endpoint is not...

**Comment by arkodg** [comment]
+1 to a `ForwardProxy` / `DynamicEndpoint` type in `Backend`
raised https://github.com/envoyproxy/envoy/issues/38452 to see if we can create a unique dynamic proxy http filter per xDS Cluster

@guydc how is BTLSP going to work here ? creating a BTLSP per Hostname is going to defeat the purpose here imo

**Comment by guydc** [comment]
As discussed offline, Envoy supports auto-SAN validation: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-upstreamhttpprotocoloptions

The major problem is that BTLSP specs force us to strictly validation the SAN/Hostame specified in BTLSP. I'm ok with adding an `autoSANValidation` feature in the `DynamicEndpoint` or in `BackendTrafficPolicy`.

**Comment by arkodg** [comment]
@guydc brought another good point offline around SNI Forward Proxy support for TLSRoute
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter

**Comment by vgopi109** [comment]
+1

**Comment by pkit** [comment]
@arkodg Ok, it looks like it's too early to close, as it doesn't really work. At least in my case.
The problem is: it does not define `envoy.filters.http.dynamic_forward_proxy` no matter what I do, which leads to 404 all over.
So my case is: authz + extproc + dynamic forward
All works fine **if configured manually in envoy**.
Through gateway I see the following in egctl:
```
                          httpFilters:
                            - name: envoy.filters.http.cors
                              typedConfig:
                                '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                            - disabled: true
                              name: envoy.filters.http.ext_authz/securitypolicy/airfold-system/tools-authz
                              typedConfig:
                                '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                                grpcService:
                                  envoyGrpc:
                                    authority: tools-authz.airfold-system:50051
                                    clusterName: securitypolicy/airfold-system/tools-authz/extauth/0
                                  timeout: 10s
                                transportApiVersion: V3
                            - disabled: true
                              name: envoy.filters.http.ext_proc/envoyextensionpolicy/airfold-system/tools-ext-proc/extproc/0
                              typedConfig:
                                '@type': type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
                                allowModeOverride: true
                                grpcService:
                                  envoyGrpc:
                                    authority: tools-ext-proc.airfold-system:50051
                                    clusterName: envoyextensionpolicy/airfold-system/tools-ext-proc/extproc/0
                                  timeout: 10s
                                messageTimeout: 1s
                                mutationRules:
                                  allowAllRouting: true
                                  allowEnvoy: true
                                processingMode:
                                  requestHeaderMode: SEND
                                  requestTrailerMode: SKIP
                                  responseHeaderMode: SEND
                                  responseTrailerMode: SKIP
                            - name: envoy.filters.http.router
                              typedConfig:
                                '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                                suppressEnvoyHeaders: true
```
The kubernetes objects are:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tools-forward-proxy
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: api
      namespace: api-gateway
  hostnames:
    - "tools.staging.airfold.co"
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: tools-dynamic-resolver
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: tools-dynamic-resolver
spec:
  type: DynamicResolver
  tls:
    wellKnownCACertificates: System
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: tools-ext-proc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: tools-forward-proxy
  extProc:
    - backendRefs:
        - name: tools-ext-proc
          port: 50051
      processingMode:
        request: {}
        response: {}
        allowModeOverride: true
      messageTimeout: "1s"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: tools-authz
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: tools-forward-proxy
  extAuth:
    grpc:
      backendRefs:
        - name: tools-authz
          port: 50051
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: ext-proc-patch-policy
  namespace: api-gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: api
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: tcp-443
      operation:
        op: add
        jsonPath: "$..http_filters[?match(@.name, 'envoy.filters.http.ext_proc.*tools-ext-proc.*')].typed_config"
        path: "mutation_rules"
        value:
          allow_all_routing: true
          allow_envoy: true
```
The last one is needed to allow ext proc to change the host to anything.
When I define it manually I add:
```
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache_config
                        dns_lookup_family: V4_ONLY
                        typed_dns_resolver_config:
                          name: envoy.network.dns_resolver.getaddrinfo
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.getaddrinfo.v3.GetAddrInfoDnsResolverConfig
```
I hope I can add it with patch policy, but it would be nice if it worked out of the box.
And I suppose it did work for some use cases? Bot not mine.

Envoy gateway 1.5 and envoy proxy 1.35.1

**Comment by pkit** [comment]
Added patch policies (applied successfuly)
```
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: tcp-443
      operation:
        op: add
        path: "/filter_chains/0/filters/0/typed_config/http_filters/3"
        value:
          disabled: true
          name: envoy.filters.http.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
            dns_cache_config:
              dns_lookup_family: V4_PREFERRED
              dns_refresh_rate: 30s
              name: httproute/airfold-system/tools-forward-proxy/rule/0
    - type: "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
      name: api-gateway/api/https
      operation:
        op: add
        jsonPath: "$.virtual_hosts[?(@.name == 'tools_staging_airfold_co')].routes[0].typed_per_filter_config"
        path: "envoy.filters.http.dynamic_forward_proxy"
        value:
          "@type": "type.googleapis.com/envoy.config.route.v3.FilterConfig"
          config: {}

```
So now the http filter is enabled and is placed after the ext proc, as  it should.
And it's enabled per route by the second patch.

Still gives 404 for no reason.

The logs are:
```
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][ext_proc] [source/extensions/filters/http/ext_proc/ext_proc.cc:1556] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] Received request headers response
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][ext_proc] [source/extensions/filters/http/ext_proc/processor_state.cc:151] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] applying headers response. body mode = NONE
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][ext_proc] [source/extensions/filters/http/ext_proc/processor_state.cc:112] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] Applying header mutations
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][ext_proc] [source/extensions/filters/http/ext_proc/processor_state.cc:665] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] Clearing route cache due to the filter RouterCacheAction is configured with DEFAULT and response has clear_route_cache set.
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][ext_proc] [source/extensions/filters/http/ext_proc/processor_state.cc:42] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] Finish external processing call
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][ext_proc] [source/extensions/filters/http/ext_proc/processor_state.cc:63] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] Traffic direction INBOUND: timer disabled
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][ext_proc] [source/extensions/filters/http/ext_proc/processor_state.cc:217] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] The message had no body
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][ext_proc] [source/extensions/filters/http/ext_proc/processor_state.cc:555] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] Continuing processing
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][router] [source/common/router/router.cc:480] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] no route match for URL '/uuid'
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][ext_proc] [./source/extensions/filters/http/ext_proc/ext_proc.h:513] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] When onLocalReply() is called, set processing_complete_ to true to skip external processing
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][http] [source/common/http/filter_manager.cc:1064] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] Preparing local reply with details route_not_found
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][http] [source/common/http/filter_manager.cc:1106] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] Executing sending local reply.
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][http] [source/common/http/conn_manager_impl.cc:1895] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] encoding headers via codec (end_stream=true):
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy ':status', '404'
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy 'date', 'Sat, 23 Aug 2025 18:53:20 GMT'
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy 
envoy-api-gateway-api-08b09ece-bc6b94564-626r8 envoy [2025-08-23 18:53:20.114][18][debug][http] [source/common/http/conn_manager_impl.cc:2010] [Tags: "ConnectionId":"8788","StreamId":"7401708410087185752"] Codec completed encoding stream.
```

**Comment by pkit** [comment]
It works now.
I needed 4 patches in envoy patch policy to actually enable Dynamic Forward Proxy for HTTPS traffic.
1. Enable `allow_all_routing: true` to actually dynamically route anywhere I want.
2. Two patches to enable `envoy.filters.http.dynamic_forward_proxy` in proper places.
3. Last patch to overwrite `domains: ["*"]` and that's the crucial one. Otherwise because `hostname` is required for https it won't route anywhere except the original domain.

Example patches:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: example-patch-policy
  namespace: gw-namespace
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gw-name
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: tcp-443
      operation:
        op: add
        jsonPath: "$..http_filters[?match(@.name, 'envoy.filters.http.ext_proc.*my-ext-proc.*')].typed_config"
        path: "mutation_rules"
        value:
          allow_all_routing: true
          allow_envoy: true
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: tcp-443
      operation:
        op: add
        path: "/filter_chains/0/filters/0/typed_config/http_filters/2"
        value:
          disabled: true
          name: envoy.filters.http.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
            dns_cache_config:
              dns_lookup_family: V4_PREFERRED
              dns_refresh_rate: 30s
              name: httproute/my-namespace/my-http-route/rule/0
    - type: "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
      name: gw-namespace/gw-name/https
      operation:
        op: add
        jsonPath: "$.virtual_hosts[?(@.name == 'foo_domain_com')].routes[0].typed_per_filter_config"
        path: "envoy.filters.http.dynamic_forward_proxy"
        value:
          "@type": "type.googleapis.com/envoy.config.route.v3.FilterConfig"
          config: {}
    - type: "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
      name: gw-namespace/gw-name/https
      operation:
        op: replace
        jsonPath: "$.virtual_hosts[?(@.name == 'foo_domain_com')]"
        path: "domains"
        value:
          - "*"
```
First patch is needed in my case but may be irrelevant for people who don't do routing with ext proc.

**Comment by arkodg** [comment]
@pkit are you updating the Host header in ext proc ?
there are some other options to also update the Host header https://gateway.envoyproxy.io/docs/tasks/traffic/http-urlrewrite/#rewrite-url-host-name-by-header-or-backend

**Comment by pkit** [comment]
@arkodg yes, we rewrite `:authority` in ext proc.
And it works fine.
It rewrites `host` pretty well.
We just route dynamically to any upstream that is mapped in our k/v store.
The use case is similar to "url shortener" but for routing APIs.

**Comment by arkodg** [comment]
thanks for clarifying
I think allowing modification of system headers (like :authority) is a seperate feature request which exposes/configures https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/common/mutation_rules/v3/mutation_rules.proto#envoy-v3-api-msg-config-common-mutation-rules-v3-headermutationrules in the ext proc API

we should track this in a seperate issue as its orthogonal to dynamic forward proxy

**Comment by pkit** [comment]
@arkodg I think setting up `domains: ["*"]` is related to dynamic forward proxy. As it's not dynamic if we cannot route anywhere else?

**Comment by arkodg** [comment]
@pkit can you show an example of your Gateway and HTTPRoute, want to understand how you're setting `hostnames`

**Comment by pkit** [comment]
@arkodg 
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: foo
  namespace: api-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: foo-eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      hostname: "foo.staging.example.com"
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
        - name: foo-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo-forward-proxy
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: foo
      namespace: api-gateway
  hostnames:
    - "foo.staging.example.com"
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: foo-dynamic-resolver
```
