### ISSUE TITLE
Make it possible to configure secure access to Envoy admin endpoint

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/gateway#3565]
*Description*:
Make configurable access policy to Envoy admin endpoint a first class citizen in Gateway Api. E.g. Envoy admin exposes both read and write endpoints and Envoy Gateway operators may want to restrict access to write endpoints with auth.

[optional *Relevant Links*:]
Parent Envoy issue: https://github.com/envoyproxy/envoy/issues/2763

**Comment by arkodg** [comment]
@nezdolik what is the UX you are looking for here ?
currently the admin endpoint is only available on `localhost` so only someone who has access to `envoy-gateway-system` can access this

**Comment by nezdolik** [comment]
@arkodg for the case when bunch of teams have access to localhost/namespace/cluster, so we could let all those teams have access to read only endpoints and only the team that operates the gateway write+read access.

**Comment by arkodg** [comment]
one way to achieve this could be using the new backend API https://github.com/envoyproxy/gateway/pull/3550 and making sure only admins can create `Backend` resources, and reuse `HTTPRoute` and `SecurityPolicy` to authz access to the `admin` endpoint 🙃

**Comment by ira-gordin-sap** [comment]
Hi, what happens with this issue?

**Comment by liorokman** [comment]
If you enable the `Backends` extension API (see https://gateway.envoyproxy.io/latest/tasks/traffic/backend/ ) then you can create a backend that looks like this:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: admin
  namespace: default
spec:
  endpoints:
  - ip:
      address: 127.0.0.1
      port: 19000
```

Once you have this backend available, you can create a standard `HTTPRoute` and protect it with a `SecurityPolicy` to allow access to it. For example, add the following to the quickstart configuration to expose the admin port on the envoy proxy:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: admin
  namespace: default
spec:
  hostnames:
  - admin.local
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: admin
    matches:
    - path:
        type: PathPrefix
        value: /
```
