### ISSUE TITLE
Support targetSelectors in Envoy Gateway policies

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3607]
I think that since this API still needs some discussion, I will remove the `targetSelector` for now from the PR and keep only the plural `targetRefs` in this PR.

The target selectors can be done in a separate PR after the API has been designed and agreed upon.

_Originally posted by @liorokman in https://github.com/envoyproxy/gateway/pull/3581#discussion_r1639514571_

**Comment by arkodg** [comment]
sharing my preference
```
 targetSelectors:
 - group: gateway.networking.k8s.io
      kind: HTTPRoute
      matchLabels:
        app: foo
 - group: gateway.networking.k8s.io
      kind: Gateway
      matchLabels:
        app: foo       
```

**Comment by liorokman** [comment]
I think that adding the group and kind to each individual target selector isn't a good idea.

When resolving the selectors, the translating code isn't going to query the K8S API server, but rather go over the resources which were already fetched by the EG provider abstraction. The code doesn't need a group and kind to search for; instead each policy should only check the labels for those types of objects on which it supports being attached to.

The `group` field is anyways redundant - in all the policies in the `targetRef`s sections we already prevent the group field from being anything else other than `gateway.networking.k8s.io`. It means that adding a `group` field here is just plain boilerplate and adds nothing to the clarity of the API.

I think just a label matcher section is expressive enough to allow for all the various use-cases, without having to further qualify a label set with a group and a kind.

I'm also not sure that it's a good idea to have an array of target selectors here; I think a single label set is expressive enough as long as we don't include the group and the kind.

**Comment by sadovnikov** [comment]
Although, attaching the same policy to routes and gateways does not seem useful, applying it to a mix of `HTTPRoutes` and `GRPCRoutes` is a good use case. If `kind` is removed, a single selector can pick up this mix. 

The single selector works perfectly for `Deployments` and `Services`. I do not see us using multiple `targetSelectors` in `SecurityPolicies` either (unless `HTTPRoutes` and `GRPCRoutes` have to be selected separately)

**Comment by guydc** [comment]
Agree with the concern regarding incompatible behavior when kind is omitted and policy starts supporting additional targets. +1 to optional `group` and having `kind` defaulted to all relevant resources to avoid behavior changes in future versions,

**Comment by liorokman** [comment]
>  +1 to optional group and having kind defaulted to all relevant resources to avoid behavior changes in future versions,

This is exactly the same as defaulting to '*'.

If a policy type today doesn't support some type (e.g. an `HTTPRoute`), then this proposal would default a non-written kind to everything except the unsupported type. Then at version $n+1$ the policy starts to support the previously unsupported kind (e.g. `HTTPRoute`), and the definition of the default changes. Policies that previously didn't attach to `HTTPRoute` would start doing so.

As a general comment, the way I understand selectors to be used is that the policy would be written to select those Gateway API resources that match a specific business case. This means that as an admin, I would apply a given label to all the Gateway API resources that are relevant for my business case, and then expect to create a policy using the same label in the selector. I think an approach where as an admin I would have to create a separate policy saying the same thing, or specify the same labels section multiple times in multiple selectors, is just plain inconvenient.



Counting the $+1$ s, here is my understanding of the current consensus:

```yaml
# ...
spec:
   targetSelectors:
   - kind: <kind of resource> # defaults to '*'
     group: # optional, defaults to gateway.networking.k8s.io if not specified, and an error to have any other value
     matchLabels:
          a: set-of
          labels: to-select-the
          relevant: resources
# ...
```

Where the semantics of the `kind` field are that `*` means "All of the set of kinds that are supported by the policy in question"

This leaves an inconvenient detail, where for policies like `BackendTrafficPolicy` and `SecurityPolicy` the default `kind` value of `*` is probably meaningless, since it would include the `Gateway` type as well as all the route types. The admin would be forced to make sure that `Gateways` are not matched by the labels specified in the `matchLabels` part, which means that specifying the `kind` in the selector section becomes either redundant or useless (depending on your PoV).

Also: is it an error to _not_ specify anything in the `matchLabels` section?
