### ISSUE TITLE
OIDC Security Policy with private CA or selfsigned certificate

### ISSUE THREAD

**Issue by nbrns** [envoyproxy/gateway#3622]
*Description*:

I want to secure my http routes using an OIDC security policy. The OIDC provider is a Keycloak which uses a certificate issued by a private CA or maybe even a self-signed certificate. When creating the security policy, it doesn't get accepted, as the gateway cannot validate the OIDC issuers TLS certificate.

I could not find a (documented) way to add trusted certificates to the gateway and the managed envoys.

*Repro steps*:

- deploy a Keycloak which uses a private CA or a self-signed certificate for TLS
- configure a SecurityPolicy
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-example
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend
  oidc:
    provider:
      issuer: "https://example.com/auth/realms/master"
    clientID: "api-gateway"
    clientSecret:
      name: "my-app-client-secret"
    redirectURL: "https://example.com/backend"
    logoutPath: "/backend/logout"
```

*Environment*:

envoy gw version (also helm): 1.0.2
envoy image: envoyproxy/envoy:distroless-v1.29.5

*Logs*:

Security policy conditions:
```yaml
...
      conditions:
        - lastTransitionTime: '2024-06-17T12:56:47Z'
          message: >-
            Error fetching endpoints from issuer: Get
            "https://example.com/auth/realms/master/.well-known/openid-configuration":
            tls: failed to verify certificate: x509: certificate signed by
            unknown authority
...
```

I can't see a detailed message about the error in the gateway logs.
