### ISSUE TITLE
HTTP2 Connect support

### ISSUE THREAD

**Issue by denniskniep** [envoyproxy/gateway#3663]
*Description*:
It should be possible to use the [HTTP Verb "CONNECT"](https://en.wikipedia.org/wiki/HTTP_tunnel) to start a tcp tunnel  through envoy to an upstream target.
This would have the benefit that one can use the http filters during initialization of  the tcp tunnel (i.e. oauth2 filter for authentication and ext_auth for authorization).

Here is a small PoC with pure envoy config:
https://github.com/denniskniep/envoy-http-connect-tunnel-demo

Assuming this example HTTPRoute:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: default
spec:
  hostnames:
  - www.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: backend
      port: 3000
    matches:
    - path:
        type: PathPrefix
        value: /
```

This example will be translated to this VirtualHost:
```
{
       "virtual_hosts": [
              {
                     "name": "default/eg/http/www_example_com",
                     "domains": [
                            "www.example.com"
                     ],
                     "routes": [
                            {
                                   "match": {
                                          "prefix": "/"
                                   },
                                   "route": {
                                          "cluster": "httproute/default/backend/rule/0",
                                          "upgrade_configs": [
                                                 {
                                                        "upgrade_type": "websocket"
                                                 }
                                          ]
                                   },
                                   "name": "httproute/default/backend/rule/0/match/0/www_example_com"
                            }
                     ]
              }
       ]
}
```

To make this HTTPRoute able to handle `HTTP Connect` requests we need to configure the following:
```
  virtual_hosts:
  - name: default/eg/http/www_example_com
    domains:
    - "www.example.com"
    routes:
    - match:
        connect_matcher:
          {}
      route:
        cluster: "httproute/default/backend/rule/0",
        upgrade_configs:
        - upgrade_type: CONNECT
          connect_config:
            {}
```

We need to utilize the `connect_matcher` (see [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routematch)) for route matching.
Important is that the  `connect_matcher` can not be used together with `prefix` matcher! (Because of the precisely one requirement)

And we need to specify appropriate `upgrade_configs` (see [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction))

Additionally there are further `HTTP CONNECT` related settings on [HttpConnectionManager](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html)

But they don´t seem to have any effect on the actual functionality, if the ones on route level are set appropriately. See:
* [HttpConnectionManager upgrade_configs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-upgradeconfig)
* [HttpConnectionManager http2_protocol_options allow_connect](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-http2protocoloptions)

**What would be the "right way" to model this in/as envoy gateway resource?**

Does it make sense to add a property to the [ClientTrafficPolicy](https://gateway.envoyproxy.io/latest/api/extension_types/#clienttrafficpolicyspec)? This would take effect on the specified route if targetrefs [sectionname](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.LocalPolicyTargetReferenceWithSectionName) is set to the HTTPRoute or affect every route if targetRef is set on a gateway level ?

Adding the following property to ClientTrafficPolicy. A dedicated object gives us the opportunity to easily add [more of these](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routeaction-upgradeconfig-connectconfig) config props later if necessary
```
connectConfig: {
  enabled: true,
  
}
```
