### ISSUE TITLE
EnvoyProxy Bootstrap configuration can't merge a list

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#3691]
I would like to change the value of `envoy.restart_features.use_eds_cache_for_ads` to false using this `EnvoyProxy` CR:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  bootstrap:
    type: Merge
    value: |
      layered_runtime:
        layers:
        - name: global_config
          staticLayer:
            envoy.restart_features.use_eds_cache_for_ads: false
```

Got two `global_config` keys in the bootstrap configuration.

```yaml
layeredRuntime:
  layers:
  - name: global_config
    staticLayer:
      envoy.restart_features.use_eds_cache_for_ads: true
      re2.max_program_size.error_level: 4294967295
      re2.max_program_size.warn_level: 1000
  - name: global_config
    staticLayer:
      envoy.restart_features.use_eds_cache_for_ads: false
```

Instead, the expected result should be :

```yaml
layeredRuntime:
  layers:
  - name: global_config
     staticLayer:
      envoy.restart_features.use_eds_cache_for_ads: false
      re2.max_program_size.error_level: 4294967295
      re2.max_program_size.warn_level: 1000
```
