### ISSUE TITLE
Ratelimit pod could not connect xDS Management Server

### ISSUE THREAD

**Issue by daidv94** [envoyproxy/gateway#3725]
*Description*:
Envoy gateway v1.0.1 deployed with ratelimit backed redis enabled encountered a bug that the ratelimit pod could not connect to the xDS Management server.
ArgoCD is used to deploy envoy gateway stack

*Repro steps*:
**Install envoy gateway with the following configuration**
`Chart.yaml`
```yaml
dependencies:
  - name: gateway-helm
    version: v1.0.1
    repository: oci://docker.io/envoyproxy

apiVersion: v2
name: gateway-helm
description: The Helm chart for Envoy Gateway
type: application

version: v1.0.1
appVersion: "latest"

maintainers:
  - name: envoy-gateway-steering-committee
    url: https://github.com/envoyproxy/gateway/blob/main/GOVERNANCE.md
  - name: envoy-gateway-maintainers
    url: https://github.com/envoyproxy/gateway/blob/main/CODEOWNERS

keywords:
  - gateway-api
  - envoyproxy
  - envoy-gateway
  - eg

home: https://gateway.envoyproxy.io/

sources:
  - https://github.com/envoyproxy/gateway
```
`values.yaml` file
```yaml
gateway-helm:
  deployment:
    envoyGateway:
      image:
        repository: docker.io/envoyproxy/gateway
        tag: 'v1.0.1'
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
    kubeRbacProxy:
      image:
        repository: gcr.io/kubebuilder/kube-rbac-proxy
        tag: v0.11.0
      resources:
        limits:
          cpu: 50m
          memory: 56Mi
        requests:
          cpu: 50m
          memory: 56Mi
    ports:
    - name: grpc
      port: 18000
      targetPort: 18000
    - name: ratelimit
      port: 18001
      targetPort: 18001
    replicas: 2
    pod:
      annotations: {}
      labels:
        env: dev

  rootNamespace: envoy-gateway-system
  config:
    envoyGateway:
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      provider:
        type: Kubernetes
      logging:
        level:
          default: debug
      rateLimitDeployment:
        replicas: 3
        container:
          image: envoyproxy/ratelimit:master
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            runAsUser: 2000
            allowPrivilegeEscalation: false
      extensionApis:
        enableEnvoyPatchPolicy: true
      rateLimit:
        backend:
          type: Redis
          redis:
            url: redis.example.com:6379
            tls:
              certificateRef:
                name: envoy-rate-limit
                namespace: envoy-gateway-system

  envoyGatewayMetricsService:
    ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https

  createNamespace: false

  kubernetesClusterDomain: cluster.local

  certgen:
    job:
      annotations:
        argocd.argoproj.io/hook: PreSync
        # "helm.sh/hook-weight": "-1"
        # "helm.sh/hook-delete-policy": hook-succeeded
        # argocd.argoproj.io/hook: Skip
        # argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
      ttlSecondsAfterFinished: 50
    rbac:
      annotations: {}
      labels: {}

```
**Check the logs initatation of ratelimit pod**
```text
envoy-ratelimit-1-5b7d6df49d-v4p22 envoy-ratelimit-1 time="2024-07-01T10:52:15Z" level=info msg="Starting xDS client connection for rate limit configurations"
envoy-ratelimit-1-5b7d6df49d-v4p22 envoy-ratelimit-1 time="2024-07-01T10:52:15Z" level=info msg="Dialing xDS Management Server: 'envoy-gateway:18001'"
```
Pod could not established the connection to the management server. I've checked the network policy, they are in the same namespace and can connect through TCP.

As far as I know, it is sucessfully if we're able see the logs like this.
![image](https://github.com/envoyproxy/gateway/assets/45174998/5bb91559-e052-41f1-9493-bc0a620b61fe)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
- Envoy version: v1.0.1
- Helm oci: v1.0.1
- AWS EKS 1.28
- ArgoCD v2.11

*Logs*:
```logs
envoy-ratelimit-7b8cfc4d4c-t2h7h envoy-ratelimit time="2024-07-01T11:04:48Z" level=info msg="Tracing disabled"
envoy-ratelimit-7b8cfc4d4c-t2h7h envoy-ratelimit time="2024-07-01T11:04:48Z" level=info msg="Starting xDS client connection for rate limit configurations"
envoy-ratelimit-7b8cfc4d4c-t2h7h envoy-ratelimit time="2024-07-01T11:04:48Z" level=info msg="Dialing xDS Management Server: 'envoy-gateway:18001'"
envoy-ratelimit-7b8cfc4d4c-t2h7h envoy-ratelimit time="2024-07-01T11:04:48Z" level=warning msg="connecting to redis on master.shared-envoy-ratelimit-shared.vswbdv.use1.cache.amazonaws.com:6379 with pool size 10"
envoy-ratelimit-7b8cfc4d4c-t2h7h envoy-ratelimit time="2024-07-01T11:04:48Z" level=warning msg="Listening for debug on '0.0.0.0:6070'"
envoy-ratelimit-7b8cfc4d4c-t2h7h envoy-ratelimit time="2024-07-01T11:04:48Z" level=warning msg="Listening for gRPC on '0.0.0.0:8081'"
envoy-ratelimit-7b8cfc4d4c-t2h7h envoy-ratelimit time="2024-07-01T11:04:48Z" level=warning msg="Listening for HTTP on '0.0.0.0:8080'"
```
