### ISSUE TITLE
503s during service upgrade

### ISSUE THREAD

**Issue by alexandermarston** [envoyproxy/gateway#3740]
*Description*:
I observed a large spike in 503s while a number of our services were upgrading. As an example:

You can see that the following pod terminated at 09:37:17:

```
log:2024-07-03T09:37:17.125250Z info ads ADS: "10.0.60.40:54496" hello-world-7ff5b79994-r6jbp.production-271 terminated
```

but at 09:44:19, Envoy was still trying to send requests to the terminated pod

```
log_obj:{
  authority:hello-world.production.my.app
  bytes_received:2956
  bytes_sent:152
  downstream_local_address:10.0.142.87:10443
  downstream_remote_address:10.0.238.117:52017
  duration:3
  protocol:HTTP/1.1
  response_code:503
  response_code_details:via_upstream
  response_flags:-
  start_time:2024-07-03T09:44:19.301Z
  upstream_host:10.0.60.40:8080
  upstream_local_address:10.0.142.87:53528
}
```

During the rolling upgrade, we did have available replicas so I'm not sure why Envoy was not updated with the new pod IPs.

<img width="860" alt="Screenshot 2024-07-03 at 18 13 57" src="https://github.com/envoyproxy/gateway/assets/15369229/1d767618-2a33-4747-9d27-84697a2dda31">
<img width="860" alt="Screenshot 2024-07-03 at 18 13 47" src="https://github.com/envoyproxy/gateway/assets/15369229/fdf3550f-48bf-4ccb-bb6c-06ef85d3ced9">

*Repro steps*:

Unfortunately, I have been unable to reproduce this so far

*Environment*:

```
➜  ~ egctl version
client: v1.0.2
server:
- Name: envoy-gateway-7f86dfc97b-wm9cf
  Namespace: envoy-gateway
  envoyGatewayVersion: v1.0.2
  envoyProxyVersion: distroless-v1.29.5
  gatewayAPIVersion: v1.0.0
  gitCommitID: 8cf16eec9eb5eaada1d978550f32855719d2a00d
```

*Logs*:
