### ISSUE TITLE
EnvoyProxy patch type JSONMerge undocumented / not very useful

### ISSUE THREAD

**Issue by seankhliao** [envoyproxy/gateway#3840]
*Description*:

Background: for small scale tests (single node), I want to run envoyproxy without a load balancer and expose it directly using `hostPort`. To do this I need to patch the container ports of the resulting envoy deployment.

The two supported types of patching are StrategicMerge and JSONMerge.
A StrategicMerge type won't work because it uses containerPort as keys which aren't unique (see also upstream k8s issue https://github.com/kubernetes/kubernetes/issues/105610 ).
The JSONMerge is undocumented in the CRDs or in documentation, but implemented, however, [RFC 7396](https://datatracker.ietf.org/doc/html/rfc7396#section-2) states the following, which is not very useful when I'd have to patch the entire containers array.

> Also, it is not possible to patch part of a target that is not an object, such as to replace just some of the values in an array.

*Repro steps*:

This results in a single port of protocol UDP:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: http-gateway
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP
      envoyDeployment:
        strategy:
          type: Recreate
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                    - name: envoy
                      ports:
                        - containerPort: 10080
                          hostPort: 80
                        - containerPort: 10443
                          protocol: TCP
                          hostPort: 443
                        - containerPort: 10443
                          protocol: UDP
                          hostPort: 443
```

*Environment*:

gateway version v1.0.2

*Logs*:

N/A

**Comment by kamalmarhubi** [comment]
@seankhliao did you find any workarounds?

**Comment by arkodg** [comment]
if you're trying to run the deployment or [daemonset](https://gateway.envoyproxy.io/docs/api/extension_types/#kubernetesdaemonsetspec) in host mode you could run
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: http-gateway
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP
      envoyDeployment:
        useListenerPortAsContainerPort: true
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  hostNetwork: true
 ```

**Comment by kamalmarhubi** [comment]
@arkodg I wanted to avoid using the host network namespace; also I think you patch needs `dnsPolicy: ClusterFirstWithHostNet` to allow it to resolve the XDS endpoint. I also ran into problems with binding privileged ports that I gave up trying to resolve (adding `NET_BIND_SERVICE ` capability didn't seem to sort it out, and I definitely want to avoid `NET_ADMIN` or `privileged: true` on an externally facing HTTP server).

In the end, I was able to get it to work with this patch:
```
patch:
  type: StrategicMerge
  value:
    spec:
      template:
        spec:
          containers:
            - name: envoy
              ports:
                - containerPort: 10080
                  hostPort: 80
                  name: http-80
                  protocol: TCP
                - containerPort: 19001
                  name: metrics
                  protocol: TCP

```

however this is a bit messy because it requires updating the patch every time you update the listeners on the gateway.

**Comment by erikschul** [comment]
@arkodg  I agree that hostNetwork is bad practice (although repeated frequently in this repo).
hostPort is better, and at least with Cilium, it works without any additional privileges.
I also use hostPort, and the lack of support in Envoy Gateway means that I will continue to use Contour.

**Comment by arkodg** [comment]
@erikschul can link the relevant contour documentation for enabling something like this

**Comment by erikschul** [comment]
@arkodg 
https://projectcontour.io/docs/main/deploy-options/
"Envoy as Daemonset"

**Comment by arkodg** [comment]
I see, thanks for sharing, looks like Contour, auto populates the `hostPort` in `DaemonSet` mode.
Envoy Gateway's DaemonSet mode https://gateway.envoyproxy.io/docs/api/extension_types/#kubernetesdaemonsetspec doesnt support this feature by default but you can achieve it by setting the values via the `patch` field or using a `NodePort` service (ports cannot be fixed for this), keeping this issue open to hear what others think of this

**Comment by erikschul** [comment]
Even if it's not explicitly supported, it would be nice to see it as a documented (i.e recognized) use case, like under Tasks/Traffic/Using hostPorts (and examples of Deployment/DaemonSet)

**Comment by seankhliao** [comment]
Cilium's gateway support hostNetwork, though I believe they don't remap listener ports like envoy does from 443->10443 so it can just work. https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/gateway-api/#host-network-mode

They call out:
> This is useful in cases where a LoadBalancer Service is unavailable, such as in development environments or environments with cluster-external loadbalancers.

I've mostly wanted this for local / simple (few nodes) bare metal deploys.

**Comment by guoard** [comment]
> What should be an alternative ot these if those are not available?
> hostNetwork: true
> dnsPolicy: ClusterFirstWithHostNet

I achieved the same purpose with the following configuration:

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
spec:
  provider:
    type: Kubernetes
    kubernetes:
      useListenerPortAsContainerPort: true
      envoyService:
        type: ClusterIP
      envoyDaemonSet:
        container:
          image: envoyproxy/envoy:v1.37.1
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
        patch:
          type: StrategicMerge
          value:
            spec:
              updateStrategy:
                type: RollingUpdate
                rollingUpdate:
                  maxSurge: 0
                  maxUnavailable: 1
              template:
                spec:
                  hostNetwork: true
                  dnsPolicy: ClusterFirstWithHostNet
```

Of course, you can replace `DaemonSet` with a `Deployment` if needed.
