### ISSUE TITLE
Make EnvoyGateway's ExtensionManager part configureable via chart

### ISSUE THREAD

**Issue by aoledk** [envoyproxy/gateway#3867]
*Description*:

If users want to use ExtensionManager, first they have to deploy EG via chart, then modify `envoy-gateway-config` ConfigMap which contains EnvoyGateway YAML content to setup ExtensionManager for EG, steps have been demonstrated in _Envoy Gateway Extension Server_ Task [^1].

ExtensionManager part YAML content:

```yaml
extensionManager:
  # Envoy Gateway will watch these resource kinds and use them as extension policies
  # which can be attached to Gateway resources.
  policyResources:
  - group: example.extensions.io
    version: v1alpha1
    kind: ListenerContextExample
  hooks:
    # The type of hooks that should be invoked
    xdsTranslator:
      post:
      - HTTPListener
  service:
    # The service that is hosting the extension server
    fqdn: 
      hostname: extension-server.envoy-gateway-system.svc.cluster.local
      port: 5005
```

The ConfigMap modification will be done via 2 options:

1. option 1: `kubectl edit` manually.
2. option 2: `kubectl patch` automatically.
    1. retrieve `envoy-gateway.yaml` key's old value.
    2. append ExtensionManager part YAML content to old value, as new value.
    3. patch new value to `envoy-gateway.yaml` key.
    
If users can configure ExtensionManager when installing EG via chart, that will be more convenience.

[optional *Relevant Links*:]

[^1]: https://gateway.envoyproxy.io/latest/tasks/extensibility/extension-server/#configure-envoy-gateway
