### ISSUE TITLE
Creation of SecurityPolicy with `targetSelectors` fails

### ISSUE THREAD

**Issue by sadovnikov** [envoyproxy/gateway#3901]
*Description*:

> Creation of SecurityPolicy with `targetSelectors` only fails with the `either targetRef or targetRefs must be used` message

*Repro steps*:
> Create SecurityPolicy below

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  labels:
    eg/namespace: reference-apps
  name: eg-fallback-oidc
  namespace: reference-apps
spec:
  oidc:
    clientID: xxxxxxxxxx
    clientSecret:
      name: oauth2-secret
    provider:
      issuer: >-
        https://login.microsoftonline.com/xxxxxxxxxx/v2.0
    scopes:
      - 'api://xxxxxxxxxx/oidc'
      - offline_access
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      matchLabels:
        eg/namespace: reference-apps
```

*Environment*:

> Version v1.1.0-rc.1, installed with the helm chart

```
dependencies:
- name: gateway-helm
  version: v1.1.0-rc.1
  repository: oci://docker.io/envoyproxy
```

It must be coming from the [x-kubernetes-validation](https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml#L1131-L1133). 

These CRDS are in the `generated` directory and I'm failing to find their source to fix the bug
