### ISSUE TITLE
OIDC: allows multiple subdomains share the same OIDC configuration

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#3919]
The EG OIDC (OAuth2 filter under the hood) stores ID and access tokens in cookies without specifying `Domain`. This configuration prevents sharing the same OIDC configuration across subdomains.

The API might be something like this:
```
oidc:
      provider:
        issuer: "https://accounts.google.com/"
      clientID: "client1.apps.googleusercontent.com"
      clientSecret:
        name: "client1-secret"
      redirectURL: "https://www.example.com/bar/oauth2/callback"
      logoutPath: "/bar/logout"
      cookieDomain: ".example.com"
```
