### ISSUE TITLE
Allow ClientTrafficPolicy to affect all listeners of a merged Gateway

### ISSUE THREAD

**Issue by pingiun** [envoyproxy/gateway#3972]
*Description*:

In my setup, I have a load-balancer that does not do TLS termination in front of my envoy proxy in my cluster. I want to use the PROXY protocol in this setup, because otherwise I cannot see the upstream IP in my application, or anywhere in the cluster for that matter.

When using one gateway behind the load balancer, this easy to setup. I just have a ClientTrafficPolicy with `enableProxyProtocol: true` on the single Gateway that receives traffic from the loadbalancer.

However, I am currently making a Helm chart setup where I can start new web apps whenever I add a new Helm release to my cluster. These web apps are on their own domains and require a TLS certificate. Because I cannot dynamically add to my global Gateway (I don't think), I have enabled `mergeGateways: true` to merge all the Gateway resources into a single envoy proxy. This way, all the individual Gateways get TLS certificates from cert-manager, but they are all behind the global load-balancer.

My problem now is that the ClientTrafficPolicy from the first gateway applies to all the listeners of the gateway, and because the http port between the two gateways is shared, it also applies to the other gateway, which envoy blocks with this message: https://github.com/envoyproxy/gateway/blob/0b52320ba6fb5d65796470cd367d1f8d5d27a191/internal/gatewayapi/clienttrafficpolicy.go#L372

But in my setup, I actually have the ClientTrafficPolicy on the new Gateways set up by the Helm releases as well. So I actually want this behaviour of having the policy hold for all http listeners! Unfortunately this check, which I can see normally makes sense, blocks a legitimate use case of mine where I want all http listeners affected by the proxy protocol filter.

I hope that because ClientTrafficPolicy is a envoy gateway resource and not a Gateway SIP resource it can be easily extended to allow functionality like this. I was thinking maybe it could something like this:

```yaml
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: eg-proxy-protocol
  namespace: rood-wp
spec:
  applyToAllListeners: true # Something like this may be necessary to assert this behaviour is wanted
  enableProxyProtocol: true
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: GatewayClass # Note: this names the class because mergeGateways
    name: eg
```

*Relevant Links*:
Thread I had in discussions about this: https://github.com/envoyproxy/gateway/discussions/3970

It provides a partial workaround, but still requires me to name all domain (prefixes) that the global http listener should listen on

**Comment by liorokman** [comment]
I think what you're looking for is to create some sort of "default" `ClientTrafficPolicy`, which would contain values that can be overridden by "non-default" instances.  I think that the `applyToAllListeners` API is not a good idea, since it's ambiguous. What would happen if there are multiple instances of a policy that all turn on this flag, and contain conflicting instructions? There is a need for some sort of "default" settings, but I think that the better way to get to this is with an implementation of [GEP-2649](https://gateway-api.sigs.k8s.io/geps/gep-2649/) in Envoy Gateway.

For now, `ClientTrafficPolicy` instances can't be set across namespaces, and can't have multiple instances attached to the same gateway host+port combination.

Maybe the [following](https://gateway-api.sigs.k8s.io/guides/multiple-ns/) could work for you:

1. Create a single shared `Gateway` resource in one namespace. This gateway should specify the allowed namespaces using a selector. See the below for an example.
2. Apply your single `ClientTrafficPolicy` on it directly. 
3. Don't turn on the `mergeGateways` feature. 
4. Create all of your `HTTPRoute` resources in different namespaces, as you are doing right now. Make sure that the namespaces are labelled to match the selector you defined in the Gateway resource.



```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    shared: "true"
  name: other
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    shared: "true"
  name: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
  - allowedRoutes:
      namespaces:
        from: Selector
        # Any namespaces labelled to match this selector can contribute routes to this listener.
        selector:
          matchLabels:
            shared: "true"
    name: http
    port: 80
    protocol: HTTP
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: eg-proxy-protocol
  namespace: default
spec:
  enableProxyProtocol: true
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: default
spec:
  hostnames:
  - www.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
    namespace: default
  rules:
  - backendRefs:
    - group: ""
      # this service resource lives in the default namespace
      kind: Service
      name: backend1
      port: 3000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: other
spec:
  hostnames:
  - www.otherexample.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
    namespace: default
  rules:
  - backendRefs:
    - group: ""
      # this service resource lives in the other namespace
      kind: Service
      name: backend2
      port: 3000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```

**Comment by pingiun** [comment]
@liorokman I tried this, but then I got the condition "There were no hostname intersections between the HTTPRoute and this parent ref's Listener(s)."

As I write in the [discussion](https://github.com/envoyproxy/gateway/discussions/3970#discussioncomment-10183641):

Unfortunately this still is not a perfect solution, as it requires me to enumerate all the domains I want to listen to on the central Gateway. I want to specify the domain names in seperate gateways so I can easily make new instances of my Helm chart and have them receive https traffic via cert-manager

**Comment by liorokman** [comment]
@pingiun Are you sure that you tried what I wrote above? I tried it locally, and it works fine for me.

Notice that in my suggestion, you have exactly one `Gateway` resource, and that gateway resource doesn't list any hostname in it. 

From what you described in the discussion, this is different than your attempt. You tried to have multiple Gateways and to merge them into one. I'm suggesting you _don't_ do this, and instead have exactly one `Gateway` to which you can attach routes from multiple namespaces.

The hostname is listed in the `HTTPRoute`, which attaches to the single shared `Gateway` resource. A single `ClientTrafficPolicy`  is created that enables the proxy protocol for all the routes from all of the namespaces.

**Comment by pingiun** [comment]
@liorokman Oh I thought I had to at least list the hostnames to get cert-manager to issue certificates, but I'll try this without listing any hostnames in the listeners

**Comment by pingiun** [comment]
Okay thank you @liorokman, everything just works right now. I did not realise I could all do it much simpler

**Comment by pingiun** [comment]
Oh nevermind, I somehow missed this error:
```
Skipped a listener block: spec.listeners[1].hostname: Required value: the hostname cannot be empty
```

**Comment by liorokman** [comment]
> Required value: the hostname cannot be empty

This is not an Envoy Gateway error. It's from cert-manager, as far as I can tell.

I'm not sure what you're trying to do. If you need to create certificates, and you're _not_ using Envoy Gateway to serve TLS traffic, why don't you create the certificates with Cert-Manager's [Certificate](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate) CRD directly? No need to tie this to Envoy Gateway.

**Comment by pingiun** [comment]
I am using Envoy Gateway to serve TLS traffic

**Comment by pingiun** [comment]
> Another way that you might try is that instead of applying a single ClientTrafficPolicy to the entire gateway, you could merge the gateways, and then create ClientTrafficPolicy resources in each namespace that targets just the listener contributed by the specific Gateway resource that you added in each gateway. You do this by specifying the SectionName in the targetRef structure.

I don't think this is possible because [this code](https://github.com/envoyproxy/gateway/blob/0b52320ba6fb5d65796470cd367d1f8d5d27a191/internal/gatewayapi/clienttrafficpolicy.go#L343-L382) checks if any listeners listen on the same port. And because of my external load balancer pointing to Envoy, all the HTTP listeners need to listen on that same port.

But thank you for suggesting splitting up just the HTTPS listeners. I'll try that

**Comment by liorokman** [comment]
> > Another way that you might try is that instead of applying a single ClientTrafficPolicy to the entire gateway, you could merge the gateways, and then create ClientTrafficPolicy resources in each namespace that targets just the listener contributed by the specific Gateway resource that you added in each gateway. You do this by specifying the SectionName in the targetRef structure.
> 
> I don't think this is possible because [this code](https://github.com/envoyproxy/gateway/blob/0b52320ba6fb5d65796470cd367d1f8d5d27a191/internal/gatewayapi/clienttrafficpolicy.go#L343-L382) checks if any listeners listen on the same port. And because of my external load balancer pointing to Envoy, all the HTTP listeners need to listen on that same port.
> 

That code only applies to HTTP listeners, not to HTTPS listeners.

**Comment by pingiun** [comment]
> > > Another way that you might try is that instead of applying a single ClientTrafficPolicy to the entire gateway, you could merge the gateways, and then create ClientTrafficPolicy resources in each namespace that targets just the listener contributed by the specific Gateway resource that you added in each gateway. You do this by specifying the SectionName in the targetRef structure.
> > 
> > 
> > I don't think this is possible because [this code](https://github.com/envoyproxy/gateway/blob/0b52320ba6fb5d65796470cd367d1f8d5d27a191/internal/gatewayapi/clienttrafficpolicy.go#L343-L382) checks if any listeners listen on the same port. And because of my external load balancer pointing to Envoy, all the HTTP listeners need to listen on that same port.
> 
> That code only applies to HTTP listeners, not to HTTPS listeners.

Oh I'm sorry I thought you were talking about any Gateways. 

Just to make sure I understand correctly, your suggested setup is this:

- One global Gateway which listens for HTTP requests, it has it's own ClientTrafficPolicy for PROXY protocol.
- One HTTPS Gateway per app that wants to listen on a domain. It has it's own ClientTrafficPolicy for PROXY protocol, it get's merged into the global Gateway but it's just an https listener so merging goes fine
- Every app now needs two HTTPRoute resources if they want to listen on the HTTP listening global gateway and on their own https listening gateway


This a correct summary?

**Comment by liorokman** [comment]
> Oh I'm sorry I thought you were talking about any Gateways.

Listeners are defined in `Gateway` resources.

> 
> Just to make sure I understand correctly, your suggested setup is this:
> 
> * One global Gateway which listens for HTTP requests, it has it's own ClientTrafficPolicy for PROXY protocol.
> * One HTTPS Gateway per app that wants to listen on a domain. It has it's own ClientTrafficPolicy for PROXY protocol, it get's merged into the global Gateway but it's just an https listener so merging goes fine
> * Every app now needs two HTTPRoute resources if they want to listen on the HTTP listening global gateway and on their own https listening gateway
> 
> This a correct summary?

It's not so simple. If you enable `mergeGateways`, it is applied for all the gateways managed by Envoy Gateway.  I don't think you can merge some gateways and not others. 

But if you only have a single `Gateway` resource define the HTTP listener, and not define it over and over again in each merged `Gateway` definition, then you should be able to:

* Enable `mergeGateways`
* Define a single "shared" gateway that has only an HTTP listener and nothing else. 
* Define a single `ClientTrafficPolicy` to enable the proxy protocol on the merged gateway level - as per your original approach.
* In each application namespace:
   * Define a `Gateway` with only the HTTPS section, since you need to specify the hostname in these sections
   * Define one `HTTPRoute` resource for the application, and use multiple `parentRef` items. One that attaches to the shared (HTTP) `Gateway` and another that attaches to the local `Gateway`

All of the gateways should be merged to a single one, but there will only be one HTTP listener defined, so there will be no ambiguity for the `ClientTrafficPolicy`.

**Comment by liorokman** [comment]
@pingiun Is there still an issue to be solved here?

**Comment by pingiun** [comment]
Maybe this setup can be written down in a guide, as it may be applicable to more setups. But no code needs to be changed I think

**Comment by marktuk** [comment]
I am not sure I understand the solution. Do we need create a dummy listener on the "base" `Gateway` that gets the `ClientTrafficPolicy` applied, and then let other namespaces define their own `Gateway` and listeners? Can anyone share a sample?

**Comment by arkodg** [comment]
@marktuk do you have multiple Gateways with http listeners on the same port with mergeGateway enabled ?

**Comment by marktuk** [comment]
> [@marktuk](https://github.com/marktuk) do you have multiple Gateways with http listeners on the same port with mergeGateway enabled ?

Yes, so I have something like below **after** merging, these are actually all defined separate namespaces:

```
  listeners:
    - name: admin
      hostname: "admin.example.com"
      port: 80
      protocol: HTTP
    - name: app
      hostname: "app.example.com"
      port: 80
      protocol: HTTP
    - name: api
      hostname: "api.example.com"
      port: 80
      protocol: HTTP
```

I tried defining a `ClientTrafficPolicy` alongside each `Gateway`, but then I hit the error above. The policy is actually identical, so I could just define it once, but I couldn't figure out where to put it.

For now, I've just gone back to having pretty much all of the config other than `HttpRoute` in the same namespace and repo as the controlplane. I had a similar problem with `SecurityPolicy` where it couldn't access a secret from another namespace even with a `ReferenceGrant` in place.
