### ISSUE TITLE
Health check for backends.gateway.envoyproxy.io

### ISSUE THREAD

**Issue by czczycz** [envoyproxy/gateway#3987]
something like:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: static-upstream
  namespace: default
spec:
  endpoints:
  - ip:
      address: 10.212.100.1
      port: 8080
  - ip:
      address: 10.212.100.2
      port: 8080
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: health-check-static-upstream
  namespace: default
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: static-upstream
  healthCheck:
    active:
      timeout: 3s
      interval: 5s
      unhealthyThreshold: 3
      healthyThreshold: 1
      type: HTTP
      http:
        path: "/healthz"
        expectedStatuses:
          - 200
```
