### ISSUE TITLE
telemetry does not expose Authorization header

### ISSUE THREAD

**Issue by pkit** [envoyproxy/gateway#3994]
Using the following telemetry config:
```yaml
  telemetry:
    accessLog:
      settings:
        - format:
            type: JSON
            json:
              start_time: "%START_TIME%"
              method: "%REQ(:METHOD)%"
              "x-envoy-origin-path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
              protocol: "%PROTOCOL%"
              response_code: "%RESPONSE_CODE%"
              response_flags: "%RESPONSE_FLAGS%"
              response_code_details: "%RESPONSE_CODE_DETAILS%"
              upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
              bytes_received: "%BYTES_RECEIVED%"
              bytes_sent: "%BYTES_SENT%"
              duration: "%DURATION%"
              upstream_duration: "%COMMON_DURATION(US_TX_BEG:US_RX_END:ms)%"
              "x-envoy-upstream-service-time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
              "x-forwarded-for": "%REQ(X-FORWARDED-FOR)%"
              "user-agent": "%REQ(USER-AGENT)%"
              "x-request-id": "%REQ(X-REQUEST-ID)%"
              ":authority": "%REQ(:AUTHORITY)%"
              authorization: "%REQ(AUTHORIZATION)%"
              upstream_host: "%UPSTREAM_HOST%"
              upstream_cluster: "%UPSTREAM_CLUSTER%"
              upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
              downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%"
              downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
              requested_server_name: "%REQUESTED_SERVER_NAME%"
              route_name: "%ROUTE_NAME%"
          sinks:
            - type: OpenTelemetry
              openTelemetry:
                host: otel-collector.monitoring.svc.cluster.local
                port: 4317
                resources:
                  k8s.cluster.name: "cluster1"
```
When examining the log event body I see:
```json
{
  "start_time": "2024-08-03T04:12:10.500Z",
  "method": "POST",
  "x-envoy-origin-path": "/v1/run/data.json",
  "protocol": "HTTP/2",
  "response_code": "200",
  "response_flags": "-",
  "response_code_details": "via_upstream",
  "connection_termination_details": "-",
  "upstream_transport_failure_reason": "-",
  "bytes_received": "593",
  "bytes_sent": "377",
  "duration": "228",
  "x-envoy-upstream-service-time": "-",
  "x-forwarded-for": "46.248.134.173",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
  "x-request-id": "72683feb-3427-4376-bd58-cec278e65ec5",
  ":authority": "api.example.co",
  "upstream_host": "10.99.39.136:80",
  "upstream_cluster": "httproute/example-system/api-server-route/rule/0",
  "upstream_local_address": "10.99.45.255:35834",
  "downstream_local_address": "10.99.45.255:10443",
  "downstream_remote_address": "46.248.134.173:58966",
  "requested_server_name": "api.example.co",
  "route_name": "httproute/example-system/api-server-route/rule/0/match/0/api_staging_example_co"
}
```
Authorization header totally missing from the body.
If I stdout the telemetry on envoy, I see it in the attributes. But it gets deleted in body??
