### ISSUE TITLE
Applied BackendTrafficPolicy breaks HTTPRoute request timeout

### ISSUE THREAD

**Issue by vladimirfx** [envoyproxy/gateway#4091]
*Description*:

When any BackendTrafficPolicy is applied to HTTPRoute the route request timeout setting is ignored. And there is no way to set such timeout in BackendTrafficPolicy. Please suggest a workaround if any.

*Repro steps*:

Route:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: some-api
  labels:
    app.kubernetes.io/part-of: some-service
spec:
  parentRefs:
    - name: common
      namespace: gateway-system
  hostnames:
    - "some-api.example.com"
  rules:
    - backendRefs:
        - name: some-service
          namespace: some
          port: 8000
      timeouts:
        request: "130s"
```

Policy:

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: conn-limit
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      matchLabels:
        app.kubernetes.io/part-of: some-service
  circuitBreaker:
    maxConnections: 1

```

Request timeout (130s) is ignored and default (15s) is used instead.

*Environment*:

EG version 1.1.0
