### ISSUE TITLE
Support  HTTPs Active  Health Checks For TLS Passthrough Upstreams

### ISSUE THREAD

**Issue by muzcategui1106** [envoyproxy/gateway#4100]
*Description*:
Envoy gateway supports health checks for applications using TLS termination by creating an `HTTPRoute` and a  BackendTrafficPolicy](https://gateway.envoyproxy.io/latest/api/extension_types/#backendtrafficpolicy). 

However, this setup does not work for TLS passthrough. When we define a health check for a TLS passthrough `Listerner` that has an associated `TLSRoute` we get the following error.

`2024-08-09T01:45:23.429Z        ERROR   gateway-api     runner/runner.go:186    unable to validate xds ir, skipped sending it   {"runner": "gateway-api", "error": "field HTTPHealthChecker.Host should be specified"}` 

TLS passthrough is common in many organizations where app teams dont want to share the cert in the cluster where envoy gateway is running or where latency is a concern and they do not wish to decrypt and rencrypt.  It is common for an organization to have a common CA cert chain that can be used to validate any certificates created by the compnay's CA, in such cases, appt teams can configure it via a configmap or it can be supplied by cluster admins by default. 

This feature request aims to add support for active health checks for tls passthrough applications by using the same mechanism as TLS termination listeners with HTTPRoutes. 

The fix seems simple in theory but the devil is on the details. We need to setup the health check hostname for TLS routes just as we do for HTTPRoutes.

* [HTTPRoute Implementation](https://github.com/envoyproxy/gateway/blob/eeb62c88f8949f8da8a1278ec5515ffa1a004444/internal/gatewayapi/backendtrafficpolicy.go#L400)
* [TLSRoute Implementation](https://github.com/envoyproxy/gateway/blob/eeb62c88f8949f8da8a1278ec5515ffa1a004444/internal/gatewayapi/backendtrafficpolicy.go#L356)

[Validation Function](https://github.com/envoyproxy/gateway/blob/eeb62c88f8949f8da8a1278ec5515ffa1a004444/internal/ir/xds.go#L2030)

**Comment by muzcategui1106** [comment]
I would like to work on it. It might take a little while before I am allowed by my compnay's policy to contribute to it

**Comment by arkodg** [comment]
seems like a valid use to support 
we probably need to add this line https://github.com/envoyproxy/gateway/blob/eeb62c88f8949f8da8a1278ec5515ffa1a004444/internal/gatewayapi/backendtrafficpolicy.go#L400 for TCP

**Comment by muzcategui1106** [comment]
@arkodg it does not seem that straight forward after looking into it because `ir.TCPRoute` struct does not have a `Hostname` filed. Adding one is an option but it would mean creating a separate `ir.TCPRoute` for each hostname in the TCP listener similar how it is done for HTTPRoutes where a separate `ir.HTTPRoute` is created per hostname in the listener. 

A separate option but perhaps not ideal is set the hostname entry on the health check based on the first SNI hostname inside `ir.TCPRoute.TLS.TLSInspectorConfig.SNIs` . That however does not seem super stable because there is always a possibility that the first hostname in the SNI config is no longer present in one of the application cert's SANs

What do you think?

**Comment by arkodg** [comment]
hey @muzcategui1106, I think it's fine to set the hostname to `ir.TCPRoute.TLS.TLSInspectorConfig.SNIs[0]` if `ir.TCPRoute.TLS != nil && .......`
if that assumption made is wrong, we can revisit the `HealthCheck` API in the future
wdyt @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
@muzcategui1106 does the feature work if we delete the `ErrHCHTTPHostInvalid` check ?

**Comment by muzcategui1106** [comment]
@arkodg no it does not. there is no hostname field in the health check and the endpoint just becomes `UNHEALTHY`

I tried doing the the SNI fix we proposed above. That sort of worked, the endpoints became `HEALTHY` and I saw traffic flowing to my upstream pod coming from envoy-proxy. However, the TLS passthrough listener broke. See the below output. Not sure what is going on there yet.

```
curl -v --resolve "passthrough.example.com:6443:10.244.0.28" https://passthrough.example.com:6443 --cacert ca.crt
* Added passthrough.example.com:6443:10.244.0.28 to DNS cache
* Hostname passthrough.example.com was found in DNS cache
*   Trying 10.244.0.28:6443...
* Connected to passthrough.example.com (10.244.0.28) port 6443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: ca.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* (5454) (IN), , Unknown (72):
* error:0A00010B:SSL routines::wrong version number
* Closing connection 0
curl: (35) error:0A00010B:SSL routines::wrong version number
```

For context we can replicate this by

* Setting up this [example](https://gateway.envoyproxy.io/docs/tasks/security/backend-tls/) . Add a SAN to the cert otherwise the healthcheck wont work
* create a configmap with the ca cert so you can run the health check TLS verification
* Create the following objects

```
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: tlsroute
  namespace: default
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: passthrough-echoserver
  validation:
    caCertificateRefs:
    - name: ca
      group: ''
      kind: ConfigMap
    hostname: passthrough.example.com
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: tlsroute
  namespace: default
spec:
  healthCheck:
    active:
      healthyThreshold: 1
      http:
        path: /
        method: GET
        expectedStatuses: [200, 302] 
      interval: 2s
      timeout: 10s
      type: HTTP
      unhealthyThreshold: 3
  targetRef:
    group: gateway.networking.k8s.io
    kind: TLSRoute
    name: tlsroute
```

**Comment by arkodg** [comment]
@muzcategui1106 can you make the health check e/p http only ?

the addition of `BackendTLSPolicy` for `passthrough-echoserver` is adding another tls socket to the cluster which is breaking tls passthrough (which is pure tcp)

**Comment by muzcategui1106** [comment]
@arkodg not sure if I follow. I have the following TLSRoute

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: tlsroute
  namespace: default
spec:
  hostnames:
  - passthrough.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: passthrough-echoserver
      port: 443
      weight: 1
```

the backend service ultimately directs to an echo server that expects a TLS connection. I can create another port within the service to go the the httpPort but that does not help me here because I cannot configure the TLSRoute to go to a port that expects TLS and a port that doesnt. When connecting to the listener I will ultimately intermittent failures because I would be hitting the http port half of the time

I can configure another TLS route but that would ultimately defeat the purpose of the health check because I am not health checking the targets of the TLS route that is attached to the TLS listener.

Let me know if I am completely wrong here

**Comment by arkodg** [comment]
youre right @muzcategui1106, for TLS Passthrough, the healh check is limited to tcp checks with the current API

**Comment by muzcategui1106** [comment]
what would be your recommendation to enable this in incremental steps. I would not mind working on smaller features first to accomplish this goal. But yeah the way the API is designed does not seem to make it trivial to do :/

**Comment by muzcategui1106** [comment]
Seems like we can use `transport_socket_match_criteria`  at the healthcheck level. I am going to try to use EnvoyPatchPolicy to see if I can patch the envoy proxy configuration with a new transport socket to match the healthcheck

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto

**Comment by arkodg** [comment]
> Seems like we can use `transport_socket_match_criteria` at the healthcheck level. I am going to try to use EnvoyPatchPolicy to see if I can patch the envoy proxy configuration with a new transport socket to match the healthcheck
> 
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto

yeah that option should help here.
I'm a -1 on exposing this at the API level, because this is not a common use imo, but hoping you can still achieve this using EnvoyPatchPolicy.

lets keep this issue open and see if any others in the community also have such a requirement

**Comment by mushrushu** [comment]
Hey! Just wanted to chime in on our use case. We've been using pure envoyproxy for quite a while and now we are eyeing the envoy gateway implementation as an engine for envoy configuration. One of the most common cases for us is load balancing between multiple k8s clusters. In such a case we use tcp_proxy filter with tls passthrough for the traffic and transport_socket_matches for the https health checks. It looks something like this:
```yaml
  transport_socket_matches:
  - name: "enableTLS"
    match:
      acceptTLS: true
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext"
        common_tls_context:
          tls_params:
            ecdh_curves:
              - "X25519"
              - "P-256"
              - "P-384"
  - name: "defaultToPlaintext"
    match: {}
    transport_socket:
      name: envoy.transport_sockets.raw_buffer
      typed_config:
        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer"
```
