### ISSUE TITLE
Use RBAC authorize based on IdToken Claims returned by OAuth2 Filter

### ISSUE THREAD

**Issue by denniskniep** [envoyproxy/gateway#4140]
**Description**:
I want to authorize actions (with RBAC Filter) based on the claims from the IdToken (JWT) which is returned by the OAuth2 Filter.

Example UseCase: Authenticated user must be in a certain group, before he is able to view that route!

1. User authenticates with [OAuth2 Filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter)
2. OAuth2 Filter stores IdToken in Cookie
3. [JWT Filter](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/jwt_authn_filter) verifies IdToken and write claims to [Dynamic State / Metadata](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/data_sharing_between_filters#arch-overview-data-sharing-between-filters) (see properties `payload_in_metadata`, `normalize_payload_in_metadata` and `failed_status_in_metadata` from [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-jwtprovider))
4. [RBAC Filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rbac_filter#config-http-filters-rbac) allows access if the Claim (now located in Metadata) is matching the rule. GroupClaim contains RoleX (see [MetadataMatcher ](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/metadata.proto#type-matcher-v3-metadatamatcher)& [ListMatcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/metadata.proto#type-matcher-v3-metadatamatcher)

**What needs to be done?**
- [x]  Fix current limitation, that no cookies are written if `forwardAccessToken: false` is set (see https://github.com/envoyproxy/envoy/pull/35839)
- [x]  Enhance [JWT Provider](https://gateway.envoyproxy.io/latest/api/extension_types/#jwtprovider) to support writing claims into Metadata via  `payload_in_metadata`, `normalize_payload_in_metadata` and `failed_status_in_metadata`
- [x]  Enhance [AuthorizationRule](https://gateway.envoyproxy.io/latest/api/extension_types/#authorizationrule)´s [Principal](https://gateway.envoyproxy.io/docs/api/extension_types/#principal) with ability to define [MetadataMatcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/metadata.proto#type-matcher-v3-metadatamatcher) (see https://github.com/envoyproxy/gateway/pull/4009 and https://github.com/envoyproxy/gateway/pull/4167)

**Comment by zetaab** [comment]
@denniskniep as https://github.com/envoyproxy/envoy/pull/35839 was merged, does that need changes in gateway side?

**Comment by zhaohuabing** [comment]
@zetaab @denniskniep I think right now authorization based on IDToken Claims can be achieved with a SecurityPolicy like this:

```yaml
  apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: SecurityPolicy
    ......
    oidc:
      provider:
        issuer: "https://foo.bar.com"
      ...
      cookieNames:
        idToken: "MyIdTokenCookie"
    jwt:
      providers:
      - name: foo
        issuer: https://foo.bar.com
        remoteJWKS:
          uri: https://foo.bar.com/jwt/public-key/jwks.json
        extractFrom:
          cookies:
          - MyIdTokenCookie
    authorization:
      defaultAction: Deny
      rules:
      - name: "allow-jwt-claim"
        action: Allow
        principal:
          jwt:
            provider: foo
            scopes:
            - "foo"
            - "bar"
            claims:
            - name: "sub"
              values:
              - "1234567890"
            - name: "roles"
              valueType: "StringArray"
              values:
              - "admin"
              - "superuser"  
```

**Comment by zetaab** [comment]
Yep, i am using it already and works fine 😁

**Comment by kkumlien** [comment]
> @zetaab @denniskniep I think now authorization based on IDToken Claims can be achieved with a SecurityPolicy like below:

Does the `IdToken `need to be set as cookie in order to use the claims for RBAC? E.g. if I set `disable_id_token_set_cookie: true` will it continue to work?
Is there an equivalent config to the one above for **Envoy Proxy**, in case I don't use the Gateway?

**Comment by zetaab** [comment]
It does not work without expose

**Comment by denniskniep** [comment]
@kkumlien maybe that's an option for you once it is implemented: https://github.com/envoyproxy/envoy/issues/23508

**Comment by denniskniep** [comment]
@zetaab I think we don´t need to change smth. in envoy gateway.

**Comment by denniskniep** [comment]
@zhaohuabing awesome! The SecurityPolicy with IDToken Claims authZ works great

**Comment by kkumlien** [comment]
thanks all! cookie encryption definitely helps, though I don't understand why those cookies should be sent downstream in this case: token processing is only required inside Envoy for RBAC purposes. Envoy effectively acts as an OAuth2 client in this case, so sending the token(s) downstream is unnecessary, especially considering the cookie size limit.
should I log a feature request for envoyproxy/envoy?

**Comment by kkumlien** [comment]
separate note: I don't see in Envoy Proxy's RBAC filter a direct equivalent of the above:

```
principal:
  jwt: ...
```

does the following make sense for EP (after the _oauth2_ filter):

in _jwt_authn_ filter, something like:

```
    providers:
      my_jwt:
        from_cookies:
        - IdToken
        payload_in_metadata: my_jwt
```

then in _RBAC_ filter, something like (check if claimed role="admin"):

```
          principals:
          - metadata:
              filter: envoy.filters.http.jwt_authn
              path:
              - key: my_jwt
              - key: claims
              - key: role
              value:
                string_match:
                  exact: "admin"
```
