### ISSUE TITLE
Add support for "invert" matches for Exact/Regex Header matches in BackendTrafficPolicy

### ISSUE THREAD

**Issue by evankanderson** [envoyproxy/gateway#4147]
*Description*:
We would like to be able to set higher limits on specific rate limiting keys, with a lower default limit, e.g.

```
      # Allow 500 reqs/hour for named users
      # Allow 100 reqs/hour for other logged-in users (with JWT mapped to x-user-id)
      # and 50 reqs/hour for users who are not logged in (empty x-user-id)
      - clientSelectors:
        - headers:
          - type: Exact
            name: x-user-id
            value: user-one
        limit:
          requests: 500
          unit: Hour
      - clientSelectors:
        - headers:
          - type: Distinct
            name: x-user-id
        # NEW FUNCTIONALITY
        # Without this, the "Distinct" value also matches "user-one", and we can't grant a higher limit, only a lower one.
        - headers:
          - type: Distinct
            invert: true
            value: user-one
        limit:
          requests: 100
          unit: Hour
      - clientSelectors:
        - sourceCIDR:
            type: Distinct
            value: 0.0.0.0/0
        - headers:
          - type: Exact
            header: x-user-id
            value: ""
        limit:
          requests: 50
          unit: Hour

```
(A mode with "first match wins" and ignores the others would be another option, but this seems harder to fit into the existing API.)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

HeaderMatch supports [`invert_match`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-headermatcher)

Envoy Gateway configuration is [managed in `buildRouteRateLimits`](https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/ratelimit.go#L173) -- this probably applies except for `Distinct` matches.

**Comment by arkodg** [comment]
hey, this is similar to https://github.com/envoyproxy/gateway/issues/2193, which suggests a similar field like `invert` to create more distinct buckets

**Comment by evankanderson** [comment]
Ah!  Somehow my search hadn't found that. 

I've suggested a slightly different implementation -- do you have a sense as to which design you'd prefer?

**Comment by arkodg** [comment]
hey curious why its different, first match is going to get tricky, prefer taking the approach of creating more specific buckets.

Below config will ratelimit all users except `user-one` at 100/Hour
```
      - clientSelectors:
        - headers:
          - type: Distinct
            name: x-user-id
          - type: Exact
            name: x-user-id
            invert/dontMatch: true
            value: user-one
         limit:
           requests: 100
           unit: Hour     
 ```

**Comment by evankanderson** [comment]
Using more-specific buckets will work, but as the set of buckets grows, the
inverted conditions on the lower-priority buckets end up getting longer.
e.g.

```
- clientSelectors:
  - headers:
    - type: Distinct
      name: x-user-id
    - type: Exact
      name: x-user-id
      invert: true
      value: user-one
    - type: Exact
      name: x-api-key
      value: ""
    - type: Exact
      name: x-testing-client
      value: ""
```
