### ISSUE TITLE
HTTPRoute Status Not Updated After Adding Backend

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#415]
I create a gatewayclass, gateway, and httproute. EG surfaces an error:
```
2022-09-23T16:51:34.608Z	ERROR	controller/controller.go:326	Reconciler error	{"runner": "provider", "controller": "httproute", "object": {"name":"httpbin","namespace":"default"}, "namespace": "default", "name": "httpbin", "reconcileID": "1d30e643-0896-4171-9323-7fc6aa75e865", "error": "failed to get service default/httpbin"}
```

I then create the backend service but the route's status is never updated:
```
...
  status:
    parents:
    - conditions:
      - lastTransitionTime: "2022-09-23T16:51:30Z"
        message: Route is accepted
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2022-09-23T16:51:30Z"
        message: Service default/httpbin not found
        observedGeneration: 1
        reason: BackendNotFound
        status: "False"
        type: ResolvedRefs
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: eg
```

cc: @arkodg @skriss

**Comment by danehans** [comment]
I'm seeing this issue even when the backend is created before the httproute.

**Comment by danehans** [comment]
I was able to work around the issue by deleting the httproute, gateway, and gatewayclass. After recreating the gatewayclass, gateway, and httproute (after creating the backend) the httproute surfaced the proper status conditions:
```
  status:
    parents:
    - conditions:
      - lastTransitionTime: "2022-09-23T17:10:28Z"
        message: Route is accepted
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: eg
```
