### ISSUE TITLE
Need a setting to delay start of shutdown sequence

### ISSUE THREAD

**Issue by millermatt** [envoyproxy/gateway#4156]
*Description*:

>Describe the desired behavior, what scenario it enables and how it
would be used.

## Current

Envoy Proxy container stops accepting _new_ connections as soon as the Envoy Proxy pod starts terminating. For reasons described below, this means that zero downtime Envoy Proxy deployment rollouts are _not possible_ when using AWS+NLB.

## Desired

Envoy Proxy container should continue to accept new connections for a configurable amount of time when the Envoy Proxy pod starts terminating. This will allow zero downtime Envoy Proxy deployment rollouts.

>Any extra documentation required to understand the issue.

## Key points

- AWS NLBs send _new_ requests to NLB targets (Envoy Proxy pods) until the target has failed a _minimum_ of 2 health checks ([UnhealthyThresholdCount](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html#health-check-settings)) that are a _minimum_ of 5 seconds apart ([HealthCheckIntervalSeconds](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html#health-check-settings)).
- Envoy Proxy pods stop accepting _new_ requests [immediately when they start terminating](https://github.com/envoyproxy/gateway/blob/301eeddfa4c2f7e4e612874a9c5b13a976156c3e/internal/cmd/envoy/shutdown_manager.go#L132), so there is a guaranteed 5-10 seconds of downtime for new requests coming from the NLB when a proxy pod starts terminating.

## Timing details

Here's a timeline where the pod start terminating immediately following a successful health check from the NLB:

- time 0s: pod starts terminating
- time 0s: envoy proxy container stops taking new requests, but waits for existing requests to finish
- time 0s-5s: NLB gets new requests and sends them to the terminating pod, because it hasn't failed 2 health checks yet. the requests fail
- time 5s: NLB sends a health check request. it fails
- time 5s-10s: NLB gets new requests and sends them to the terminating pod, because it hasn't failed 2 health checks yet. the requests fail
- time 10s: NLB sends a health check request. it fails
- time 10s+: NLB no longer sends requests to the terminating pod

## Possible solution

1. Configure the NLB target health checks to hit a new proxy route (e.g. `/lbhealthz`) that returns a 200 normally. This is important: a) It is not the same endpoint used for pod liveness/readiness probes and b) ShutdownManager knows about it and can toggle it to return non-200 status codes.
2. Add a `gracefulShutdownDelay` (default: `0` for backwards compatibility) or similar property to [ShutdownConfig](https://gateway.envoyproxy.io/docs/api/extension_types/#shutdownconfig) that controls the timing between when the pod goes into a terminating state and when shutdown_manager.go calls `postEnvoyAdminAPI("healthcheck/fail")`.
    - the shutdown container's preStop hook calls `shutdown_manager.go:ShutDown()` as it currently does
    - `shutdown_manager.go:ShutDown()` would call a new `/lbhealthcheck/fail` endpoint on the proxy container immediately, causing `/lbhealthz` to no longer return a 200 status code. NLB health checks start failing, but new and existing requests continue to get processed.
    - after `gracefulShutdownDelay` seconds, `shudown_manager.go` would call `/healthcheck/fail` and `/drain_listeners?graceful&skip_exit`.

AWS NLB users could set `gracefulShutdownDelay` to match their NLB's `UnhealthyThresholdCount * HealthCheckIntervalSeconds` to allow new requests while the NLB health checks are failing.

**Comment by czczycz** [comment]
Same issue.
My proposed solution is:
Implement a controller to watch the status of envoyproxy Pods. When a Pod is found to be in the "Terminating" state, call the NLB (Network Load Balancer) API to remove traffic from this Pod.

**Comment by arkodg** [comment]
hey @millermatt, this issue you are hitting is probably very specific to your setup and configurations. I'd recommend also adding your `EnvoyProxy` config here so its easier to compare and also reproduce.

**Comment by millermatt** [comment]
I am able to consistently reproduce the problem using a very bare minimum deploy of envoy-gateway.

For sure, thank you. I'm attaching files here for a bare minimum config that demonstrates the problem.
[envoy-gateway-config-01-millermatt.zip](https://github.com/user-attachments/files/16910331/envoy-gateway-config-01-millermatt.zip)


Here is my test process:
1. Deploy the attached config and wait for the NLB to be available with healthy targets in the target group.
2. Start `curl` in a loop against the load balancer
3. Do a rollout-restart on the Envoy Proxy Deployment created by the gateway controller
4. Observe that some of the `curl` commands get terminated connections as soon as an Envoy Proxy Pod starts terminating

Given what I've described in this issue's description, we are _guraranteed_ downtime, because
1. the terminating pods _immediately_ stop accepting new requests
2. the load balancer target _must_ experience at least 2 request refusals before it stops sending requests

Here is the curl loop command I use:
```
while true ; do echo "$(date) $(curl -sv https://<load-balancer-host> 2>/dev/stdout | grep '< HTTP')" ; done
```

This is what the curl loop output looks like as soon as a proxy pod starts terminating:
```
Fri Sep  6 10:35:29 CDT 2024 < HTTP/1.1 404 Not Found
Fri Sep  6 10:35:30 CDT 2024 < HTTP/1.1 404 Not Found
Fri Sep  6 10:35:30 CDT 2024 < HTTP/1.1 404 Not Found
Fri Sep  6 10:35:30 CDT 2024 < HTTP/1.1 404 Not Found
Fri Sep  6 10:35:31 CDT 2024
Fri Sep  6 10:35:36 CDT 2024
Fri Sep  6 10:35:42 CDT 2024 < HTTP/1.1 404 Not Found
Fri Sep  6 10:35:42 CDT 2024 < HTTP/1.1 404 Not Found
Fri Sep  6 10:35:42 CDT 2024 < HTTP/1.1 404 Not Found
Fri Sep  6 10:35:43 CDT 2024 < HTTP/1.1 404 Not Found
```

**Comment by ross-at-coactive** [comment]
Just starting with envoy gateway, and +1 here

I've used a custom-configured envoy in EKS with the ALB controller under a 5-9s uptime goal. Unfortunately we didn't use xDS so we used plain rollouts for (frequent-ish) configuration changes including traffic splitting. So we _had_ to have no-downtime rollouts and followed [this EKS guide for load balancing](https://aws.github.io/aws-eks-best-practices/networking/loadbalancing/loadbalancing/) pretty closely. But (AFAIK) xDS doesn't solve for "normal" proxy pod churn anyway. 

In my experience what is described here was 100% a requirement to _not_ have (in our case) `503`s during _every_ rollout or otherwise-triggered pod shutdown during normal operations, like scale-in evictions after a period of high traffic. Our customized shutdown logic had exactly this kind of configurable delay in a `preStop` hook before initializing the graceful draining process, with parameters synced to the ALB health checks pointing at the admin server via helm templating voodoo. An AWS A/NLB can't get the endpoint/endpoint slice updates "fast" so it has to rely on "slow" heath checks pointed at envoy's admin readiness endpoint, which we can fail on the internal termination signal. 

I bet it's junk but we used this [hand-rolled shutdown handler sidecar](https://github.com/wrossmorrow/envoy-shutdown-handler/tree/main) modeled after what I saw in contour and discussed in a variety of envoy/istio and related github issues. [Here's where this proposed config is used](https://github.com/wrossmorrow/envoy-shutdown-handler/blob/ad55ec5a8e80d25744bf28a6874201eae863b00a/main.go#L201-L205) for external, target-specific probe failures to be observed, subsequently watching the draining process to admit process termination.

**Comment by arkodg** [comment]
@ross-at-coactive we do something similar in Envoy Gateway where the `preStop` hook calls an elaborate shutdown routine, more in https://github.com/envoyproxy/gateway/blob/358427167d2aac6a8219198943d1c445c843dc5b/internal/cmd/envoy/shutdown_manager.go#L119

@millermatt looks like you are using explicit NLB health checks
```
          # configure a network load balancer
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: traffic-port
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: https
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-success-codes: "200-499"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "2"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
 ```
 
 my suggestion is to  define a ClientTrafficPolicy https://gateway.envoyproxy.io/docs/tasks/traffic/client-traffic-policy/ with a `healthCheck` section, something like
 ```
 healthCheck:
   path: "/healthz"
 ```
 
 and also add another annotation for path
 ```
 service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
 ```
 
 as well as for interval
 ```
 service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "2"
 ```
 
 Reference: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#health-check

**Comment by millermatt** [comment]
@arkodg

> we do something similar in Envoy Gateway where the `preStop` hook calls an elaborate shutdown routine, more in

@ross-at-coactive can surely clarify more, but the routines are not similar. The Envoy Gateway routine you refer to causes all _new_ requests to be refused as soon as the pod starts terminating. The routine @ross-at-coactive refers to says in its docs:

> set a delay between health check failing and graceful connection draining, to account for some period during which new connections might still be arriving

_This is the key part missing in the current Envoy Gateway shutdown implementation._ There is no way to set a delay between the time when health checks start failing and graceful termination begins. 

---

> looks like you are using explicit NLB health checks

Yes, in an effort to cause them to fail ASAP.

Here is my current config after applying the ClientTrafficPolicy below and adding the healthcheck-interval annotation with the lowest allowed value (`5`, not `2`):

```yaml
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: traffic-port
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-success-codes: "200"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <redacted>
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true,deregistration_delay.timeout_seconds=300
    service.beta.kubernetes.io/aws-load-balancer-type: external
```

---

At your suggestion, I've added this ClientTraffic policy:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: mygateway
  namespace: proxy-namespace
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mygateway
  healthCheck:
    path: "/healthz"
```

All other config is from the zip file I uploaded above.

There is still downtime as soon as any Envoy Proxy pod starts terminating.

```
Tue Sep 10 09:52:23 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:23 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:24 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:24 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:24 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:25 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:25 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:26 CDT 2024 < HTTP/1.1 503 Service Unavailable
Tue Sep 10 09:52:26 CDT 2024 < HTTP/1.1 503 Service Unavailable
Tue Sep 10 09:52:27 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:27 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:28 CDT 2024 < HTTP/1.1 503 Service Unavailable
Tue Sep 10 09:52:28 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:29 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:29 CDT 2024 < HTTP/1.1 503 Service Unavailable
Tue Sep 10 09:52:30 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:30 CDT 2024 < HTTP/1.1 503 Service Unavailable
Tue Sep 10 09:52:31 CDT 2024 < HTTP/1.1 503 Service Unavailable
Tue Sep 10 09:52:31 CDT 2024 < HTTP/1.1 503 Service Unavailable
Tue Sep 10 09:52:31 CDT 2024 < HTTP/1.1 503 Service Unavailable
Tue Sep 10 09:52:32 CDT 2024
Tue Sep 10 09:52:37 CDT 2024
Tue Sep 10 09:52:43 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:43 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:44 CDT 2024 < HTTP/1.1 200 OK
Tue Sep 10 09:52:44 CDT 2024 < HTTP/1.1 200 OK
```

---

I get the impression that your understanding is that the NLB will stop sending new non-health-check requests to the Envoy Proxy pod as soon as the pod starts failing health checks. This is not true. New requests will continue to arrive while the proxy container is draining and not accepting new requests.

Or perhaps you believe the pod will handle new requests while the pod is terminating? This is also not true. The `preStop` hook on the shutdown manager container tells the proxy container immediately to stop accepting new requests and to finish processing existing requests.
