### ISSUE TITLE
JSONPath not correctly translated to JSONPatch paths

### ISSUE THREAD

**Issue by liorokman** [envoyproxy/gateway#4162]
*Description*:
Consider the following fragment of the Envoy Proxy bootstrap yaml:
```yaml
layered_runtime:
  layers:
  - name: global_config
    static_layer:
      re2.max_program_size.error_level: 4294967295
      re2.max_program_size.warn_level: 1000
  - name: some_other_layer
     static_layer:
        key.entry: value
```

I would like to add the key `envoy.some.key.or.other.made.up` into the `static_layer` of the layer called `global_config`.

A JSONPatch that works looks like this:

```yaml
- op: add
  path: /layered_runtime/layers/0/static_layer/envoy.some.key.or.other.made.up
  value: a value
```

But this patch assumes that the layer I want to add the key to is always the first. 

I tried to use a `JSONPath` instead, with the following example:

```yaml
- op: add
  jsonPath: $.layered_runtime.layers[?@.name=='global_config'].static_layer['envoy.some.key.or.other.made.up']
  value: a value
```

I have to use the bracket syntax (`['envoy.some.key.or.other.made.up']`) because the dots must not be treated as one of the JSONPath separators. This is valid JSONPath according to the [RFC](https://www.rfc-editor.org/rfc/rfc9535.html):

> JSONPath expressions move further down the hierarchy using dot notation ($.store.book[0].title) or the bracket notation ($['store']['book'][0]['title']); both replace XPath's / within query expressions, where dot notation serves as a lightweight but limited syntax while bracket notation is a heavyweight but more general syntax.

This results in the following key added to the correct hash:
```yaml
layers:
   - name: global_config
     static_layer:
      '[''envoy.some.key.or.other.made.up'']': a value
       envoy.restart_features.use_eds_cache_for_ads: false
       envoy.something.completely.made.up: arbitrary string
       re2.max_program_size.error_level: 4294967295
```

I get the same result for this JSONPath string as well:

```yaml
- op: add
  jsonPath: $['layered_runtime']['layers'][?@.name=='global_config']['static_layer']['envoy.some.key.or.other.made.up']
  value: a value
```

The translation from JSONPath to a Path used by the JSONPatch should not have the brackets as part of the result.

`$.layered_runtime.layers[?@.name=='global_config'].static_layer['envoy.some.key.or.other.made.up']` should translate to `/layered_runtime/layers/0/static_layer/envoy.some.key.or.other.made.up` and not to `/layered_runtime/layers/0/static_layer/'[''envoy.some.key.or.other.made.up'']'`

**Comment by arkodg** [comment]
cc @denniskniep

**Comment by denniskniep** [comment]
@liorokman can you try this:
```
- op: add
  jsonPath: $.layered_runtime.layers[?@.name=='global_config'].static_layer
  path: envoy.some.key.or.other.made.up
  value: a value
```

**Comment by liorokman** [comment]
@denniskniep I tried this, and this works.

Don't you think that it's a little counter-intuitive relative to how regular `JSONPatch` add operations are specified? When `JSONPath` is not being used, the `path` used also points to a place that doesn't exist yet in the document.

For example: 
```yaml
- op: add
  path: /layered_runtime/layers/0/static_layer/envoy.some.key.or.other.made.up
  value: a value
```

In this case, the `envoy.some.key.or.other.made.up` value doesn't exist, yet the `JSONPatch` RFC says that this is how it should be specified in order to `add` a new key.

At the very least, the documentation should be clear that the value of the `path` attribute is appended to the calculated values of the `jsonPath` attribute. I couldn't find this information in the current documentation.
