### ISSUE TITLE
loadBalancer setting is invalid, only one setting can be set

### ISSUE THREAD

**Issue by ovaldi** [envoyproxy/gateway#4202]
YAML
```
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: least-request-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: backend
  loadBalancer:
    type: LeastRequest
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```

gateway controller log
```
2024-09-10T07:54:55.221Z    ERROR    gateway-api    runner/runner.go:186    unable to validate xds ir, skipped sending it    {"runner": "gateway-api", "error": "loadBalancer setting is invalid, only one setting can be set"}
2024-09-10T07:54:55.221Z    ERROR    watchable    message/watchutil.go:56    observed an error    {"runner": "gateway-api", "error": "loadBalancer setting is invalid, only one setting can be set"}
```

K8s Version: v1.29
Envoy Gateway Version: v1.1.0

**Comment by zirain** [comment]
wordaround, please add flowing:
```
    loadBalancer:
      type: LeastRequest
      slowStart:
        window: 300s
```
