### ISSUE TITLE
Can I target a BackendTrafficPolicy to a specific path/url

### ISSUE THREAD

**Issue by stecullum** [envoyproxy/gateway#4218]
*Description*:

Can a BackendTrafficPolicy target a  domain and path or just the route object ( eh HttpRoute which only listens on a hostname )

I want to only apply my backend policy for a specific path. In my case i have the urls

- `my.example.com/websocket` --> traffic sent to websockets server
- `my.example.com/website` --> traffic sent to website

I need to apply a BackendTrafficPolicy that overrides the default `maxConnection:  1024` for websockets but i dont this to apply to the `my.example.com/website` route 

Consider this...
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: myroute
  namespace: default
spec:
  parentRefs:
    - name: eg-gateway
      namespace: envoy-gateway-system
      kind: Gateway
  hostnames:
    - "my.example.com"
  rules:    
    - matches:
        - path:
            type: Exact
            value: /websocket
      backendRefs:
        - group: ""
          kind: Service
          name: websockets-server
          namespace: default

    - matches:
        - path:
            type: Exact
            value: /website
      backendRefs:
        - group: ""
          kind: Service
          name: website
          namespace: default
          ...
```

And a `BackendTrafficPolicy` to handle websockets
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: websockets-policy
  namespace: default
spec:
  targetRefs:  
  /// how to make this only apply to `my.example.com/websocket` not `my.example.com`
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: myroute
  circuitBreaker:
    maxConnections: 2000000 # max connections EACH envoy instance can send to a downstream svc ( made up number to future proof num players )
    maxParallelRequests: 15000 # Limit concurrent requests per pod
    maxRequestsPerConnection: 1000000 # Allow a large number of requests per connection
```

Thanks
