### ISSUE TITLE
EnvoyGateway rateLimitDeployment ignores pod labels

### ISSUE THREAD

**Issue by oscarboher** [envoyproxy/gateway#4226]
*Description*:
When configuring the rate limit deployment through the `envoy-gateway-config` configmap, the `provider.kubernetes.rateLimitDeployment.pod.labels` field is ignored.
Other fields at the same level like annotations are respected.

*Repro steps*:
* gateway v1.1 (experimental channel)
* envoy-gateway installed through helm chart v0.0.0-latest
* create GatewayClass with envoy controller.
* Update `envoy-gateway-config` configmap in `envoy-gateway-system` namespace with the following values:
  
  ````
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: envoy-gateway-config
    namespace: envoy-gateway-system
  data:
    envoy-gateway.yaml: |
      apiVersion: gateway.envoyproxy.io/v1alpha1
      kind: EnvoyGateway
      provider:
        type: Kubernetes
        kubernetes:
          rateLimitDeployment:
            replicas: 4
            pod:
              labels:
                my-label: test
              annotations:
                test-anno: test
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      rateLimit:
        backend:
          type: Redis
          redis:
            url: redis.redis-system.svc.cluster.local:6379
        telemetry:
          metrics:
            prometheus:
              disable: false
          
        
  ```
* Rollout restart envoy-gateway deployment for it to pick up the changes.
* Deployment envoy-ratelimit has the annotation `test-anno: test` in the pod spec, but not the label `my-label: test`

*Environment*:
* gateway v1.1 (experimental channel)
* envoy-gateway installed through helm chart v0.0.0-latest
* image gw controller: docker.io/envoyproxy/gateway-dev:latest

**Comment by zirain** [comment]
this indeed a bug, @oscarboher would you like to send a fix?

BTW, I think we may also have issue on merging annotations.

**Comment by zirain** [comment]
that's the point.

**Comment by arkodg** [comment]
hey @oscarboher thanks for giving it a try, assigning this you for now, let us know how we can help

**Comment by arkodg** [comment]
a workaround could be to use the `patch` field  https://gateway.envoyproxy.io/docs/api/extension_types/#kubernetesdeploymentspec

I haven't tested this config, but something similar should help here

```
rateLimitDeployment:
  patch:
    template:
      metadata:
        labels:
          my-label: test
```
