### ISSUE TITLE
Incorrect validation of topologyKey when specifying pod affinity

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/gateway#4232]
EG fails to translate pod affinity specification for deployment:
```
...
                    podAntiAffinity:
                      requiredDuringSchedulingIgnoredDuringExecution:
                        - podAffinityTerm:
                            labelSelector:
                              matchExpressions:
                                - key: "app.kubernetes.io/name"
                                  operator: In
                                  values:
                                    - envoy
                            topologyKey: "kubernetes.io/hostname"
```
Results in errors in EG logs:
```
 spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: \"\": name part must be non-empty, spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: \"\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]"}
```
The value of topologyKey field is correct according to k8s docs.
