### ISSUE TITLE
Static unhashed service name

### ISSUE THREAD

**Issue by eadwu** [envoyproxy/gateway#4243]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Don't append any hash to the end of the name?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

```
    gateway.envoyproxy.io/owning-gateway-name: eg-netdata
    gateway.envoyproxy.io/owning-gateway-namespace: netdata
  name: envoy-netdata-eg-netdata-c2cc8355
```

Expectation is either `envoy-netdata-eg-netdata` or `eg-netdata`.

**Comment by eadwu** [comment]
Since it is a static derivation I guess it's fine but I'm not sure why there is a hash for the service.

`printf namespace/name | sha256sum` - trim name up to 48 characters and concat first 8 of hash

**Comment by arkodg** [comment]
the current naming with the hash ensures that the deployment and service name is under 63 chars (limit)

you can set specific name using the EnvoyProxy resource
https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: "foo"
```
https://gateway.envoyproxy.io/docs/api/extension_types/#kubernetesservicespec
