### ISSUE TITLE
Add support for headers_to_add of AuthorizationRequest in Ext-Auth

### ISSUE THREAD

**Issue by thomgun** [envoyproxy/gateway#4267]
*Description*:
We are currently evaluating envoy gateway. The external authorizer service we are using, requires that some `X-Forwarded` headers are sent in authorization request.

With istio, this can be achieved by configure ` includeAdditionalHeadersInCheck`, e.g.
```
meshConfig:
  extensionProviders:
  - name: "my-ext-authz"
    envoyExtAuthzHttp:
       ...
      includeAdditionalHeadersInCheck: # required additional headers sent to auth-service in the check request.
        X-Forwarded-Uri: '%REQ(:PATH)%'
        X-Forwarded-Host: '%REQ(Host)%'
        X-Forwarded-Method: '%REQ(:METHOD)%'
        X-Forwarded-Proto: 'https'
      ....
```
which configures `headers_to_add` in `AuthorizationRequest`. Would it be possible to add a similar config in the `SecurityPolicy` ?

[optional *Relevant Links*:]
* Config of `headers_to_add` in  `AuthorizationRequest` : https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-authorizationrequest

**Comment by arkodg** [comment]
@thomgun have you tried using the `headersToExtAuth` field to solve your use case ? are the `X-Forwarded` headers already part of the request ?
https://gateway.envoyproxy.io/docs/api/extension_types/#extauth
https://gateway.envoyproxy.io/docs/tasks/security/ext-auth/

**Comment by thomgun** [comment]
@arkodg,
AFAIK the `headersToExtAuth` are adding headers already in the request to authorizer service. But in our use case envoy gateway would be the entrypoint of the cluster and the load balancer in front of the gateway don't deliver these headers. That's the reason why we use  `includeAdditionalHeadersInCheck` in istio setup.

**Comment by arkodg** [comment]
can this functionality be achieved using `EarlyRequestHeaders` / ` Early Header Mutation` 
https://github.com/envoyproxy/gateway/blob/d00737b69766460ae97c3bc451baa43b9b5fa85a/api/v1alpha1/clienttrafficpolicy_types.go#L139 @guydc ?

**Comment by guydc** [comment]
> can this functionality be achieved using EarlyRequestHeaders /  Early Header Mutation

It should be possible, here are the EG docs for early header modification: https://gateway.envoyproxy.io/latest/tasks/traffic/http-request-headers/#early-header-modification 

Additionally, the ext-auth `HeadersToExtAuth` should be used to instruct which added headers should be sent to ext-auth https://gateway.envoyproxy.io/docs/api/extension_types/#extauth 

@thomgun  - please note that some of the headers that you mentioned will be overwritten by envoy. So, the value that you set with an early modification would be available to ext-auth, but the upstream may see a different value set by envoy.

**Comment by arkodg** [comment]
thanks for confirming @guydc !
hey @thomgun you'll need to use the latest bits `v0.0.0-latest` to try this new feature out. This should also be available in `v1.2.0` that should hopefully be available by end Oct 2024

**Comment by thomgun** [comment]
HiHo @arkodg ,
sorry for answering late, was a little busy last days.

I have tested the solution and can confirm that this is working:  We deployed a `ClientTrafficPolicy` :
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: enable-early-headers
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gw
  headers:
    earlyRequestHeaders:
      set:
        - name: "X-Forwarded-Uri"
          value: "%REQ(:PATH)%"
        - name: "X-Forwarded-Host"
          value: "%REQ(Host)%"
        - name: "X-Forwarded-Method"
          value: "%REQ(:METHOD)%"
        - name: "X-Forwarded-Proto"
          value: "https"
```
and added the four headers to `extAuth.headersToExtAuth` of the `SecurityPolicy`.
Thanks for pointing to the right direction. So I will close the issue.
