### ISSUE TITLE
Mutual TLS - Skip client certificate validation

### ISSUE THREAD

**Issue by haritzsaiz** [envoyproxy/gateway#4280]
*Description*:

Is it possible to request a client certificate during the (mutual) TLS handshake that:

- If no certificate is presented, the requests is forwarded to the upstream services
- If given by the client, the certificate is not validated at all by the Gateway. Simply the certificate information is forwarded to the upstream services using XFCC headers.

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: enable-mtls
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  tls:
    maxVersion: "1.2"
    clientValidation:
      optional: true
      caCertificateRefs:
      - kind: "Secret"
        group: ""
        name: "my-ca-secret"
  headers:
    xForwardedClientCert:
      mode: AppendForward
      certDetailsToAdd: 
      - Chain
```

If I've understood the documentation correctly, it's only possible configuring optional mutual TLS, that is:
- If no certificate is presented, the request is forwarded to the upstream services
- If given by the client, the certificate is **ALWAYS** validated at all by the Gateway using the given `caCertificateRefs` .

In fact, I've seen that if `caCertificateRefs` is not correcly specified, the`Certificate Request` is not present in the TLS handshake. Would it be possible perphaps if  `caCertificateRefs` is null / not set, that simply no client certificate validation is performed?
