### ISSUE TITLE
replacePrefixMatch broken in main

### ISSUE THREAD

**Issue by zetaab** [envoyproxy/gateway#4331]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

with envoy gateway 1.1 I was using following spec

```
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /docs/
```

So my goal is to add `/docs/` prefix to all url paths. So it will be modified like `/docs/<originalpath>`.

However, with latest main it will not add the ending slash anymore. I was forced to use 

```
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /docs//
```

to get same behaviour working.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

eg 1.1 and latest main

*Logs*:
>Include the access logs and the Envoy logs.
