### ISSUE TITLE
How to set `direct_response` (Return an arbitrary HTTP response directly, without proxying)

### ISSUE THREAD

**Issue by yuyicai** [envoyproxy/gateway#4346]
*Description*:
How to set `direct_response` using envoy gateway?
The envoy proxy native configuration:
```yaml
route_config:
  virtual_hosts:
    - name: direct
      domains:
        - "www.example.com"
      routes:
        - match:
            prefix: "/404"
          direct_response: 
            status: 404
```

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-route-direct-response
