### ISSUE TITLE
Second parentRef in a HTTPRoute specifies "default" namespace

### ISSUE THREAD

**Issue by xmath279** [envoyproxy/gateway#4387]
*Description*:

When a HTTPRoute references two different sections of a Gateway, the second `parentRef` has the namespace set to `default` instead of defaulting to the namespace of the HTTPRoute.

*Repro steps*:

Create a HTTPRoute with parentRefs such as this:

```yaml
parentRefs:
- group: gateway.networking.k8s.io
  kind: Gateway
  name: default
  sectionName: tls-section
- group: gateway.networking.k8s.io
  kind: Gateway
  name: default
  sectionName: insecure-section
```

After this is created, using `kubectl describe` on the route reveals the following:

```yaml
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-10-04T21:36:14Z"
      message: Route is accepted
      observedGeneration: 6
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-10-04T21:36:14Z"
      message: Resolved all the Object references for the Route
      observedGeneration: 6
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: default
      sectionName: tls-section
  - conditions:
    - lastTransitionTime: "2024-10-04T21:36:14Z"
      message: There were no hostname intersections between the HTTPRoute and this
        parent ref's Listener(s).
      observedGeneration: 6
      reason: NoMatchingListenerHostname
      status: "False"
      type: Accepted
    - lastTransitionTime: "2024-10-04T21:36:14Z"
      message: Resolved all the Object references for the Route
      observedGeneration: 6
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: default
      namespace: default
      sectionName: insecure-section
```

As you can see, the second parentRef gets the namespace set to `default` which causes the error `There were no hostname intersections between the HTTPRoute and this parent ref's Listener(s).` because the parentRef does not exist in the `default` namespace.

*Environment*:

Envoy Gateway 1.1.0

*Logs*:

Irrelevant
