### ISSUE TITLE
Envoy gateway does not start https endpoint correctly

### ISSUE THREAD

**Issue by zozo6015** [envoyproxy/gateway#4396]
*Description*:
>I have setup an envoy gateway with a http and https listeners. The https listener it does not seam to start and it's failing with the following logs in the pod:
`[2024-10-06 09:29:27.660][1][warning][misc] [source/extensions/filters/network/http_connection_manager/config.cc:83] internal_address_config is not configured. The existing default behaviour will trust RFC1918 IP addresses, but this will be changed in next release. Please explictily config internal address config as the migration step.`

*Repro steps*:
 
Created the EnvoyProxy:

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  logging:
    level:
      default: warn
  provider:
    kubernetes:
      envoyDeployment:
        container:
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 150m
              memory: 640Mi
        pod:
          annotations:
            example: value
      envoyHpa:
        maxReplicas: 10
        metrics:
          - resource:
              name: cpu
              target:
                averageUtilization: 60
                type: Utilization
            type: Resource
        minReplicas: 1
    type: Kubernetes

```

GatewayClass:

```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: https-http
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
```

Gateway:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
  name: shared-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: https-http
  listeners:
    - allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: 'true'
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: ssl
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: 'true'
      name: http
      port: 80
      protocol: HTTP
```

*Environment*:
>kubernetes version 1.28.2
  envoy-gateway version: v1.1.2

*Logs*:
Pod: envoy-envoy-gateway-system-shared-gateway-test-680c4482-86xtgtl log:

`[2024-10-06 09:29:27.660][1][warning][misc] [source/extensions/filters/network/http_connection_manager/config.cc:83] internal_address_config is not configured. The existing default behaviour will trust RFC1918 IP addresses, but this will be changed in next release. Please explictily config internal address config as the migration step.`
