### ISSUE TITLE
Gateways never become ready/programmed when running daemonset EnvoyProxy

### ISSUE THREAD

**Issue by jukie** [envoyproxy/gateway#4416]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

I'm trying to run envoy proxy as a daemonset which was implemented with https://github.com/envoyproxy/gateway/pull/3092.
I think the cause of this bug is https://github.com/envoyproxy/gateway/blob/d1cc0ba4372fd7d3f8ede1a1278930e21c22b9f2/internal/gatewayapi/status/gateway.go#L163-L168 and doing a lookup on deployment vs daemonset.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Use the below configuration with an EnvoyProxy to trigger using a daemonset:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  mergeGateways: true
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet:
        strategy:
          type: RollingUpdate
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: gateway-demo
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
```

Then the programmed status will always show as false even though the gateway is actually functional:
```
Status:
  Conditions:
    Last Transition Time:  2024-10-09T16:12:58Z
    Message:               Deployment replicas unavailable
    Observed Generation:   1
    Reason:                NoResources
    Status:                False
    Type:                  Programmed
```
>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.
