### ISSUE TITLE
Add redis config option so that I can use helm

### ISSUE THREAD

**Issue by daniel-white** [envoyproxy/gateway#4425]
*Description*:
I'm going to be using global rate limiting. Right now the steps call for a `ConfigMap` to patch the `envoy-gateway.yaml` file to get the redis backend. With setting this file and starting a restart of the gateway deployment, this is not easily managed. I'd imagine that we have a resource that we can easily set the redis url without that dance.

[optional *Relevant Links*:]
Enabling steps: https://gateway.envoyproxy.io/docs/tasks/traffic/global-rate-limit/#enable-global-rate-limit-in-envoy-gateway

**Comment by zhaohuabing** [comment]
This can be supported by add a Redis configuration knob in the helm Value file. Something like:

```yaml
redis:
   url: myredis:6379
   tls: 
     ....
```

**Comment by arkodg** [comment]
I'm not sure I understand the ask here

a helm config like
```
config:
  envoyGateway:
    logging:
      level:
        default: debug
    rateLimit:
      backend:
        type: Redis
        redis:
          url: redis.redis-system.svc.cluster.local:6379        
```

should let you configure and enable global ratelimiting

You shouldnt need to restart the deployment anymore in the next release since https://github.com/envoyproxy/gateway/issues/3209 has been fixed (docs will be updated soon)
