### ISSUE TITLE
Adding BackendTrafficPolicy removes the HTTPRoute timeout configuration 

### ISSUE THREAD

**Issue by tejaboppana** [envoyproxy/gateway#4426]
*Description*:
When we create a HTTPRoute with `timeouts ` and create BackendTrafficPolicy attached to this HTTPRoute, the route timeout is wiped out. This issue is similar to https://github.com/envoyproxy/gateway/issues/4091

*Repro steps*:
- Create HTTPRoute with timeouts 
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-app-1
spec:
  parentRefs:
  - name: my-gateway
  hostnames:
  - "foo.com"
  rules:
  - matches:
    - path:
        value: "/foo"
      headers:
      - name: "version"
        value: "2"
    - path:
        value: "/v2/foo"
    timeouts:
       request: "0s"
```

- Create a BackendTrafficPolicy attached to the above HTTPRoute 
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: test
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: http-app-1
   timeout:
      http:
         connectionIdleTimeout: "300s"
```

*Environment*:
Gateway versions 1.1.2
