### ISSUE TITLE
Ratelimit based on path and method

### ISSUE THREAD

**Issue by s0uky** [envoyproxy/gateway#4449]
*Description*:
This feature request is follow up from Slack discussion with @arkodg .

The functionality for defining multiple rate limits was previously available through `RateLimitFilters`. However, these filters were removed from the codebase [around version 0.6.0](https://github.com/envoyproxy/gateway/issues/2006). A new CRD named `BackendTrafficPolicy` was introduced, and the `rateLimit` field now belongs to this CRD.

It would be beneficial to be able to define multiple rate limits again for entire paths within `BackendTrafficPolicy`. This would allow for a use case where a "basic" rate limit could be applied to unauthenticated clients, while a stricter "proper" rate limit could be applied to users with valid JWT authentication ([basic authentication is a separate consideration](https://github.com/envoyproxy/gateway/issues/2947)).

**Comment by arkodg** [comment]
this should be possible with https://gateway.envoyproxy.io/docs/tasks/traffic/global-rate-limit/

Option 1 - match on `:path`
sometthing like
```
  rateLimit:
    type: Global
    global:
      rules:
      - clientSelectors:
        - headers:
          - name: :path
            value: /app
        limit:
          requests: 3
          unit: Hour
```          
Option 2
Create 2 HTTPRoutes (same hostname but different rules for different path matches) and apply a unique BTP for each HTTPRoute
