### ISSUE TITLE
Empty Connection Limit causes XDS rejection

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#4457]
*Description*:
If an empty connection limit is configured in CTP, envoy rejects xds. 

```
"details": "Proto constraint validation failed (ConnectionLimitValidationError.MaxConnections: value must be greater than or equal to 1): stat_prefix: \"tls-terminate-10443\"\nmax_connections {\n}\n"}
```

*Repro steps*:
Follow quickstart and apply the following CTP:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: connection-limit-ctp
  namespace: default
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  connection:
    connectionLimit: {}
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.
