### ISSUE TITLE
HTTPRoute upstream timeouts not honoured when BackendTrafficPolicy resource is Created.

### ISSUE THREAD

**Issue by nebed** [envoyproxy/gateway#4478]
*Description*:

when backendRequest timeout is set in HTTPRoute, and there is a BackendTrafficPolicy assigned to that route. the backendRequest timeout is not honoured.

*Repro steps*:
create HTTPRoute resource with timeouts, create BackendTrafficPolicy Implementing ratelimit for that route.

*Environment*:
gateway version - v1.1.2

*Logs*:
Route with ratelimit and timeouts set
```
    pathMatch:
      distinct: false
      name: ""
      prefix: /api/resell    
    traffic:
      rateLimit:
        global:
          rules:
          - headerMatches:
            - distinct: true
              name: x-claim-name
            limit:
              requests: 2
              unit: Minute
```
Route with no rate limit
```
    pathMatch:
      distinct: false
      name: ""
      prefix: /
    traffic:
      timeout:
        http:
          requestTimeout: 15m0s
 ```
