### ISSUE TITLE
docs: How to achieve Backend failover?

### ISSUE THREAD

**Issue by ferdinandosimonetti** [envoyproxy/gateway#4501]
*Description*:
I'd like to implement failover in case of unhealty backend workload for an HTTPRoute.
**Scenario**:
- two workloads (workload4 and workload2) with their respective Services (workload4 and workload2)
- during normal operations, 100% of the requests coming in through the HTTPRoute should be routed to workload4
- if workload4's Pods fail (or are not present) for whatever reason, then 100% of requests should be routed to workload2 

I'm using **v0.0.0-latest** Helm Chart version and I've set **config.envoyGateway.extensionApis.enableBackend=true**

I tried this HTTPRoute

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tobackend
  namespace: default
spec:
  parentRefs:
    - name: test-fsmn-xyz
      sectionName: https
  hostnames:
    - "test0.fsmn.xyz"
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: workload4
        - group: gateway.envoyproxy.io
          kind: Backend
          name: workload2
      matches:
        - path:
            type: PathPrefix
            value: /tobackend
```

And these Backends

````
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: workload4
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: workload4.default.svc.cluster.local
        port: 80
````

```
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: workload2
  namespace: default
spec:
  fallback: True
  endpoints:
    - fqdn:
        hostname: workload2.default.svc.cluster.local
        port: 3000
```

But, as if I set workload4's Pods to fail, I keep getting 503 status replies, instead of failing over to workload2's Pods
I guess I'm missing something important, here.
Thanks in advance!

*Relevant Links*:
[Enable Backend](https://gateway.envoyproxy.io/docs/tasks/traffic/backend/#enable-backend)

**Comment by guydc** [comment]
You should also let envoy know how to determine that a certain backend is unhealthy for the failover to kick-in. You can achieve this using either Active or Passive healthchecks in BackendTrafficPolicy applied to the `tobackend` route:
- https://gateway.envoyproxy.io/latest/api/extension_types/#activehealthcheck
- https://gateway.envoyproxy.io/latest/api/extension_types/#passivehealthcheck

**Comment by yongzhang** [comment]
> You should also let envoy know how to determine that a certain backend is unhealthy for the failover to kick-in. You can achieve this using either Active or Passive healthchecks in BackendTrafficPolicy applied to the `tobackend` route:
> 
> * https://gateway.envoyproxy.io/latest/api/extension_types/#activehealthcheck
> * https://gateway.envoyproxy.io/latest/api/extension_types/#passivehealthcheck

@arkodg Sorry I just ask a question here:
In the example [here](https://gateway.envoyproxy.io/latest/tasks/traffic/failover/), I can see `targetRefs` refers to the whole `HTTPRoute`, what if we have multiple rules in the route?
```
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: passive-health-check
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ha-example
```

For example, 
```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ha-example
  namespace: default
spec:
  hostnames:
  - www.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg 
    namespace: default
  rules:
  - backendRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: active
      namespace: default
      port: 3000
    - group: gateway.envoyproxy.io
      kind: Backend
      name: passive 
      namespace: default
      port: 3000
    matches:
    - path:
        type: PathPrefix
        value: /test1
  - backendRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: active2
      namespace: default
      port: 3000
    - group: gateway.envoyproxy.io
      kind: Backend
      name: passive2
      namespace: default
      port: 3000
    matches:
    - path:
        type: PathPrefix
        value: /test2
```
In this case how HC works against backends in the 2 rules?

Let me explain my use case:
- I have 2 targets (e.g. service-1, service-2)
- I have a domain with multiple paths, but all routing to the one of the 2 service
- Some paths routing to service-1, and use service-2 as failover
- Some paths routing to service-2, and use service-1 as failover

So as this docs, looks like I have to create 4 Backends like this:
```
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: service-1-active
spec:
  endpoints:
    - fqdn:
        hostname: ${service-1}
        port: 443
  tls:
    wellKnownCACertificates: true

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: service-1-passive
spec:
  endpoints:
    - fqdn:
        hostname: ${service-2}
        port: 443
  fallback: true
  tls:
    wellKnownCACertificates: true

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: service-2-active
spec:
  endpoints:
    - fqdn:
        hostname: ${service-2}
        port: 443
  tls:
    wellKnownCACertificates: true

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: service-2-passive
spec:
  endpoints:
    - fqdn:
        hostname: ${service-1}
        port: 443
  fallback: true
  tls:
    wellKnownCACertificates: true
```

And then define a HTTPRoute like this:
```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-route
spec:
  parentRefs:
    - name: gateway
  hostnames:
    - "${my_domain}"
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: service-1-active
        - group: gateway.envoyproxy.io
          kind: Backend
          name: service-1-passive
      matches:
        - path:
            type: PathPrefix
            value: /test1
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: service-2-active
        - group: gateway.envoyproxy.io
          kind: Backend
          name: service-2-passive
      matches:
        - path:
            type: PathPrefix
            value: /test2
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: service-1-active
        - group: gateway.envoyproxy.io
          kind: Backend
          name: service-1-passive
      matches:
        - path:
            type: PathPrefix
            value: /test3
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: service-2-active
        - group: gateway.envoyproxy.io
          kind: Backend
          name: service-2-passive
      matches:
        - path:
            type: PathPrefix
            value: /test4
```

Does it looks right? If this is correct, how can I add active HC? And the problem is, for each rule, does it mean each rule will create HC, so in my case will my backends receive too many HC requests?
