### ISSUE TITLE
Restrict /metrics endpoint access to internal subnet only

### ISSUE THREAD

**Issue by SergeiCherevko** [envoyproxy/gateway#4503]
Hello, I have an HTTPRoute

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: xxx-route
  namespace: xxx
spec:
  parentRefs:
    - name: eg
  hostnames:
    - xxx.example.com
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: xxx
          namespace: xxx
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```

However, this domain also exposes /metrics for scraping by the Kubernetes cluster.

I need to restrict access to these metrics and allow access only from the 10.0.0.0/8 subnet, but not from external sources. How can I achieve this?

**Comment by arkodg** [comment]
my recommendation would be to use https://kubernetes.io/docs/concepts/services-networking/network-policies/ for this

**Comment by zirain** [comment]
For security practice, you'd better use another port for metric, and listen on localhost/podip instead of `0.0.0.0`.

**Comment by SergeiCherevko** [comment]
I made another one HTTPRoute with /metrics path
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: xxx-metrics-route
  namespace: xxx
spec:
  parentRefs:
    - name: eg
  hostnames:
    - xxx.example.com
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: xxx
          namespace: xxx
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /metrics
 ```
 
 and Security Policy
 
 ```
 apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: xxx-metrics-policy
  namespace: xxx
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: xxx-metrics-route
  authorization:
    defaultAction: Deny
    rules:
      - action: Allow
        principal:
          clientCIDRs:
            - 10.0.0.0/8
      - action: Allow
        principal:
          clientCIDRs:
            - 172.16.0.0/12
```

and it works good
