### ISSUE TITLE
Could we loose jwtProvider validation for issuer ?

### ISSUE THREAD

**Issue by wengyao04** [envoyproxy/gateway#4534]
*Description*:
>Describe the issue.

We use jwt authentication
```
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: security-policy
  namespace: eg-test
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: my-http-route
  jwt:
    providers:
      - name: foo
        issuer: foo.<company-domain-name>.com
        remoteJWKS:
          uri: https://<mysts>/jwks/<foo>
```
But we see error in gateway controller log
```
2024-10-26T03:32:32.610Z	ERROR	gateway-api	runner/runner.go:186	unable to validate xds ir, skipped sending it	{"runner": "gateway-api", "error": "invalid issuer; must be a URL or email address: mail: missing '@' or angle-addr\ninvalid issuer; must be a URL or email address: mail: missing '@' or angle-addr"}
2024-10-26T03:32:32.610Z	ERROR	watchable	message/watchutil.go:56	observed an error	{"runner": "gateway-api", "error": "invalid issuer; must be a URL or email address: mail: missing '@' or angle-addr\ninvalid issuer; must be a URL or email address: mail: missing '@' or angle-addr"}
```
It is caused by this [issuer validation check](https://github.com/envoyproxy/gateway/blob/main/api/v1alpha1/validation/securitypolicy_validate.go#L71-L78). However, the `iss` in our use case is `foo.<company-domain-name>.com`. Do you think if we can loose the validation check ?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
