### ISSUE TITLE
Oauth2-proxy as ExtAuth 

### ISSUE THREAD

**Issue by zeisich** [envoyproxy/gateway#4562]
*Description*:
I'm assessing whether we can move away from our current Ingress/Auth Ambassador Edge-Stack in favor of Envoy Gateway or others. We heavily rely on JWT & OIDC filtering at the moment and EG unfortunately has a less than optimal implementation of a combination of both compared to AES. I therefore try to use oauth2-proxy as ExtAuth in a SecurityPolicy.

This is my extAuth spec, successfully calling the endpoint of oauth2-proxy [that should either return `202` or `401`](https://oauth2-proxy.github.io/oauth2-proxy/configuration/integration#forwardauth-with-401-errors-middleware).
``` yaml
extAuth:
    failOpen: false
    headersToExtAuth:
    - Cookie
    - X-Auth-Request-User
    - X-Auth-Request-Groups
    - X-Auth-Request-Email
    - X-Auth-Request-Preferred-Username
    - X-Forwarded-Proto
    - X-Forwarded-Host
    - X-Forwarded-Uri
    - X-Auth-Request-Access-Token
    http:
      backendRefs:
      - group: ""
        kind: Service
        name: oauth2-proxy
        port: 80
      path: /oauth2/auth
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway1
```

My envoy actually reports this `202` code correctly, however, still considers it as `ext_authz_denied`.

``` json
{
  "start_time": "2024-10-29T15:10:29.515Z",
  "method": "GET",
  "x-envoy-origin-path": "/",
  "protocol": "HTTP/2",
  "response_code": "202",
  "response_flags": "UAEX",
  "response_code_details": "ext_authz_denied",
  "connection_termination_details": "-",
  "upstream_transport_failure_reason": "-",
  "bytes_received": "0",
  "bytes_sent": "13",
  "upstream_host": "-",
  "upstream_cluster": "httproute/dummy-app/dummy-app/rule/0",
  "route_name": "httproute/dummy-app/dummy-app/rule/0/match/0/*"
}
```

I'm not sure how this makes sense, what kind of response would the envoy proxy expect in order to let my request through?
