### ISSUE TITLE
TLS Backend cert validation types

### ISSUE THREAD

**Issue by lsjostro** [envoyproxy/gateway#4595]
*Description*:
I'm trying to configure TLS Backend validation of a service (out of my control and out side k8s). The cert on that external service is not using SAN DNS. Only Common name. Is there a better way other then creating a patch like this to remove validation `san_type: DNS`?
   
```
# foo-svc cert doesn't use SubjectAltName DNS so we need to patch away SAN DNS validation.
# CA cert validation is working, just not using SubjectAltName DNS which I'm patching away for now
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: foo-svc-delete-san-patch
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: eg
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.cluster.v3.Cluster"
      name: "httproute/external-legacy-services/foo-svc/rule/0"
      operation:
        op: remove
        path: "/transport_socket_matches/0/transport_socket/typed_config/common_tls_context/combined_validation_context/default_validation_context/match_typed_subject_alt_names/0"
```
