### ISSUE TITLE
BackendRef weights not work

### ISSUE THREAD

**Issue by czczycz** [envoyproxy/gateway#4602]
I am testing the HttpRoute. I config BackendRefs with different weights(backend0 weight = 99 and backend1 weight = 1).

I sent thousands of requests and found that backend0 and backend1 received roughly the same number of requests.

I obtained the cluster configuration by admin API (/clusters?format=json). The clusters configuration shows that backend0 and backend1 have the same weight=1.

This is my httpRoute:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: myroute
  namespace: default
spec:
  hostnames:
  - example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gw1
    namespace: default
    sectionName: http-80
  rules:
  - backendRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: backend0
      namespace:default
      port: 80
      weight: 99
    - group: gateway.envoyproxy.io
      kind: Backend
      name: backend1
      namespace: default
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```
This is my clusters config:
```
"host_statuses": [
        {
            "address": {
                "socket_address": {
                    "address": "10.234.125.2",
                    "port_value": 80
                }
            },
            "stats": [],
            "health_status": {
                "eds_health_status": "HEALTHY"
            },
            "weight": 1,
            "locality": {
                "region": "httproute/default/myroute/rule/0/backend/0"
            }
        },
        {
            "address": {
                "socket_address": {
                    "address": "10.234.125.3",
                    "port_value": 80
                }
            },
            "stats": [],
            "health_status": {
                "eds_health_status": "HEALTHY"
            },
            "weight": 1,
            "locality": {
                "region": "httproute/default/myroute/rule/0/backend/1"
            }
        }
    ]
```

**Comment by czczycz** [comment]
I checked the history and found this [#PR](https://github.com/envoyproxy/gateway/pull/1494/files#diff-d0da16bff73f9d98d6346ffcf878a7bf6c689dbe11a8176598319ddb0b2a7a0dR96)
After I adjusted the code and rebuilt EG, everything was fine.
![image](https://github.com/user-attachments/assets/769ae581-47f1-430b-a3aa-e0c64bf54935)

**Comment by czczycz** [comment]
It seems that locality.LoadBalancingWeight doesn't work [https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/cluster.go#L460](url)

**Comment by czczycz** [comment]
It seems locality.LoadBalancingWeight that doesn't work [here](https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/cluster.go#L460)

**Comment by arkodg** [comment]
which version are you on @czczycz 
there are conformance tests for traffic splitting, which pass for Envoy Gateway
https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-weight.yaml

**Comment by czczycz** [comment]
@arkodg  v1.1.0
I am testing HttpRoute with Backend CRD. Are the conformance tests you mentioned above intended for the k8s service?

**Comment by zirain** [comment]
I cannot reproduce with following examples:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: myroute
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: backend-v1
          port: 8080
          weight: 99
        - group: gateway.envoyproxy.io
          kind: Backend
          name: backend-v2
          namespace: default
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend-v1
spec:
  endpoints:
    - fqdn:
        hostname: infra-backend-v1.default
        port: 8080
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend-v2
spec:
  endpoints:
    - fqdn:
        hostname: infra-backend-v2.default
        port: 8080

```

output:

```yaml
- cluster:
        '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
        circuitBreakers:
          thresholds:
          - maxRetries: 1024
        commonLbConfig:
          localityWeightedLbConfig: {}
        connectTimeout: 10s
        dnsLookupFamily: V4_ONLY
        dnsRefreshRate: 30s
        lbPolicy: LEAST_REQUEST
        loadAssignment:
          clusterName: httproute/default/myroute/rule/0
          endpoints:
          - lbEndpoints:
            - endpoint:
                address:
                  socketAddress:
                    address: infra-backend-v1.default
                    portValue: 8080
              loadBalancingWeight: 1
            loadBalancingWeight: 99
            locality:
              region: httproute/default/myroute/rule/0/backend/0
          - lbEndpoints:
            - endpoint:
                address:
                  socketAddress:
                    address: infra-backend-v2.default
                    portValue: 8080
              loadBalancingWeight: 1
            loadBalancingWeight: 1
            locality:
              region: httproute/default/myroute/rule/0/backend/1
        name: httproute/default/myroute/rule/0
        outlierDetection: {}
        perConnectionBufferLimitBytes: 32768
        respectDnsTtl: true
        type: STRICT_DNS
```

**Comment by arkodg** [comment]
thanks @zirain for triaging this one, closing this for now since there doesnt seem to be any issue

**Comment by czczycz** [comment]
@zirain Please try IP in Backend.spec.endpoints
I check [EG codes](https://github.com/envoyproxy/gateway/blob/v1.1.0/internal/xds/translator/translator.go#L835), FQDN uses `type: STRICT_DNS` in envoyproxy configs but Ip uses `type: EDS`

**Comment by zirain** [comment]
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: backend-v1
          port: 3000
          weight: 99
        - group: gateway.envoyproxy.io
          kind: Backend
          name: backend-v2
          namespace: default
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend-v1
spec:
  endpoints:
    - ip:
        address: 10.244.0.225
        port: 3000
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend-v2
spec:
  endpoints:
    - ip:
        address: 10.244.0.226
        port: 3000
```

```
- endpointConfig:
        '@type': type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
        clusterName: httproute/default/backend-route/rule/0
        endpoints:
        - lbEndpoints:
          - endpoint:
              address:
                socketAddress:
                  address: 10.244.0.225
                  portValue: 3000
              healthCheckConfig: {}
            healthStatus: HEALTHY
            loadBalancingWeight: 1
          loadBalancingWeight: 99
          locality:
            region: httproute/default/backend-route/rule/0/backend/0
        - lbEndpoints:
          - endpoint:
              address:
                socketAddress:
                  address: 10.244.0.226
                  portValue: 3000
              healthCheckConfig: {}
            healthStatus: HEALTHY
            loadBalancingWeight: 1
          loadBalancingWeight: 1
          locality:
            region: httproute/default/backend-route/rule/0/backend/1
        policy:
          overprovisioningFactor: 140
```

```
for i in {1..100}; do curl -s -X GET 172.18.0.204/ | grep service; done
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v1",
 "service": "infra-backend-v2",
```

**Comment by czczycz** [comment]
Thanks @zirain 
I found the reason why my load assignment weights don't work.
I have an EPP CR for my cluster, and it looks like the yaml below. In envoyproxy cluster, the `common_lb_config. localityWeightedLbConfig` is replaced by `common_lb_config.healthy_panic_threshold`(from EPP). Therefor load assignment weights will be ignored.
After I delete my epp, everything works fine.
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: epp
spec:
  jsonPatches:
  - name: httproute/default/myroute/rule/0
    operation:
      op: add
      path: /common_lb_config
      value:
        healthy_panic_threshold:
          value: 0
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: gw
  type: JSONPatch
```
