### ISSUE TITLE
Google OIDC Authentication stop to work in 1.2.0.rc1 

### ISSUE THREAD

**Issue by MarynaIshchenko** [envoyproxy/gateway#4625]
*Description*:
After upgrading to version 1.2.0.rc1 authentification with Securitypolicy stop to work with error:
"OAuth flow failed" and logs "response_code_details":"oauth.missing_credentials".

Config:

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: example-oidc
  namespace: example
spec:
  oidc:
    clientID: XXXX.apps.googleusercontent.com
    clientSecret:
      group: ""
      kind: Secret
      name: google-oauth-oidc
    logoutPath: /logout
    provider:
      issuer: https://accounts.google.com
    redirectURL: https://example.com/oauth2
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-ui

Perhaps it's connected with NONCE implementation, because previously:
state: http://example.com/

and now:

state: url=http%3A%2F%2Fexample.com%2F&nonce=1730721470322991

BTW, [example](https://gateway.envoyproxy.io/latest/tasks/security/oidc/#register-an-oidc-application) doesn't reflect any change in configuration for new version.

**Comment by zhaohuabing** [comment]
I can't reproduce this issue. The OIDC authn with Google provider works fine in my dev machine.

> [example](https://gateway.envoyproxy.io/latest/tasks/security/oidc/#register-an-oidc-application)

Nonce support is transparent to either the EG and the OIDC provider, so no changes in the docs.

**Comment by jmullo** [comment]
Nonce is transparent only if the OIDC provider behaves as expected: https://github.com/envoyproxy/envoy/issues/36871

**Comment by zhaohuabing** [comment]
> Nonce is transparent only if the OIDC provider behaves as expected: [envoyproxy/envoy#36871](https://github.com/envoyproxy/envoy/issues/36871)

`nonce` is supposed to be transparent to the OIDC provider, I didn't realize that some OIDC providers would inspect the `state` parameter and remove the `nonce` outside of it. 

The Google OIDC Authentication doesn't do that according to my testing.

**Comment by zhaohuabing** [comment]
Raised a PR to opt nonce out in Envoy. We shouldn't have this issue with the Google OIDC.  Could you please help verify this? @MarynaIshchenko

**Comment by jaynis** [comment]
I am experiencing a very similar issue which I have described in #4718 and which could be related. My issue happens quite randomly and only after some time (everything works fine in the beginning). This could also be the reason why you cant easily reproduce this @zhaohuabing (if it is related at all).
 
@MarynaIshchenko have you tried to enable debug logging in envoy and/or doing a fresh envoy gateway installation with a minimal configuration?

**Comment by MarynaIshchenko** [comment]
I have envoy gateway-helm-v1.0.1 and SecurityPolicy:

```
apiVersion: v1
items:
- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: SecurityPolicy
  metadata:
    annotations:
    labels:
      argocd.argoproj.io/instance: swagger-ui
    name: swagger-oidc
    namespace: monitoring
  spec:
    oidc:
      clientID: XXXXXXXXX.apps.googleusercontent.com
      clientSecret:
        group: ""
        kind: Secret
        name: google-oauth-oidc
      logoutPath: /logout
      provider:
        issuer: https://accounts.google.com
      redirectURL: https://swagger.stg.myorg.com/oauth2
    targetRef:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: swagger-swagger-ui
kind: List
metadata:
  resourceVersion: ""
```

And after upgrading to v1.2.1 it has an error "OAuth flow failed"


Also I've removed helm-chart and installed it back( v1.2.1), but it still doesn't work.

**Comment by zhaohuabing** [comment]
@MarynaIshchenko Could you please share the below information for further debugging?
* The Gateway and HTTPRoute resource
* The EG log
* The Envoy debugg level log, you can turn it on by using an `EnvoyProxy` like below:

```
cat <<EOF | kubectl apply -f -                                                      
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: default
spec:
  logging:
    level:
      default: debug
EOF
```

```
cat <<EOF | kubectl apply -f -                                                      
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: custom-proxy-config
  listeners:
    - name: http
      protocol: HTTP
      port: 80
EOF
```
