### ISSUE TITLE
earlyRequestHeaders not accepted

### ISSUE THREAD

**Issue by gid-fieldcode** [envoyproxy/gateway#4672]
Seeing the new feature with the `earlyRequestHeaders`, we found that it's essential for us so we upgraded to 1.2.1. We used `helm upgrade --install envoy-gateway oci://docker.io/envoyproxy/gateway-helm --version v1.2.1 -n envoy-gateway`

So now we have defined this resource, using syntax from the documentation page:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: enable-early-headers
  namespace: test
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: apps
  headers:
    earlyRequestHeaders:
      add:
        - name: "x-header-erp"
          value: "foobar"
```

...and when we apply it we get this error: 

`ClientTrafficPolicy in version "v1alpha1" cannot be handled as a ClientTrafficPolicy: strict decoding error: unknown field "spec.headers.earlyRequestHeaders"`

What could we be missing here?
