### ISSUE TITLE
IPv6: Envoy readiness should listen on the IPv6 when the IPFamily is IPv6

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#4683]
```
          static_resources:
            listeners:
            - name: envoy-gateway-proxy-ready-0.0.0.0-19001
              address:
                socket_address:
                  address: 0.0.0.0
                  port_value: 19001
                  protocol: TCP
  ```
