### ISSUE TITLE
Add support for specifying alt_stat_name for an upstream cluster

### ISSUE THREAD

**Issue by sekar-saravanan** [envoyproxy/gateway#4717]
*Description*:
Add support for specifying **alt_stat_name** for an upstream cluster in the Envoy configuration. This would be extremely useful for better identifying services in observability. 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto

[optional *Relevant Links*:]
https://envoyproxy.slack.com/archives/C03E6NHLESV/p1731494818346729

**Comment by zirain** [comment]
looks like [ClusterSettings](https://github.com/envoyproxy/gateway/blob/cc7104891d49d1c89b15f4b712ef055dbf4d65c9/api/v1alpha1/shared_types.go#L521) is a good place for this
@sekar-saravanan can you share more details about the user case

**Comment by arkodg** [comment]
can we auto populate this to a backendRef FQDN instead ?

**Comment by sekar-saravanan** [comment]
@zirain This is primarily for observability purposes. Currently, the cluster_name label provided by the EG metric appears as follows: _**httproute/seceng/gateway-dummy-service-external-origin/rule/0.**_ 
Supporting a configurable alt_stats_name would significantly improve the manageability and readability of metrics, making them more user-friendly.

**Comment by guydc** [comment]
If users control the prefix, they can decide to merge stats of various clusters when per-route-rule stat granularity is not required. This would also make it possible to better control scale of stats, which could be significant in EG, due to the way clusters are created. 

Auto-generating the alt_name (if user opts-in) would be a good option to reduce cardinality as well. I think that there are some questions, though:
- What should the alt_name be when a Backend with multiple FQDNs or no FQDNs is used? In this case, it might be better to use the resource's namespaced-name. 
- What should the alt_name be when multiple backends are referenced by a route rule?

**Comment by guydc** [comment]
Notes from community meeting:
- User opt-in is required, as applying an alt_stat_name may lead to stats being merged across route rules and http routes, creating an incompatible change.  
- Auto-Generating an alt_stat_name based on namespaced-name of xRoute and BackendRef(s) reduces the scale of metrics and makes it easier to for users to search for metrics based on the service (as requested in this issue), instead of an anonymous indexed route rule. We may need to truncate the stat name if the list of backends is too long. 
- If we adopt weighted clusters, as mentioned in #5352, there would not be a need to collapse stats, as clusters would be created 1:1 with Backends/Services/ServiceImports. 

So, if a user attaches a BTP to a route and enables a new `statNameFromBackends` knob, given the following route:

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-app-1
spec:
  parentRefs:
  - name: my-gateway
  hostnames:
  - "foo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /bar
    backendRefs:
    - name: my-service1
      port: 8080
    - name: my-service2
      port: 8080
```

The cluster alt_stat_name would look something like 'default/http-app-1/default/my-service1/default/my-service2'. 

@sekar-saravanan - WDYT?
