### ISSUE TITLE
Hostname doesn't support subdomain with single character in Backend Object

### ISSUE THREAD

**Issue by nothinux** [envoyproxy/gateway#4793]
*Description*:
Hi, we have an issue with backend object when trying to set the hostname with subdomain that has single character in it. For example if we set the hostname to this subdomain `backend.s.collector.example.com` it will trigger this error

`The Backend "backend" is invalid: spec.endpoints[0].fqdn.hostname: Invalid value: "backend.s.collector.example.com": spec.endpoints[0].fqdn.hostname in body should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9]))*$'`

However when we set it to `backend.staging.collector.example.com` there's no issue

Is the regex is expected to not allow subdomain with single character?
https://github.com/envoyproxy/gateway/blob/a383dd97e4c7fe726f064c03f48a06e8b049001f/api/v1alpha1/backend_types.go#L97-L98

Example manifest

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend
  namespace: envoy-gateway-system
spec:
  endpoints:
  - fqdn:
      hostname: backend.s.collector.example.com
      port: 80
```
