### ISSUE TITLE
Envoy Operator throws error while following extension-server documentation.

### ISSUE THREAD

**Issue by Tharsanan1** [envoyproxy/gateway#4812]
*Description*:
>While following [this doc](https://gateway.envoyproxy.io/docs/tasks/extensibility/extension-server/) when applying the custom CR i observe error log at the EnvoyOperator

*Repro steps*:
> Follow the steps in the documentation

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
> 
`2024-11-29T09:11:52.779Z    ERROR    provider    kubernetes/status_updater.go:124    unable to update status    {"runner": "provider", "name": "listeneruser", "namespace": "default", "error": "listenercontextexamples.example.extensions.io \"listeneruser\" is forbidden: User \"system:serviceaccount:envoy-gateway-system:envoy-gateway\" cannot update resource \"listenercontextexamples/status\" in API group \"example.extensions.io\" in the namespace \"default\""}`

**Comment by arkodg** [comment]
cc @liorokman

**Comment by zirain** [comment]
did you update the role for EG?
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-xxxxxx-controller
rules:
  - apiGroups:
      - "xxxxxxxxxx"
    resources:
      - "xxxxx"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-xxxxx-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-ai-gateway-controller
subjects:
  - kind: ServiceAccount
    name: envoy-gateway
    namespace: envoy-gateway-system
---

```
