### ISSUE TITLE
Envoy Gateway OIDC: Error with Self-Signed Certificate

### ISSUE THREAD

**Issue by williamdlm** [envoyproxy/gateway#4838]
I have a Kubernetes cluster using Envoy Gateway and I need it to always authenticate with a Keycloak instance running outside the cluster. Since it is in a development environment, it uses a self-signed certificate.

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-example
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  oidc:
    provider:
      issuer: "https://my.keycloak.org/realms/myrealm"
    clientID: "envoy"
    clientSecret:
      name: "my-app-client-secret"
    redirectURL: "http://myapp.local:10080/app1"
    logoutPath: "/protocol/openid-connect/logout"
```

However, when I check this resource after it's created, I get the following error message:

```
message: 'OIDC: error fetching endpoints from issuer: Get "https://my.keycloak.org/realms/myrealm/.well-known/openid-configuration":
        tls: failed to verify certificate: x509: certificate signed by unknown authority.'
```

I found a similar case reported here: https://github.com/envoyproxy/gateway/issues/3622

Based on the suggestion in the comments here: https://github.com/envoyproxy/gateway/issues/3622#issuecomment-2463537929

I tried the following:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-example
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  oidc:
    provider:
      issuer: "https://my.keycloak.org/realms/myrealm"
      backendRefs:
      - name: backend-policy-tls
        port: 443
        kind: BackendTLSPolicy
    clientID: "envoy"
    clientSecret:
      name: "my-app-client-secret"
    redirectURL: "http://myapp.local:10080/app1"
    logoutPath: "/protocol/openid-connect/logout"
```

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: backend-policy-tls
spec:
  targetRefs:
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    name: oidc-example
  validation:
    caCertificateRefs:
    - group: ""
      kind: Secret
      name: keycloak-cert
    hostname: my.keycloak.org
```

However, the same error persists: "tls: failed to verify certificate: x509: certificate signed by unknown authority."

I need help with this, preferably with an example of the correct way to make this work.

---

**Comment by arkodg** [comment]
cc @zhaohuabing

**Comment by shivanidwivedi10** [comment]
Hi @arkodg I am also facing the same issue. Kindly find the details below

We are using Envoy Gateway (installed via Helm chart) as the Gateway API in our MicroK8s cluster running on a Red Hat VM in an air-gapped environment. Our setup includes:

Backend application running as a pod inside the MicroK8s cluster.
Keycloak server also deployed as a pod in the same cluster.
Domain: https://xxx.yyy.cloud, which resolves via /etc/hosts entries and is secured with a self-signed certificate.

**Current Behavior:**
Accessing https://xxx.yyy.cloud works as expected in Firefox (after bypassing the warning for the self-signed certificate).
Without Keycloak as the authentication server, everything functions correctly.
We have also made our host machine trust the self-signed certificates.

**Problem:**
Even after making host trust the certificate and after creating a security policy that uses Keycloak for authentication, we still receive the following error:
OIDC: error fetching endpoints from issuer: get "https://xxx.yyy.cloud/realms/myrealm/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority.

**Goal:**
Make the security policy trust the self-signed certificate we’ve created. We need to either:

1. Configure the security policy to trust the self-signed certificate, or
2. Find a way to bypass certificate validation in the security policy.
 
 Please find the yaml files we have used:
```
 -backend.yaml
 apiVersion: gateway.envoyproxy.io/v1alpha1 
  kind: Backend
  metadata:
    name: backend-keycloak
    namespace: some-ns
  spec:
    endpoints:
    - fqdn:
        hostname: 'xxx.yyy.cloud'
        port: 443
```
```
-backend-tls-policy.yaml
apiVersion: gateway.networking.k8s.io/v1alpha3 
kind: BackendTLSPolicy
metadata:
  name: keycloak-backend-policy
  namespace: some-ns
spec:
  targetRef:
  -  group: gateway.envoyproxy.io
     kind: Backend
     name: backend-keycloak
  validation:
    caCertificateRefs:  
    -   group: ""
        name: tls-ca
        kind: Secret     #usedConfigMap as well
    hostname: xxx.yyy.cloud
```
```

-security-policy.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: xxx-security-policy
  namespace: some-ns
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: gateway-routes-oidc
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: gateway-api-routes-oidc
  oidc:
    provider:
      issuer: "https://xxx.yyy.cloud/realms/myrealm"
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: backend-keycloak
          port: 443
        backendSettings:
          retry:
            numRetries: 3
            perRetry:
              backOff:
                baseInterval: 1s
                maxInterval: 5s
            retryOn:
              triggers: ["5xx", "gateway-error", "reset"]
    clientID: "some.envoy-oidc.client"
    clientSecret:
      name: "my.oidc.client-secret"
    redirectURL: "https://xxx.yyy.cloud/xxxyyy/main/oauth2/callback"
    logoutPath: "/xxxyyy/main/logout"
    forwardAccessToken: true
    refreshToken: true
    cookieNames:
      accessToken: mmmmm
      idToken: nnnnnnn

```

Even after using backendrefs and BackendTLSPolicy, we are still facing the same OIDC error.
Kindly let us know if we are missing something in the yaml files I provided above or if you could share some example files we can refer to. This is something we are facing and trying to solve from past 2-3 days now.

**Comment by zhaohuabing** [comment]
The specified ca is only used by the envoy. Envoy Gateway doesn't use the specified ca to fetch the endpoints from issue's well-known openid configuration url.

**Comment by shivanidwivedi10** [comment]
Thank you for checking this! @zhaohuabing I have tried with authorizationEndpoint and tokenEndpoint as well, with this we are able to get the Keycloak page after entering Username and password, it gives a blank page stating OAuth Flow Failed.
Any suggestions!

**Comment by zhaohuabing** [comment]
> d with authorizationEndpoint and tokenEndpoint as well, with this we are able to get the Keycloak page after entering Username and password, it gives a blank page stating OAuth Flow Failed.
> NOTE: I am doing this deployment in an air-gapped machine (RHEL 8)

@shivanidwivedi10 Keycloak should work. Envoy Gateway runs an e2e test with Keycloak. You can comapre your configuration with the e2e to see if there are any noticable differences.

https://github.com/envoyproxy/gateway/blob/main/test/e2e/testdata/oidc-securitypolicy.yaml
https://github.com/envoyproxy/gateway/blob/main/test/e2e/testdata/oidc-keycloak.yaml
https://github.com/envoyproxy/gateway/blob/main/test/e2e/testdata/oidc-securitypolicy-backendcluster.yaml

Are there any errors in the envoy log when the OAuth flow failed?

**Comment by williamdlm** [comment]
> The specified ca is only used by the envoy. Envoy Gateway doesn't use it to fetch the endpoints from issue's well-known openid configuration url.
> 
> @williamdlm @shivanidwivedi10 As a workaround, you can explicitly set the `authorizationEndpoint` adn `tokenEndpoint`.

Thank you for your response! Using `authorizationEndpoint` and `tokenEndpoint`, the `SecurityPolicy` works without the previous error.
However, like @shivanidwivedi10, I encountered the following error: "OAuth Flow Failed", but I couldn't find any logs related to this issue in Keycloak.



> @shivanidwivedi10 Keycloak should work. Envoy Gateway runs an e2e test with Keycloak for every commit. You can comapre your configuration with the e2e to see if there are any noticable differences.
> 
> https://github.com/envoyproxy/gateway/blob/main/test/e2e/testdata/oidc-securitypolicy.yaml https://github.com/envoyproxy/gateway/blob/main/test/e2e/testdata/oidc-keycloak.yaml https://github.com/envoyproxy/gateway/blob/main/test/e2e/testdata/oidc-securitypolicy-backendcluster.yaml
> 
> Are there any errors in the envoy log when the OAuth flow failed?

Here are my configurations for comparison:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app1-route
  namespace: default
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: app1-service
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /app1
        
---

apiVersion: v1
data:
  client-secret: MnkyWnpFMThsbWFDYXE0U0VFcVhZU3hmTnBQT2VKb2g=
kind: Secret
metadata:
  name: my-app-client-secret
  namespace: default
type: Opaque

---

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-example
  namespace: default
spec:
  oidc:
    clientID: envoy
    clientSecret:
      group: ""
      kind: Secret
      name: my-app-client-secret
    logoutPath: /protocol/openid-connect/logout
    provider:
      authorizationEndpoint: https://my.keycloak.org/realms/master/protocol/openid-connect/auth
      issuer: https://my.keycloak.org/realms/master
      tokenEndpoint: https://my.keycloak.org/realms/master/protocol/openid-connect/token
    redirectURL: http://myapp.local:10080/app1
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: app1-route
```

I reviewed them alongside your example, but I didn't notice anything unusual that could explain the issue.
