### ISSUE TITLE
Envoy Proxy deployment is not reconciled properly when removing resource cpu limit 

### ISSUE THREAD

**Issue by fboula** [envoyproxy/gateway#4842]
*Description*:
Our envoy proxy deployments are not reconciled properly when we remove CPU limits from the `EnvoyProxy` spec. 

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: test
...
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  labels:
    app.kubernetes.io/instance: test-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: gateway-1.0.0
  name: test
  namespace: envoy-gateway-system
spec:
  logging:
    level:
      default: warn
  provider:
    kubernetes:
      envoyDeployment:
        container:
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
```

Upon verification the spec of the deployment still includes a CPU limit

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: test
    gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
  name: envoy-envoy-gateway-system-test-5ea56ca9
  namespace: envoy-gateway-system
spec:
  template:
    spec:
      containers:
      - name: envoy
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
```

If we recreate the the `envoyProxy` and the associated `Deployment` with

```bash
kubectl delete envoyproxies.gateway.envoyproxy.io test
kubectl delete deployments.apps envoy-envoy-gateway-system-test-5ea56ca9
kubectl apply -f envoyproxies-test.yaml
```

The new deployment created form the `envoyProxy` matches the proxy spec and does not set a cpu limit on the envoy container.

*Repro steps*:
1. Create a Gateway and an EnvoyProxy and set `spec.provider.kubernetes.envoyDeployment.container.resources.limits.cpu`
2. Edit the EnvoyProxy spec by unsetting `spec.provider.kubernetes.envoyDeployment.container.resources.limits.cpu`  

*Environment*:
- Envoy-gateway v1.2.1 installed using helm-chart.
- Manifest are deployed with ArgoCD. 

*Logs*:
No error logs from the `envoy-gateway` gateway pod in `INFO` level.

**Comment by surenraju** [comment]
I attempted to reproduce the issue in both Envoy Gateway `v1.2.1` and `v1.3.0` using the following steps:

**Installed Envoy Gateway v1.3.0:**

`helm install eg oci://docker.io/envoyproxy/gateway-helm --version v1.3.0 -n envoy-gateway-system --create-namespace`

**Applied the default quickstart configuration:**

`kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/v1.3.0/quickstart.yaml -n default`

**Deployed an initial EnvoyProxy resource with CPU and memory limits:**

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: custom-proxy-config
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
```

**Updated the EnvoyProxy resource by removing the CPU limit:**

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: custom-proxy-config
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
```

**Results & Observations**
	•	After applying the update, I verified the `Deployment` and found that the CPU limit was correctly removed.
	•	The Envoy Proxy deployment reconciled properly as expected.
	•	No manual deletion of the `EnvoyProxy` or `Deployment` was required.

**Potential Cause of the Issue**

Since I was unable to reproduce the issue, it is likely related to ArgoCD sync behavior. Possible explanations:
