### ISSUE TITLE
Outlier detection (passive health checking) is enabled by default without a BTP 

### ISSUE THREAD

**Issue by lsjostro** [envoyproxy/gateway#4854]
*Description*:
Passive health checking seems to be enabled by default without specifying a BTP. This might not always be preferred (even though passive health checks is super useful).

*Repro steps*:
Create a GW and HTTPRoute with no BTP and dump config, you will find `"outlier_detection": {}` present which enabled passive health with default values. 

*Environment*:
EG 1.2.3

*Logs*:
look at the `envoy_cluster_outlier_detection_ejections_active{}` metric to see that outlier detection is active.

**Comment by arkodg** [comment]
thanks for reporting, issue looks legit

https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/testdata/in/xds-ir/http-route.yaml

https://github.com/envoyproxy/gateway/blob/905405e72ed5da070ef2d041e524efb8511d837f/internal/xds/translator/testdata/out/xds-ir/http-route.clusters.yaml#L16

**Comment by lsjostro** [comment]
removing this line should be enough? https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/cluster.go#L106. + fixing the translator tests. `OutlierDetection` field will then be `nil` and not initiated and not included in the final config. I can open a PR if that helps?

**Comment by arkodg** [comment]
looks like its been this way[ since the beginning](https://github.com/envoyproxy/gateway/blob/34e187e5250247ba151bfd68f7d28c98ed8c5c20/internal/xds/translator/cluster.go#L42) 

@lsjostro can you share your use case why you'd like to disable it ?

if we re changing behavior, this probably needs a bigger discussion @envoyproxy/gateway-maintainers

**Comment by lsjostro** [comment]
Yeah sure. First it's a bit misleading that you have passive health check enabled on all clusters even though you haven't explicit enabled it using a BTP. Second you might have tiers of Api gateways (proxyies). Envoy on first tier then another tier of envoys or other proxies before actually hitting the real service that might throw 500s. With outlier detection enabled on the first tier doesnt really make sense.

**Comment by lsjostro** [comment]
workaround until fixed. 

```yaml
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: remove-outlier-detection
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: my-eg
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.cluster.v3.Cluster"
      name: "httproute/some-namespace/backend-svc/rule/0"
      operation:
        op: remove
        path: "/outlier_detection"
```
