### ISSUE TITLE
support other `upgradeType`s then just `websocket`

### ISSUE THREAD

**Issue by foosinn** [envoyproxy/gateway#4859]
*Description*:

Currently this section is automatically added to all dynamic https routes:

```
[...]
"upgradeConfigs": [
  {
    "upgradeType": "websocket"
  }
]
[...]
```

I was unable to find a way to modify that. For some tools (in my case https://github.com/juanfont/headscale) it's required to change this value.

It would be awesome to have that configurable. Thanks!

**Comment by foosinn** [comment]
Found a workaround :tada:

1. Enable `EnvoyPatchPolicy`: https://gateway.envoyproxy.io/latest/tasks/extensibility/envoy-patch-policy/#enable-envoypatchpolicy

2. Apply the policy to the cluster (replace the Gateway in `targetRef` and the underscored domain in `jsonPath` with your values)
```
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: headscale
  namespace: envoy-gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: default
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
      name: envoy-gateway-system/default/https
      operation:
        op: replace
        jsonPath: "..virtual_hosts[?match(@.name, '.*vpn_example_org')].routes[0].route.upgrade_configs[0]"
        path: upgrade_type
        value: tailscale-control-protocol
```
