### ISSUE TITLE
Add an option to configure HPA for the Envoy Gateway deployment in Helm

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#4929]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

**Comment by Dean-Coakley** [comment]
Not sure I understand what is required here.

Would it just be a case of adding something like?:
```diff
diff --git a/charts/gateway-helm/values.tmpl.yaml b/charts/gateway-helm/values.tmpl.yaml
index cfcd9532..51517556 100644
--- a/charts/gateway-helm/values.tmpl.yaml
+++ b/charts/gateway-helm/values.tmpl.yaml
@@ -80,6 +80,16 @@ config:
       controllerName: gateway.envoyproxy.io/gatewayclass-controller
     provider:
       type: Kubernetes
+      # envoyHpa:
+      #   minReplicas: 2
+      #   maxReplicas: 10
+      #   metrics:
+      #     - resource:
+      #         name: cpu
+      #         target:
+      #           averageUtilization: 60
+      #           type: Utilization
+      #       type: Resource
     logging:
       level:
         default: info
```
(Ref: https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/#customize-envoyproxy-horizontal-pod-autoscaler) 

And then I think those entries would get pulled in by the templating in https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/templates/envoy-gateway-config.yaml 

Or am I misunderstanding?

**Comment by arkodg** [comment]
the API would probably be at the top level https://github.com/envoyproxy/gateway/blob/fcdbafa5925482f705c2efd7ff8f54e348372d64/charts/gateway-helm/values.tmpl.yaml#L76 similar to the `deployment` and `service` field and would need a template similar to https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/templates/envoy-gateway-deployment.yaml

**Comment by Dean-Coakley** [comment]
Ah whoops, gotcha.

I've started working on this.


Based on the issue title "Add an option" I've put HPA behind a boolean.
The top level config looks like:
```
hpa:
  enable: false
  # minReplicas: 1
  maxReplicas: 1
  metrics: []
    # - resource:
    #     name: cpu
    #     target:
    #       averageUtilization: 80
    #       type: Utilization
    #   type: Resource
  behavior: {}
```

Does that look reasonable enough?
