### ISSUE TITLE
Bug: extAuth.headersToExtAuth does not forward headers

### ISSUE THREAD

**Issue by TobiasGleiter** [envoyproxy/gateway#4975]
*Description*:

Envoy should forward headers to the ext auth service but the headers e.g. Cookies are not returned.

*Environment*:
SecurityPolicy Version:
      gateway.envoyproxy.io/v1alpha1

Images:
      image: envoyproxy/gateway:v1.2.3
      image: docker.io/envoyproxy/gateway:v1.2.3
      image: envoyproxy/envoy:distroless-v1.32.1
      image: envoyproxy/gateway:v1.2.3
      image: docker.io/envoyproxy/envoy:distroless-v1.32.1
      image: docker.io/envoyproxy/gateway:v1.2.3

**Comment by zhaohuabing** [comment]
@TobiasGleiter Did you confirm `HeadersToExtAuth`? By default, only the following headers will be included in the check request to an HTTP authorization server: Host, Method, Path, Content-Length, and Authorization.

See: https://gateway.envoyproxy.io/docs/api/extension_types/#extauth

**Comment by TobiasGleiter** [comment]
@zhaohuabing Yes, I did. See attached:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
...
spec:
  extAuth:
    http:
      backendRefs:
        - name: kern-authorization
          namespace: kern
          port: 9002
    headersToExtAuth:
      - "Cookie"
      - "Authorization"
```

The default header `authorization` works well. Am I missing something?
