### ISSUE TITLE
Cannot reuse HTTPRouteFilter with urlRewrite for multiple HTTPRoute

### ISSUE THREAD

**Issue by TomerJLevy** [envoyproxy/gateway#4989]
*Description*:
When applying multiple `HTTPRoute` resources that reference the same `HTTPRouteFilter` with a `urlRewrite` configuration, an error occurs for all the `HTTPRoute` resources. The error message states:
Cannot configure multiple urlRewrite filters for a single HTTPRouteRule.

However, each `HTTPRoute` only applies one `urlRewrite`, so the error seems incorrect. This issue prevents reusing `HTTPRouteFilter` objects for multiple routes, which should be allowed.

*Repro steps*:
1. Follow the official installation guide as written here: https://gateway.envoyproxy.io/latest/tasks/quickstart/#installation
2. But instead of the regular `HTTPRoute`, apply these:
```yaml
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: route-filter
spec:
  urlRewrite:
    path:
      replaceRegexMatch:
        pattern: /
        substitution: /
      type: ReplaceRegexMatch

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: backend
        port: 3000
        weight: 1
      filters:
      - extensionRef:
          group: gateway.envoyproxy.io
          kind: HTTPRouteFilter
          name: route-filter
        type: ExtensionRef
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-2
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: backend
        port: 3000
        weight: 1
      filters:
      - extensionRef:
          group: gateway.envoyproxy.io
          kind: HTTPRouteFilter
          name: route-filter
        type: ExtensionRef
      matches:
        - path:
            type: PathPrefix
            value: /
```
3. Observe the error message on all `HTTPRoute` resources:
```Cannot configure multiple urlRewrite filters for a single HTTPRouteRule.```

*Environment*:
Latest versions
