### ISSUE TITLE
Fix IP Assignment to Gateway in On-Prem Environment

### ISSUE THREAD

**Issue by sinkog** [envoyproxy/gateway#5012]
# Issue Title: Fix IP Assignment to Gateway in On-Prem Environment

## Description:
Our goal is to introduce Envoy Gateway in an on-prem Kubernetes environment using MetalLB and Cilium. Below is a summary of the issues and observations, particularly when trying to assign a fixed access IP to a service.

## Observations:

1. **Static IP Assignment to Gateway**:
   - When assigning a static IP to the Gateway as per the documentation, it creates a `LoadBalancer` type service with the assigned IP appearing as the `externalIP`.

2. **Kubernetes and `externalIP` Handling**:
   - In Kubernetes, the `externalIP` is primarily handled by internal routing. If an external provider sets up a route to the IP, the routing works well, allowing external traffic to reach the service.

3. **MetalLB and `LoadBalancerIP`**:
   - The CNI (Container Network Interface) and MetalLB operate in a way that they manage services of `LoadBalancer` type, and if a `LoadBalancerIP` is assigned, it will pick an IP from the pool if the IP is available and assign it. 

4. **Pool Settings and IP Assignment**:
   - If the MetalLB pool is configured to assign only dedicated IPs, a standard `LoadBalancer` service will not receive an IP. This results in the service staying in a `pending` state until a suitable IP is found.
   - If the `externalIP` is assigned, the `pending` state is overridden, but no automatic advertisement takes place, requiring manual route configuration to reach the desired IP.

5. **Multiple `externalIP` Issue**:
   - If there is no enforced pool, a service may end up with two `externalIP`s, which could be identical. This can create confusion regarding the service's availability, as multiple IPs are associated with the same service.

## Topic and Suggested Solution:
In an on-prem environment where fixed IP addresses are required, Kubernetes' `externalIP` and `LoadBalancerIP` behave differently. The `externalIP` often requires manual configuration in routers and the network infrastructure, whereas the `LoadBalancerIP` can be dynamically managed by Kubernetes and MetalLB.

- **Public Cloud Services**: The `externalIP` can be appropriately used if the IP address is advertised by the provider. In such configurations, IPs are usually managed and advertised by the cloud provider’s infrastructure.
- **On-prem Environments**: The `externalIP` may not be sufficient, as IP advertisement does not happen automatically, and manual routing configuration is necessary to direct traffic to the desired service IP.
- The `LoadBalancerIP` is more standardized in Kubernetes, and both MetalLB and Cilium rely on this for automatic advertisement. Using `LoadBalancerIP` ensures proper traffic routing and allows Kubernetes to handle scaling automatically.

## Request:
- We ask for an investigation into how the integration between `externalIP` and `LoadBalancerIP` can be improved in on-prem Kubernetes environments to ensure fixed IP handling. Additionally, we request that MetalLB and Cilium properly handle the advertisement and routing of IPs, especially in scenarios where the `externalIP` is set.

**Comment by arkodg** [comment]
hey @sinkog 

1. You should be able to set the `loadBalancerIP` field [using EnvoyProxy resource](https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/)
https://gateway.envoyproxy.io/docs/api/extension_types/#kubernetesservicespec

2. a. You should also be able to set the `externalIP` field by using [Gateway.Spec.Addresses](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.Gateway) which internally will set the value in the generated service's `externalIP`  or you could
b. directly edit the generated service and modify it using the `patch` field https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/#patching-service-for-envoyproxy

**Comment by tekulvw** [comment]
Specifically for metallb, you can also specify the `metallb.io/loadBalancerIPs` annotation which is applied to the envoy service:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: proxy
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          metallb.io/loadBalancerIPs: 192.168.1.205
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: proxy
```
