### ISSUE TITLE
Evnoy ExtAuth GRPC re-connecting

### ISSUE THREAD

**Issue by zilinjak** [envoyproxy/gateway#5014]
*Description*:
> It seems that when envoy comunicates with ExtAuth using GRPC new GRPC connection is used every time, which is not ideal for latency.

*Repro steps*:
> Install Envoy and connect it to GRPC service for ExtAuth. I can't really show our ExtAuth but [this](https://github.com/salrashid123/envoy_external_authz) should be sufficient.

*Environment*:
> K8S deployment of EnvoyGateway + K8S deployment of grpc service

*Config*
```
  extAuth:
    failOpen: true
    grpc:
      backendRefs:
        - group: ''
          kind: Service
          name: ...
          port: 8080
```
