### ISSUE TITLE
Single stack IPv6 on dual stack cluster not passing ready checks

### ISSUE THREAD

**Issue by tekulvw** [envoyproxy/gateway#5017]
*Description*:

I have a dual stack (IPv4-first) cluster and am trying to create a single stack gateway. I expect the gateway service to have `ipFamilies: ["IPv6"]` and `ipFamilyPolicy: SingleStack`. Using the proxy config below, the gateway pod never passes readiness checks.

The k8s event log for the gateway pod:

```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  3m1s                 default-scheduler  Successfully assigned envoy-gateway-system/envoy-gateway-eg-ipv6-d7ea7f64-59bb5cf866-bpfrf to talos-b8s-ysm
  Normal   Pulled     3m                   kubelet            Container image "docker.io/envoyproxy/envoy:distroless-v1.32.2" already present on machine
  Normal   Created    3m                   kubelet            Created container: envoy
  Normal   Started    3m                   kubelet            Started container envoy
  Normal   Pulled     3m                   kubelet            Container image "docker.io/envoyproxy/gateway:v1.2.4" already present on machine
  Normal   Created    3m                   kubelet            Created container: shutdown-manager
  Normal   Started    3m                   kubelet            Started container shutdown-manager
  Warning  Unhealthy  1s (x18 over 2m51s)  kubelet            Startup probe failed: Get "http://10.244.26.31:19001/ready": dial tcp 10.244.26.31:19001: connect: connection refused
```

*Repro steps*:

Create a gateway with this proxy config on a dual stack IPv4-first cluster:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: homelab-proxy-ipv6-config
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        annotations:
          metallb.io/address-pool: ipv6-dynamic-pool
        patch:
          value:
            spec:
              ipFamilies:
                - IPv6
              ipFamilyPolicy: SingleStack
  ipFamily: IPv6
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:

Gateway helm chart v1.2.4

*Logs*:
>Include the access logs and the Envoy logs.
