### ISSUE TITLE
Could we loose Backend endpoints IP loopback validation ?

### ISSUE THREAD

**Issue by wengyao04** [envoyproxy/gateway#5058]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Hi, we are using Envoy Gateway (EG) to manage traffic between our on-prem and public cloud services. However, in our internal network setup, we have a restriction that disable direct access to public cloud environments without routing traffic through an internal HTTP proxy.

The traffic flow is
client->envoy->[proxy2]->exampleorg.com

The issue is similar to https://github.com/envoyproxy/envoy/issues/21175, where a loopback is required for tcp tunneling. We follow their solution to reach public cloud services. 

After we upgrade EG, we find that the Backends IP loopback validation is added https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/backend.go#L61-L63 which prevents us to create a loopback backend. Could we loose the Backend endpoints IP loopback validation ?

Your advice would be greatly appreciated.
Thank you!

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zirain** [comment]
cc @guydc

**Comment by guydc** [comment]
Hi @wengyao04. Maybe you can use something like this: https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/#adding-additional-entries-with-hostaliases to create a 127.0.0.2 alias that passes our validations (e.g. `custom.local`) then route to it in your backend. You'll probably need to patch the envoy deployment using EnvoyProxy CR.

**Comment by wengyao04** [comment]
Hi @guydc  Thank you for your suggestion. I try your suggestion and it does not fit in our use case. We use the tunneling to access AWS bedrock-runtime which require AWS sigv4

When we set backend with 127.0.0.1
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: bedrock-us-east-1
  namespace: gateway
spec:
  endpoints:
  - ip:
      address: 127.0.0.1
      port: 10002
```
The request is forwarded to 127.0.0.1:1002 to connect to our internal http proxy , the request authority name is still bedrock, I add logging in envoy with format
```
 [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" "%HOSTNAME%"
```

```
[2025-01-29T03:52:54.125Z] "POST /model/<model-name>/converse HTTP/1.1" 200 - 152 722 2964 "10.244.204.122" "curl/8.7.1" "f03ff752-4a60-4f5d-8a3c-7a8694a2440c" "bedrock-runtime.us-east-1.amazonaws.com" "127.0.0.1:10002" "envoy-gateway-eg-fef97bb3-6787b94b68-dmsnt"
```

But if we switch to host alias
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: bedrock-us-east-1
  namespace: gateway
spec:
  - fqdn:
      hostname: loopback.bedrock-us-east-1.local
      port: 10002
```

We get `InvalidSignature` from AWS
```
{"type":"error","error":{"type":"InvalidSignatureException:http://internal.amazon.com/coral/com.amazon.coral.service/","code":"403","message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}}
```

The reason is the the authority is overwrited to `oopback.bedrock-us-east-1.local`, this is the envoy log
```
2025-01-29T03:51:37.996Z] "POST /model/<model-name>/converse HTTP/1.1" 403 - 152 324 85 "10.244.204.122" "curl/8.7.1" "78fafb49-1ade-463e-9dd9-eeff0de0ce0f" "loopback.bedrock-us-east-1.local" "127.0.0.1:10002" "envoy-gateway-eg-fef97bb3-6787b94b68-dmsnt"
```

When aws verify the signature they thought the host is modified to `loopback.bedrock-us-east-1.local`
