### ISSUE TITLE
provider: EG should not provision if `parametersRef` not found

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#5080]
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-daemonset
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: eg-daemonset
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg-daemonset
  namespace: default
spec:
  ipFamily: IPv4
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet:
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                    - name: envoy
                      readinessProbe:
                        initialDelaySeconds: 5
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo-route
  namespace: default
spec:
  parentRefs:
    - name: eg-daemonset
  rules:
    - backendRefs:
        - name: infra-backend-v1
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /foo

```

output:

```yaml
k get deployments.apps -n envoy-gateway-system
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
envoy-default-eg-daemonset-aee8b7f7   1/1     1            1           16s
envoy-gateway                         1/1     1            1           38s

╭─ ~/Codes/servicemesh/gateway on xds-ready-listener !2                                         Ruby 9.2.6.0 at ○ kind-envoy-gateway at 16:58:09
╰─❯ k get ds -n envoy-gateway-system
NAME                                  DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
envoy-default-eg-daemonset-aee8b7f7   1         1         1       1            1           <none>          20s

```

**Comment by zirain** [comment]
EG should not provision provider if `parametersRef` resource not found.
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-daemonset
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: eg-daemonset
```
