### ISSUE TITLE
docs: Highlight how a format string can be used as a value for a header

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#5087]
*Description*:
>Describe the issue.

Envoy allows you to use format strings https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-strings which can use set as header values.

here's an example where it can used to set the Host header value in the `X-Forwarded-Host` header.

```
    - filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Proto
                value: "https"                            
              - name: X-Forwarded-Port
                value: "443"          
              - name: X-Forwarded-Host
                value: "%REQ(Host)%"
```

Would be great to add a similar example where users can access traffic attributes using this technique

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
