### ISSUE TITLE
Allow tracing sampleRate smaller than 1%

### ISSUE THREAD

**Issue by dghubble** [envoyproxy/gateway#5089]
*Description*:

Envoy Gateway's `EnvoyProxy` CustomResourceDefinition expects the tracing field's `sampleRate` to be an integer, allowing 0 to 100.

I'd like to keep tracing on, but sample perhaps 0.01% of traffic. This does not seem to be directly possible, although envoy-proxy itself [seems to support](https://github.com/envoyproxy/gateway/blob/0ee0a8af8e0a86bfbafbca4cee6d5432afa07830/internal/ir/xds.go#L2210) float64 sample rates.

```
# desired
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
spec:
  telemetry:
    tracing:
      sampleRate: 0.01
...
```

[optional *Relevant Links*:]

https://gateway.envoyproxy.io/latest/api/extension_types/#proxytelemetry

> SamplingRate controls the rate at which traffic will be
selected for tracing if no prior sampling decision has been made.
Defaults to 100, valid values [0-100]. 100 indicates 100% sampling
