### ISSUE TITLE
Option to overwrite every OAuth2Filter Cookie via OIDCCookieNames

### ISSUE THREAD

**Issue by denniskniep** [envoyproxy/gateway#5152]
**FeatureRequest:**
Can we extend [SecurityPolicy.OIDC.CookieNames](https://gateway.envoyproxy.io/docs/api/extension_types/#oidccookienames) to be able to optionally overwrite every possible OAuth2Filter cookie name (adding: `oauth_hmac`, `oauth_expires`, `refresh_token`, `oauth_nonce`) [see here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/oauth2/v3/oauth.proto#envoy-v3-api-msg-extensions-filters-http-oauth2-v3-oauth2credentials-cookienames)? Currently you can only overwrite `bearer_token` and `id_token`.

**UseCase:**
I would like to be able to remove the internal OAuthFilter cookies before forwarding the request to upstream.

Happy to take this task.

**Comment by denniskniep** [comment]
not stale

**Comment by denniskniep** [comment]
Not stale

**Comment by coro** [comment]
We also have interest in this, specifically for RefreshToken - we would like to be able to migrate from an existing OIDC solution with static refresh token cookie names, and having a preemptible refresh token name means we can seamlessly migrate specific routes over to Envoy.

**Comment by coro** [comment]
As discussed in #5655 with @zhaohuabing, it sounds like instead of allowing configurability of these internal cookie names, the best way forwards would be for the core OAuth filter to automatically remove these cookies (`RefreshToken-xxxxx`, `CodeVerifier-xxxxx` and `OAuthxxxxx-xxxxx`) before forwarding to the Backend.

**Comment by zhaohuabing** [comment]
Envoy PR: https://github.com/envoyproxy/envoy/pull/40228

**Comment by zhaohuabing** [comment]
I'm closing this issue as https://github.com/envoyproxy/envoy/pull/40228 has been merged and will be included in Envoy 1.35. 

This will be available in EG v 1.5. No control-plane side change is needed.

**Comment by arkodg** [comment]
thanks for driving this in upstream @zhaohuabing 🚀

**Comment by c4tz** [comment]
Hi, I'd still like to have this feature (please tell me if I need to open a new issue).

**Use Case:** I'm currently in the process of migrating from Ingress-Nginx + oauth2-proxy to Envoy with an OIDC SecurityPolicy attached to the Gateway. I have two k8s clusters and in both of them, there is an EG instance. One has its apps reachable on `foo.staging.example.com` and one on `foo.example.com` (Production). Now, if I cannot set all the OIDC cookie names, there is a conflict when you visit the latter domain and then the first, because the `.example.com`-cookies (e.g. "CodeVerifier") will also be available on `.staging.example.com` as it is a subdomain.

There are some unattractive workarounds to this:
* I could give the staging cluster its own domain, but this would mean replacing it in many, many configs and creating new certs.
* Currently, I solved it by applying a `EnvoyPatchPolicy` which overrides the cookie_names directly in the proxy's xDS¹. This is very unstable, as it depends on the number of SecurityPolicies attached to the Gateway (because one can only use an index to specify the exact filter path).

I'd be happy to pick up @coro 's work from the PR (if there are any changes needed at all), but I first wanted to discuss this topic here.

¹ said `EnvoyPatchPolicy` (for the sake of completeness):
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: oidc-cookie-names
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: "gateway/eg/https"
      operation:
        op: add
        path: "/filter_chains/0/filters/0/typed_config/http_filters/0/typed_config/config/credentials/cookie_names"
        value:
          bearer_token: "__oidc_staging_AccessToken"
          oauth_hmac: "__oidc_staging_OauthHMAC"
          oauth_expires: "__oidc_staging_OauthExpires"
          id_token: "__oidc_staging_IdToken"
          refresh_token: "__oidc_staging_RefreshToken"
          oauth_nonce: "__oidc_staging_OauthNonce"
          code_verifier: "__oidc_staging_CodeVerifier"

```
