### ISSUE TITLE
Multiple HTTPS Listeners Fails

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#520]
TLS termination fails for one listener when multiple HTTPS listeners are configured.

__Reproducer:__
Create the TLS assets for both listeners.
```
# Create root cert and key.
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -subj '/O=example Inc./CN=example.com' -keyout example.com.key -out example.com.crt

# Create cert/key for listener 1
openssl req -out foo.example.com.csr -newkey rsa:2048 -nodes -keyout foo.example.com.key -subj "/CN=foo.example.com/O=httpbin organization"
openssl x509 -req -days 365 -CA example.com.crt -CAkey example.com.key -set_serial 0 -in foo.example.com.csr -out foo.example.com.crt


# Create cert/key for listener 2
openssl req -out bar.example.com.csr -newkey rsa:2048 -nodes -keyout bar.example.com.key -subj "/CN=bar.example.com/O=httpbin organization"
openssl x509 -req -days 365 -CA example.com.crt -CAkey example.com.key -set_serial 0 -in bar.example.com.csr -out bar.example.com.crt
```

Store the certs/keys in a Secret:
```
kubectl create secret tls foo-cert --key=foo.example.com.key --cert=foo.example.com.crt
kubectl create secret tls bar-cert --key=bar.example.com.key --cert=bar.example.com.crt
```

Create the example backend app:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
```

Create the GatewayClass:
```
cat <<EOF | kubectl apply -f -
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
EOF
```

Create the Gateway:
```
cat <<EOF | kubectl apply -f -
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  listeners:
  - name: http
    protocol: HTTP
    port: 8080
  - name: https-foo
    protocol: HTTPS
    port: 8443
    hostname: foo.example.com
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: foo-cert
  - name: https-bar
    protocol: HTTPS
    port: 8443
    hostname: bar.example.com
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: bar-cert
EOF
```

Create the Gateway, and HTTPRoute:
```
cat <<EOF | kubectl apply -f -
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  parentRefs:
    - name: eg
  hostnames:
  - "foo.example.com"
  - "bar.example.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: httpbin
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
EOF
```

The xds IR that gets generated:
```
2022-10-07T22:56:55.860Z	INFO	runner/runner.go:88	default-eg:
  HTTP:
  - Address: 0.0.0.0
    Hostnames:
    - '*'
    Name: default-eg-http
    Port: 8080
    Routes:
    - AddRequestHeaders: null
      BackendWeights:
        Invalid: 0
        Valid: 0
      Destinations:
      - Host: 10.96.134.155
        Port: 80
        Weight: 1
      DirectResponse: null
      HeaderMatches:
      - Exact: foo.example.com
        Name: :authority
        Prefix: null
        SafeRegex: null
      Name: default-httpbin-rule-0-match-0-foo.example.com
      PathMatch:
        Exact: null
        Name: ""
        Prefix: /
        SafeRegex: null
      QueryParamMatches: null
      Redirect: null
      RemoveRequestHeaders: null
    - AddRequestHeaders: null
      BackendWeights:
        Invalid: 0
        Valid: 0
      Destinations:
      - Host: 10.96.134.155
        Port: 80
        Weight: 1
      DirectResponse: null
      HeaderMatches:
      - Exact: bar.example.com
        Name: :authority
        Prefix: null
        SafeRegex: null
      Name: default-httpbin-rule-0-match-0-bar.example.com
      PathMatch:
        Exact: null
        Name: ""
        Prefix: /
        SafeRegex: null
      QueryParamMatches: null
      Redirect: null
      RemoveRequestHeaders: null
    TLS: null
  - Address: 0.0.0.0
    Hostnames:
    - bar.example.com
    Name: default-eg-https-bar
    Port: 8443
    Routes:
    - AddRequestHeaders: null
      BackendWeights:
        Invalid: 0
        Valid: 0
      Destinations:
      - Host: 10.96.134.155
        Port: 80
        Weight: 1
      DirectResponse: null
      HeaderMatches: null
      Name: default-httpbin-rule-0-match-0-bar.example.com
      PathMatch:
        Exact: null
        Name: ""
        Prefix: /
        SafeRegex: null
      QueryParamMatches: null
      Redirect: null
      RemoveRequestHeaders: null
    TLS:
      PrivateKey: <SNIP>
      ServerCertificate: <SNIP>
  - Address: 0.0.0.0
    Hostnames:
    - foo.example.com
    Name: default-eg-https-foo
    Port: 8443
    Routes:
    - AddRequestHeaders: null
      BackendWeights:
        Invalid: 0
        Valid: 0
      Destinations:
      - Host: 10.96.134.155
        Port: 80
        Weight: 1
      DirectResponse: null
      HeaderMatches: null
      Name: default-httpbin-rule-0-match-0-foo.example.com
      PathMatch:
        Exact: null
        Name: ""
        Prefix: /
        SafeRegex: null
      QueryParamMatches: null
      Redirect: null
      RemoveRequestHeaders: null
    TLS:
     PrivateKey: <SNIP>
      ServerCertificate: <SNIP>
```

Infra IR:
```
2022-10-07T22:56:55.861Z	INFO	runner/runner.go:90	default-eg:
  Proxy:
    Config: null
    Image: envoyproxy/envoy:v1.23-latest
    Listeners:
    - Address: ""
      Ports:
      - ContainerPort: 8080
        Name: http
        Protocol: HTTP
        ServicePort: 8080
      - ContainerPort: 8443
        Name: https-foo
        Protocol: HTTPS
        ServicePort: 8443
    Metadata:
      Labels:
        gateway.envoyproxy.io/owning-gateway-name: eg
        gateway.envoyproxy.io/owning-gateway-namespace: default
    Name: default-eg
```

Requires: #519
