### ISSUE TITLE
Rate limit service node selector via Helm chart

### ISSUE THREAD

**Issue by iamalryz** [envoyproxy/gateway#5202]
*Description*:
Is there any way to control where rate limit service will be deployed via Helm chart? I can edit `envoy-gateway-config` ConfigMap manually after deploying like this:
```yaml
apiVersion: v1
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
   ...
    provider:
      kubernetes:
        rateLimitDeployment:
          pod:
            nodeSelector:
              ...
```

And it works fine: rate limit service will be deployed to nodes specified by node selector. But I could not find how can I achieve this in official Helm chart.
