### ISSUE TITLE
Settings status code for ExtAuth when used with SecurityPolicy

### ISSUE THREAD

**Issue by zilinjak** [envoyproxy/gateway#5214]
Hi,
Im using **SecurityPolicy** with **ExtAuth** ref to our GRPC service. We would like to return to the users status code `401`. 

The filter which is used by Envoy Proxy has that option to set - `status_on_error` - [docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto), which default to `403`. 

The **SecurityPolicy** seems to be lacking this settings, which means that I can't set the status code returned by Envoy Proxy. Hence is there any other way how to set the `status_on_error` + I need the ext auth to be enabled on whole Gateway and all routes created in it. If not are there any plans on creating this option ?

Thanks

**Comment by arkodg** [comment]
hey closing this one as a dup of https://github.com/envoyproxy/gateway/issues/5180, lets discuss this issue there

**Comment by zilinjak** [comment]
I have just tested it using envoy proxy locally with these steps:

## Start ExtAtuh on http://localhost:8080

## Start HTTPBIN on http://localhost:36000
```
docker run -p 36000:80 kennethreitz/httpbin
```

## Start proxy with this configuration

```
envoy -c envoy_test_config.yaml --log-level debug
```

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 8081 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
          http_filters:
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              grpc_service:
                envoy_grpc:
                  cluster_name: ext-authz
                timeout: 600s
              status_on_error:
                code: 401
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: some_service
    connect_timeout: 600s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 36000
  - name: ext-authz
    type: static
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: ext-authz
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8080
    # This timeout controls the initial TCP handshake timeout - not the timeout for the
    # entire request.
    connect_timeout: 600s
```

Now when I curl the httpbin which is proxied by EnvoyProxy

```
curl -v localhost:8081/api/foo -H "Token: Foo-bar"
```

I can see in extAuth log 
```
status {
  code: 16
  message: "Permission denied"
}
```
which has been created with code I linked before. 

but the response is still - HTTP 403

```
curl -v localhost:8081/api/foo -H "Token: Foo-bar"
*   Trying [::1]:8081...
* connect to ::1 port 8081 failed: Connection refused
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081
> GET /api/foo HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/8.4.0
> Accept: */*
> Token: Foo-bar
> 
< HTTP/1.1 403 Forbidden
< date: Thu, 06 Feb 2025 10:33:29 GMT
< server: envoy
< content-length: 0
< 
```

@arkodg  this leads me that its problem of EnvoyProxy ?
