### ISSUE TITLE
How does ratelimit support cluster/sentinel redis type ?

### ISSUE THREAD

**Issue by wengyao04** [envoyproxy/gateway#5219]
*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

Hi, The ratelimit server exposes `REDIS_TYPE` env variable https://github.com/envoyproxy/ratelimit/blob/main/src/settings/settings.go#L127
```
RedisType       string `envconfig:"REDIS_TYPE" default:"SINGLE"`
```

I try to override this environment variable in the envoygateway configmap like
```
    provider:
      type: Kubernetes
      rateLimitDeployment:
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                    - env:
                        - name: REDIS_TYPE
                          value: "BB_REDIS"
```

But the the env value is not merged.  Our redis setup is a little bit different from Redis Sentinel setup, we maintain a custom version of envoyproxy/ratelimit and thus require us to override this value.

**Comment by zirain** [comment]
I can do this with following configuration:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: 'envoy-gateway-system'
  labels:
    helm.sh/chart: gateway-helm-v0.0.0-latest
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/instance: gateway-helm
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    logging:
      level:
        default: info
    provider:
      kubernetes:
        rateLimitDeployment:
          container:
            image: docker.io/envoyproxy/ratelimit:master
          patch:
            type: StrategicMerge
            value:
              spec:
                template:
                  spec:
                    containers:
                    - imagePullPolicy: Always
                      name: envoy-ratelimit
                      env:
                      - name: REDIS_TYPE
                        value: "BB_REDIS"
        shutdownManager:
          image: docker.io/envoyproxy/gateway-dev:latest
      type: Kubernetes
    rateLimit:
      backend:
        type: Redis
        redis:
          url: redis.redis-system.svc.cluster.local:6379
```
