### ISSUE TITLE
Support v4_prefix_mask_len and v6_prefix_mask_len for IP-Based Rate Limiting in BackendTrafficPolicy

### ISSUE THREAD

**Issue by ryanhristovski** [envoyproxy/gateway#5226]
### Description
Currently, Envoy Gateway does not support prefix-based rate limiting when using sourceCIDR for client IPs in BackendTrafficPolicy. This makes it difficult to apply rate limits on IPv6 subnets (e.g., /64) rather than individual IP addresses.

### Proposed API Change
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: policy-httproute
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: http-ratelimit
  rateLimit:
    type: Global
    global:
      rules:
        - clientSelectors:
            - sourceCIDR:
                value: "0.0.0.0/0"  # Match all IPs
                type: Distinct
              v4_prefix_mask_len: 24   # IPv4 rate limit by /24 subnets
              v6_prefix_mask_len: 64   # IPv6 rate limit by /64 subnets
          limit:
            requests: 3
            unit: Hour
```
### Expected Behavior

- If a request comes from IPv4 (192.168.1.50), the rate limiter should apply to 192.168.1.0/24.
- If a request comes from IPv6 (2001:abcd:ef01:2345:6789:abcd:ef01:234), the rate limiter should apply to 2001:abcd:ef01:2345::/64.
- If v4_prefix_mask_len or v6_prefix_mask_len are not set, default behavior should apply:
    - IPv4 defaults to /32 (per-IP rate limiting).
    - IPv6 defaults to /128 (per-IP rate limiting).

**Comment by ryanhristovski** [comment]
Realized this can be accomplished with:
```
    rateLimit:
      type: Global
      global:
        rules:
        - clientSelectors:
          - sourceCIDR:
              type: "Distinct"
              value: "::/64"
```
Closing
