### ISSUE TITLE
combining http1.http10.useDefaultHost (ClientTrafficPolicy) with wildcard listener not possible

### ISSUE THREAD

**Issue by medarion** [envoyproxy/gateway#5280]
*Description*:
I'd like to configure two HTTP listeners on a Gateway on port 80, the first one with a hostname set (example.tld), the second one without/wildcard. I want to enable the `useDefaultHost` ClientTrafficPolicy option to allow legacy clients to reach the server using the default hostname example.tld. I need the second host with the wildcard to be able to serve clients that connect directly with the IP address.
 
Doing this will result in two listeners on the Gateway and the error ["cannot set http10 default host on listener with only wildcard hostnames"](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/clienttrafficpolicy.go#L700). Looking at the [code](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/clienttrafficpolicy.go#L675), it should be ok if there was only one listener that carries both Hostnames. But while [very old docs suggest that "compatible listeners"](https://gateway.envoyproxy.io/v0.2/design/gatewayapi-translator/#listener-compatibility) may be merge into one, this seems impossible now, as listener names must be unique (or maybe the whole concept was abandoned, but it's still mentioned in [Design Decisions](https://gateway.envoyproxy.io/contributions/design/system-design/#design-decisions)). So looking at the code in [ProcessListeners](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/listener.go#L118), there does not seem a way for `HTTPListener.Hostnames` to ever have more than one element, which prevents the intended behaviour in [translateHTTP1Settings](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/clienttrafficpolicy.go#L674) to choose the first non-wildcard hostname from a listener's list of hostnames.
So the question may boil down to: can I get multiple hostnames into a listener?

The next thing I tried was to specify the sectionName of the first listener in the ClientTrafficPolicy. But then I run into ["ClientTrafficPolicy is being applied to multiple http listeners on the same port, which is not allowed"](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/clienttrafficpolicy.go#L357). Which makes me wonder: can this error message (equal ports overlap) and the current code of translateHTTP1Settings (different behaviour for different listeners with the same port) be correct at the same time?

My current solution is to specify the IP address as the hostname of the second listener, which seems to work. But it's not great, as the [Gateway API spec](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Hostname) clearly states for the hostname that "IPs are not allowed".

Another option may be to introduce a new option in the ClientTrafficPolicy that allows to specify the default hostname directly. But perhaps I missed something and there is an easier solution already available?

*Repro steps*:
Deploy a gateway with such a listener config:
```
  listeners:
    - name: http-with-default-hostname
      protocol: HTTP
      port: 80
      hostname: example.tld
    - name: http
      protocol: HTTP
      port: 80
```

and a ClientTrafficPolicy:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: gateway
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
  http1:
    http10:
      useDefaultHost: true
```

*Environment*:
1.3.0

**Comment by arkodg** [comment]
thanks for all the details !

can you try this out on the listener

```
  listeners:
    - name: http-with-default-hostname
      protocol: HTTP
      port: 80
```


and then have a dedicated HTTPRoute with `example.tld` set in the hostnames ?
