### ISSUE TITLE
Allow disabling `generate_request_id`

### ISSUE THREAD

**Issue by jukie** [envoyproxy/gateway#5281]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

I'd like the ability to disable the behavior of generating request IDs without using an EnvoyPatchPolicy. Would it make sense to add this to `ClientTrafficPolicy` under HeaderSettings?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

ClientTrafficPolicy.HeaderSettings spec: https://github.com/envoyproxy/gateway/blob/1ba03b643046cfe05ce1a500a4c1fc43235823db/api/v1alpha1/clienttrafficpolicy_types.go#L103-L144

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: patch-pol
spec:
  jsonPatches:
  - name: default/eg/https
    operation:
      op: add
      path: /filter_chains/0/filters/0/typed_config/generate_request_id
      value: false
    type: type.googleapis.com/envoy.config.listener.v3.Listener
```
