### ISSUE TITLE
Add support for max request header size

### ISSUE THREAD

**Issue by zeisich** [envoyproxy/gateway#5368]
*Description*:
I've been trying different things to allow requests with a particularly large Authorization header to be accepted. This is how I configured `EnvoyProxy` with a JSONPatch on the bootstrap configuration.

``` yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy
spec:
  mergeGateways: true
  bootstrap:
    type: JSONPatch
    jsonPatches:
      - op: "add"
        jsonPath: "static_resources.listeners[0].filter_chains[0].filters[0].typed_config"
        path: "max_request_headers_kb"
        value: 96
```

I can see it reflecting on my pods:
``` yaml hl_lines='32'
listeners:
      - address:
          socketAddress:
            address: 0.0.0.0
            portValue: 19001
        filterChains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              httpFilters:
              - name: envoy.filters.http.health_check
                typedConfig:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                  headers:
                  - name: :path
                    stringMatch:
                      exact: /ready
                  passThroughMode: false
              - name: envoy.filters.http.router
                typedConfig:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              maxRequestHeadersKb: 96
              routeConfig:
                name: local_route
                virtualHosts:
                - domains:
                  - '*'
                  name: prometheus_stats
                  routes:
                  - match:
                      prefix: /stats/prometheus
                    route:
                      cluster: prometheus_stats
              statPrefix: eg-ready-http
        name: envoy-gateway-proxy-ready-0.0.0.0-19001
```
 
But I still get status `431 Request Header Fields Too Large`. Any help appreciated.

**Comment by arkodg** [comment]
any useful info in the access logs ?

**Comment by zeisich** [comment]
Not much:
``` json
{
  "start_time": "2025-02-28T08:39:29.687Z",
  "method": "-",
  "x-envoy-origin-path": "-",
  "protocol": "HTTP/1.1",
  "response_code": "431",
  "response_flags": "DPE",
  "response_code_details": "http1.headers_too_large",
  "connection_termination_details": "-",
  "upstream_transport_failure_reason": "-",
  "bytes_received": "0",
  "bytes_sent": "31",
  "duration": "17",
  "x-envoy-upstream-service-time": "-",
  "x-forwarded-for": "-",
  "user-agent": "-",
  "x-request-id": "-",
  ":authority": "-",
  "upstream_host": "-",
  "upstream_cluster": "-",
  "upstream_local_address": "-",
  "downstream_local_address": "----------",
  "downstream_remote_address": "-----------",
  "requested_server_name": "--------------------",
  "route_name": "-"
}
```

**Comment by zirain** [comment]
what it the listener you want to patch? if you want to patch a dynamic listener, please use `EvnoyPatchPolicy`.

**Comment by zeisich** [comment]
Basically every listener - so from your question I take that my understanding of `bootstrap` is wrong and that right now I'm just patching some static listeners, i.e. the healthcheck? 

I will try `EnvoyPatchPolicy` and report back.

**Comment by zeisich** [comment]
Got it to work with:
``` yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: max-headers-patch-policy
  namespace: envoy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: eg
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: envoy/k8s-foundation/https
      operation:
        op: add
        jsonPath: "filter_chains[0].filters[0].typed_config"
        path: max_request_headers_kb
        value: 96
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: envoy/k8s-foundation/https
      operation:
        op: add
        jsonPath: "filter_chains[1].filters[0].typed_config"
        path: max_request_headers_kb
        value: 96
```

Thank you for the advice @zirain 

I'm unsure though about the implications of `mergeGateways` and the necessity to apply the `EnvoyPatchPolicy` to the `GatewayClass`, rather than a single `Gateway`. Why would I have to choose the `GatewayClass` when in my `jsonPatches` I have to name the `Listeners` anyway?
