### ISSUE TITLE
Unable to use sectionName with SecurityPolicy

### ISSUE THREAD

**Issue by mogopz** [envoyproxy/gateway#5384]
Hello! I am trying to create a **SecurityPolicy** that references a specific `sectionName` in an **HTTPRoute** but am getting an error:

> The SecurityPolicy "example-api" is invalid: spec: Invalid value: "object": this policy does not yet support the sectionName field

Here is an example manifest:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-api
spec:
  hostnames:
    - example.com
  parentRefs:
    - name: private-gateway
      namespace: envoy-gateway
  rules:
    - name: api
      backendRefs:
        - name: example-api
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
    - name: auth
      backendRefs:
        - name: example-api
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /auth/
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: example-api
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: example-api
      sectionName: auth
  basicAuth:
    users:
      name: example-api-auth
```

I had a quick look through open issues and couldn't see this being tracked anywhere. Are there any plans to implement this?
