### ISSUE TITLE
Support XFFC validation as First class api in SecurityPolicy

### ISSUE THREAD

**Issue by nathanwang-ops** [envoyproxy/gateway#5392]
*Description*:
>When using mTLS for AuthN, RBAC AuthZ should support client certification validation
```
    authorization:
      defaultAction: Deny
      rules:
        principal:
          clientCert:
            Subject: foo.bar.com
            URI: http://foo.bar.com
```
[optional *Relevant Links*:]
https://github.com/envoyproxy/gateway/issues/2250
https://github.com/envoyproxy/gateway/pull/5310

**Comment by guydc** [comment]
Hi @nathanwang-ops ! 

XFCC may contain multiple appended client certs or no client certs at all, depending on how envoy is configured and other proxies along the way work. 

Should this validation apply to the current peer cert used to establish the MTLS connection with envoy, irregardless of the contents of XFCC? 

In your example, is Subject the DNS SAN and URI the URI SAN?

**Comment by nathanwang-ops** [comment]
@guydc 
This validation should only apply to current peer cert used to establish the mTLS connection.
In the example, the Subject is the DNS SAN and URI is URI SAN.

**Comment by nathanwang-comp** [comment]
Will this be included in 1.4

**Comment by joshuaecook** [comment]
Hello all, I'd like to offer a potential contribution to Gateway in PR #9936 : add a `ClientCertPrincipal` to `SecurityPolicy.authorization`, giving the ability to specify per-route access control based on the SAN identity carried in the peer certificate. Currently we're limited to a gateway-wide list of allowed peer identities, even though Envoy Proxy is able to configure access controls at a finer granularity. Our change adds new principal rules for `HTTPRoute` and `GRPCRoute` authorization policies that lower to Envoy's native SSL matching inputs.


Here's an example config matching requests whose mTLS client certificate carries the given SPIFFE URI SAN:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: clientcert-authz
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: backend-route
  authorization:
    rules:
      - action: Allow
        principal:
          clientCert:
            subjectAltNames:
              uris:
                - exact: "spiffe://cluster.local/ns/payments/sa/checkout"
```
