### ISSUE TITLE
Support for nested json access logs

### ISSUE THREAD

**Issue by BadLiveware** [envoyproxy/gateway#5403]
*Description*:
Support for nested json access logs, which I believe envoy supports with the `typed_json_format` https://www.envoyproxy.io/docs/envoy/v1.33.0/configuration/observability/access_log/usage#format-dictionaries, would gives us the ability to follow GCP structured logging format: https://cloud.google.com/logging/docs/structured-logging#structured_logging_special_fields

**Comment by zirain** [comment]
EG supported [json log format](https://gateway.envoyproxy.io/docs/api/extension_types/#proxyaccesslogformat), what is the difference?

**Comment by BadLiveware** [comment]
> EG supported [json log format](https://gateway.envoyproxy.io/docs/api/extension_types/#proxyaccesslogformat), what is the difference?

Doesnt support nesting, i.e only flat json

**Comment by zirain** [comment]
TBH, I never practiced with it.
Can you share more details about it?
What is the struct format you are expecting?

**Comment by gabe565** [comment]
I'd really love for this to be officially supported, but I was able to use `EnvoyPatchPolicy` to patch the underlying config:
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: log-format
  namespace: envoy-gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy
  type: JSONPatch
  jsonPatches:
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: envoy-gateway-system/envoy/https
      operation:
        op: replace
        path: /filter_chains/0/filters/0/typed_config/access_log
        value:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              log_format:
                omit_empty_values: true
                json_format:
                  timestamp: "%START_TIME%"
                  responseCodeDetails: "%RESPONSE_CODE_DETAILS%"
                  responseFlags: "%RESPONSE_FLAGS%"
                  httpRequest:
                    requestMethod: "%REQ(:METHOD)%"
                    requestUrl: "%REQ(:SCHEME)%://%REQ(:AUTHORITY)%%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                    requestSize: "%BYTES_RECEIVED%"
                    status: "%RESPONSE_CODE%"
                    responseSize: "%BYTES_SENT%"
                    userAgent: "%REQ(USER-AGENT)%"
                    remoteIp: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                    referer: "%REQ(REFERER)%"
                    latency: "%DURATION%ms"
                    protocol: "%PROTOCOL%"
```

**Comment by arkodg** [comment]
cc @zirain

**Comment by zirain** [comment]
I have no strong opinion want to bring it into EG(without bring too much complex).

**Comment by Sreini** [comment]
my use case - I use envoy as a gateway on kubernetes, hosted on Google Cloud. Google Cloud reads logging of off stdout but wants it to be in a specific format, which is a nested json log format. Right now there is the Envoy Patch Policy workaround but its not ideal that this is the only way

**Comment by hpedrorodrigues** [comment]
> my use case - I use envoy as a gateway on kubernetes, hosted on Google Cloud. Google Cloud reads logging of off stdout but wants it to be in a specific format, which is a nested json log format. Right now there is the Envoy Patch Policy workaround but its not ideal that this is the only way

I have the same use case. So far, I'm using the text format to configure this:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gateway
spec:
  logging:
    level:
      # https://docs.tetrate.io/envoy-gateway/v1.0.x/administration/debug-logs
      default: warn
  # https://gateway.envoyproxy.io/docs/tasks/observability/proxy-accesslog/
  # https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage
  telemetry:
    accessLog:
      settings:
        - format:
            type: Text
            # https://docs.cloud.google.com/logging/docs/structured-logging
            text: >
              {"severity":"%CEL(response.code < 400 ? 'INFO' : 'WARNING')%","timestamp":"%START_TIME(%Y-%m-%dT%H:%M:%S.%3fZ)%","request-id":"%REQ(X-REQUEST-ID)%","connection_termination_details":"%CONNECTION_TERMINATION_DETAILS%","requested_server_name":"%REQUESTED_SERVER_NAME%","response_code_details":"%RESPONSE_CODE_DETAILS%","response_flags":"%RESPONSE_FLAGS%","x-forwarded-for":"%REQ(X-FORWARDED-FOR)%","httpRequest":{"requestMethod":"%REQ(:METHOD)%","requestUrl":"%REQ(:SCHEME)%://%REQ(:AUTHORITY)%%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","requestSize":"%DOWNSTREAM_WIRE_BYTES_RECEIVED%","status":"%RESPONSE_CODE%","responseSize":"%BYTES_SENT%","userAgent":"%REQ(USER-AGENT)%","remoteIp":"%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%","serverIp":"%DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%","referer":"%REQ(REFERER)%","latency":"%DURATION%ms","protocol":"%PROTOCOL%"},"upstream":{"address":"%UPSTREAM_HOST%","cluster":"%UPSTREAM_CLUSTER%","local_address":"%UPSTREAM_LOCAL_ADDRESS%","response":{"length":"%UPSTREAM_WIRE_BYTES_RECEIVED%","latency":"%RESPONSE_DURATION%ms","status":"%RESPONSE_CODE%"},"transport_failure_reason":"%UPSTREAM_TRANSPORT_FAILURE_REASON%"},"downstream":{"local_address":"%DOWNSTREAM_LOCAL_ADDRESS%","remote_address":"%DOWNSTREAM_REMOTE_ADDRESS%","bytes_received":"%BYTES_RECEIVED%"},"logging.googleapis.com/labels":{"route_name":"%ROUTE_NAME%"}}
          sinks:
            - type: File
              file:
                path: /dev/stdout
```
