### ISSUE TITLE
TLS Termination at NLB, http listener on port 443

### ISSUE THREAD

**Issue by jessebye** [envoyproxy/gateway#5418]
*Description*:
I'd like to do TLS termination at the AWS NLB layer, then send traffic in plain HTTP to the backend. I was able to do this with Istio ingress, but am having trouble with this same setup in Envoy Gateway.

Here is the Gateway:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:<account>:certificate/<id>
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  name: gw
  namespace: test
spec:
  gatewayClassName: envoy
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Same
      name: https
      port: 443
      protocol: HTTP
```

And then routes like this:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ssl-redirect
  namespace: test
spec:
  parentRefs:
  - name: gw
    namespace: test
    port: 80
  hostnames:
    - gw.foo.bar
  rules:
    - filters:
      - requestRedirect:
          scheme: https
          statusCode: 301
        type: RequestRedirect
      matches:
      - path:
          value: /api
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api
  namespace: test
spec:
  parentRefs:
  - name: gw
    namespace: test
    port: 443
  hostnames:
    - gw.foo.bar
  rules:
    - backendRefs:
      - name: api
        port: 80
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            replacePrefixMatch: /
            type: ReplacePrefixMatch
      matches:
      - path:
          type: PathPrefix
          value: /api
```

The http->https redirect works great, but then `curl -i https://gw.foo.bar/api` gives me this error:

```
* Host gw.foo.bar:443 was resolved.
* IPv6: (none)
* IPv4: 10.100.12.214
*   Trying 10.100.12.214:443...
* Connected to gw.foo.bar (10.100.12.214) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
* Closing connection
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```

What am I missing?

[optional *Relevant Links*:]
n/a
