### ISSUE TITLE
How can I change the default timeout(15s) with GRPCROUTE?

### ISSUE THREAD

**Issue by sunerpy** [envoyproxy/gateway#5446]
*Description*:
>I use GRPCROUTE to forward frontend traffic to backend microservices. However, since the backend service takes a long time to execute, the connection is automatically disconnected.

I checked the issues and documentation, and found that HTTPRoute allows setting a timeout, but I couldn't find relevant information for GRPCRoute.

How can I set the timeout for gRPC?

**Comment by arkodg** [comment]
if this is for unary rpc, you can use the `spec.timeout.requestTimeout` field https://gateway.envoyproxy.io/docs/api/extension_types/#httptimeout in BackendTrafficPolicy

looks like we dont have any support for streaming rpc, keeping this issue open for resolving it.

**Comment by sunerpy** [comment]
> if this is for unary rpc, you can use the `spec.timeout.requestTimeout` field https://gateway.envoyproxy.io/docs/api/extension_types/#httptimeout in BackendTrafficPolicy
> 
> looks like we dont have any support for streaming rpc, keeping this issue open for resolving it.

Thanks for your reply, it worked for unary RPC. For stream RPC, I temporarily using a continuous health check response...

**Comment by arkodg** [comment]
thanks, editing the title to track setting timeouts for streaming rpc

**Comment by jephthia** [comment]
Just hit this issue, lost a day trying to figure out why my bidirectional stream kept closing 15 seconds after the client triggered a half close once it was done streaming requests. This whole time I thought the issue had to be with either my client or server until I stumbled on this and realized that envoy was the one closing out the stream:
https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts
> A route [timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout) is the amount of time that Envoy will wait for the upstream to respond with a complete response. This timeout does not start until the entire downstream request stream has been received.
> Attention
> This timeout defaults to 15 seconds, however, it is not compatible with streaming responses (responses that never end), and will need to be disabled. Stream idle timeouts should be used in the case of streaming APIs as described elsewhere on this page.

I think it would be worth mentioning it in here:
https://gateway.envoyproxy.io/docs/tasks/traffic/gatewayapi-support/#grpcroute
because at first glance gRPC seems supported by default by the Envoy Gateway API but this short timeout basically makes streams unusable, especially since it cannot be changed yet, or at least not easily.

<hr>

Though after a lot of trial and error and following the guide here https://gateway.envoyproxy.io/docs/tasks/extensibility/envoy-patch-policy/ I finally managed to configure it and my streams are now back to working, so I'll just drop it here in case anyone else might need this until this issue is resolved.
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: timeout-patch-policy
  namespace: envoy-gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gtw
  type: JSONPatch
  jsonPatches:
    - type: 'type.googleapis.com/envoy.config.route.v3.RouteConfiguration'
      name: 'envoy-gateway-system/envoy-gtw/https'
      operation:
        op: add
        jsonPath: "..routes[?(@.name == 'grpcroute/envoy-gateway-system/my-grpc-route/rule/0/match/-1/my-subdomain_example_com')]"
        path: '/route/timeout'
        value: '0s'
```
