### ISSUE TITLE
Weird inconsistent handling of namespace in Standalone mode

### ISSUE THREAD

**Issue by mathetake** [envoyproxy/gateway#5474]
*Description*:

The existence of `namespace` in the resources passed to the standalone mode make the working resources not working only with the standalone mode. The log doesn't show any useful message, basically silencing any errors and it seems almost impossible to debug to reach the conclusion that namespace is the culprit.  The documentation in https://gateway.envoyproxy.io/docs/tasks/operations/standalone-deployment-mode/ not mentioning this behavior either. So, EG definitely should fix it by respecting namespaces or document this behavior as expected. 

*Repro steps*:

The following yam is not working (route not found) `curl localhost:8888/ --head` returns `404` due to route not found:

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: aigw-run
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: aigw-run
  namespace: default
spec:
  gatewayClassName: aigw-run
  listeners:
    - name: http
      port: 8888
      protocol: HTTP
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: openai
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: api.openai.com
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: aigw-run
  namespace: default
spec:
  parentRefs:
    - name: aigw-run
      namespace: default
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: openai
      matches:
        - path:
            value: /
```

On the other hand, the following yaml is working: the same curl gets 400 bad request from the OpenAI upstream:

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: aigw-run
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: aigw-run
spec:
  gatewayClassName: aigw-run
  listeners:
    - name: http
      port: 8888
      protocol: HTTP
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: openai
spec:
  endpoints:
    - fqdn:
        hostname: api.openai.com
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: aigw-run
spec:
  parentRefs:
    - name: aigw-run
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: openai
      matches:
        - path:
            value: /
```

which basically only removes the namespace specifier from the resources.
