### ISSUE TITLE
Support headers for responseOverride

### ISSUE THREAD

**Issue by jordangarside-kiwi** [envoyproxy/gateway#5475]
It's common to want to do a redirect when auth fails, but that's currently not possible as `responseOverride` only supports rewriting the `statusCode` and `body`:
```
responseOverride: [
  {
    match: {
      statusCodes: [
        {
          type: 'Value',
          value: 401,
        },
        {
          type: 'Value',
          value: 403,
        },
      ],
    },
    response: {
      statusCode: 302,
      // not supported
      headers: [
        {
          name: 'Location',
          value: `https://${ssoHost}/oauth2/sign_in?rd={url}`,
        },
      ],
    },
  },
```

```
Kubernetes API server: failed to create typed patch object (oauth2-proxy/oauth2-proxy-response-override; gateway.envoyproxy.io/v1alpha1, Kind=BackendTrafficPolicy): .spec.responseOverride[0].response.headers: field not declared in schema
```

Same request:
https://github.com/envoyproxy/gateway/discussions/4254#discussion-7192030

**Comment by Chever-John** [comment]
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: auth-redirect-patch
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: your-http-route-name  # 替换为您的 HTTPRoute 名称
  patches:
    - type: JSONPatch
      value:
      - op: add
        path: /spec/virtualHosts/0/routes/0/typed_per_filter_config/envoy.filters.http.custom_response
        value:
          config:
            custom_response_matcher:
              matcher_list:
                matchers:
                - predicate:
                    single_predicate:
                      input:
                        name: response-code
                        typed_config:
                          '@type': type.googleapis.com/envoy.type.matcher.v3.HttpResponseStatusCodeMatchInput
                      value_match:
                        safe_regex:
                          google_re2: {}
                          regex: ^(401|403)$
                  on_match:
                    action:
                      name: redirect
                      typed_config:
                        '@type': type.googleapis.com/envoy.extensions.http.custom_response.redirect_policy.v3.RedirectPolicy
                        redirect_action:
                          host_redirect: "your-sso-host"
                          path_redirect: "/oauth2/sign_in"
                          scheme_redirect: "https"
                          strip_query: false
                          response_code: FOUND
                        status_code: 302
```

I tried to write a configuration, hopefully it helps!

This configuration implements an authentication redirection mechanism that:

- Intercepts HTTP responses for the targeted HTTPRoute

- Detects when a 401 (Unauthorized) or 403 (Forbidden) status code is returned

- Automatically redirects the client to a specified SSO login page (https://your-sso-host/oauth2/sign_in)

- Performs the redirection using HTTP 302 (Found) status code

- Preserves all query parameters from the original request during redirection
