### ISSUE TITLE
Matching hostnames with a wildcard label

### ISSUE THREAD

**Issue by sadovnikov** [envoyproxy/gateway#5500]
*Description*:

According to the [API specs](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteSpec), the hostnames in HTTP Routes can use wildcard label `"*"` or can be skipped completely, which would mean almost the same as `*` hostname. The precedence for the hostnames and HTTPRouteMatches is described.

An HTTPRoute with the pseudo-spec below makes traffic on all hosts with all paths forwarded to the `"passthrough-service"` service unless it's matched by another, more specific route.

```
spec:
  parentRefs: 
  - { gateway ref }
  rules:
  - backendRefs: 
    - { "passthrough-service" }
    matches:
    - path:
        type: PathPrefix
        value: /
```

However, adding an HTTPRoutes for a specific hostname and with a specific path-prefix changes this behaviour. Requests to `www.host.org`, with paths not matching `/pathmatch` prefix are not forwarded to the `"passthrough-service"` anymore. Instead, they get `NR`

```
spec:
  parentRefs:
  - { gateway ref }
  hostname:
  - www.host.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /pathmatch
    backendRefs:
    - { "host-path-matched-service" }
```

*Repro steps*:

#5436 is my attempt to reproduce this bug. However, the test succeeds. I believe it's due to the used test framework.

*Environment*:

Image `docker.io/envoyproxy/gateway:v1.3.1`

*Extra*:

The "catch-all" HTTP Route above adds the following `virtual_host` to the Envoy config. It's created for the `"*"` domain. 

```
{
  "name": "envoy-gateway-system/default/https/*",
  "domains": [
    "*"
  ],
  "routes": [
    {
      "match": {
        "prefix": "/"
      },
      "route": {
        "cluster": "httproute/ambassador-system/eg-passthrough/rule/0",
        "upgrade_configs": [{"upgrade_type": "websocket"}]
      },
      "metadata": {
        "filter_metadata": {
          "envoy-gateway": {
            "resources": [{"namespace": "ambassador-system", "kind": "HTTPRoute", "name": "eg-passthrough" }]
          }
        }
      },
      "name": "httproute/ambassador-system/eg-passthrough/rule/0/match/0/*"
    }
  ],
  "metadata": {}
}
```

The second HTTP Route creates a virtual host for the `"www.host.org"` domain.

A request for the `"www.host.org"` domain arrives and gets matched only by the rules in that particular virtual host. The matching rules from `"*"` or other less specific hostnames are not checked.

The matching rules in virtual hosts should include rules from less specific hosts. Or Envoy, after not finding a match in the most specific virtual host, should apply rules from less specific virtual hosts

**Comment by sadovnikov** [comment]
@zhaohuabing, could you please take a look at this?

**Comment by arkodg** [comment]
@sadovnikov this isnt a bug imo, its tiered matching, can you workaround it by adding 
```
  - backendRefs: 
    - { "passthrough-service" }
    matches:
    - path:
        type: PathPrefix
        value: /
```

to the HTTPRoute ?
