### ISSUE TITLE
TCP Health Check is not working

### ISSUE THREAD

**Issue by paraniraja** [envoyproxy/gateway#5506]
*Description*:
I am trying to setup a TCP health check in BackendTrafficPolicy attached to a TCPRoute, a simple echo server is running as a backend service and prints the messages. TCPRoute is working fine, able to see the message in POD when routed via eg.
However I am not seeing any messages as part of healthcheck.

*Repro steps*:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: btp
  namespace: default
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: backend
  healthCheck:
    passive:
      baseEjectionTime: 1s
      interval: 1s
      maxEjectionPercent: 100
      consecutive5XxErrors: 2
      consecutiveGatewayErrors: 0
      consecutiveLocalOriginFailures: 5
    active:
      timeout: "1s"
      interval: "5s"
      unhealthyThreshold: 3
      healthyThreshold: 1
      type: TCP
      tcp: {}
```
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: backend-tcp1
spec:
  parentRefs:
    - name: eg
      namespace: default
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend2
          namespace: default
          port: 3000
```

*Environment*:
Gateway : 1.3.1
Proxy: v1.33.0
