### ISSUE TITLE
Per HttpRoute(API) cluster creation

### ISSUE THREAD

**Issue by NomadXD** [envoyproxy/gateway#551]
*Description*:
With the current implementation a cluster is created per each of the routes. For example in the following HttpRoute, 3 clusters will be created one for each "/abc", "/def" and "/ghi".

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: httpbin
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /abc
        - path:
            type: PathPrefix
            value: /def
        - path:
            type: PathPrefix
            value: /ghi
```

Envoy proxy uses a cluster to represent a backend service (host and port) and there's NO point of creating multiple clusters if each route of the same HttpRoute points to the same cluster. **The current approach is not very scalable if Envoy proxy is used for an API gateway** with several thousands APIs deployed as memory usage increases with the number of clusters created. If we can have an implementation where we can choose to create clusters per HttpRoute, then we can support a wide range of API gateway related use cases. For example the a swagger / OpenAPI 3 can be directly converted to a HttpRoute and deployed in Envoy Proxy where only 1 cluster is created per API. 

I also know that Gateway API is supposed to be a super set of Ingress API and basically targeted at improving the Ingress API with additional capabilities. **But IMO in order to fully utilize the features of Envoy proxy, we should consider the use cases related to API gateways too.**

Any plans to support these API gateway related use cases in future ? Or is this fully focused on ingress related use cases ?

**Comment by arkodg** [comment]
thanks for raising this issue, adding this to the 0.3.0 milestone
in case someone would like to pick this one, here's one suggestion on how to dedup clusters
* naming the RouteDestination IR https://github.com/envoyproxy/gateway/blob/2fb3ca8954705dabbcfa08007b658655fcb60f46/internal/ir/xds.go#L239 or creating a wrapper struct around the list
https://github.com/envoyproxy/gateway/blob/2fb3ca8954705dabbcfa08007b658655fcb60f46/internal/ir/xds.go#L169
* reusing the named RouteDestination in the Gateway API translator
https://github.com/envoyproxy/gateway/blob/2fb3ca8954705dabbcfa08007b658655fcb60f46/internal/gatewayapi/translator.go#L630
* reusing the named RouteDestination in the xds Translator https://github.com/envoyproxy/gateway/blob/2fb3ca8954705dabbcfa08007b658655fcb60f46/internal/xds/translator/cluster.go#L42

**Comment by youngnick** [comment]
I think it's important to remember that this is a first cut at Gateway API support @NomadXD, it's in no way intended to be final.

I think that deduping clusters like this is a great optimization that, as you say, will reduce memory usage substantially.

**Comment by NomadXD** [comment]
@arkodg Can you assign me this ?

**Comment by NomadXD** [comment]
@youngnick @arkodg Opened a PR to fix this. Kubernetes Gateway Spec supports `backendRefs` at `spec.rules` and `spec.rules.matches`. 

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: bar-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "bar.example.com"
  rules:
  - matches:
    - headers:
      - type: Exact
        name: env
        value: canary
    backendRefs:
    - name: bar-svc-canary
      port: 8080
  - backendRefs:
    - name: bar-svc
      port: 8080
```

With the PR I opened (#623 ) we are looking only at the backendRefs in `spec.rules` and creating a single cluster with load balance endpoints. And I think the ideal case would be to create per route clusters (Resource level clusters) only if the user has specified `spec.rules.matches` and use backendRefs at `spec.rules` to create API level clusters.
