### ISSUE TITLE
Expose possibility to configure (http1_safe_)max_connection_duration, max_requests_per_connection

### ISSUE THREAD

**Issue by aukevanleeuwen** [envoyproxy/gateway#5520]
*Description*:

When Envoy (with HPA) is receive load from a small number of clients (i.e. as a L2 proxy behind a CDN), the load is not evenly distributed across pods after scaling. The reason being that the extra load will not always come in the form of new connections, but rather from existing connections with HTTP `Keep-Alive` enabled (default AFAICT). A similar issue is described in a bit more detail here: https://github.com/istio/istio/issues/27280.

To force load to be redistributed, there are different knobs on the Envoy (server) side:
* Via https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto:
  * `common_http_protocol_options.max_connection_duration`
  * `common_http_protocol_options.max_requests_per_connection`
  * `http1_safe_max_connection_duration`

But these are currently not configurable via the Gateway API. It would be nice if we can set them. Note: IMHO it seems very reasonable to default `http1_safe_max_connection_duration` to `true` if using `max_connection_duration` to avoid a race condition also detailed here: https://github.com/envoyproxy/envoy/issues/13388. This last issue is from 2020, but I noticed a reasonably new (2024) option has been added because of https://github.com/envoyproxy/envoy/issues/34356. 

As an alternative (or on top of) it would be nice to configure `max_requests_per_connection` to be able to have control over closing connections from the server (Envoy proxy) side, therefore having the ability to rebalance traffic in the cluster.

*Relevant Links*:
* [Slack thread](https://envoyproxy.slack.com/archives/C03E6NHLESV/p1742214225514989)
* https://github.com/istio/istio/issues/27280
* https://github.com/envoyproxy/envoy/issues/34356

**Comment by aukevanleeuwen** [comment]
⠀

**Comment by jukie** [comment]
I've been achieving this with a patch policy and would also like to see it directly supported

**Comment by jukie** [comment]
Does this look good for the API under ClientTrafficPolicy?
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
spec:
  connection:
    connectionLimit:
      maxConnectionDuration: duration
      maxRequestsPerConnection: uint32
  http1:
    safeMaxConnectionDuration: bool # Only applicable when `connection.connectionLimit.maxConnectionDuration` is set
```
