### ISSUE TITLE
Envoy xDS metadata for `Cluster` and `LocalityLbEndpoints` resources

### ISSUE THREAD

**Issue by muwaqar** [envoyproxy/gateway#5523]
*Description*:
Currently EnvoyGateway propagates xDS metadata for Route and VirtualHost resources, but not for Cluster and LbEndpoints.

Note that the [main documentation page](https://gateway.envoyproxy.io/contributions/design/metadata/) for this feature currently says the following:

> [Service](https://kubernetes.io/docs/concepts/services-networking/service/), [ServiceImport](https://multicluster.sigs.k8s.io/concepts/multicluster-services-api/#serviceimport-and-endpointslices) and [Backend](https://gateway.envoyproxy.io/latest/api/extension_types/#backend) metadata and port name are propagated to envoy [cluster](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto) metadata.

This is incorrect, as evident from the [code](https://github.com/envoyproxy/gateway/blob/292894057fd4083b1c4dce691d510c1a6bc53073/internal/xds/translator/cluster.go#L86) since `buildXdsCluster()` never sets any metadata.

The proposal in this ticket is to:

1) `Route` metadata be propagated to `Cluster` xDS.

Each `*RouteRule` creates a distinct xDS cluster which encapsulates upstream endpoints of its `backendRefs`.

Accordingly, maybe we can put the `*Route` metadata into the `Cluster` xDS?

For example:

For a HTTPRoute as:
```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  annotations:
    gateway.envoyproxy.io/foo: bar
  name: myroute
  namespace: myns
spec:
  rules:
    matches:
    - path:
        type: PathPrefix
        value: /mypath
```

we get:
```
name: httproute/myns/myroute/rule/0
type: CDS
[...]
metadata:
  filter_metadata:
    envoy-gateway:
      resources:
        - namespace: myns
          groupVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          annotations:
            foo: bar
          name: myroute
``` 

2) `BackendReference` (`Service`, `ServiceImport`, `Backend`) metadata be propagated to `LocalityLbEndpoints` xDS. 

If a `*RouteRule` contains multiple `BackendReference`, each of these are modeled as separate `LocalityLbEndpoints`. 

Accordingly, maybe we can put the `BackendReference` metadata into the `LocalityLbEndpoints` xDS?

For example:

For a HTTPRoute as:
```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  annotations:
    gateway.envoyproxy.io/foo: bar
  name: myroute
  namespace: myns
spec:
  rules:
    - backendRefs:
      - group: ""
         kind: Service
         name: svc-1
         port: 3000
       - group: ""
         kind: Service
         name: svc-2
         port: 3000  
```

we get:
```
clusterName: httproute/myns/myroute/rule/0
endpoints:
- lbEndpoints:
  - endpoint:
      address:
      [...]
  locality:
    region: httproute/myns/myroute/rule/0/backend/0
  metadata:
    filter_metadata:
      envoy-gateway:
        resources:
          - namespace: myns
            groupVersion: ""
            kind: Service
            name: svc-1
- lbEndpoints:
  - endpoint:
      address:
      [...]
  locality:
    region: httproute/myns/myroute/rule/0/backend/1
  metadata:
      filter_metadata:
        envoy-gateway:
          resources:
            - namespace: myns
              groupVersion: ""
              kind: Service
              name: svc-2
```

[optional *Relevant Links*:]

The feature is documented at https://gateway.envoyproxy.io/contributions/design/metadata/.
