### ISSUE TITLE
Envoy Gateway Installation with Argo CD Fails Due to Annotation Size Limit

### ISSUE THREAD

**Issue by djbulsink** [envoyproxy/gateway#5546]
*Description*:
When installing Envoy Gateway with Argo CD, the following error occurs:  

`error when patching "/dev/shm/3535441978": CustomResourceDefinition.apiextensions.k8s.io "envoyproxies.gateway.envoyproxy.io" is invalid: metadata.annotations: Too long: may not be more than 262144 bytes`

This error is caused by the large size of the manifest. When applying the manifest using `kubectl apply`, the limit of **262144 bytes** is not reached. However, when using **Argo CD** or `kubectl apply` with additional annotations, the manifest exceeds this limit.

*Repro steps*:

###  Using Argo CD  
Create an **Application** resource with the following configuration:  

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: operators
spec:
  destination:
    namespace: envoy-gateway
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gateway-helm
    helm:
      valuesObject: {}
    repoURL: docker.io/envoyproxy
    targetRevision: v1.3.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
```

### Using kubectl

The issue is also reproducible by applying the EnvoyProxies Custom Resource Definition (CRD) directly using kubectl apply:

```bash
kubectl apply -f https://raw.githubusercontent.com/envoyproxy/gateway/refs/heads/release/v1.3/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
```

This results in the following error:
```
The CustomResourceDefinition "envoyproxies.gateway.envoyproxy.io" is invalid: metadata.annotations: Too long: may not be more than 262144 bytes
```

*Environment*:
Helm chart version: v1.3.1

*Logs*:

```
error when patching "/dev/shm/3535441978": CustomResourceDefinition.apiextensions.k8s.io "envoyproxies.gateway.envoyproxy.io" is invalid: metadata.annotations: Too long: may not be more than 262144 bytes
```
