### ISSUE TITLE
Unable to specify `samplingFraction` in `EnvoyProxy#telemetry.tracing`

### ISSUE THREAD

**Issue by aukevanleeuwen** [envoyproxy/gateway#5571]
*Description*:
I'm unable to specify a `samplingFraction` in `EnvoyProxy`. 

*Repro steps*:
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: foo
spec:
  telemetry:
    tracing:
      provider:
        backendRefs:
          - group: ''
            kind: Service
            name: "otel-collector"
            namespace: "monitoring"
            port: 4317
        type: OpenTelemetry
      samplingFraction:
        numerator: 100
        denominator: 100
```

```shell
❯ k -n default apply -f envoy-proxy.yaml
The EnvoyProxy "foo" is invalid: spec.telemetry.tracing: Invalid value: "object": only one of SamplingRate or SamplingFraction can be specified
```

I'm hitting this validation: https://github.com/envoyproxy/gateway/blob/54efa343998cfcc0b8305721c94f04c9dc29610c/api/v1alpha1/tracing_types.go#L11

Due to this default:
https://github.com/envoyproxy/gateway/blob/54efa343998cfcc0b8305721c94f04c9dc29610c/api/v1alpha1/tracing_types.go#L22

So basically `samplingRate` defaults to `100`, which means that I can never specify a `samplingFraction`. 

When I update the custom resource definition and manually comment out the `default: 100` on `samplingRate`, I'm able to apply the manifest.
