### ISSUE TITLE
filter order not change after apply EnvoyProxy

### ISSUE THREAD

**Issue by wu0407** [envoyproxy/gateway#5636]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: The expected value isn't returned, etc.

I want to change the filter order, move envoy.filters.http.ext_authz after envoy.filters.http.jwt_authn, but it's not work.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
spec:
  filterOrder:
  - name: envoy.filters.http.ext_authz
    after: envoy.filters.http.jwt_authn

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: jwt-example
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend
  jwt:
    providers:
    - name: example
      remoteJWKS:
        uri: http://jwks.default.svc/jwks.json
      claimToHeaders:
      - header: user-id
        claim: user
  extAuth:
    headersToExtAuth:
      - user-id
    http:
      backendRefs:
        - name: http-ext-auth
          port: 9002
      headersToBackend: ["subscription-plan"]
```
envoy config

```
"filters": [
         {
          "name": "envoy.filters.network.http_connection_manager",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
           "stat_prefix": "http-10080",
           "rds": {
            "config_source": {
             "ads": {},
             "resource_api_version": "V3"
            },
            "route_config_name": "default/eg/http"
           },
           "http_filters": [
            {
             "name": "envoy.filters.http.ext_authz/securitypolicy/default/jwt-example",
             "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
              "http_service": {
               "server_uri": {
                "uri": "http://http-ext-auth.default:9002",
                "cluster": "securitypolicy/default/jwt-example/extauth/0",
                "timeout": "10s"
               },
               "authorization_response": {
                "allowed_upstream_headers": {
                 "patterns": [
                  {
                   "exact": "subscription-plan",
                   "ignore_case": true
                  }
                 ]
                }
               }
              },
              "transport_api_version": "V3",
              "allowed_headers": {
               "patterns": [
                {
                 "exact": "user-id",
                 "ignore_case": true
                }
               ]
              }
             },
             "disabled": true
            },
            {
             "name": "envoy.filters.http.jwt_authn",
             "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication",
              "providers": {
               "httproute/default/backend/rule/0/match/0/www_example_com/example": {
                "remote_jwks": {
                 "http_uri": {
                  "uri": "http://jwks.default.svc/jwks.json",
                  "cluster": "jwks_default_svc_80",
                  "timeout": "10s"
                 },
                 "cache_duration": "300s",
                 "async_fetch": {}
                },
                "forward": true,
                "payload_in_metadata": "example",
                "claim_to_headers": [
                 {
                  "header_name": "user-id",
                  "claim_name": "user"
                 }
                ],
                "normalize_payload_in_metadata": {
                 "space_delimited_claims": [
                  "scope"
                 ]
                }
               }
              },
              "requirement_map": {
               "httproute/default/backend/rule/0/match/0/www_example_com": {
                "provider_name": "httproute/default/backend/rule/0/match/0/www_example_com/example"
               }
              }
             }
            },
            {
             "name": "envoy.filters.http.router",
             "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router",
              "suppress_envoy_headers": true
             }
            }
           ],
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.
envoy-gateway : v1.3.2

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by wu0407** [comment]
Sorry, I forgot to set `infrastructure` in `Gateway`. 

It works after setting next 
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: custom-proxy-config
```
