### ISSUE TITLE
help request: use range_matchers in the gateway to match headers for traffic splitting

### ISSUE THREAD

**Issue by debuggedme** [envoyproxy/gateway#5654]
*Description*:

Is there a way to use `range_matchers` in the gateway to match headers for traffic splitting?

[optional *Relevant Links*:]

- https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/range.proto.html
- https://gateway.envoyproxy.io/docs/tasks/traffic/http-traffic-splitting/

**Comment by debuggedme** [comment]
Maybe there are some ways to handle this situation



```go
	// Header matches
	for _, headerMatch := range headerMatches {
		stringMatcher := buildXdsStringMatcher(headerMatch)

		headerMatcher := &routev3.HeaderMatcher{
			Name: headerMatch.Name,
			HeaderMatchSpecifier: &routev3.HeaderMatcher_StringMatch{
				StringMatch: stringMatcher,
			},
		}
		outMatch.Headers = append(outMatch.Headers, headerMatcher)
	}
```

- https://github.com/envoyproxy/gateway/blob/v1.3.2/internal/xds/translator/route.go#L161-L172
- https://pkg.go.dev/github.com/envoyproxy/go-control-plane/envoy@v1.32.4/type/v3#Int64Range

**Comment by arkodg** [comment]
can you share your use case @debuggedme

**Comment by debuggedme** [comment]
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "localhost"
  rules:
    - backendRefs:
        - kind: Service
          name: whoami
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - kind: Service
          name: whoami-1
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
          headers:
            - type: RangeMatchers # <--- like this
              name: client_ver
              start: 1
              end: 10
```
