### ISSUE TITLE
Active Health Check via BackendTrafficPolicy Not Marking Unhealthy Backends Down

### ISSUE THREAD

**Issue by Tyrone-W** [envoyproxy/gateway#5664]
*Description*:
I'm experiencing an issue with Envoy gateway health checking to backends.

I've configured healthchecking on a httproute referencing two backends, one of which intentionally returning a 503.

The logs do not show healthchecking being performed and traffic is sent to the downed backend.

I would expect envoy to healthcheck the backend and mark it as down, so traffic is only sent to the backend marked as up.

*Repro steps*:
Manfiests to replicate provided below:

The httproutefilter doesn't have a status but has been accepted as it's providing the expected function ensuring the backends receive the hostname provided in the spec.
```---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    provider:
      type: Kubernetes
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    extensionApis:
      enableBackend: true 
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
  hostnames:
    - "example.com"
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: az1
        - group: gateway.envoyproxy.io
          kind: Backend
          name: az2
      matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.envoyproxy.io
            kind: HTTPRouteFilter
            name: header-host-rewrite
status:
  parents:
  - conditions:
    - lastTransitionTime: "2025-04-02T16:47:25Z"
      message: Route is accepted
      observedGeneration: 3
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-04-02T16:47:25Z"
      message: Resolved all the Object references for the Route
      observedGeneration: 3
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: envoy-gateway-system
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: header-host-rewrite
spec:
  urlRewrite:
    hostname:
      type: Backend
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: healthcheck
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: httproute
  loadBalancer:
    type: RoundRobin
  healthCheck:
    active:
      timeout: 5s
      interval: 5s
      type: HTTP
      http:
        path: /
      unhealthyThreshold: 3
      healthyThreshold: 3
status:
  ancestors:
  - ancestorRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: envoy-gateway-system
    conditions:
    - lastTransitionTime: "2025-03-24T10:08:21Z"
      message: Policy has been accepted.
      reason: Accepted
      status: "True"
      type: Accepted
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: az1
spec:
  endpoints:
    - fqdn:
        hostname: az1.example.com
        port: 80
status:
  conditions:
  - lastTransitionTime: "2025-03-25T11:20:38Z"
    message: The Backend was accepted
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: az2
spec:
  endpoints:
    - fqdn:
        hostname: az2.example.com
        port: 80
status:
  conditions:
  - lastTransitionTime: "2025-03-27T17:46:59Z"
    message: The Backend was accepted
    observedGeneration: 2
    reason: Accepted
    status: "True"
    type: Accepted
```

*Environment*:
envoyproxy Version 1.33.1

*Logs*:
The hc logging component doesn't show in the logs I've capture, the below config_dump shows the healthcheck has been added to the httproute hostname but the backend hosts haven't got their own healthchecks. 
```
   "dynamic_active_clusters": [
    {
     "version_info": "5a761b6cf6240ec11e2b66c32b6a6fa1721b14e4839d890491a14795e24571fa",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "httproute/envoy-gateway-system/example/rule/0",
      "type": "STRICT_DNS",
      "connect_timeout": "10s",
      "per_connection_buffer_limit_bytes": 32768,
      "health_checks": [
       {
        "timeout": "5s",
        "interval": "5s",
        "unhealthy_threshold": 3,
        "healthy_threshold": 3,
        "http_health_check": {
         "host": "example.com",
         "path": "/",
         "expected_statuses": [
          {
           "start": "200",
           "end": "201"
          }
         ]
        }
       }
      ],
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      },
      "dns_refresh_rate": "30s",
      "dns_lookup_family": "V4_PREFERRED",
      "common_lb_config": {
       "locality_weighted_lb_config": {}
      },
      "load_assignment": {
       "cluster_name": "httproute/envoy-gateway-system/example/rule/0",
       "endpoints": [
        {
         "locality": {
          "region": "httproute/envoy-gateway-system/example/rule/0/backend/0"
         },
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "az1.example.com",
              "port_value": 80
             }
            }
           },
           "load_balancing_weight": 1
          }
         ],
         "load_balancing_weight": 1
        },
        {
         "locality": {
          "region": "httproute/envoy-gateway-system/example/rule/0/backend/1"
         },
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "az2.example.com",
              "port_value": 80
             }
            }
           },
           "load_balancing_weight": 1
          }
         ],
         "load_balancing_weight": 1
        }
       ]
      },
      "respect_dns_ttl": true
     },
     "last_updated": "2025-04-03T09:33:48.216Z"
    },
   ]
```

I would expect envoy to render config similar to the following which is taken from using envoy(non gateway) to test this scenario.

```load_assignment:
  cluster_name: my-service
  endpoints:
  - lb_endpoints:
    - endpoint:
        health_check_config:
          hostname: az1.example.com
        address:
          socket_address:
            address: az1.example.com
            port_value: 443
    - endpoint:
        health_check_config:
          hostname: az2.example.com
        address:
          socket_address:
            address: az2.example.com
            port_value: 443
transport_socket:
  name: envoy.transport_sockets.tls
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
health_checks:
- timeout: 5s
  interval: 10s
  unhealthy_threshold: 2
  healthy_threshold: 1
  http_health_check:
    path: /```

**Comment by arkodg** [comment]
thanks for swinging by in the end user meeting today, and sharing all the details

took another look at this, here's what's happening

1. This is the configuration Envoy Gateway generates

```
"health_checks": [
       {
        "timeout": "5s",
        "interval": "5s",
        "unhealthy_threshold": 3,
        "healthy_threshold": 3,
        "http_health_check": {
         "host": "example.com",
         "path": "/",
         "expected_statuses": [
          {
           "start": "200",
           "end": "201"
          }
         ]
        }
       }
```

This was generated since the BackendTrafficPolicy applies to the HTTPRoute

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: healthcheck
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: httproute
  loadBalancer:
    type: RoundRobin
  healthCheck:
    active:
      timeout: 5s
      interval: 5s
      type: HTTP
      http:
        path: /
      unhealthyThreshold: 3
      healthyThreshold: 3
....
```

the hostname set here is `example.com` . This is taken from the Route Hostname

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
  hostnames:
    - "example.com"
....
```

What you are looking for is an active health configuration thats per backend, i.e. `hostname: az1.example.com` and `hostname: az2.example.com`

This is not supported today since the BackendTrafficPolicy applies to a Route, and not per Backend.

My recommendation is to use Passive Health Checks instead, here's an example

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: passive-health-check
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ha-example 
  healthCheck:
    passive:
      baseEjectionTime: 10s
      interval: 2s
      maxEjectionPercent: 100
      consecutive5XxErrors: 1 
      consecutiveGatewayErrors: 0
      consecutiveLocalOriginFailures: 1
      splitExternalLocalOriginErrors: false
```
