### ISSUE TITLE
Make retry_host_predicate Configurable or Remove Default from Retry Policy

### ISSUE THREAD

**Issue by LinMoskovitch** [envoyproxy/gateway#5689]
Currently, Envoy Gateway sets the following retry host predicate by default in all [retry policies](https://github.com/envoyproxy/gateway/blob/521b78b6efdcd13ebe3fe14c06c45681a84ef97c/internal/xds/translator/route.go#L619):

```json
"retry_host_predicate": [
  {
    "name": "envoy.retry_host_predicates.previous_hosts",
    "typed_config": {
      "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
    }
  }
]
```

This behavior is hardcoded and cannot be disabled or customized by users.
In the case of clusters with only a single host, this predicate causes retries to fail immediately, since there are no other hosts to select from.

### Request:

Please consider making `retry_host_predicate` configurable.
Alternatively, remove it from the default retry policy unless explicitly set by the user.

Thanks

**Comment by guydc** [comment]
> Another way to solve this could be to conditionally add this if the number of endpoints is more than 1

I think that this might not work well when using a single FQDN endpoint which resolves to multiple IP addresses (a pretty common use case). In these cases, the predicate is beneficial, but would not be auto-configured. 

Thoughts on adding a new knob like `useFailedHosts` to the retry config?

**Comment by arkodg** [comment]
sure +1 to `ignorePreviousEndpoints` or something similar

**Comment by guydc** [comment]
Hi Lin. 

I tried to reproduce this issue using the following config, where there's a single host. 

```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            host_rewrite_literal: www.envoyproxy.io
                            cluster: service_envoyproxy_io
                            retry_policy:
                              retry_on: retriable-status-codes
                              host_selection_retry_max_attempts: 5
                              num_retries: 10
                              retriable_status_codes: 200
                              retry_host_predicate:
                                - name: "envoy.retry_host_predicates.previous_hosts"
                                  typed_config:
                                    "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"

  clusters:
    - name: service_envoyproxy_io
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: service_envoyproxy_io
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 100.28.201.155 #www.envoyproxy.io
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: www.envoyproxy.io

```

A request leads to the following log, indicating that the retry limit was reached (URX).

```
[2025-04-23T23:00:23.839Z] "GET / HTTP/1.1" 200 URX 0 15986 1796 1769 "-" "curl/8.7.1" "e9c762fa-1df2-457f-ae32-aef8ea4f660d" "www.envoyproxy.io" "100.28.201.155:443"
```

Also, the stats indicate that the 10 retry attempts were made:

```
cluster.service_envoyproxy_io.upstream_rq_retry: 10
cluster.service_envoyproxy_io.upstream_rq_retry_backoff_exponential: 10
cluster.service_envoyproxy_io.upstream_rq_retry_backoff_ratelimited: 0
cluster.service_envoyproxy_io.upstream_rq_retry_limit_exceeded: 1
cluster.service_envoyproxy_io.upstream_rq_retry_overflow: 0
cluster.service_envoyproxy_io.upstream_rq_retry_success: 0
cluster.service_envoyproxy_io.upstream_rq_rx_reset: 0
cluster.service_envoyproxy_io.upstream_rq_timeout: 0
cluster.service_envoyproxy_io.upstream_rq_total: 11
```

Can you share an example that reproduces the problem?
