### ISSUE TITLE
Support listener health check modes

### ISSUE THREAD

**Issue by nareddyt** [envoyproxy/gateway#5699]
## Background

Envoy supports configuring the listener health check in 4 different modes: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#http-health-checking-filter

## Current Behavior

When a listener health endpoint is specified via [ClientTrafficPolicy.healthCheck](https://gateway.envoyproxy.io/docs/api/extension_types/#healthchecksettings), EG implicitly configures the health check listener in **No pass through** mode.

https://github.com/confluentinc/envoy-gateway/blob/d4aae99ef274c66927a4594fb20d2c877c48d3b8/internal/xds/translator/healthcheck.go#L71-L83

## Desired Behavior

ClientTrafficPolicy should expose knobs to configure the different modes.

Especially the **No pass through, computed from upstream cluster health** would be helpful. I am under the impression that this is a fairly standard configuration for production, and we plan to use this at Confluent.

Note that ClientTrafficPolicy would also need to support `cluster_min_healthy_percentages` xDS field in the [health check filter config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/health_check/v3/health_check.proto#envoy-v3-api-msg-extensions-filters-http-health-check-v3-healthcheck).

**Comment by nareddyt** [comment]
cc @muwaqar

**Comment by illrill** [comment]
Great feature to create a health endpoint that considers the combined / aggregated health of multiple upstream services. Useful when relying on an external tool for global load balancing / failover between multiple k8s clusters (e.g. Azure Front Door, Azure Traffic Manager).

API suggestion where each `backendRefs` item is translated into `cluster_min_healthy_percentages` objects

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: aggregate-health
spec:
  targetRefs:
    - kind: Gateway
      name: my-gateway
  healthCheck:
    path: /aggregate-health
    backendRefs:
      - kind: Service
        name: my-service1
        port: 8080
        minHealthyPercentage: 50
      - kind: Service
        name: my-service2
        port: 3000
        minHealthyPercentage: 100
```

**Comment by arkodg** [comment]
sure +1, interested to see what shape this takes

@illrill

**Comment by nareddyt** [comment]
> API suggestion where each backendRefs item is translated into cluster_min_healthy_percentages objects

Unfortunately `backendRefs` is used by a ton of other features, so I'm not sure if we can easily add `minHealthyPercentage` there. Maybe we can make a wrapper `BackendRefWithHealthPercentages` ?

https://gateway.envoyproxy.io/docs/api/extension_types/#backendref

**Comment by illrill** [comment]
Thinking about this... Correct me if I'm wrong but with the current CDS model we cannot use `backendRefs` (`BackendRefWithHealthPercentages`) directly here because upstream clusters are tied to a Route (cluster = route rule x backend ref). Wouldn't we rather need to select the Routes?

```
healthCheck:
  path: /example
  passTrough: false
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: my-app
      namespace: default
      sectionName: rule-1
```

... but even then we only get half way since we also need the backendRef to compute the full CDS cluster name, right?

---

If https://github.com/envoyproxy/gateway/issues/8265 comes to life then we could say that "advanced" listener health check modes can only be used on CTP that targets Route, then we could probably use some flavor of `backendRefs` (`BackendRefWithHealthPercentages`) directly here.

Alternatively if https://github.com/envoyproxy/gateway/issues/5307 comes to life then CDS cluster would be generated per **Service/Backend** (no more relation to Route) and we could also probably use `backendRefs` (`BackendRefWithHealthPercentages`) directly here

```
healthCheck:
  path: /example
  passTrough: false
  backendRefs:
    - kind: Service
      name: my-app
      namespace: default
      port: 80
      minHealthyPercentage: 40
```
