### ISSUE TITLE
How can I modify response_type to OIDC Authentication Request

### ISSUE THREAD

**Issue by char-iot** [envoyproxy/gateway#5744]
*Description*:
>Describe the issue.
according to https://github.com/envoyproxy/gateway/issues/5133 I could do following to add and modify request uri:
```
/authorize?
&code_challenge_method=S256
&response_type=code%20idtoken

```
I switched code_challenge_method back and forth from plain to S256, both show up in request Uri
but no matter what I change response_type to, "response_type=code" always shows up in request uri.

Any workaround to that?

>settings:
```yaml
  oidc:
    provider:
      issuer: "https://keycloak.home-domain.com/identity"
      authorizationEndpoint: "https://keycloak.home-domain.com/identity/connect/authorize?code_challenge_method=plain&response_type=codeblanc"
      tokenEndpoint: "https://keycloak.home-domain.com/identity/connect/token"
    clientID: "gw"
    clientSecret:
      name: "secret"
    redirectURL: "https://app.home-domain.com/auth"
    logoutPath: "/SignedOut"
```

**Comment by arkodg** [comment]
cc @zhaohuabing

**Comment by char-iot** [comment]
btw, proxy log:
```json
{
    ":authority": "app.home-domain.com",
    "bytes_received": 0,
    "bytes_sent": 0,
    "connection_termination_details": null,
    "downstream_local_address": "10.42.81.31:10443",
    "downstream_remote_address": "172.16.9.203:58285",
    "duration": 0,
    "method": "GET",
    "protocol": "HTTP/2",
    "requested_server_name": "app.home-domain.com",
    "response_code": 302,
    **"response_code_details": "oauth.missing_credentials",**
    "response_flags": "-",
    "route_name": "httproute/app-test-ns/eg-route-app-test/rule/0/match/0/app_home-domain_com",
    "start_time": "2025-04-16T22:32:06.553Z",
    "upstream_cluster": "httproute/app-test-ns/eg-route-app-test/rule/0",
    "upstream_host": null,
    "upstream_local_address": null,
    "upstream_transport_failure_reason": null,
    "user-agent": "insomnia/2023.5.8",
    "x-envoy-origin-path": "/",
    "x-envoy-upstream-service-time": null,
    "x-forwarded-for": "172.16.9.203",
    "x-request-id": "1d653123-6ea6-40e7-89a3-b08cfd465a7d"
}
```

**Comment by char-iot** [comment]
I also added response_mode=fragment to the authorizationEndpoint, also worked.

**Comment by zhaohuabing** [comment]
Hi @char-iot `code_challenge_method` is not allowed in the `authorizationEndpoint`. The he Envoy OAuth2 filter always set `code_challenge_method` to "S256" internally.  Since plain is less secure than S256, curious to know your use case for needing it?

**Comment by char-iot** [comment]
Hi @zhaohuabing no real use case. I'm actually trying to change response type to `response_type=code%20idtoken`, but it won't change or rather it always shows up in request uri `response_type=code`. 
As for `code_challenge_method ` it was just to prove if I change this, it shows up in request uri and it does. meanwhile, no matter what I change, response type stays at `response_type=code`.
As per my later comment, I also changed response mode per `response_mode=fragment` and it also worked and showed up in request uri.

![Image](https://github.com/user-attachments/assets/fc343e0e-cee7-4773-b5e5-db2264cf44b2)

**Comment by zhaohuabing** [comment]
Hi @char-iot `response_type` is also not allowed to be changed. The OAuth2 filter always set the `response_type` to `code` because it only support the Authorization Code Flow. The token `response_type` is not supported because it's not secure.

`response_mode=fragment` is used for implicit flow, I guess that's why you got this error message from the authorization server.

**Comment by char-iot** [comment]
Hello @zhaohuabing figured. Company's Authentication Server has been EoL many years ago 😰 , that's one of the reasons why I couldn't provide more details to my setup. I think other team spend last 3 y trying to migrate to keycloak or azureb2c 😅 . I'll host my own simple keycloak just to poc envoy gateway setups. btw, loved your london talk where you polled and a bunch of test setups and just 3 in production 😂  a side question:
- is there anyway to make exceptions for oidc/ security policies? like for /health or some subpath? or would I have to make another route without securitypolicy just for that?

**Comment by char-iot** [comment]
token is not secure but they do still consider `code id_token` to be secure.

> Clients SHOULD instead use the response type code (i.e., authorization code grant type) as specified in [Section 2.1.1](https://datatracker.ietf.org/doc/html/rfc9700#ac) or any other response type that causes the authorization server to issue access tokens in the token response, such as the code id_token response type. This allows the authorization server to detect replay attempts by attackers and generally reduces the attack surface since access tokens are not exposed in URLs. It also allows the authorization server to sender-constrain the issued tokens (see [Section 2.2](https://datatracker.ietf.org/doc/html/rfc9700#token_replay_prevention)).

https://datatracker.ietf.org/doc/html/rfc9700#section-2.1.2

**Comment by zhaohuabing** [comment]
> is there anyway to make exceptions for oidc/ security policies? like for /health or some subpath? or would I have to make another route without securitypolicy just for that?

Yes, to skip a specific path or subpath, you'll need a separate route without SecurityPolicy.

> token is not secure but they do still consider code id_token to be secure.

code is the only supported flow in the OAuth2 filter. Furthermore, users shouldn't need to worry which flow EG uses under the hood to obtain tokens.

**Comment by char-iot** [comment]
@zhaohuabing thank you so much. after a few debugging session, all the steps worked except last when envoy send the state in to exchange for access token and refresh token, it fails. In trace logs I dig out some how it sends the request without the scopes, offline_access and AppID. Where should I look further?

**Comment by zhaohuabing** [comment]
E2E test succeed, so it should work. If you need additional scopes, your can figure via the `scopes` filed in the SecurityPolicy.

Have you noticed anything different between your setup and the [EG OIDC docs](https://gateway.envoyproxy.io/latest/tasks/security/oidc/)?

**Comment by char-iot** [comment]
I did
```yaml
spec:
    oidc:
      clientID: 00000000-0000-0000-0000-000000000000
      clientSecret:
        group: ''
        kind: Secret
        name: app-secrets
      cookieDomain: testapp.company.com
      logoutPath: /logout
      provider:
        authorizationEndpoint: https://company1.b2clogin.com/company1.onmicrosoft.com/b2c_policy/oauth2/v2.0/authorize
        issuer: https://company1.b2clogin.com/00000000-0000-0000-0000-000000000001/v2.0/
        tokenEndpoint:  https://company1.b2clogin.com/company1.onmicrosoft.com/b2c_policy/oauth2/v2.0/token
      redirectURL: https://testapp.company.com/auth
      scopes:
        - offline_access
        - https://company1.onmicrosoft.com/00000000-0000-0000-0000-000000000002/refimasterdata
    targetRefs:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: eg-route-testapp
```

**Comment by char-iot** [comment]
@zhaohuabing thanks! it works now.
I tried to update from 1.3.2 to 1.3.3 and then 1.4.0 and deleted the helm release and all it's CRDs. reinstalled with 1.4.0 then it started working, even when I downgrade to 1.3.3 and 1.3.2 (I started with 1.3.2 so only tested so far.) So I suspect some old CRD wasn't updated properly.
Also I realized I should have open a Q&A under Discussions instead of an issue. Apologies.
I did a clean up and reinstall of all resources, oidc user login still working, I'm getting tokens in cookies:

![Image](https://github.com/user-attachments/assets/b038f14c-ad06-4d8d-9431-09f2771ebfd6)

I copied the value of AccessToken to insomnia (postman like tool), did a GET events. I should get a json object but instead I got a 302 redirect to IDP with reason `"response_code_details":"oauth.missing_credentials"` then I realized bearer token is being verified via jwt. So I added jwt section to securitypolicy spec acorrding [EG JWT docs](https://gateway.envoyproxy.io/docs/tasks/security/jwt-authentication/#use-a-local-jwks-to-authenticate-requests) and https://github.com/envoyproxy/gateway/discussions/2425#discussioncomment-8141456:
```
  jwt:
    providers:
    - name: company1
      issuer: "https://company1.b2clogin.com/00000000-0000-0000-0000-000000000003/v2.0/"
      audiences: ["00000000-0000-0000-0000-000000000000"]
      localJWKS:
        type: ValueRef
        valueRef:
          group: ""
          kind: ConfigMap
          name: jwt-local-jwks
```
But the response is the same and the log also shows it got the correct `'authorization', 'Bearer `

![Image](https://github.com/user-attachments/assets/12827cf4-443b-4d7a-8e9f-c7572abf148e)

What am I missing here?
