### ISSUE TITLE
Envoy deployment replicas are being overwritten constantly

### ISSUE THREAD

**Issue by Ido-Itz** [envoyproxy/gateway#5751]
When EnvoyGateway creates an Envoy deployment, it sets an initial value for the deployment replicas (configured via `spec.provider.kubernetes.envoyDeployment.replicas` on the `EnvoyProxy` resource).

When using HPA, it will dynamically change the replica count based on cluster conditions.

Observed behavior:
1. Set the initial replica count to X
2. During runtime, the HPA decides the desired replica count should be Y
3. The HPA changes the replicas on the deployment spec to Y
4. Envoy Gateway reconciles the replicas back to the original value X
5. Repeat (3) and (4) indefinitely

This causes Envoy pods to be constantly created and deleted, in some cases causing the cluster to autoscale nodes up and down as well.

Ideally, EnvoyGateway should not reconcile the replica count on the Envoy deployment after it was created, to allow the HPA to properly manage it.

**Comment by Ido-Itz** [comment]
The correct behavior is also referenced here: https://github.com/envoyproxy/gateway/blob/main/api/v1alpha1/envoyproxy_types.go#L336

> ```go
> // EnvoyHpa defines the Horizontal Pod Autoscaler settings for Envoy Proxy Deployment.
> // Once the HPA is being set, Replicas field from EnvoyDeployment will be ignored.
> //
> // +optional
> EnvoyHpa *KubernetesHorizontalPodAutoscalerSpec `json:"envoyHpa,omitempty"`
> ```

**Comment by arkodg** [comment]
@Ido-Itz @YoniRomm is not recommended to set replica and hpa, since those fields are consumed by different controllers
https://github.com/kubernetes/kubernetes/issues/25238

#5021 removes the strong opinion of resetting replica if hpa is set

I missed updating the API docs https://github.com/envoyproxy/gateway/issues/5751#issuecomment-2812228254 , will raise a PR to fix this

**Comment by YoniRomm** [comment]
@arkodg wouldn’t it better to add a webhook validation that throws an error if both fields are configured ? You want to make the user experience better.

**Comment by arkodg** [comment]
the core question that needs to be answered here is - is there a use case for the user to set both replica and hpa, if there isnt why does k8s allow it

**Comment by lejlapri1** [comment]
Hey! I see that a fix was merged into 1.3.0-rc.1, but I am using 1.4.2 and seeing this behavior. I have hpa enabled and configured, and did not configure any value for replicas. My values.yaml just looks like:
```
hpa:
  enabled: true
  minReplicas: 4
  maxReplicas: 30
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
```

**Comment by arkodg** [comment]
@lejlapri1 can you share the deployment spec of the generated resource

**Comment by lejlapri1** [comment]
@arkodg here it is!

```yaml
# Source: gateway-helm/templates/envoy-gateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-gateway
  namespace: 'envoy-gateway-system'
  labels:
    control-plane: envoy-gateway
    helm.sh/chart: gateway-helm-1.4.2
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/instance: envoy-gateway
    app.kubernetes.io/version: "v1.4.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: envoy-gateway
      app.kubernetes.io/name: gateway-helm
      app.kubernetes.io/instance: envoy-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "19001"
        prometheus.io/scrape: "true"
      labels:
        control-plane: envoy-gateway
        app.kubernetes.io/name: gateway-helm
        app.kubernetes.io/instance: envoy-gateway
    spec:
      containers:
      - args:
        - server
        - --config-path=/config/envoy-gateway.yaml
        env:
        - name: ENVOY_GATEWAY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: cluster.local
        image: docker.io/envoyproxy/gateway:v1.4.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: envoy-gateway
        ports:
        - containerPort: 18000
          name: grpc
        - containerPort: 18001
          name: ratelimit
        - containerPort: 18002
          name: wasm
        - containerPort: 19001
          name: metrics
        - name: webhook
          containerPort: 9443
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /config
          name: envoy-gateway-config
          readOnly: true
        - mountPath: /certs
          name: certs
          readOnly: true
      imagePullSecrets: []
      serviceAccountName: envoy-gateway
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          defaultMode: 420
          name: envoy-gateway-config
        name: envoy-gateway-config
      - name: certs
        secret:
          secretName: envoy-gateway
```
