### ISSUE TITLE
EnvoyPatchPolicy + Merged Gateways - docs perhaps need improvement ?

### ISSUE THREAD

**Issue by Antvirf** [envoyproxy/gateway#5768]
This came up when I was trying to find a way to [disable timeouts on `GRPCRoute` objects, to support long-lived GRPC streams](https://github.com/envoyproxy/gateway/issues/5446). `EnvoyPatchPolicy` objects offer a way to directly patch xDS resources, so they looked like a potential short-term solution until this feature is added in by Envoy Gateway.

However, in an environment with **merged** Gateways, this specific use case does not actually work with `EnvoyPatchPolicies`. This is because:

- To make a patch work for this use case, you'll need to point it at a `type.googleapis.com/envoy.config.route.v3.RouteConfiguration` xDS resource
- In an environment with merged Gateways, **listeners of the same protocol and port get grouped up together under one `RouteConfiguration`**
- As a result, if your environment has e.g. `10` Gateways, the `RouteConfiguration` xDS resource will only be created for the very first Gateway, and all others become `virtual_host` entries underneath it.
- As a result, in order to work,the `EnvoyPatchPolicy` needs to target a `RouteConfiguration` that in fact belongs to another `Gateway` object - which could change / get renamed / get deleted at any time.

Granted, `EnvoyPatchPolicy` comes with a set of caveats that the docs include, and its purpose as a temporary workaround-tool is well understood. I do still think it would be really great to have the docs updated to be more specific, especially if there are (more of?) such cases where the way Envoy Gateway is configured can make patches unusable.

Unfortunately I don't know the interiors of Envoy well enough to say whether that's the case. I'd be happy to update the docs on this specific scenario, but I feel like this area could use the eyes and 🧠 of someone more knowledgeable on the topic 😄

**Comment by Ninir** [comment]
Hey @Antvirf, I've been in your exact spot a few days ago. I've been switching to using BackendTrafficPolicy targeting that route, which allowed us to not only set the timeout, but idle_timeout, retries, retry conditions, etc.

<img width="811" alt="Image" src="https://github.com/user-attachments/assets/63f298ac-1675-45cf-83da-7c2470cf04d8" />

Not sure if that can help in your case, but yet, your point still stands!

**Comment by Antvirf** [comment]
quick draft @arkodg https://github.com/envoyproxy/gateway/pull/5822

**Comment by tim64195419** [comment]
I encountered a similar issue. Routing to the embedding model through the Envoy Gateway on k8s always results in an idle_timeout problem.

I cannot find a way to set a global stream_idle_timeout from the gateway to the service model. The default 300s timeout will cause the connection to be cut off due to stream idleness.

The current patch I found involves modifying the configuration of a specific virtual_host through EnvoyPatchPolicy, and I even have to specify the correct index for it to take effect.

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
 name: vllm-idle-timeout
 namespace: vllm
spec:
 type: JSONPatch
 targetRef:
   group: gateway.networking.k8s.io
   kind: GatewayClass
   name: vllm-envoy-gateway
 jsonPatches:
   - name: "vllm/vllm-envoy-gateway/http"
     type: "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
     operation:
       op: add
       path: /virtual_hosts/0/routes/1/route/idle_timeout
       value: "500s"
   - name: "vllm/vllm-envoy-gateway/https"
     type: "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
     operation:
       op: add
       path: /virtual_hosts/0/routes/1/route/idle_timeout
       value: "500s"
```
