### ISSUE TITLE
External authorization service unable to access cookies when configured with SecurityPolicy

### ISSUE THREAD

**Issue by xww9** [envoyproxy/gateway#5789]
*Description*:
I use ory/oathkeeper as an external authorization, configured as follows. However, the logs show that oathkeeper cannot parse cookies from HTTP requests that pass through the envoy gateway. If it is directly with oathkeeper, it can retrieve the cookies. Therefore, I suspect that incorrect envoy configuration might be causing this issue.

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: magik-platform
  namespace: magik
status:
  parents:
    - conditions:
        - lastTransitionTime: '2025-04-21T12:07:58Z'
          message: Route is accepted
          observedGeneration: 4
          reason: Accepted
          status: 'True'
          type: Accepted
        - lastTransitionTime: '2025-04-21T12:07:58Z'
          message: Resolved all the Object references for the Route
          observedGeneration: 4
          reason: ResolvedRefs
          status: 'True'
          type: ResolvedRefs
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: magik-ai
        namespace: envoy-gateway-system
spec:
  hostnames:
    - web-backend.magikcloud.cn
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: magik-ai
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: user-manager
          port: 80
          weight: 1
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /
              type: ReplacePrefixMatch
      matches:
        - path:
            type: PathPrefix
            value: /user/
```
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oathkeeper-auth-policy
  namespace: magik
status:
  ancestors:
    - ancestorRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: magik-ai
        namespace: envoy-gateway-system
      conditions:
        - lastTransitionTime: '2025-04-20T11:45:47Z'
          message: Policy has been accepted.
          reason: Accepted
          status: 'True'
          type: Accepted
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
spec:
  extAuth:
    http:
      backendRefs:
        - group: ''
          kind: Service
          name: oathkeeper-api
          namespace: ory
          port: 4456
      headersToBackend:
        - Authorization
        - X-User-ID
        - Host
        - X-Forwarded-Uri
        - X-Forwarded-Method
        - Cookie
      path: /decisions
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: magik-platform
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
