### ISSUE TITLE
Failover isn't working in the latest build

### ISSUE THREAD

**Issue by MaYuan-02** [envoyproxy/gateway#5813]
Failover in this [doc](https://gateway.envoyproxy.io/latest/tasks/traffic/failover/) cannot work as expected.
After simulating an active app failure, Envoy continues sending requests to it

In the released v1.3.0, I observed that failover depends on a "BIG"(rule-level) cluster, with weights for different backends within a rule set in the endpoints.
This implementation make add-header filter at the backend level defective. 
I notice this issue has been fixed in https://github.com/envoyproxy/gateway/pull/3246. But this disrupts failover.
When I enable backend-level filter, the rule-level cluster is absent, causing the failover to not work in this scenario.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by MaYuan-02** [comment]
The current failover requires integration with the health check feature and does not allow users to specify target services for failover, which can be somewhat confusing. Can we consider making some modifications to this feature's API?

I have a preliminary idea:
Failover is actually based on the endpoint's priority. Could we support referencing multiple services in the Envoy Gateway backend, allowing users to set priority and overprovisioning factors for each service?

**Comment by arkodg** [comment]
thanks for flagging this
when backend specific filters are set, internally weighted clusters is used per backendRef, and i dont think there's any way to set priority for a cluster atm
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-weightedcluster

**Comment by arkodg** [comment]
cc @mathetake @yuzisun this affects Envoy AI Gateway features that may rely on backend specific filters in the future

one way to solve this could be to add a `priority` field within weighted clusters in upstream envoy proxy

**Comment by MaYuan-02** [comment]
I'm considering whether we could allow users to set a failover target, not just the other backend within the same rule. By doing this, we could merge the failover cluster endpoints with the normal endpoints into a single large cluster, setting the failover endpoints to a lower priority.

We could implement this using HTTPRouteFilter or BackendTrafficPolicy.
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
      - name: svc-1
        port: 8000
        weight: 1
        filters:
        - type: ExtensionRef
          extensionRef:
            group: xxx
            kind: HTTPRouteFilter
            name: test-failover
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: fail-over
spec:
  failover: 
    bakcendRef:
      xx: xx
    overprovisioning: x
```
