### ISSUE TITLE
Support configuring the service for Gateway

### ISSUE THREAD

**Issue by dimm0** [envoyproxy/gateway#5825]
*Description*:

Is it possible to change the externalTrafficPolicy to Cluster in LoadBalancer service, or the service type to ClusterIP?

I see https://github.com/envoyproxy/gateway/pull/2432 for EnvoyService, but nothing for Gateway.

It's also suggested in https://gateway-api.sigs.k8s.io/geps/gep-1762/?h=externaltrafficpolicy#customizations.

**Comment by illrill** [comment]
I think this clarification is what you may be looking for:

- The _Envoy Gateway_ is just the "controller" component that's installed for example via the Helm chart, and it comes with a ClusterIP service.

- The _Envoy Proxy_ is the actual "traffic handler" or "data plane" component (spawned and managed by Envoy Gateway) and you can control how its Deployment / Service / HPA / PDB is generated via the `EnvoyProxy` CR.

https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/ https://gateway.envoyproxy.io/docs/api/extension_types/#envoyproxy

```yaml
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      # Configure the Envoy Proxy service to be cluster-internal
      envoyService:
        type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-default
  namespace: default
spec:
  gatewayClassName: envoy-gateway-default
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: envoy-proxy-config
  [...]
```

**Comment by dimm0** [comment]
I'm trying to use the AIGateway, and there's no EnvoyProxy object created at all. I might be still asking the wrong question.

What I have currently is:

```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-ai-gateway-nrp
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-ai-gateway-nrp
  namespace: nrp-llm
spec:
  gatewayClassName: envoy-ai-gateway-nrp
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-nrp
  namespace: nrp-llm
spec:
  schema:
    name: OpenAI
  targetRefs:
    - name: envoy-ai-gateway-nrp
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: gemma3
      backendRefs:
        - name: envoy-ai-gateway-nrp-gemma3
```
