### ISSUE TITLE
Admin not working in standalone mode

### ISSUE THREAD

**Issue by rdavison** [envoyproxy/gateway#5856]
*Description*:

I set up a standalone deployment using containers by following the instructions at https://gateway.envoyproxy.io/docs/tasks/operations/standalone-deployment-mode/ 

Then I tried exposing port 19000 to get access to the admin interface, but it doesn't seem to work. See https://envoyproxy.slack.com/archives/C03E6NHLESV/p1745945411939359 for more info

>What issue is being seen? Describe what should be happening instead of
the bug, for example: The expected value isn't returned, etc.

```
$ curl --verbose http://0.0.0.0:19000/
*   Trying 0.0.0.0:19000...
* Connected to 0.0.0.0 (0.0.0.0) port 19000
> GET / HTTP/1.1
> Host: 0.0.0.0:19000
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

```yaml
# docker-compose.yaml

services:
  envoy-gateway:
    image: envoyproxy/gateway:v1.3.2
    ports:
      - 8888:8888
      - 19000:19000
    volumes:
      - "./volumes/envoy-gateway:/tmp/envoy-gateway"
    command:
      - "server"
      - "--config-path"
      - "/tmp/envoy-gateway/standalone.yaml"
```

```yaml
# standalone.conf

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyGateway
gateway:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
provider:
  type: Custom
  custom:
    resource:
      type: File
      file:
        paths: ["/tmp/envoy-gateway/config"]
    infrastructure:
      type: Host
      host: {}
logging:
  level:
    default: debug
extensionApis:
  enableBackend: true
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

See above

*Logs*:
>Include the access logs and the Envoy logs.

No logs printed

**Comment by arkodg** [comment]
the port is set to 0, which makes listener port selection dynamic 
https://github.com/envoyproxy/gateway/blob/c55b814d1326a046e664ba60b1e058c14f21cb40/internal/infrastructure/host/proxy_infra.go#L73
cc @shawnh2

**Comment by shawnh2** [comment]
<img width="1060" alt="Image" src="https://github.com/user-attachments/assets/95736964-2fb1-43a2-950f-7d66ae9f70fd" />

yes, you can find its admin address in the output log

**Comment by arkodg** [comment]
@shawnh2 any reason why it's not fixed ?

**Comment by rdavison** [comment]
Correct me if I'm wrong, but afaict the problem isn't that the admin mode doesn't work, but that I can't specify a stable port number to it. This isn't really a problem in k8s because you can easily set up port forwarding, but it's not as straightforward if you're trying to launch standalone mode through docker, since you have to know the port up front, unless you want to open a whole range of ports.

**Comment by kivra-ahmwar** [comment]
I deployed envoy gateway in kubernetes with helm and i the pods don't even listen to any port that points to admin. Im running version 1.3.2. https://gateway.envoyproxy.io/v1.3/troubleshooting/envoy-proxy-admin-interface/ These docs are not correct. These are the only ports the pods listen to:
```
        ports:
        - containerPort: 18000
          name: grpc
          protocol: TCP
        - containerPort: 18001
          name: ratelimit
          protocol: TCP
        - containerPort: 18002
          name: wasm
          protocol: TCP
        - containerPort: 19001
          name: metrics
          protocol: TCP

```
