### ISSUE TITLE
OpenTelemetry tracing to Tempo fails using backendRef, works using host/port (HTTP used instead of GRPC?)

### ISSUE THREAD

**Issue by rtomadpg** [envoyproxy/gateway#5887]
*Description*:

Attempting to get OpenTelemetry tracing to Tempo working, I noticed following EnvoyProxy configuration works:

```
...
  telemetry:
    tracing:
      samplingRate: 100
      provider:
        type: OpenTelemetry
        host: tempo-distributor.tempo.svc.cluster.local.
        port: 4317
      customTags:
        ...
```

... but this does NOT work:

```
...
  telemetry:
    tracing:
      samplingRate: 100
      provider:
        type: OpenTelemetry
        backendRefs:
          - name: tempo-distributor
            namespace: tempo
            port: 4317
            group: ''
            kind: Service
      customTags:
        ...
```

"It works" means:
- Tempo receives the data. Traces are visible via Tempo API or Grafana.
- HTTP 200s: `envoy_cluster_upstream_rq{envoy_cluster_name="tracing",envoy_response_code="200"}` > 0

"It does not work" means:
- Tempo receives data, but tcpdump shows connection resets (by Tempo). Nothing in Grafana
- HTTP 502s: `envoy_cluster_upstream_rq{envoy_cluster_name="tracing",envoy_response_code="502"}` > 0

*Repro steps*:

- Install Tempo (or another OTEL collector)
- Configure a Envoy Proxy with OTEL tracing, using a backendRef to Tempo
- Check Tempo

*Environment*:
- AWS EKS 1.32
- Gateway v1.3.2, installed via Helm chart
- Using Envoy Proxy v1.33.1
- Envoy Proxy with aforementioned config snippet

*Logs*:

I've compared Envoy config_dump output between tracing-to-service-hostname vs tracing-to-backend. Here are the differences relevant to tracing:

1. when it works, the provider has `grpc_service.envoy_grpc.authority`:

<img width="1492" alt="Image" src="https://github.com/user-attachments/assets/2220dfdf-fb9a-4688-9400-e06773f1280a" />

2. the socket address is different: the service hostname vs the service endpoint:

<img width="1555" alt="Image" src="https://github.com/user-attachments/assets/ecf31927-b5fc-4348-94ec-e69639922926" />

And here is a screenshot of the tcpdump showing a HTTP POST is used to the GRPC port 4317:

<img width="1586" alt="Image" src="https://github.com/user-attachments/assets/111a747c-e715-47d6-9205-4552bb9812da" />

And here are the response codes for the "tracing" cluster during my tests, showing 502 codes with the backendRef, and 200 codes with the hostport:

<img width="1917" alt="Image" src="https://github.com/user-attachments/assets/0e288a73-1e57-4b43-9c1d-7324c7e851a3" />

**Comment by fallard84** [comment]
I'm encountering the same issue, and using the `provider.host` and `provider.port` fixes the issue for me.

**Comment by arkodg** [comment]
cc @zirain

**Comment by zirain** [comment]
can you share the svc yaml? you may need set `appProtocol` on the port.

**Comment by rtomadpg** [comment]
Hi @zirain, thank you for looking into this.

We're using the official Tempo Helm chart https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed 
Looking in the distributor Service template https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/distributor/service-distributor.yaml I see:

```
    - name: grpc-distributor-otlp
      port: 4317
      protocol: TCP
      targetPort: grpc-otlp
      {{- if .Values.distributor.appProtocol.grpc }}
      appProtocol: {{ .Values.distributor.appProtocol.grpc }}
      {{- end }}
```

The values file defaults this value to `null`:
```
distributor:
  ...
  appProtocol:
    # -- Set the optional grpc service protocol. Ex: "grpc", "http2" or "https"
    grpc: null
```

We do not override this default, so - as you suspected - the deploy Service does not have `appProtocol` set.


Let me test what happens if I set `distributor.appProtocol.grpc: grpc`
