### ISSUE TITLE
Issue with validation with incorrect header values

### ISSUE THREAD

**Issue by DerrickMartinez** [envoyproxy/gateway#5901]
While migrating from Gloo to Envoy Gateway I discovered that a single malformed header can stall the controller for every other host on the same Gateway.
If a ResponseHeaderModifier filter sets a header using the YAML pipe (|), the resulting multi-line value slips through validation, but afterwards no further config changes are reconciled. New routes/hosts return 404 because the Gateway is stuck on the bad object.

Envoy Gateway: 1.3.2
Kubernetes: v1.31.7

*Steps to reproduce:*
```
rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        set:
        - name: Content-Security-Policy
          value: |
            default-src 'none'; connect-src https://*.example.com
```

1. Confirm the route shows Accepted: true.
2. Add another HTTPRoute (or edit the same one) to introduce a new host.
3. Curl the new host → 404.
