### ISSUE TITLE
Issue with gateway-helm chart in version 1.4.0-rc.2

### ISSUE THREAD

**Issue by hansselvig** [envoyproxy/gateway#5903]
*Description*:
There is a problem resolving `.Values.topologyInjector.enabled` in _rbac.tpl file due to how it is being referenced in envoy-gateway-rbac.yaml.
On line 22 it is passing the range context to the template instead of the root context, which in turns leads to a problem resolving `.Values.topologyInjector.enabled` in _rbac.tpl.

*Repro steps*:
Example config:

```
config:
  envoyGateway:
    provider:
      kubernetes:
        watch:
          type: Namespaces
          namespaces:
            - namespace1
            - namespace2
```

`helm template oci://docker.io/envoyproxy/gateway-helm --version 1.3.2 -f example.yaml`
`helm template oci://docker.io/envoyproxy/gateway-helm --version 1.4.0-rc.2 -f example.yaml`

With 1.3.2, the above works well, but with 1.4.0-rc.2, it produces this error:
`Error: template: gateway-helm/templates/envoy-gateway-rbac.yaml:22:3: executing "gateway-helm/templates/envoy-gateway-rbac.yaml" at <include "eg.rbac.namespaced" .>: error calling include: template: gateway-helm/templates/_rbac.tpl:12:14: executing "eg.rbac.namespaced" at <.Values.topologyInjector.enabled>: can't evaluate field Values in type string`

*Environment*:
version 1.4.0-rc.2

Proposed fix in https://github.com/envoyproxy/gateway/pull/5902
