### ISSUE TITLE
gamma support

### ISSUE THREAD

**Issue by christiancadieux** [envoyproxy/gateway#5928]
*Description*:
> Does envoy-gateway support Routes where the parentRefs refere to a kubernetes service - 
If not - can it be supported
example from a cilium-gateway httpRoute:

```
apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    name: nginx-route-gamma
  spec:
    parentRefs:
    - group: ""
      kind: Service
      name: gamma-nginx
      port: 80
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
