### ISSUE TITLE
Introduce support for section-specific annotations in HTTPRoute that propagate to specific route rule XDS metadata

### ISSUE THREAD

**Issue by Tharsanan1** [envoyproxy/gateway#5960]
### Description
Currently using httproute annotations i can add static xds metadata. But when we need to add specific static metadata to a specific xds route rule this is not supported. for this I m proposing the following annotation structure. 

`gateway.envoyproxy.io/rule.<rule-index>.match.<match-index>.<key>: <value>`

- rule.i: Targets the i-th rule in .spec.rules.
- match.j: Targets the j-th match entry in .spec.rules[i].matches.
- key: The metadata key you want applied in that scope.

#### Example

```
metadata:
  annotations:
    gateway.envoyproxy.io/not-rule-specific: value
    gateway.envoyproxy.io/rule.0.match.0.logging-level: debug
    gateway.envoyproxy.io/rule.1.match.1.logging-level: warn
```

#### Resulting XDS Metadata Translation:

```
name: httproute/namespace/myroute/rule/0/match/0/*
metadata:
  filter_metadata:
    envoy-gateway:
      resources:
        - kind: HTTPRoute
          name: myroute
          namespace: myns
          annotations:
            logging-level: debug
            not-rule-specific: value
...
...
name: httproute/namespace/myroute/rule/1/match/1/*
metadata:
  filter_metadata:
    envoy-gateway:
      resources:
        - kind: HTTPRoute
          name: myroute
          namespace: myns
          annotations:
            logging-level: warn
            not-rule-specific: value
```

Shall I implement this improvement and send a PR?

 This kind of improvement is marked as future enhancement in the doc. [link](https://gateway.envoyproxy.io/contributions/design/metadata/#:~:text=Supporting%20section%2Dspecific%20metadata%2C%20e.g.%20HTTPRoute%20Metadata%20annotations%20that%20are%20propagated%20only%20to%20a%20specific%20route%20rule%20XDS%20metadata.)
