### ISSUE TITLE
TLS Termination Fails

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#600]
As part of https://github.com/envoyproxy/gateway/pull/542, simple TLS termination was working but no longer does.

[Envoy Config Dump](https://gist.githubusercontent.com/danehans/04a08855ae36c168c108da27b3507ce8/raw/757a2a440f99357ab9483f88d39e8265399012e6/envoy_tls_term_cfg_dump.log)

I tried updating the HTTPS listener to use hostname `secure.example.com` but no luck. Note that I regenerated the TLS assets with `secure.example.com` instead of `www.example.com`.

### Gateway:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  listeners:
  - name: http
    protocol: HTTP
    port: 8080
  - name: https-foo
    protocol: HTTPS
    port: 8443
    hostname: "secure.example.com"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: example-cert
        namespace: envoy-gateway-system
```
