### ISSUE TITLE
Allow custom image repository for Envoy Proxy image

### ISSUE THREAD

**Issue by rtomadpg** [envoyproxy/gateway#6066]
*Description*:

We're running a caching AWS ECR for all 3rd party images and would like Envoy Proxy to pull its image from it, without having to pin the image tag/version, and let Envoy Gateway decide on the tag/version. 

Currently it's possible to configure the Envoy Proxy image, but only as a single repository + tag combination.
The "KubernetesContainerSpec" has an "image" string parameter, which we set like:

```
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          image: 1234.dkr.ecr.eu-west-1.amazonaws.com/dockerhub/envoyproxy/envoy:v1.33.1
```

As you can see, the "image" must include the tag. There is no separate fields for repository and tag. 

Being able to specify repository and tag separately, is a common pattern.

It would be great if following Envoy Proxy configuration would be supported:

```
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          image:
            repository: 1234.dkr.ecr.eu-west-1.amazonaws.com/dockerhub/envoyproxy/envoy
            tag: v1.33.1
```

**Comment by sudiptob2** [comment]
Interested in working on this issue. Here are a couple of thoughts about the implementation. Let me know your opinion.

Currently, the image field is a simple string, and changing its type to a structured object (like `image.repository` and `image.tag`) would be a breaking change for existing users. To keep this backward-compatible, I think we can consider two options here.

**Option 1: Add a separate optional tag field**
Introduce a new tag field alongside the existing image string:
```yaml
container:
  image: envoyproxy/envoy
  tag: v1.33.1
```
If `tag` is provided, it will be appended to the `image` string. If the image already contains a tag, it will become a double-tag though `(e.g., image: img:base, tag: latest → img:base:latest).`

Users will be responsible for ensuring that the resulting image string is valid.

**Option 2: Introduce a new imageSpec block**
Use a slightly different wording for the new struct (`imageSpec` instead of `image`)

```yaml
container:
  image: # fallback
  imageSpec:
    repository: 1234.dkr.ecr.eu-west-1.amazonaws.com/dockerhub/envoyproxy/envoy
    tag: v1.33.1
```
This aligns with the standard patterns used in other projects. Parsing logic would prioritize `imageSpec` if present. The existing `image` field remains supported, but we could mark it as deprecated in future versions.
