### ISSUE TITLE
%PATH% in accessLog causes Not supported field in StreamInfo: PATH

### ISSUE THREAD

**Issue by mohammad5305** [envoyproxy/gateway#6094]
*Description*:
i have the following accessLog format
```
%DOWNSTREAM_DIRECT_REMOTE_ADDRESS_WITHOUT_PORT% Usr: [] Time: [%START_TIME_LOCAL%] Req: "%REQ(:method)% %PATH(WG:PATH)% %PROTOCOL%" UA: %REQ(USER-AGENT)% St: %RESPONSE_CODE% RL/BB/RT: %BYTES_RECEIVED% %DOWNSTREAM_WIRE_BYTES_SENT% %DURATION% Ch: - UPC/UPH/UPR: %COMMON_DURATION(US_CX_BEG:US_CX_END:ms)% - %COMMON_DURATION(US_RX_BEG:US_RX_END:ms)% %REQ(X-Real-IP)% %REQ(X-Forwarded-For)% %REQ(:scheme)% REF: "%REQ(Referer)%" UPS: %UPSTREAM_HOST% DNS: %REQ(HOST)%'
```

when using %PATH% in log format it my envoy proxy gets rejected with this error:
```
2025-05-15T23:59:25.109Z        ERROR   xds-server      cache/snapshotcache.go:344      Envoy rejected the last update with code 13 and message Error adding/updating listener(s) envoy-gateway-system/envoy-gateway/http: Not supported field in StreamInfo: PATH
```

but if i use %REQ(:path)% it works fine.

my gateway manifest:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      name: edge-proxy-config
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
```
