### ISSUE TITLE
gateway-crds-helm v1.4.0 install fails – rendered release exceeds 1 MiB Secret size limit

### ISSUE THREAD

**Issue by zackijack** [envoyproxy/gateway#6105]
*Description*:
When installing gateway-crds-helm v1.4.0 we hit:
```
Error: create: failed to create: Secret “sh.helm.release.v1.eg-crds.v1” is invalid: data: Too long: must have at most 1048576 bytes
```
Helm stores the whole rendered release in a single Secret. Kubernetes hard-limits any Secret to 1 MiB (1 048 576 bytes). Because this chart bundles ~40 Gateway-API CRDs, the compressed release record exceeds that limit and the API server rejects the Secret. 

Expected behaviour: the chart should install cleanly, or the docs should tell users to apply the CRDs manually (`helm template | kubectl apply`).

*Repro steps*:

Install the gateway-crds-helm v1.4.0 chart with Helm (any install method). The install fails with the Secret size error above.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:

- gateway-crds-helm chart: v1.4.0
- helm: v3.17.3
- kubernetes: v1.31.6-gke

*Logs*:
```
Error: create: failed to create: Secret “sh.helm.release.v1.eg-crds.v1” is invalid: data: Too long: must have at most 1048576 bytes
```

**Comment by arkodg** [comment]
this is a known issue https://github.com/envoyproxy/gateway/pull/5616#issuecomment-2840245509

https://github.com/envoyproxy/gateway/issues/4001#issuecomment-2367361128

https://github.com/envoyproxy/gateway/issues/5940 will hopefully explain this limitation and add a recommendation that involves `helm template` instead

**Comment by aukevanleeuwen** [comment]
For those people that are using Terraform and want to install the CRDs separately from the EG implementation, this is a work around:

```hcl
# Generate the CRD manifests
data "helm_template" "envoy_gateway_crds" {
  chart   = "oci://docker.io/envoyproxy/gateway-crds-helm"
  name    = "envoy-gateway-crds-helm"
  version = local.envoy_gateway_version

  values = [
    yamlencode({
      crds = {
        gatewayAPI = {
          enabled = true
        }
        envoyGateway = {
          enabled = true
        }
      }
    })
  ]
}

# The above 'helm template' can generate multi-document yaml files, we
# need to split those, because kubectl_manifest will only apply the first
# document.
data "kubectl_file_documents" "envoy_gateway_crds" {
  for_each = data.helm_template.envoy_gateway_crds.manifests

  content = each.value
}

resource "kubectl_manifest" "envoy_gateway_crds" {
  # Form a flattened map of every yaml document (not file!) with a
  # unique key so that we can apply them one by one.
  for_each = merge([
    for key, data in data.kubectl_file_documents.envoy_gateway_crds : {
      for idx, doc in data.documents : "${key}-${idx}.yaml}" => doc
    }
  ]...)

  # Note: this is required, because otherwise `kubectl apply` would add
  # a kubectl.kubernetes.io/last-applied-configuration annotation that
  # exceeds the annotation max-size limit.
  # Server-side-apply is considered good practice anyway.
  server_side_apply = true
  yaml_body         = each.value
}
```



**Note**: I'm using [this provider](https://github.com/gavinbunney/terraform-provider-kubectl) for the `kubectl_manifest` resource, but it probably works with the Hashicorp Kubernetes one as well 🤞 .

**Comment by ion-elgreco** [comment]
@arkodg may I suggest splitting up the CRDs in multiple helm charts so that we stay below this size constraint of secrets/configmaps

**Comment by navaneeth-dev** [comment]
There is no way to do templating with FluxCD! This is a major problem right now.

**Comment by zirain** [comment]
does FluxCD support server side apply?

**Comment by navaneeth-dev** [comment]
I think so. But how does the normal helm chart work but not this one?

**Comment by zirain** [comment]
That's our bad to put too much things in one single crd, the bad thing is that we cannot delete them.

**Comment by navaneeth-dev** [comment]
Sorry to ask a stupid question, why can't you delete them?

**Comment by zirain** [comment]
you cannot simply delete an API for compatibility.

**Comment by ion-elgreco** [comment]
> you cannot simply delete an API for compatibility.

But you can though, just name it a breaking change

**Comment by hovvsoon** [comment]
When using FluxCD v2 with HelmRelease to install CRDs (e.g., Gateway API CRDs and Envoy CRDs), the process fails because the generated Kubernetes Secret exceeds the 1MB size limit. This happens even when the CRDs are split into separate Helm charts or HelmRelease resources.

Interestingly, the default Traefik CRDs shipped with K3s — which are also distributed as a standalone, CRD-only Helm chart and include the Gateway API CRDs — can be successfully deployed via HelmRelease without hitting this limit.

I haven’t investigated the root cause in depth; this is based purely on observed behavior.

**Comment by gclawes** [comment]
Have any of the mitigations described here been applied?

https://jkroepke.de/2026/02/handling-large-crds-in-helm-and-the-1mb-release-limit/

In particular, I wonder if **Technique 4: CRD handling through helm hooks** would help

**Comment by davidandreoletti** [comment]
Same issue with v1.8.1 with this values.yaml

```
crds:
  gatewayAPI:
    enabled: false
    channel: "experimental"
  envoyGateway:
    enabled: true   # only install envoy gateway's own CRDs as per https://github.com/envoyproxy/gateway/issues/4001#issuecomment-2367361128
```

What's the recommended solution to only install envoy gateway's own CRDs ?

**Comment by arkodg** [comment]
linking the documented steps in https://gateway.envoyproxy.io/docs/install/install-helm/#installing-crds-separately

**Comment by davidandreoletti** [comment]
> linking the documented steps in https://gateway.envoyproxy.io/docs/install/install-helm/#installing-crds-separately

```
crds:
  gatewayAPI:
    enabled: false.                         <= This is not installed as expected
    channel: "experimental"
  envoyGateway:
    enabled: true                           <= This is installed
```

I have followed the doc, setup helm to install ONLY the envoy gateway's CRDs and still experience the same issue `create: failed to create: Secret "sh.helm.release.v1.gateway-crds-helm2.v1" is invalid: data: Too long: may not be more than 1048576 bytes'`

The recommended setup to workaround the issue is; `We’re using helm template piped into kubectl apply instead of helm install due to a [known Helm limitation](https://github.com/helm/helm/pull/12277) related to large CRDs in the templates/ directory.)`)

@arkodg The limitation is within helm yet why not split the envoy-gateway CRDs into another 2 sub groups to work around it ?

**Comment by voron** [comment]
Not stale

**Comment by davidandreoletti** [comment]
> @arkodg The limitation is within helm yet why not split the envoy-gateway CRDs into another 2 sub groups to work around it ?

Ping @arkodg

**Comment by guanchzhou** [comment]
This looks resolved by the docs added in #5940: the ["Installing CRDs separately"](https://gateway.envoyproxy.io/latest/install/install-helm/#installing-crds-separately) section now recommends `helm template … | kubectl apply`, which bypasses Helm's release Secret entirely and avoids the 1 MiB limit (the whole-release-in-one-Secret cap is an inherent Helm/Kubernetes limitation, not something the chart can work around for a plain `helm install`). Probably safe to close.

**Comment by dnelen** [comment]
Not stale! 

I think every Helm chart SHOULD be installable using `helm` out of box. Requiring workarounds like `helm template ... | kubectl apply` breaks users expectations and prevents the chart from working with common deployment workflows, such as `helm install/upgrade` and GitOps controllers like FluxCD

**Comment by 98jan** [comment]
Hi,

if anyone is looking for a workaround with FluxCD that works:

1. Create a GitRepository to load CRD files from GitHub from latest release (v1.8.3).
  **Note:** :  don't use the gateway-helm-crds, these can't be used by FluxCD as a go expression is in the crd yaml files. Just use the packaged ones from gateway-helm
  ```YAML
  apiVersion: source.toolkit.fluxcd.io/v1
  kind: GitRepository
  metadata:
    name: envoy-gateway-crds
    namespace: flux-system
  spec:
    interval: 5m
    url: https://github.com/envoyproxy/gateway.git
    ref:
      # should match helm chart version
      tag: v1.8.3
    # only add envoy gateway crds
    ignore: |
      # exclude
      /*
      # include
      !charts/gateway-helm/charts/crds/crds/generated
  ```

2. Create Flux Kustomizations
```YAML
# create gitRepository manifest
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-crds-repo
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/<path>/envoy-gateway-crds
  prune: true
---
# install envoy gateway crds
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-crds
  namespace: flux-system
spec:
  prune: true
  dependsOn:
    - name: envoy-gateway-crds-repo
  sourceRef:
    kind: GitRepository
    name: envoy-gateway-crds
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
```

With that I am able to manage the envoy gateway crds with FluxCD.

Could make sense to document this solution in the docs?

**Comment by guanchzhou** [comment]
Fair points — let me walk back my earlier "probably close" suggestion. A couple of clarifications, then a concrete docs proposal:

**On the 1 MiB limit itself:** this isn't something the chart can fix. Helm stores the entire rendered release in a single Secret, and Kubernetes hard-caps any Secret at 1 MiB. The Gateway API + Envoy Gateway CRD bundle is ~2.4 MB (the `envoyproxies` CRD alone is ~1.38 MB), so even compressed it can't fit one release record. This is inherent to large-CRD charts, not specific to EG — which is why CRDs are conventionally applied outside the Helm release record.

**Confirming @98jan's Flux note (it's an important gotcha):** the CRDs under `charts/gateway-crds-helm/templates/generated/` are wrapped in Helm templating — e.g. line 1 is `{{- if .Values.crds.envoyGateway.enabled }}` — so they can't be consumed as raw manifests by Flux/kustomize. The **raw, un-templated** copies live under `charts/gateway-helm/charts/crds/crds/generated/`, which is exactly what your GitRepository `ignore` block targets. 👍

**Proposal:** rather than close, add a **GitOps / FluxCD** subsection to the existing [Installing CRDs separately](https://gateway.envoyproxy.io/latest/install/install-helm/#installing-crds-separately) docs, capturing @98jan's GitRepository + Kustomization pattern (and the raw-vs-templated CRD path caveat). I'm happy to open that docs PR if maintainers are on board.

(Separately, if there's appetite to make `gateway-crds-helm` itself Flux-consumable — e.g. a values flag or a raw-manifest artifact — that'd be a larger discussion worth its own issue.)

**Comment by davidandreoletti** [comment]
"Make gateway-crds-helm itself Flux-consumable"

This is what I am after.

**Comment by 98jan** [comment]
Right now I don't see there any options, as it fails also with native helm install commands, which FluxCD uses under the hood. With following manifest I tried to run it with serverSideApply, but doesn't matter as the secret created from a helm install/upgrade is just too big.

```YAML
# !!! Note: as crd helm chart is too big it can't be applied with this resource !!!
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-crds
spec:
  install:
    # CRDs are to big, therefore apply it on serverside
    serverSideApply: true
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
  upgrade:
    serverSideApply: enabled
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
  chart:
    spec:
      chart: gateway-crds-helm
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
      version: 1.8.3
  interval: 1h
  values:
    crds:
      # gateway api is already installed separate
      gatewayAPI:
        enabled: false
      envoyGateway:
        enabled: true
```

The only option with the known limitations is the setup from my earlier message.

For the gateway-helm-crds I don't understand why the envoy crds are configurable. This is the helm chart for installing the envoy crds  if gateway api crds are needed standalone then the gateway api installation should be used. Then I could directly consume the CRDS from the crds helm chart.
