### ISSUE TITLE
v1.4.0 Envoy Gateway fails to update Gateway status despite valid configuration — addresses[0].value set to "None"

### ISSUE THREAD

**Issue by ryanhristovski** [envoyproxy/gateway#6142]
Envoy Gateway is failing to update the status of a Gateway resource with a validation error related to addresses[0].value, even though the Gateway configuration is valid and specifies a correct IP address.

Envoy Gateway Logs:
```
envoy-gateway-6f9b57dd5d-5c4fz envoy-gateway 2025-05-21T16:50:10.210Z	ERROR	provider	kubernetes/status_updater.go:119	unable to update status{"runner": "provider", "name": "internal-gateway", "namespace": "infra-routing", "error": "Gateway.gateway.networking.k8s.io \"internal-gateway\" is invalid: [status: Invalid value: \"\": \"addresses[0]\" must validate one and only one schema (oneOf). Found none valid, status: Invalid value: \"\": \"addresses[0].value\" must validate at least one schema (anyOf), status.addresses[0].value: Invalid value: \"None\": addresses[0].value in body must be of type ipv4: \"None\", <nil>: Invalid value: \"null\": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]"}
```

Gateway Config:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/instance: external-envoy-proxy
  name: external-gateway
  namespace: infra-routing
spec:
  gatewayClassName: external-gateway-class
  listeners:
  - allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
    name: http
    port: 80
    protocol: HTTP
status:
  addresses:
  - type: IPAddress
    value: 172.20.208.49
```

Service Config:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: external-gateway
    gateway.envoyproxy.io/owning-gateway-namespace: infra-routing
  name: external-envoy
  namespace: infra-routing
spec:
  clusterIP: 172.20.208.49
  clusterIPs:
  - 172.20.208.49
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 10080
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: external-gateway
    gateway.envoyproxy.io/owning-gateway-namespace: infra-routing
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by arkodg** [comment]
this isnt adding up

https://github.com/envoyproxy/gateway/blob/eb7266c042f4573d7e67c9ea02a19e0deff6e17f/internal/gatewayapi/status/gateway.go#L80 is the piece of logic that sets the value for type `ClusterIP` only If its valid value

also seeing the status already populated in the Gateway
```
status:
  addresses:
  - type: IPAddress
    value: 172.20.122.112
```

but actual address is

```
spec:
  clusterIP: 172.20.208.49
  clusterIPs:
  - 172.20.208.49
```

cc @nezdolik

**Comment by ryanhristovski** [comment]
@arkodg referenced the wrong gateway, updated with the correct gateway config

**Comment by arkodg** [comment]
@ryanhristovski this doesnt seem like the right `Gateway` either bcause the status is already written

**Comment by ryanhristovski** [comment]
Ahh, we need a headless service during our migration to work with our legacy ingress. So based on local tests, this seems to be causing the error:
```
# Source: envoy-proxy/templates/headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: internal-envoy-headless
  namespace: infra-routing
  labels:
    app.kubernetes.io/component: proxy
    gateway.envoyproxy.io/owning-gateway-name: internal-gateway
    gateway.envoyproxy.io/owning-gateway-namespace: infra-routing
spec:
  type: ClusterIP
  clusterIP: None # This makes it a headless service
  ports:
    - name: http
      port: 80
      targetPort: 10080
      protocol: TCP
  selector:
    app.kubernetes.io/component: proxy
    gateway.envoyproxy.io/owning-gateway-name: internal-gateway
    gateway.envoyproxy.io/owning-gateway-namespace: infra-routing
```
