### ISSUE TITLE
Support Metadata for Weighted Clsuters

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#6144]
*Description*:
@arkodg writes in #5875 

> there's one edge case that needs to be solved ... For some cases, specifically when a Backend Filter exists, we create a
>  * Weighted xDS cluster for every route rule
>  * xDS cluster for every backendRef

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by guanchzhou** [comment]
This looks resolved by #5875 (cluster and endpoint xDS metadata, merged).

I verified the exact edge case from that thread — a route that splits across weighted backendRefs **with a Backend Filter** (which forces a weighted xDS cluster per route rule + a cluster per backendRef). With per-setting `metadata` configured, the translator correctly attaches it to each backend's endpoints as locality `filterMetadata` under the `envoy-gateway` namespace:

```yaml
# endpoints (EDS) for the weighted route:
  metadata:
    filterMetadata:
      envoy-gateway:
        resources:
        - name: backend-primary   # first weighted backendRef
  ...
  metadata:
    filterMetadata:
      envoy-gateway:
        resources:
        - name: backend-backup    # second weighted backendRef
```

So destination/backend metadata does reach weighted-backed destinations today — it lands at the endpoint/locality level (where subset-LB / metadata matching consumes it), not on the CDS cluster, which is the expected place for backend metadata. The duplicate-cluster concern for the unfiltered case is separately addressed by `mergeBackends` (#9477). Unless there's a specific remaining gap (e.g. metadata expected on the CDS `Cluster` itself for weighted entries), this can probably be closed.
