### ISSUE TITLE
Gateway not creating UDP Listeners (with DaemonSet?)

### ISSUE THREAD

**Issue by crocinsocks** [envoyproxy/gateway#6156]
*Description*

A listener is not being created for a UDP port on the Envoy Proxy, whereas TCP/HTTP listeners work as expected. This may be related to the use of a `DaemonSet` (the configuration has not yet been tested with a `Deployment`). Notably, the Envoy Proxy `Service` is updated with the correct UDP port, which suggests that Envoy Gateway is processing the configuration and recognizing the port.

There are no errors in the logs from either Envoy Gateway or Envoy Proxy. Based on this and the fact that the UDP listener is absent from the config dump and there are no errors logged, it appears that Envoy Gateway is not even attempting to configure a listener for this UDP port.

*Reproduction Steps*

Create a `Gateway` and `UDPRoute` as shown below:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: envoy-gateway-class
  listeners:
    - name: 21110-udp
      port: 21110
      protocol: UDP
      allowedRoutes:
        kinds:
          - kind: UDPRoute
        namespaces:
          from: Same
```

*Environment*

Envoy Gateway Version (Latest): `docker.io/envoyproxy/gateway-dev@sha256:e8beabddf486ca0878bb8a7e935c716e046e6e7560ed1c8cf4dac224a3ae557f`
Deployment Type: DaemonSet (not tested with Deployment)

*Observed Behavior*

- The `Service` for Envoy Proxy includes the UDP port as expected.
- The Envoy admin interface (`/config_dump`) does **not** show a UDP listener under `type.googleapis.com/envoy.admin.v3.ListenersConfigDump`.
- There are **no errors** in the logs of either Envoy Gateway or Envoy Proxy that reference the UDP listener or port.

*Expected Behavior*

A UDP listener should be created and appear in the listener config dump. If there is a reason the listener is not being created (e.g. a misconfiguration or unsupported scenario), an error or warning should be emitted by Envoy Gateway.
