### ISSUE TITLE
Reconsider LoadBalancer configuration mappings

### ISSUE THREAD

**Issue by jukie** [envoyproxy/gateway#6200]
*Description*:
For each load balancing policy, I suggest we expose a configuration struct rather than putting every field into `LoadBalancer`.

For example with Least Request I'd like to have the ability to increase `choice_count` as well as configure `selection_method` but these are specific to Least Request so don't make sense under the `LoadBalancer` type.
Ref: https://www.envoyproxy.io/docs/envoy/v1.34.1/api-v3/extensions/load_balancing_policies/least_request/v3/least_request.proto.html#extensions-load-balancing-policies-least-request-v3-leastrequest
```
{
  "choice_count": {...},
  "active_request_bias": {...},
  "slow_start_config": {...},
  "locality_lb_config": {...},
  "selection_method": ...
}
```

Current:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
spec:
  loadBalancer:
    slowStart:
      window: 15s
    type: LeastRequest
```

Proposal:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
spec:
  loadBalancer:
    leastRequest:
      slowStart:
        window: 15s
    # Deprecate existing fields and remove in future version
    #type: LeastRequest
    #slowStart:
    #  window: 15s
```
