### ISSUE TITLE
docs: CORS example task question

### ISSUE THREAD

**Issue by Dean-Coakley** [envoyproxy/gateway#6266]
*Description*:
I'm working on a PR to improve the CORS example task: https://gateway.envoyproxy.io/docs/tasks/security/cors/

I have some questions:
1. [Applying CORS within a HTTPFilter](https://gateway.envoyproxy.io/docs/tasks/security/cors/#configuring-cors-with-httpcorsfilter) does not seem to work. When I try to apply the manifest I get the error `strict decoding error: unknown field "spec.rules[0].filters[0].cors`. - How can I fix it?
2. If I send a request to `http://www.bar.com` the example says I should expect no CORS headers. However I seem to see a subset in my response. Is this expected?
    ```
    < access-control-allow-methods: GET, POST
    < access-control-allow-headers: x-header-1, x-header-2
    ```

**Comment by Dean-Coakley** [comment]
> 1. [Applying CORS within a HTTPFilter](https://gateway.envoyproxy.io/docs/tasks/security/cors/#configuring-cors-with-httpcorsfilter) does not seem to work. When I try to apply the manifest I get the error `strict decoding error: unknown field "spec.rules[0].filters[0].cors`. - How can I fix it?

Something like this?
```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  hostnames:
  - www.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: backend
      port: 3000
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: "Access-Control-Allow-Origin"
          value: "http://foo.com/, http://subdomain.foo.com/"
        - name: "Access-Control-Allow-Methods"
          value: "GET, POST"
        - name: "Access-Control-Allow-Headers"
          value: "x-header-1, x-header-2"
        - name: "Access-Control-Expose-Headers"
          value: "x-header-3, x-header-4"
```
