### ISSUE TITLE
Envoy complains about request_trailer_mode not being set to SEND with 1.4.1

### ISSUE THREAD

**Issue by sanjaypujare** [envoyproxy/gateway#6270]
*Description*:
I installed the latest 1.4.1 of Envoy Gateway and tried to use the new FullDuplex body mode in one of my EnvoyExtensionPolicies. However Envoy complains about "request_trailer_mode not being set to SEND"

*Repro steps*:
I added an extension as follows:

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: my-ext-proc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  extProc:
    - backendRefs:
        - name: my-ext-proc-ingress
          port: 443
      processingMode:
        request:
          body: FullDuplexStreamed
        response: 
          body: FullDuplexStreamed
```

However when I triggered this extension by sending a request, Envoy generates an error as follows:

severity: "ERROR"

```[source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) default/eg/http: If the ext_proc filter has the request_body_mode set to FULL_DUPLEX_STREAMED, then the request_trailer_mode has to be set to SEND```

I notice there's no way to add "trailers" in the extension. How can we use FullDuplexStreamed body mode? How was it verified in the tests?

*Environment*:
gateway version, envoy version: 1.4.1

*Logs*:
