### ISSUE TITLE
Envoy doesn't respect EndpointSlice terminating: true pod status

### ISSUE THREAD

**Issue by ajax-suprun-r** [envoyproxy/gateway#6277]
*Description*:
During upstream pod replacement with GRPC stream opened i'm receiving GRPC status code 13, i'm expecting status code 14.

```
gRPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Received RST_STREAM with error code 0"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:<ip address>:443 {grpc_status:13, grpc_message:"Received RST_STREAM with error code 0"}"
```

I did some research and saw that envoy deletes cluster endpoint(eg pod IP) from list only when pod is deleted from endpoint slice, when it's still there but with status `terminating: true` nothing happens at all, for example AWS ALB controller starts to deregister pod from target group when pod in terminating status.

I was expecting that envoy respects `terminating: true` status of pod in endpoint slice and will start to drain connections to this pod.

*Repro steps*:
1. Open grpc stream (any dummy grpc server and client should suite)
2. Restart upstream pod
3. Observe an error. 

Envoy config below:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: <backend_traffic_policy_name>
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: <gateway_name>
  timeout:
    http:
      connectionIdleTimeout: 30s
      requestTimeout: 0s
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: <client_traffic_policy_name>
  namespace: envoy-gateway-system
spec:
  enableProxyProtocol: true
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: <gateway_name>
  timeout:
    http:
      idleTimeout: 120s
    tcp:
      idleTimeout: 120s
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: <route_name>-443
  namespace: <namespace>
spec:
  hostnames:
    - example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: <gateway_name>
      namespace: envoy-gateway-system
      port: 443
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: <service_name>-stable
          port: 443
          weight: 100
```

*Environment*:
```
gateway version: v1.4.0
envoy version: v1.34.1
```

**Comment by arkodg** [comment]
this is intentional to align with k8s https://kubernetes.io/blog/2022/12/30/advancements-in-kubernetes-traffic-engineering/#traffic-loss-from-load-balancers-during-rolling-updates

more in https://github.com/envoyproxy/gateway/pull/4946

**Comment by ajax-suprun-r** [comment]
Did some additional testing and got status of each endpoint during pod replacement, we're not using `Deployment` resource where rolling update has behavior of: create new pod, terminate old one.
We're using argo rollouts where replace behavior is to create new one and set old one to terminating at the same time, in this case terminating pod status is UNHEALTHY, not DRAINING and this causes an error even if new pod is started and serves traffic.

When new pod becomes HEALTHY old pod never goes to DRAINING status, which is not OK at all, it should drain connections to the old pod.

![Image](https://github.com/user-attachments/assets/5cd0a25f-c7bd-479b-b46e-fd8a93818031)

Should i set some additional params?

Pods pre stop configuration, new pod is ready near 1m after scheduling, so new pod ready to serve traffic before old pod goes down.
```
terminationGracePeriodSeconds: 180

lifecycle:
  preStop:
    exec:
      command:
      - /bin/bash
      - -c
      - sleep 120
```

**Comment by arkodg** [comment]
@ajax-suprun-r you can add passive health check to make sure unhealthy endpoints are evicted from the load balancing pool by envoy proxy

```
kind: BackendTrafficPolicy
metadata:
  name: passive-health-check-policy
spec:
  healthCheck:
    passive:
      baseEjectionTime: 10s
      consecutive5XxErrors: 1
      consecutiveGatewayErrors: 0
      consecutiveLocalOriginFailures: 1
      interval: 2s
      maxEjectionPercent: 100
      splitExternalLocalOriginErrors: false
  retry:
    numRetries: 2
    perRetry:
      backOff:
        baseInterval: 100ms
        maxInterval: 10s
      timeout: 250ms
    retryOn:
      httpStatusCodes:
        - 500
        - 503
      triggers:
        - connect-failure
        - retriable-status-codes
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: my-gw
```
