### ISSUE TITLE
Backend Routing to external HTTPS Backend

### ISSUE THREAD

**Issue by nichcuta** [envoyproxy/gateway#6302]
*Description*:
We have a scenario where traffic hitting https://www.example.com/v1/test needs to be proxied to https://www.httpbin.org/v1/test over HTTPS. Using the [backend examples](https://gateway.envoyproxy.io/docs/tasks/traffic/backend/) documentation i tested the following:

- [Route to external backend](https://gateway.envoyproxy.io/docs/tasks/traffic/backend/#route-to-external-backend) - no TLS section support so proxy call is done over HTTP
- [Dynamic Forward Proxy](https://gateway.envoyproxy.io/docs/tasks/traffic/backend/#dynamic-forward-proxy) - TLS section supported and proxy call done over HTTPS but call is done to the original FQDN (www.example.com), even if a host header rewrite filter is used.
- [Routing outside Kubernetes](https://gateway.envoyproxy.io/docs/tasks/traffic/routing-outside-kubernetes/) - Although port 443 is set in the service & endpointSlice section, proxy call is done over HTTP.

Focusing on the "Dynamic Forward Proxy" example, I'm failing to understand its current use-case coverage without the possibility to define a different backend FQDN, perhaps someone can shed some light on that?

Perhaps my use-case would be covered once Backend endpoints supports TLS section as requested in [6257](https://github.com/envoyproxy/gateway/issues/6257)?

Any ideas welcome

Nic

**Comment by arkodg** [comment]
@nichcuta you'll need to combine the `Backend` resource + `BackendTLSPolicy`
https://gateway.envoyproxy.io/docs/tasks/security/backend-tls/

**Comment by arkodg** [comment]
closing this issue for now, feel free to reopen if you have any follow ups

**Comment by nichcuta** [comment]
Thanks @arkodg, i wasn't aware that a `BackendTLSPolicy` can be bond to a `Backend` resource.

For anyone who might have a similar requirement in the future, this is a working example:
```
kubectl apply -f - <<EOF
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-https-backend
  namespace: envoy-gateway
spec:
  hostnames:
  - www.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    namespace: envoy-gateway
  rules:
  - backendRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: https-backend
    matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: URLRewrite
      urlRewrite:
        hostname: "www.httpbin.org"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: https-backend
  namespace: envoy-gateway
spec:
  endpoints:
    - fqdn:
        hostname: www.httpbin.org
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: https-backend
  namespace: envoy-gateway
spec:
  targetRefs:
  - group: gateway.envoyproxy.io
    kind: Backend
    name: https-backend
  validation:
    hostname: www.httpbin.org
    wellKnownCACertificates: System
EOF
```

**Note:** DNS Records are refreshed every 30 seconds (search for dns_refresh_rate in envoy config dump)

Thanks,
Nic
