### ISSUE TITLE
Implicitly allow OPTIONS method when cors filter attached to a path to serve preflight requests

### ISSUE THREAD

**Issue by Tharsanan1** [envoyproxy/gateway#6316]
*Description*:
Hi, 

When i use httproute with cors filter attached, i have to explicitly create a option method on the paths to support cors. Otherwise i get 404. 

For example
for the following HttpRoute
```
matches:
  - path:
      type: PathPrefix
      value: /hello
    method: "GET"
```

when i attach a cors filter i will get a 404 for preflight requests.

In order to make the cors filter works i have to explicitly add a OPTION method to the same path. like below
```
matches:
  - path:
      type: PathPrefix
      value: /hello
    method: "GET"
  - path:
      type: PathPrefix
      value: /hello
    method: "OPTIONS"
```

I suggest the following to be implemented in the EG operator. If a user attach a CORs filter to a httproute the operator should implicitly create a xds route that will enable OPTION method on the paths in the httproute and it will look match for origin and Access-Control-Request-Method. So this way we can distinguise normal requests vs preflight requests. 

Example xds:
```
routes:
- match:
    path: "/hello"
    headers:
      - name: ":method"
        exact_match: "OPTIONS"
      - name: origin
      - name: access-control-request-method
```
