### ISSUE TITLE
Show helm values way to enable backend

### ISSUE THREAD

**Issue by RicHincapie** [envoyproxy/gateway#6333]
*Description*:
As Backend is not enabled by default, [here](https://gateway.envoyproxy.io/docs/tasks/traffic/backend/) it is shown how to enable it and [here](https://gateway.envoyproxy.io/contributions/design/backend/) the enablement is not even mentioned.

At helm values, this is activated at:

````yaml
config:
  envoyGateway:
    extensionApis:
      enableBackend: true
````
I'd like to have this better documented in the helm approach.
