### ISSUE TITLE
basicauth on subpath does not allow the whole target

### ISSUE THREAD

**Issue by vixns** [envoyproxy/gateway#6357]
*Description*:

I've added a SecurityPolicy with BasicAuth targeting an HTTPRoute 

```
spec:
  basicAuth:
    users:
      group: ''
      kind: Secret
      name: basic-auth-secret
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: myroute
```

When accessing this HTTPRoute using the root path, usually `/` , after a successful authentication, all subpaths are also authenticated.
Using a subpath , eg `/anything`, any other paths ( /images, /css, etc ... ) are not authenticated and returns a 401 http code.

*Environment*:

envoy gateway version 1.3.2
