### ISSUE TITLE
Provide a method to override only registry image component of EnvoyProxy CRD

### ISSUE THREAD

**Issue by a-abella** [envoyproxy/gateway#6359]
*Description*:
Currently if you want to use an alternate registry, such as a pull-through cache, you have to override the entire image string in the EnvoyProxy CRD, for example:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: this-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          image: private-registry.com/cache/envoyproxy/envoy:distroless-v1.34.1
```

The disadvantage of this is having to manually maintain the image tag in the object spec.

I would propose the addition of a field `registry` that would be prepended to the `image` like

```yaml
(...)
    kubernetes:
      envoyDeployment:
        container:
          registry: privateregistry.com/cache
          (using default `image` value: envoyproxy/envoy:distroless-v1.34.1)
```

A null `registry` value would be equivalent to the current behavior and would allow users to include the registry directly to the image string if they so choose.
