### ISSUE TITLE
Feat: Native support for certificate fetching and rotation via SDS server

### ISSUE THREAD

**Issue by raviverma-ai** [envoyproxy/gateway#6366]
*Description*:

In continuation with [Extension server policy propagation to PostTranslateModify](https://github.com/envoyproxy/gateway/pull/5914). Although we are planning to make extension server and related sds server code Open-Source for others to use as needed. Though might be difficult for some users as it requires multiple components.

@guydc, @arkodg  Will it be good to have this support natively with Envoy Gateway itself i.e. fetch mTLS certs via any external CA of choice and auto-rotate leveraging envoy's SDS capabilities (perhaps utilising BackendTLSPolicy and/or EnvoyProxy or new Envoy Gateway CRD)?

If it really comes handy to many users, our team can start implementing it.

**Comment by arkodg** [comment]
can you elaborate a little more on what the workflow would look like  for the platform dev and app dev ?
cc @muwaqar

**Comment by raviverma-ai** [comment]
Hi @arkodg , after going through multiple design options, I finalised this option to implement in simple and cleaner way.

We should go with new EG CRD, let's say, BackendmTLSPolicy (open for any suggestions), and here is a sample CRD of how it will look like.

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendmTLSPolicy
metadata:
  name: example-mtls-policy
  namespace: default
spec:
  targetRefs:
    - kind: Gateway 
       name: eg
       namespace: default
  sds:
    caType: CertManager # we can support two options, i.e. Istio and CertManager currently
    caAddress: cert-manager-istio-csr.cert-manager.svc:443 # OR istiod.istio-system.svc.cluster.local:15012
    secretName: default
  backendRefs: # Optional
    - kind: HTTPRoute # (two options, either HTTPRoute or Service) 
       name: test-httproute
       namespace: default
```

**CRD explaination:**
1. This CRD specifies the target gateways to attache to.
2. sds configuration species where to connect to get mtls certificates.
3. backendRefs is optional with following behaviour.
    a. No backendRefs specified - Generate mtls configurations for all connected HTTPRoutes.
    b. Kind specified as HTTPRoute - Generate mtls configurations for all paths specified for that HTTPRoute.
    c. kind is specified as Service - Generate mtls configuration for only those paths matching the destination service. (optional or open for any suggestions)

**Flow:**
1. Envoy Gateway controller would read this crd and generate sds related configurations for HTTPRoutes.
2. Pushes the configuration to respective gateway pod(s).
3. As soon as gateway pod(s) get the configuration, connects to SDS server to request and fetch certificate.
4. SDS server monitors and rotates certificates.

**Architecture:**
1. We have couple of options to run  
    a. Run as separate pod. (More complex as another certificate needs to be maintained for SDS server communication)
    b. Run as separate container on Envoy Gateway pod. (Preferable option)
    c. Run as another process in same container as Envoy Gateway. (Not recommended for at least for initial releases).
2. SDS server opens uds socket (though it can support other connections), this is the easiest to make it secure with less overhead.
3. SDS server would implement Certificate CSRs for CertManager and Istio.
4. Envoy Gateway would request certificate from SDS server.
5. SDS server would create and send CSR request to configured CA and gets the certifcate.
6. SDS server provides the certificate to Envoy Gateway pod (and rotates).

<img width="569" height="671" alt="Image" src="https://github.com/user-attachments/assets/7a842621-0d81-415e-bfce-1155a6c8c3df" />
