### ISSUE TITLE
Reason for ProxyAccessLogFormatType and ProviderType  existense

### ISSUE THREAD

**Issue by MaxymVlasov** [envoyproxy/gateway#6385]
*Description*:
>Describe the issue.

Hi, I recently found that you need to specify for https://gateway.envoyproxy.io/docs/api/extension_types/#proxyaccesslogformat

```yaml
format:
  type: JSON
  json:
```

or 
```yaml
format:
  type: Text
  text:
```

which is looks as duplications.
You can require to set only `format.text` OR `format.json` to be specified simultaneously, then `format.type` will be not needed at all.

Same for https://gateway.envoyproxy.io/docs/api/extension_types/#envoygatewayprovider

```yaml
provider:
  type: Kubernetes
  kubernetes:
```
```yaml
provider:
  type: Custom
  custom:
```

I'm curious why they added in first place and why they are not removed or at least deprecated yet.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
