### ISSUE TITLE
Guide for deployment in airgap 

### ISSUE THREAD

**Issue by ion-elgreco** [envoyproxy/gateway#6425]
*Description*:
The current guides don't describe that without configuring a custom EnvoyProxy with an image specification it will automatically use the distroless image from docker.io.

Example from slack:

```yaml
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          image: envoyproxy/envoy:v1.25-latest 
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: custom-proxy-config
  listeners:
 name: http
      protocol: HTTP
      port: 80
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
