### ISSUE TITLE
Gateway API extensions: Usage of Policy Attachment vs. Filters

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/gateway#675]
*Description*:
[Policy Attachment](https://gateway-api.sigs.k8s.io/references/policy-attachment/) and [HTTPRouteFilters](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteFilter) represent two different extension points in Gateway API to implement features outside the core/extended APIs provided by the upstream project.

Envoy Gateway is moving forward with implementing more advanced features on top of the core Gateway API and part of this is developing guidelines for implementers/users on how the project will use Policies and Filters.

In this document I wrote up a design/discussion for Contour on differences between using Policies and Filters: https://github.com/projectcontour/contour/pull/4749 which should be relevant to this project as well. In particular the differences between implementing the case-study spikes for rate limiting as a Policy vs. Filter.

Some other key points to discuss that may or may not be included in the above document:
- The Policy Attachment spec has content about Policies and Filters serving different purposes here: https://gateway-api.sigs.k8s.io/references/policy-attachment/#interaction-with-custom-route-filters (particular about them not being used to set the same configuration fields)
  - If we want to use Policies to set defaults or overrides for Filters, we need to address this
- How users know what configuration is actually applied/in effect on their data-plane is an open issue, especially for Policy Attachment
  - See: https://github.com/kubernetes-sigs/gateway-api/discussions/1498#discussioncomment-4030909
  - While we can create a powerful override/default hierarchy to allow flexible configuration, if users do not know what configuration is actually in effect, that is not a great experience
  - Adding Policies influencing how Filters work adds another dimension to this, possibly convoluted user experience
- Mentioned in the document linked above, but Filters in the HTTPRoute sense to me do not directly translate to Envoy HTTP Filters, as they are configured at a much different scope
  - They may work in some cases where there are per-Route incarnations of these filters in Envoy, but that does not exist for every filter, rather most filters are created per HTTPConnectionManager FilterChain

**Comment by arkodg** [comment]
@sunjayBhatia  thanks for sharing all the research on this topic !
The EG community too needs a decide on which extension point to use for the supporting advanced API Gateway features.
I'm sharing some options here, so the community can voice their preference.
1. Use HTTPRoute Filters for all API Gateway features
```
kind: RateLimit
 apiVersion: gateway.envoyproxy.io/v1alpha1
 metadata:
  name: rl-example
 spec:
 ---
 kind: HTTPRoute
 apiVersion: gateway.networking.k8s.io/v1beta1
 spec:
   parentRefs:
   - group: gateway.networking.k8s.io
     kind: Gateway
   .....
   hostnames:
   - "example.com"
   rules:
   - matches:
     - path:
         type: PathPrefix
         value: /
     backendRefs:
     - kind: Service
       name: example
       port: 8080
     filters:
     - type: ExtensionRef
       extensionRef:
         group: gateway.envoyproxy.io
         kind: RateLimit
         name: rl-example
```

2. Use PolicyAttachment for all API Gateway features
```
kind: RateLimit
apiVersion: gateway.envoyproxy.io
metadata:
  name: rl-policy
  namespace: demo
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: example
  override:
  ....
  default:
  ...
  ```
  
  3. On a case by case basis decide which extension to choose for a specific API Gateway feature

**Comment by arkodg** [comment]
@skriss @danehans @youngnick @AliceProxy @LukeShu @Xunzhuo can you please share your thoughts and preferences on this issue, please also consider sharing alternative options.

**Comment by sunjayBhatia** [comment]
Specifically targeting #1, this comment is relevant: https://github.com/envoyproxy/gateway/pull/529#discussion_r1012164693

Not all configuration can be translated to Envoy config from per-Route configuration, due to the nature of particular Envoy filters and how Envoy Gateway's xDS translation logic may set up Listeners/Virtualhosts/Routes

**Comment by sunjayBhatia** [comment]
In addition to thinking about how things will be implemented, we should consider in this decision what the intended UX we want is, which involves what resources/personas/scopes we want to target:
- What features make sense to expose as a configuration for a *whole virtualhost*? (e.g. I want a certain configuration for foo.com and a different for bar.com)
- What features make sense to expose just per-Route?
- etc.

**Comment by arkodg** [comment]
Prefer 2 because 
* the notion of `default` and `override` is powerful, addresses persona hierarchy
* Policy can be applied to the `Gateway` but Filters cannot be applied to the `Gateway`
  * this is useful for some auth features such a client-validation / mTLS which haven't made their way into the Gateway API yet
  
Imho 3. adds cognitive load on the user and 
1. cannot be applied to `Gateway` as shared above

**Comment by lizan** [comment]
This has been discussed in the authn policy document as well in [this comment](https://docs.google.com/document/d/1TlQjBy1utEwgrxE_HVT4-EHpVJ51hgnfMuAh0Q_uNoE/edit?disco=AAAAd7WFUEQ). As a result of a brief community call we agreed on something like 2. We might want to add some sort of support with PolicyAttachment to select routes in an HTTPRoute though.

Also note that Filters in HTTPRoute does not directly translate to Envoy HTTP filters as they are configured at different scope and not all Envoy filters support per route basis and the support varies. The Envoy HTTP filters are created per HCM filter chain.

**Comment by danehans** [comment]
@arkodg I feel like https://github.com/envoyproxy/gateway/issues/675#issuecomment-1301376173 is a repeat of https://github.com/envoyproxy/gateway/issues/677. Can you please clarify?

> the notion of default and override is powerful, addresses persona hierarchy

As stated [upstream](https://github.com/kubernetes-sigs/gateway-api/discussions/1498#discussioncomment-4030909), this can become very complicated which leads to poor UX.

**Comment by danehans** [comment]
From the draft [Gateway API patterns: Policy Attachment and Metaresources](https://docs.google.com/document/d/1p_kmAOmqebX8zyHnXW5I58cD8ZhNX4QNSa_gw8uAYxw/edit?usp=sharing) doc authored by @youngnick :
> __Policy Attachment: It’s all about the defaults and overrides__
>
>The [current Policy Attachment docs](https://gateway-api.sigs.k8s.io/references/policy-attachment/) list three primary components of the Policy Attachment pattern:
>- A standardized means of attaching policy to resources.
>- Support for configuring both default and override values within policy resources.
>- A hierarchy to illustrate how default and override values should interact.
>
>I think that we should focus “Policy Attachment” around the latter two bullet points

If Policy Attachment should __not__ be used as `a standardized means of attaching a policy to resources`, then a different mechanism should be used. Let's refer to #529 as a concrete example. A dev creates an HTTPRoute to route traffic to two different backend services. The dev now wishes to attach different JWT AuthN policies to the backend services. A resource should be used to __attach__ these policies. First, the dev creates the AuthN resource, for example:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: AuthN
metadata:
  name: svc1-jwt-auth
spec:
  authType: JWT
  jwtConfig:
    <JWT config for service 1>
```

The dev repeats the above for service 2 and then __attaches__ the AuthN resource to the HTTPRoute as an implementation-specific filter:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pol-attach-example
spec:
  parentRefs:
    - name: eg
  hostnames:
    - www.example.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /svc1
      filters:
      - type: ExtensionRef
        extensionRef:
          group: gateway.envoyproxy.io
          kind: AuthN
          name: svc1-jwt-auth
      backendRefs:
      - name: svc1
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /svc2
      filters:
      - type: ExtensionRef
        extensionRef:
          group: gateway.envoyproxy.io
          kind: AuthN
          name: svc2-jwt-auth
      backendRefs:
      - name: svc2
        port: 80
```

Traffic is now authN'd to the two backend services. However, the SecOps team from example corp has more stringent JWT authN requirements. The cluster admin is now required to enforce minimum JWT authN settings and creates an AuthnPolicy that __overrides__ the settings for the above AuthN kinds. For example:

```yaml
apiVersion: gateway.envoyproxy.io
kind: AuthnPolicy
metadata:
  name: svc1-jwt-auth
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: AuthN
    name: svc1-jwt-auth
  override:
    jwtConfig:
      <INSERT_OVERRIDES>
```

The cluster admin repeats the above for service 2 and now the JWT authN config for both backend services is overridden.

Although this approach requires two kinds, AuthN and AuthnPolicy, it does provide support for multiple personas inherent in Gateway API. RBAC is properly configured so that Devs are free to configure AuthN kinds for traffic routing and infra admins can configure AuthnPolicy to override traffic routing.
