### ISSUE TITLE
decision: Segmenting API Gateway features into PolicyAttachment CRDs

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#677]
*Description*:

Adding options for how API Gateway features such as `ratelimiting` can be expressed as PolicyAttachment CRDs. Please dont focus on the names, just added placeholders.

1. one generic policy CRD with features as top level fields
```
apiVersion: gateway.envoyproxy.io/v1alpha1
 kind: Policy
 .....
 spec:
   authentication:
   .....
   ratelimiting:
   ....
 ```
2. one generic policy CRD with `networking`  (shapes traffic) and `security` (authenticates & authorizes traffic) as top fields
```
apiVersion: gateway.envoyproxy.io/v1alpha1
 kind: Policy
 .....
 spec:
   security:
     authentication:
     ....
   networking:
     ratelimiting:
     .....
 ```
3. 2 Policy CRDs - one for `networking` and the other for `security`
```
apiVersion: gateway.envoyproxy.io/v1alpha1
 kind: SecurityPolicy
 ....
 ....
 spec:
   authentication:
```   

```
apiVersion: gateway.envoyproxy.io/v1alpha1
 kind: NetworkingPolicy
 ....
 spec:
   ratelimiting:
   ....
```   

4.  1 CRD per API Gateway feature

```
apiVersion: gateway.envoyproxy.io/v1alpha1
 kind: Authentication
 ....
 spec:
   jwt:
   ....
```   

```
apiVersion: gateway.envoyproxy.io/v1alpha1
 kind: Ratelimiting
 ....
 spec:
   ....
```
