### ISSUE TITLE
Add support for Aws Lambda

### ISSUE THREAD

**Issue by YasiruShaminda** [envoyproxy/gateway#688]
*Description*:
Add support for invoke Aws Lambda

**Comment by arkodg** [comment]
thanks for raising this issue, this will most likely require EG to run in a non K8s environment as well as be able to route to non K8s Backend, hoping the community has cycles to design for this in 2023, moving it to the backlog for now

**Comment by YasiruShaminda** [comment]
I am proposing the following design for the AWS Lambda filter for the Envoy Gateway. What do you think about the design? Is this fit with requirements on envoy side and align with the other filters/policies that are available in the Envoy Gateway?

```
apiVersion: gateway.envoy.io/v1alpha1
kind: AWSLambda
metadata:
  name: lambdafunc-order
Spec:
  arn: arn:aws:lambda:us-east-1:65xxxxxxxxxx:function:randomFunc
  payloadPasstrough : false
  invocationMode: synchronous
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route-randomFunc
spec:
  parentRefs:
  - name: my-gateway
  hostnames:
  - "gateway.apis.com"
  rules:
  - matches:
    -	path:
        type: PathPrefix
        value: /randomFunc/1.0.1/order
     	method: GET
queryParams:
      - type: Exact
        name: status
        value: available
    - path:
        type: PathPrefix
        value: /randomFunc/1.0.1/menu
    filters:
	- type: extensionRef
  extensionRef:
    group: gateway.envoy.io/v1alpha1
    kind: AWSLambda
    name: lambdafunc-order
```

**Comment by arkodg** [comment]
thanks for kickstarting this debate, would recommend looking into [BackendObjectReference](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.BackendObjectReference) to consider routing to a AWSLambda backend.
```
   backendRefs:
   - group: gateway.envoy.io/v1alpha1
     kind: AWSLambda
     name: lambdafunc-order
     port: 8080
```
This should solve the user feature but before we attempt to support custom backends the project will need to think of a way
to provide extensions for service / backend to endpoint resolvers, else it might become hard to manage all these vendor based backends
for e.g. an external process can consume the user's AWS creds and translate all cloud map services to some Custom Backend resource similar to [Istio's Service Entry](https://istio.io/latest/docs/reference/config/networking/service-entry/) which EG can consume
