### ISSUE TITLE
HorizontalPodAutoscaler for envoy proxy

### ISSUE THREAD

**Issue by gitanuj** [envoyproxy/gateway#703]
*Description*:
Does envoy gateway have any design to scale out envoy proxy pods? Are there any best practices on how to handle increased number of requests? I'm mostly looking at deploying this to clouds like AWS/GCP/Azure which will allocate application/network Load Balancers but then how can I make sure that envoy proxy pod is not the bottleneck in the gateway and can scale out when needed.

**Comment by danehans** [comment]
HPA is currently not supported by Envoy Gateway. It's a feature that would be beneficial to the project. I have added the feature to the backlog. Let me know if you're interested in working on it and I can assign it to you.

> I'm mostly looking at deploying this to clouds like AWS/GCP/Azure which will allocate application/network Load Balancers...

Envoy Gateway currently creates an ELB when running in AWS.  #648 intends to design an API for managing the Envoy service, PTAL, and comment as needed.

**Comment by gitanuj** [comment]
1. Is there any design doc explaining which pods are involved in the data path for EG? I'm trying to understand if there are any other components other that EnvoyProxy which need to be scaled out as well.
2. Before implementing HPA I wanted to understand if I can simply update the number of replicas [here](https://github.com/envoyproxy/gateway/blob/7c6c37ad72a6fb2403f7ea85b94732c0e14906f7/internal/infrastructure/kubernetes/deployment.go#L131). Is there an API through which this can be exposed?

**Comment by danehans** [comment]
>Is there any design doc explaining which pods are involved in the data path for EG? I'm trying to understand if there are any other components other than EnvoyProxy which need to be scaled out as well.

Only the Envoy proxy deployment needs to be scaled. The [design docs](https://gateway.envoyproxy.io/v0.2.0/design_docs.html) are the best place for this type of info, specifically the system design and config API design docs.

> Before implementing HPA I wanted to understand if I can simply update the number of replicas [here](https://github.com/envoyproxy/gateway/blob/7c6c37ad72a6fb2403f7ea85b94732c0e14906f7/internal/infrastructure/kubernetes/deployment.go#L131). Is there an API through which this can be exposed?

You can update this field but EG will revert it back to the desired state. This field should be configurable using the [EnvoyProxy config API](https://github.com/envoyproxy/gateway/blob/v0.2.0/api/config/v1alpha1/envoyproxy_types.go). If you would like to make this field configurable, please create an issue that describes your use case and xref this issue.

**Comment by arkodg** [comment]
cc @qicz in case you're interesting in adding this to `EnvoyProxy` resource :)

**Comment by qicz** [comment]
> cc @qicz in case you're interested in adding this to `EnvoyProxy` resource :)

I am sorry for the late reply. 

I think we just need to provide the same docs about HPA.  current envoy deployment we can configure more fields and #1398 support affinity etc settings.

**Comment by qicz** [comment]
example 

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: envoy-demo
    app.kubernetes.io/name: envoy-demo
    app.kubernetes.io/part-of: envoy-demo-ns
  name: envoy-demo
  namespace: envoy-demo-ns
spec:
  progressDeadlineSeconds: 600
  replicas:  1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: envoy-demo
      app.kubernetes.io/name: envoy-demo
      app.kubernetes.io/part-of: envoy-demo-ns
  template:
    metadata:
      labels:
        app.kubernetes.io/component: envoy-demo
        app.kubernetes.io/name: envoy-demo
        app.kubernetes.io/part-of: envoy-demo-ns
    spec:
      serviceAccountName: envoy-demo-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values:
                      - ""
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: envoy-demo
                    app.kubernetes.io/name: envoy-demo
                    app.kubernetes.io/part-of: envoy-demo-ns
                namespaces:
                  - envoy-demo-ns
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: envoy-demo
          image: envoy-demo:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 1024Mi
      tolerations:
      - effect: "NoSchedule"
        key: "node-role.kubernetes.io/master"
        operator: "Exists"

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa
  namespace: envoy-demo-ns
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: envoy-demo
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
```
