### ISSUE TITLE
Support OIDC based authentication

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#881]
*Description*:
Support [OIDC](https://openid.net/specs/openid-connect-core-1_0.html) based authentication

Support in envoy 
* https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter.html
* https://github.com/envoyproxy/envoy/issues/21982

Relates to https://github.com/envoyproxy/gateway/issues/336

**Comment by lizan** [comment]
The Envoy oauth2 filter isn't really an OIDC authentication filter but issuing some custom custom format token in cookies/headers. We might want to look at some control plane for this like [vouch-proxy](https://github.com/vouch/vouch-proxy)

**Comment by arkodg** [comment]
hey @lizan assigning this issue to you since you're looking into it, please feel to unassign if anything changes

**Comment by arkodg** [comment]
@lizan do you think a new filter can be added to envoyproxy or the current oauth filter can be extended to support the OIDC flow (potentially including redirects, and an external storage backend [Redis] for server tokens) .
This would eliminate the need to achieve the same using an external service such as https://github.com/istio-ecosystem/authservice

cc @mattklein123 @ZackButcher

**Comment by lizan** [comment]
Yes that is also doable. It is likely we need to do a new filter for OIDC. We just need to agree on a plan to support what flow and how to configure token storage etc. If that's more desired for EG community we can do that. Let's compare which path is better

**Comment by mattklein123** [comment]
> Yes that is also doable. It is likely we need to do a new filter for OIDC. We just need to agree on a plan to support what flow and how to configure token storage etc. If that's more desired for EG community we can do that. Let's compare which path is better

Can we put together a short design doc on the options of sharing the filter vs. a new filter? I would imagine a lot of the logic will be shared. Perhaps there can be a common core shared between the 2 filters. I don't know enough details to know if that makes sense or not but we should see so we don't end up with substantial code duplication for a security critical feature.

**Comment by lizan** [comment]
My bad I meant the opposite we shouldn't need a new filter for OIDC. The existing oauth filter can do a very basic flow of OIDC already.

For OIDC Discovery I don't think it should should be done in Envoy directly but should be a responsibility of control plane.

**Comment by arkodg** [comment]
hey @lizan any update ?

**Comment by lizan** [comment]
I've been testing several scenarios with oauth2 filter and looks like it can be used for OIDC authentication, so we don't need additional control plane for now. Will send a PR for API review soon.

**Comment by sujeshkumar** [comment]
> I've been testing several scenarios with oauth2 filter and looks like it can be used for OIDC authentication, so we don't need additional control plane for now. Will send a PR for API review soon.

@lizan are these PRs already merged ? is there any plan to use wellknownUrls to get information like auth_endpoint / token_endpoint etc ?

**Comment by arkodg** [comment]
hey @lizan unassigning you since you mentioned you are no longer working on this.
would help the next contributor if you attached any past work to this issue, TIA !

**Comment by tmsnan** [comment]
Hi, I can work on this function, please assign it to me if no one else is working on it.

**Comment by zhaohuabing** [comment]
@tmsnan I already have a design doc and API drafted on this which I'll share soo. Would love to work with you if you're also interested in it.

**Comment by zhaohuabing** [comment]
Design: https://docs.google.com/document/d/1qowAZz0fID8KsW5TlAF6ZSVb5qhgpP3QMlsM6yVVMgs
POC demo: https://github.com/zhaohuabing/playground/tree/main/envoy/external-auth-oidc

@tmsnan @zirain @arkodg

**Comment by zhaohuabing** [comment]
We have four options for the API, which are detailed in the [design](https://docs.google.com/document/d/1qowAZz0fID8KsW5TlAF6ZSVb5qhgpP3QMlsM6yVVMgs/edit#heading=h.e6rbab3r7ef4).

I suggest we start with option 2 since this strategy has already been taken by JWT authentication and is compatible with the current [AuthenticationFilter](https://gateway.envoyproxy.io/v0.4.0/api/extension_types.html#authenticationfilter) API. We can start with option 2, collect feedback from users, and then evolve according.

Option 2. Authentication at route level
Model OIDCAuthentication as a new OIDC [AuthenticationFilter](https://gateway.envoyproxy.io/v0.4.0/api/extension_types.html#authenticationfilter) type.

Example config:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: AuthenticationFilter
metadata:
  name: google
spec:
  type: OIDC
  oidcAuthentication:
    provider:
      issuer: "https://accounts.google.com"
      authorizationEndpoint: "https://accounts.google.com/o/oauth2/v2/auth"
      tokenEndpoint: "https://oauth2.googleapis.com/token"
      jwks: xxxxxxxxxxxxxx
    clientId: xxxxxxxxxxx
    clientSecret: client-secret
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
  - name: eg
  hostnames:
  - "www.example.com"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: backend
      port: 3000
      weight: 1
    filters:
    - extensionRef:
        group: gateway.envoyproxy.io
        kind: AuthenticationFilter
        name: google
      type: ExtensionRef
    matches:
    - path:
        type: PathPrefix
        value: /foo
```
