### ISSUE TITLE
Community: add more project roles member/reviewer/approver/maintainer

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#927]
*Description*:

In order to lower the threshold for becoming a maintainer, we may need to consider adding more roles in the community, so that contributors can have a staged feedback for their contributions, and get promoted in the community through more efforts:

+ reviewer
+ maintainer(admin)
+ steering committee

This requires more teams in envoyproxy:
+ gateway-steering-committee
+ gateway-maintainers
+ gateway-reviewers

``` yaml
# OWNER

leads:
  - gateway-steering-committee

approvers:
  - gateway-maintainers

reviewers:
  - gateway-reviewers

```
